### ISSUE TITLE
expo cannot "open the project in a web browser", error in webpack-config

### ISSUE THREAD

**Issue by DrKylstein** [expo/expo-cli#1014]
## Description

expo cannot open the project in a web browser

## Expected Behavior

run `expo start:web` or `expo start` followed by pressing w, get app opened in web browser

## Observed Behavior

page never opens or an error page opens, with the following in the cli output:

```
Attempting to open the project in a web browser...
(node:14876) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `allowedHost` of 'undefined' or 'null'.
    at Object.<anonymous> (C:\Users\kdelaney\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\webpack-config\src\createDevServerConfigAsync.ts:17:34)
    at Generator.next (<anonymous>)
    at C:\Users\kdelaney\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\webpack-config\webpack\createDevServerConfigAsync.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\kdelaney\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\webpack-config\webpack\createDevServerConfigAsync.js:3:12)
    at Object.createDevServerConfigAsync [as default] (C:\Users\kdelaney\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\webpack-config\webpack\createDevServerConfigAsync.js:22:12)
    at Object.<anonymous> (C:\Users\kdelaney\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\webpack-config\src\webpack.dev.ts:16:53)
    at Generator.next (<anonymous>)
    at C:\Users\kdelaney\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\webpack-config\webpack\webpack.dev.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\kdelaney\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\webpack-config\webpack\webpack.dev.js:3:12)
    at Object.default_1 [as default] (C:\Users\kdelaney\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\webpack-config\webpack\webpack.dev.js:20:12)
    at C:\Users\kdelaney\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\webpack-config\src\index.ts:17:37
    at Generator.next (<anonymous>)
    at C:\Users\kdelaney\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\webpack-config\webpack\index.js:7:71
    at new Promise (<anonymous>)
(node:14876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:14876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Environment

  Expo CLI 3.1.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

## Reproducible Demo

This occurs with a blank managed project created by `expo init`.

I've tried it on 3.1.0 and 3.0.8, clearing the cache with -c between versions

**Comment by webnah** [comment]
same too, turn off dev mode, it works.  and turn on dev mode debug in ios

**Comment by joelworsham** [comment]
same here. Never used before, clean install, tried multiple times

**Comment by t33v33** [comment]
Hey all, I'm also keen on getting this running. From what I can tell this is due to no second argument being passed at
`/usr/local/lib/node_modules/expo-cli/node_modules/@expo/xdl/build/Webpack.js:551`
```
    config = await Web().invokeWebpackConfigAsync(env);
```
Passing `{}` or even an empty string as second arg seems to make things happy. 
```
    config = await Web().invokeWebpackConfigAsync(env, {});
```
Haven't delved too much deeper yet, but I hope this helps someone out in the meantime ;)
Cheers.

**Comment by DrKylstein** [comment]
Looks like 3.1.1 fixes it.

**Comment by AndyHubert** [comment]
I just updated to 3.1.1 and am running into the same issue.

**Comment by t33v33** [comment]
Yeah, unfortunately no change in 3.1.1 for me either, OSX 10.14.6 / node v12.

**Comment by AndyHubert** [comment]
3.1.2 fixes the problem. Thanks for the quick turn around on this!
