### ISSUE TITLE
The app just throws this issue while its idle

### ISSUE THREAD

**Issue by GodwinEbikwo** [expo/expo-cli#1023]
events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by linaia** [comment]
This issue is still here (in #519 it asks to reopen, so it is already done here)

`events.js:292
      throw er; // Unhandled ‘error’ event
      ^
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted ‘error’ event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: ‘ECONNRESET’,
  code: ‘ECONNRESET’,
  syscall: ‘read’
}`

```
Expo CLI 3.21.5 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.18.1 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.5 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.1 => 35.0.1
      react: 16.8.3 => 16.8.3
      react-dom: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
```

**Comment by EvanBacon** [comment]
Related https://forums.expo.io/t/expo-dies-every-few-minutes-with-error-read-econnreset/20095/17 -- if anyone can provide a repro, I can dig into the problem.
