### ISSUE TITLE
NextJS app frozen on "Automatically optimizing pages" 

### ISSUE THREAD

**Issue by arrygoo** [expo/expo-cli#1047]
## Description
I have a Expo+NextJS app which was working fine before Expo35 release, but it has stopped working.
One symptom is htatNextJS always starts in production (with `Creating an optimized production build`message ), even when specifically set to development, and it gives the following exception from Expo's code: 

## Expected Behavior

For the expo-nextjs app to continue running like before

## Observed Behavior

Started app with `expo start -c`, expo's dashboard shows that the app is running in development, `NODE_ENV` is not defined, but I tried setting `NODE_ENV` to development too.

NextJS initially prints that it's running on development mode, but immediately follows with:

```
 web  Starting Next.js on port 19006 in development mode.
> Using external babel configuration
> Location: "/Users/work/dev/baobab/mobile/babel.config.js"
Creating an optimized production build

Compiled successfully.

Warning: You have opted-out of Automatic Prerendering due to `getInitialProps` in `pages/_app`.
Read more: https://err.sh/next.js/opt-out-automatic-prerendering

(node:15743) UnhandledPromiseRejectionWarning: ReferenceError: navigator is not defined
    at Object.get platform [as platform] (/Users/work/dev/baobab/mobile/.next/server/static/QToxTup5MDSck0GfPGQ8G/pages/index.js:204:44)
    at _objectWithoutPropertiesLoose (/Users/work/dev/baobab/mobile/.next/server/static/QToxTup5MDSck0GfPGQ8G/pages/index.js:289:283)
    at _objectWithoutProperties (/Users/work/dev/baobab/mobile/.next/server/static/QToxTup5MDSck0GfPGQ8G/pages/index.js:287:99)
    at Object./8/S (/Users/work/dev/baobab/mobile/.next/server/static/QToxTup5MDSck0GfPGQ8G/pages/index.js:313:17)
    at __webpack_require__ (/Users/work/dev/baobab/mobile/.next/server/static/QToxTup5MDSck0GfPGQ8G/pages/index.js:23:31)
    at Object.<anonymous> (/Users/work/dev/baobab/mobile/.next/server/static/QToxTup5MDSck0GfPGQ8G/pages/index.js:11386:72)
    at Object.m9sb (/Users/work/dev/baobab/mobile/.next/server/static/QToxTup5MDSck0GfPGQ8G/pages/index.js:11534:30)
    at __webpack_require__ (/Users/work/dev/baobab/mobile/.next/server/static/QToxTup5MDSck0GfPGQ8G/pages/index.js:23:31)
    at Module.wPXi (/Users/work/dev/baobab/mobile/.next/server/static/QToxTup5MDSck0GfPGQ8G/pages/index.js:12534:67)
    at __webpack_require__ (/Users/work/dev/baobab/mobile/.next/server/static/QToxTup5MDSck0GfPGQ8G/pages/index.js:23:31)
```

The error is referring to this line in expo's code:
```

  get platform() {
    return {
      web: external_ua_parser_js_default()(navigator.userAgent)
    };
  },
```

Looks like navigator is undefined when opened with NextJS? 

## Environment

```
  Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^5.1.9 => 5.2.1
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^2.18.2 => 2.18.3
    npmGlobalPackages:
      expo-cli: 3.1.2
```

**Comment by arrygoo** [comment]
Hmm looks like my issue was with having `https://www.npmjs.com/package/expo-analytics` which would depend on an older version of `expo-constants` which doesn't support SSR
