### ISSUE TITLE
expo-cli@3.2.0 doesn't seem to be working with compiling to web.

### ISSUE THREAD

**Issue by bsthomsen** [expo/expo-cli#1065]
Starting a new project with the expo-cli version 3.2 and trying to run it for web results in an error, it seems it fails to start the webpack because of a missing module.

```
npm install -g expo-cli@3.2.0
expo init project
cd project
npm run start
press w
```

Receiving the following error:
```
(node:29580) UnhandledPromiseRejectionWarning: Error: Cannot find module './plugins'
Require stack:
- C:\Users\dev\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\webpack-config\webpack\webpack.common.js
- C:\Users\dev\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\webpack-config\webpack\webpack.dev.js
- C:\Users\dev\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\webpack-config\webpack\index.js
- C:\Users\dev\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\webpack-config\webpack.config.js
- C:\Users\dev\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\xdl\build\Web.js
- C:\Users\dev\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\xdl\build\xdl.js
- C:\Users\dev\AppData\Roaming\npm\node_modules\expo-cli\build\exp.js
- C:\Users\dev\AppData\Roaming\npm\node_modules\expo-cli\bin\expo.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (C:\Users\dev\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\webpack-config\src\webpack.common.ts:29:1)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (C:\Users\dev\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\webpack-config\src\webpack.dev.ts:8:1)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
(node:29580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:29580) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by fson** [comment]
Thanks for reporting this issue. It should be fixed in the latest version of `expo-cli`.
