### ISSUE TITLE
expo-cli fails to buil for NextJS production

### ISSUE THREAD

**Issue by arrygoo** [expo/expo-cli#1067]
## Description

This same command used to successfully build my Expo+NextJS app but now it gives an error.
## Expected Behavior

Successful deploy

## Observed Behavior
```
 expo build:web
> Using external babel configuration
> Location: "/Users/work/dev/baobab/mobile/babel.config.js"
Creating an optimized production build

Failed to compile.

./node_modules/expo/build/Expo.js 23:0-161:28
Attempted import error: 'Accelerometer' is not exported from './removed'.

> Build failed because of webpack errors
Set EXPO_DEBUG=true in your env to view the stack trace.
Creating an optimized production build .%
```
## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

```
 expo diagnostics

  Expo CLI 3.2.1 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^5.1.9 => 5.1.10
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^2.18.2 => 2.18.3
```

**Comment by arrygoo** [comment]
I have the same issue even after downgrading to `3.1.0`

**Comment by arrygoo** [comment]
@hesyifei @EvanBacon
Might be interested ^

**Comment by arrygoo** [comment]
Looks like it might have been an expo-vector-icons issue, I'll try to isolate it in a repo

**Comment by EvanBacon** [comment]
Possibly related https://github.com/expo/expo-cli/issues/1068

**Comment by EvanBacon** [comment]
min repro would be extremely helpful. Since it's still in beta I would probably get distracted fixing other bugs 😅

**Comment by arrygoo** [comment]
@EvanBacon Yes, I think this can be closed in favor of the other one you linked. After isolating the issue more now I get the error that is pasted in #1068

**Comment by TreeMan360** [comment]
For what it's worth I have the same issue.

```
Attempted import error: 'Accelerometer' is not exported from './removed'.
ModuleDependencyError: "export 'Accelerometer' was not found in './removed'
```

**Comment by arrygoo** [comment]
I had that error I believe when importing expo-vector icons, @TreeMan360 do you have that package? 

but I see #1068 all the time now :(

**Comment by TreeMan360** [comment]
@arrygoo I was using ```@expo/vector-icons``` but i have removed that to try and get past this error but I am seeing this issue with ```tapable```.
```
logs for your project will appear below. Press Ctrl+C to exit.
[ event ] build page: /
[ wait ]  compiling ...
✔ success client compiled in 26ms
✔ success server compiled in 2s 486ms
✔ success client compiled in 3s 116ms
[ error ] ./node_modules/expo/build/Expo.js 23:0-161:28
Attempted import error: 'Accelerometer' is not exported from './removed'.
[ event ] build page: /next/dist/pages/_error
[ wait ]  compiling ...
✔ success server compiled in 70ms
✔ success client compiled in 196ms
[ error ] ./node_modules/expo/build/Expo.js 23:0-161:28
Attempted import error: 'Accelerometer' is not exported from './removed'.
ModuleDependencyError: "export 'Accelerometer' was not found in './removed'
    at Compilation.reportDependencyErrorsAndWarnings (/8dc/frontend/universal-app/node_modules/next/node_modules/webpack/lib/Compilation.js:1430:21)
    at hooks.finishModules.callAsync.err (/8dc/frontend/universal-app/node_modules/next/node_modules/webpack/lib/Compilation.js:1221:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/8dc/frontend/universal-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at AsyncSeriesHook.lazyCompileHook (/8dc/frontend/universal-app/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/8dc/frontend/universal-app/node_modules/next/node_modules/webpack/lib/Compilation.js:1216:28)
    at hooks.make.callAsync.err (/8dc/frontend/universal-app/node_modules/next/node_modules/webpack/lib/Compiler.js:662:17)
    at _done (eval at create (/8dc/frontend/universal-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at _promise1.then._result1 (eval at create (/8dc/frontend/universal-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[ event ] client pings, but there's no entry for page: /_error```

**Comment by EvanBacon** [comment]
This issue refers to an experimental version of Next.js support. We completely rebuilt it and it should work fine now: https://github.com/expo/expo-cli/issues/1068#issuecomment-571429351
