### ISSUE TITLE
nextjs - expo-cli - not loading expo webpack config in dev mode

### ISSUE THREAD

**Issue by aarshaw** [expo/expo-cli#1068]
## Description

When trying to run NextJS in dev mode using `expo dev --web`

I received the below error message - I'm fairly sure this is because Next doesn't load the expo webpack config anywhere (when I log out the webpack config in the next.config.js it doesn't contain any of the aliases etc. that the expo config specifies) - I think it did in previous versions as this is a new issue that has crept up since upgrading.

## Observed Behavior

```
[ error ] ./node_modules/react-native/Libraries/Animated/src/components/AnimatedImage.js
Module not found: Can't resolve '../../../Image/Image' in 'aaron/node_modules/react-native/Libraries/Animated/src/components'
{ Error: Cannot find module '.next/server/static/development/pages/_document'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.loadComponents (/aaron/node_modules/next/dist/next-server/server/load-components.js:17:25)
    at DevServer.findPageComponents (/aaron/node_modules/next/dist/next-server/server/next-server.js:311:40)
    at DevServer.renderErrorToHTML (/aaron/next/dist/next-server/server/next-server.js:365:35)
    at DevServer.renderErrorToHTML (/aaron/node_modules/next/dist/server/next-dev-server.js:17:798)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }```
```

## Environment

```
  Expo CLI 3.2.1 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.13 => 32.0.13 
      @types/react-native: ^0.60.2 => 0.60.15 
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
```

**Comment by gfullen** [comment]
I receive this same error immediately after upgrading to expo-cli 3.2.2.  I got the error when I tried to build expo build:web (using nextjs)

**Comment by gfullen** [comment]
I've downgraded expo-cli to 3.1.0 and created a new expo project.  After adding use: nextjs to the app.json and yarn adding next I fire up yarn web and it still gives the error.

**Comment by arrygoo** [comment]
I see the same behaviour as @gfullen, tried on both mentioned versions of the cli

**Comment by JClackett** [comment]
i have this error, same env as above. 

```
[ error ] /Users/<me>/expo-next/node_modules/react-native-web/dist/exports/AppRegistry/index.js:14
import invariant from 'fbjs/lib/invariant';
       ^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:811:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
```

**Comment by TreeMan360** [comment]
@JClakket I managed to fix that error by adding react-native-web to transpile modules in nextjs.config. Using nextjs standalone I find I always need to do this with the ‘’’debug’’’ library due to it being ES201X.

https://www.npmjs.com/package/next-transpile-modules

However I admit this feels highly unnecessary in the case of RNW :)

**Comment by aarshaw** [comment]
Has anyone found a workaround for this?

**Comment by motin** [comment]
Same error as OP, arrived to at after following https://docs.expo.io/versions/latest/guides/using-nextjs/.

Partial workaround, for `Error: Cannot find module '.next/server/static/development/pages/_document'`: Add `, "pages/*.js"` to tsconfig's `include` option since expo generates a js file, not a ts file.

Expo will then complain about `@expo/next-adapter` missing. Run `npm i @expo/next-adapter`.

Now, the following error instead:
```
/path/to/project/node_modules/@expo/next-adapter/build/Document.js:3
import NextDocument, { Head, Main, NextScript } from 'next/document';
       ^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.@expo/next-adapter (/path/to/project/.next/server/static/development/pages/webpack:/external "@expo/next-adapter":1:1)
    at __webpack_require__ (/path/to/project/.next/server/static/development/pages/webpack:/webpack/bootstrap:21:1)
    at Module../pages/_document.js (/path/to/project/.next/server/static/development/pages/webpack:/pages/_document.js:1:1)
    at __webpack_require__ (/path/to/project/.next/server/static/development/pages/webpack:/webpack/bootstrap:21:1)
    at Object.0 (/path/to/project/.next/server/static/development/pages/_document.js:118:18)
    at __webpack_require__ (/path/to/project/.next/server/static/development/pages/webpack:/webpack/bootstrap:21:1)
```

Here, I am at a loss. Tried @TreeMan360's suggestion...:
```
const withTM = require("next-transpile-modules");

module.exports = withTM({
  transpileModules: ["react-native-web"]
});
```
...without success.

The `Can't resolve '../../../Image/Image'` error is also still reported btw.

**Comment by motin** [comment]
This is reproducible in a new expo-created project using the blank typescript template:

```
expo init
# here, add next config to app.json
npm i next --save
mkdir pages # necessary or expo/next complains otherwise
npm install --save-dev @types/node # necessary or expo/next complains otherwise
npm i @expo/next-adapter
expo start --web
```

I suspect that Next.js support in Expo SDK 35 is Javascript only, and maybe we can look forward to Typescript support in SDK 36?

**Comment by motin** [comment]
Unfortunately I see nothing related to next.js or typescript in [the SDK 36 project](https://github.com/orgs/expo/projects/4), so is a SDK 37 milestone plausible?

**Comment by brentvatne** [comment]
cc @EvanBacon - although he might not reply very quickly as he is currently ooo at a conference

**Comment by EvanBacon** [comment]
We completely remodeled how [Next.js support works in Expo](https://github.com/expo/expo-cli/pull/1060) a while back. You can no longer start a Next.js + Expo web project with `expo start`. We chose to do this so that you could upgrade or downgrade Next.js as needed. Please refer to the latest docs for more information https://docs.expo.io/versions/latest/guides/using-nextjs/

I also just verified that TypeScript works with Expo SDK 36. 
```js
"@expo/next-adapter": "^2.0.0-beta.11",
"expo": "~36.0.0",
"next": "^9.1.7",
"react": "~16.9.0",
"react-dom": "~16.9.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
"react-native-screens": "2.0.0-alpha.12",
"react-native-web": "~0.11.7"
```
