### ISSUE TITLE
Problem with expo build: android

### ISSUE THREAD

**Issue by Zynio** [expo/expo-cli#1069]
I have a problem after upgrading to the latest version. After entering "expo build: android". I have the message "Request failed with status code 400". 

Response data: 
'{"err": "\\" bundleIdentifier \\ "is not allowed. "," _ isApiError ": true," code ": 400}'. 

expo build: ios works fine.

In app.js: 

"android": {
      "package": "com.nuadu.mobile.test",
      "versionCode": 13,
      "config" :{
        "googleSignIn" : {
          "certificateHash" : "XXXXX"
        }
      }
    }

I reduced the version to 3.1.2 and works fine.

**Comment by kermet1983** [comment]
Experienced the same issue today. I was using node 10.13.0 and switched to 12.6.0 and my build appears to be progressing

**Comment by JimVercoelen** [comment]
+1

**Comment by chayancbnits** [comment]
+1

**Comment by bikashsahucbnits** [comment]
+1

**Comment by iranmarcius** [comment]
+1

**Comment by iranmarcius** [comment]
In my case I had the following output (with EXPO_DEBUG=true):

Request failed with status code 400
Error: Request failed with status code 400
    at createError (C:\Users\Iran\AppData\Local\Yarn\Data\global\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\Iran\AppData\Local\Yarn\Data\global\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Iran\AppData\Local\Yarn\Data\global\node_modules\axios\lib\adapters\http.js:237:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Android keystore is feched normally.

Already removed and reinstalled expo-cli after clear yarn cache. No clue of what's hapenning.

**Comment by iranmarcius** [comment]
One more information, the error occurs immediately after the message "Checking if there is a build in progress..."

**Comment by fedyk** [comment]
I have a similar problem after update `expo-cli`. You can try to use not recent version `expo-cli` for a while: 
```bash
npm uninstall -g expo-cli
npm install -g expo-cli@3.1.2
```

**Comment by iranmarcius** [comment]
Hi. Thanks for the reply. Did it already. Tried 3.2.0 and 3.2.1. Got the same error.

I cleaned my yarn cache and application node_modules too, started everything from scratch but no solution.

Unfortunately the debug messages don't supply very clarifying information, only HTTP Status code 400.

**Comment by iranmarcius** [comment]
3.1.2 works fine. Thanks a lot.

**Comment by fwcontact** [comment]
3.2.2 and 3.2.3 got same error.

**Comment by rhasan082** [comment]
latest expo version 3.4.1 works for me!

**Comment by brentvatne** [comment]
this appears to be have been an intermittent issue, apologies for the hassle

**Comment by YaleBuzz** [comment]
I am seeing this issue now. First time it is happening for me with expo. 

Here is the full stack trace:

> 
15:18
Error: Request failed with status code 400
    at createError (/Users/invierno/.nvm/versions/node/v12.5.0/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/invierno/.nvm/versions/node/v12.5.0/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/invierno/.nvm/versions/node/v12.5.0/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:74:11)

And my expo-cli version is: 

3.7.1
