### ISSUE TITLE
expo build failing

### ISSUE THREAD

**Issue by chrisdrackett** [expo/expo-cli#1094]
I'm trying to run `expo build:ios` and the build is failing. The part I'm confused about is that expo used to ask for my apple info when using this command and this isn't happening. Did something change? How is the build process getting my certs, etc?

```
  Expo CLI 3.2.3 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.11.1 - /var/folders/5j/kxtyl3156ll_5q09v0d_7b_m0000gn/T/yarn--1570670894655-0.8284745633799371/node
      Yarn: 1.19.0 - /var/folders/5j/kxtyl3156ll_5q09v0d_7b_m0000gn/T/yarn--1570670894655-0.8284745633799371/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      @types/react-native: ^0.57.65 => 0.57.65 
      expo: ^35.0.0 => 35.0.0 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
```

here is what I see when going to the build info page on expo.io:

```
INFO [2019-10-09 18:46:05.54]: 
ERROR [2019-10-09 18:46:05.54]: Before submitting an issue on GitHub, please follow the guide above and make
ERROR [2019-10-09 18:46:05.54]: sure your project is set up correctly.
ERROR [2019-10-09 18:46:05.54]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
ERROR [2019-10-09 18:46:05.54]: It's hard to tell what's causing the error, so we wrote some guides on how
ERROR [2019-10-09 18:46:05.54]: Make sure to inspect the output above, as usually you'll find more error information there
INFO [2019-10-09 18:46:05.54]: 
[stderr] /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.116.1/fastlane_core/lib/fastlane_core/ui/interface.rb:163:in `build_failure!': [!] Error packaging up the application (FastlaneCore::Interface::FastlaneBuildFailure)
ERROR [2019-10-09 18:46:05.54]: Looks like fastlane ran into a build/archive error with your project
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.116.1/gym/lib/gym/error_handler.rb:112:in `handle_package_error'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.116.1/gym/lib/gym/runner.rb:138:in `block in package_app'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.116.1/fastlane_core/lib/fastlane_core/command_executor.rb:89:in `execute'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.116.1/gym/lib/gym/runner.rb:134:in `package_app'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.116.1/gym/lib/gym/runner.rb:27:in `run'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.116.1/gym/lib/gym/manager.rb:19:in `work'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.116.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
ERROR [2019-10-09 18:46:05.54]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
ERROR [2019-10-09 18:46:05.54]: the full commands printed out in yellow in the above log.
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.116.1/gym/lib/gym/commands_generator.rb:44:in `block (2 levels) in run'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.116.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.116.1/gym/lib/gym/commands_generator.rb:75:in `run'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.116.1/gym/lib/gym/commands_generator.rb:15:in `start'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.116.1/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
[stderr] 	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.116.1/bin/fastlane:23:in `<top (required)>'
[stderr] 	from /usr/local/bin/fastlane:23:in `load'
[stderr] 	from /usr/local/bin/fastlane:23:in `<main>'
removed provisioning profile from the home directory
Error: fastlane exited with non-zero code: 1
    at ChildProcess.completionListener (/usr/local/turtle-js/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
    ...
    at spawnAsync (/usr/local/turtle-js/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnAsyncThrowError (/usr/local/turtle-js/node_modules/@expo/xdl/build/detach/ExponentTools.js:233:45)
    at runFastlane (/usr/local/turtle-js/node_modules/@expo/xdl/build/detach/IosCodeSigning.js:338:51)
    at Object.buildIPA (/usr/local/turtle-js/node_modules/@expo/xdl/build/detach/IosCodeSigning.js:213:11)
    at Object.build (/usr/local/turtle-js/node_modules/@expo/xdl/build/detach/IosIPABuilder.js:164:30)
    at <anonymous>
```

**Comment by chrisdrackett** [comment]
was able to get around this with `expo build:ios -c`
