### ISSUE TITLE
[Web][NextJs] SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by SantiagoMolinaOrozco** [expo/expo-cli#1143]
### Environment

Web with NextJs

### Steps to Reproduce

1. expo init (blank project).
2. [Running in the Browser](https://docs.expo.io/versions/latest/guides/running-in-the-browser/)
3. [Using Next.js with Expo for Web](https://docs.expo.io/versions/latest/guides/using-nextjs/)
4. Run the project

### Expected Behavior

Run the project in the browser with expo start --web

### Actual Behavior

get a `Internal Server Error`
expo console no errors
my console get this:
```
[ error ] /home/san/Projects/Wepet/blog/node_modules/react-native-web/dist/exports/StyleSheet/index.js:9
import { canUseDOM } from 'fbjs/lib/ExecutionEnvironment';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:881:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.react-native-web/dist/exports/StyleSheet (/home/san/Projects/Wepet/blog/.next/server/static/development/pages/webpack:/external "react-native-web/dist/exports/StyleSheet":1:1)
    at __webpack_require__ (/home/san/Projects/Wepet/blog/.next/server/static/development/pages/webpack:/webpack/bootstrap:21:1)
    at Module../pages/_error.js (/home/san/Projects/Wepet/blog/.next/server/static/development/pages/webpack:/pages/_error.js:1:1)
    at __webpack_require__ (/home/san/Projects/Wepet/blog/.next/server/static/development/pages/webpack:/webpack/bootstrap:21:1)
    at Object.4 (/home/san/Projects/Wepet/blog/.next/server/static/development/pages/_error.js:125:18)
    at __webpack_require__ (/home/san/Projects/Wepet/blog/.next/server/static/development/pages/webpack:/webpack/bootstrap:21:1)
    at /home/san/Projects/Wepet/blog/.next/server/static/development/pages/webpack:/webpack/bootstrap:89:1
    at Object.<anonymous> (/home/san/Projects/Wepet/blog/.next/server/static/development/pages/_error.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
/home/san/Projects/Wepet/blog/node_modules/react-native-web/dist/exports/StyleSheet/index.js:9
import { canUseDOM } from 'fbjs/lib/ExecutionEnvironment';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:881:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.react-native-web/dist/exports/StyleSheet (/home/san/Projects/Wepet/blog/.next/server/static/development/pages/webpack:/external "react-native-web/dist/exports/StyleSheet":1:1)
    at __webpack_require__ (/home/san/Projects/Wepet/blog/.next/server/static/development/pages/webpack:/webpack/bootstrap:21:1)
    at Module../pages/_error.js (/home/san/Projects/Wepet/blog/.next/server/static/development/pages/webpack:/pages/_error.js:1:1)
    at __webpack_require__ (/home/san/Projects/Wepet/blog/.next/server/static/development/pages/webpack:/webpack/bootstrap:21:1)
    at Object.4 (/home/san/Projects/Wepet/blog/.next/server/static/development/pages/_error.js:125:18)
    at __webpack_require__ (/home/san/Projects/Wepet/blog/.next/server/static/development/pages/webpack:/webpack/bootstrap:21:1)
    at /home/san/Projects/Wepet/blog/.next/server/static/development/pages/webpack:/webpack/bootstrap:89:1
    at Object.<anonymous> (/home/san/Projects/Wepet/blog/.next/server/static/development/pages/_error.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
```

I don't know if my babel can be useful:
```
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [["@babel/plugin-proposal-decorators", { "legacy": true }]]
  };
};
```

### Reproducible Demo

You can find the code in this repo, [https://github.com/SantiagoMolinaOrozco/wepet-blog](https://github.com/SantiagoMolinaOrozco/wepet-blog)

I will be attentive for anything additional that may be necessary.

**Comment by tamagokun** [comment]
same thing happening here, started happening after upgrading to Expo 35

**Comment by NoahFlowa** [comment]
+1 for this to be fixed/updated.  Except the only difference for me is that it cant import the following statement and results in Internal Server Error:

/node_modules/@expo/next-adapter/build/Document.js:3
import NextDocument, { Head, Main, NextScript } from 'next/document';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:881:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)

**Comment by EvanBacon** [comment]
This is unrelated to Expo SDK 35. The Next.js support is purely experimental, here is a PR that may fix the bugs https://github.com/expo/expo-cli/pull/1146

**Comment by oste** [comment]
@EvanBacon I went ahead and tested out the changes in #1146 and I was getting `Cannot find module '@expo/config/paths'` I resolved with `yarn add @expo/config`

It's possible that I am missed something but just wanted to point that out. Thanks for the great efforts bringing the web to expo.

My dependencies look like this
```
  "dependencies": {
    "@expo/config": "^2.5.0",
    "@expo/next-adapter": "^2.0.0-beta.1",
    "expo": "^35.0.0",
    "next": "^9.1.3",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-web": "^0.11.7"
  },
  "devDependencies": {
    "@babel/plugin-proposal-decorators": "^7.7.0",
    "babel-preset-expo": "^7.1.0",
    "expo-cli": "^3.4.1"
  },
```

As mentioned in the docs I added to app.json
```
    "web": {
      "use": "nextjs"
    }
```
babel.config:
```
module.exports = function(api) {
  const isWeb = api.caller(
    caller => caller && caller.name === "babel-loader"
  );

  return {
    presets: [
      "babel-preset-expo",
      // Only use next in the browser
      isWeb && "next/babel"
    ].filter(Boolean)
  };
};
```
next.config
```
const { withExpo } = require("@expo/next-adapter");

module.exports = withExpo({
  projectRoot: __dirname
});
```
And pages/_document.js
```
import Document from "@expo/next-adapter/document";
export default Document;
```

**Comment by SantiagoMolinaOrozco** [comment]
@5ervant hi man, sorry :see_no_evil: This is a personal project and I had a lot of work
Yes, for me it runs on Android, the problem is only on the web.

thanks ;)

**Comment by SantiagoMolinaOrozco** [comment]
I can fix it with `npm audit fix` jejeje work for me, thanks everybody.

**Comment by aakagi** [comment]
> +1 for this to be fixed/updated. Except the only difference for me is that it cant import the following statement and results in Internal Server Error:
> 
> ```
> /node_modules/@expo/next-adapter/build/Document.js:3
> import NextDocument, { Head, Main, NextScript } from 'next/document';
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
>     at Module._compile (internal/modules/cjs/loader.js:881:18)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
>     at Module.load (internal/modules/cjs/loader.js:798:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:711:12)
>     at Module.require (internal/modules/cjs/loader.js:838:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
> ```

I hope this is relevant, but I got this error as well and it turned out the way to fix it was to make sure my plugins were in the correct order.

```
const withPlugins = require('next-compose-plugins');
const { withExpo } = require('@expo/next-adapter');
const withImages = require('next-images');
const withFonts = require('next-fonts');

const nextConfig = {
  webpack(config, options) {
    ...
    return config;
  },
};

module.exports = withPlugins([
  withFonts({
    projectRoot: __dirname,
  }),
  [withImages, {
    projectRoot: __dirname,
  }],
  [withExpo],  // MAKE SURE THIS GOES LAST!
], nextConfig);

```
