### ISSUE TITLE
Error: "our app builders don't have support for 35.0.0 version yet"

### ISSUE THREAD

**Issue by 2JJ1** [expo/expo-cli#1169]
I'm simply running the command, "expo build:ios". This command worked perfectly fine all week. I haven't touched app.json at all. I had a successful build last night, but this morning, the command produces the error

> Unsupported SDK version: our app builders don't have support for 35.0.0 version yet. Submitting the app to the Apple App Store may result in an unexpected behaviour
> Unsupported SDK version

I'm very confused as I haven't done anything but change my React code. I see in this article that 35.0.0 has been supported for a while now. https://blog.expo.io/expo-sdk-35-is-now-available-beee0dfafbf4

**Comment by 2JJ1** [comment]
Looks like it fixed itself. Must've been a server issue.

**Comment by ampboris** [comment]
@2JJ1    thanks for raise this and confirm it works now. we experienced this error for all our pipeline builds this morning.
all builds are working now. 

```
Unsupported SDK version: our app builders don't have support for 35.0.0 version yet. Submitting the app to the Google Play Store may result in an unexpected behaviour
Unsupported SDK version
Error: Unsupported SDK version
    at Object.checkIfSdkIsSupported (/expo-cli@3.4.1/src/commands/build/utils.js:15:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at AndroidBuilder.validateProject (/expo-cli@3.4.1/src/commands/build/AndroidBuilder.js:47:5)
    at AndroidBuilder.run (/expo-cli@3.4.1/src/commands/build/AndroidBuilder.js:26:5)
    at AndroidBuilder.command (/expo-cli@3.4.1/src/commands/build/BaseBuilder.js:54:7)
    at Command.<anonymous> (/expo-cli@3.4.1/src/exp.ts:81:7)

```
