### ISSUE TITLE
`expo eject` bare fails with "_chalk(...).default.warn is not a function"

### ISSUE THREAD

**Issue by zk** [expo/expo-cli#1172]
## Description

Ejecting a newly created expo app fails on expo-cli 3.4.1 / node v12.13.0 with the following error:

``` bash
zkmbp:vee3 zk$ env EXPO_DEBUG=true expo eject
Warning! Your git working tree is dirty.
It's recommended to commit all your changes before proceeding,
so you can revert the changes made by this command if necessary.

? How would you like to eject your app?
  Read more: https://docs.expo.io/versions/latest/expokit/eject/ Bare
Writing app.json...
Wrote to app.json, please update it manually in the future.
Successfully copied template native code.
Updating your package.json...
_chalk(...).default.warn is not a function
TypeError: _chalk(...).default.warn is not a function
    at ejectToBareAsync (/expo-cli@3.4.1/src/commands/eject/Eject.js:216:15)
    at Object.ejectAsync (/expo-cli@3.4.1/src/commands/eject/Eject.js:102:5)
    at action (/expo-cli@3.4.1/src/commands/eject.js:5:3)
    at Command.<anonymous> (/expo-cli@3.4.1/src/exp.ts:81:7)
```

May be related to this change on Oct 18, 2019: https://github.com/expo/expo-cli/commit/91b377a492dbfbfa3dcfa607bc9d5140ee49a1c3#diff-b7c560f7e12e8167e45d7d6939c793b6R216

Please note: I chose to use npm when I was asked (at the app creation step iirc) even though I did have yarn installed.

## Expected Behavior

I ran the command `expo eject`, and chose the 'bare' option. I expected the script to complete successfully.

## Observed Behavior

The `expo eject` command exits with a non-zero code. Shell output:

```
zkmbp:vee3 zk$ env EXPO_DEBUG=true expo eject
Warning! Your git working tree is dirty.
It's recommended to commit all your changes before proceeding,
so you can revert the changes made by this command if necessary.

? How would you like to eject your app?
  Read more: https://docs.expo.io/versions/latest/expokit/eject/ Bare
Writing app.json...
Wrote to app.json, please update it manually in the future.
Successfully copied template native code.
Updating your package.json...
_chalk(...).default.warn is not a function
TypeError: _chalk(...).default.warn is not a function
    at ejectToBareAsync (/expo-cli@3.4.1/src/commands/eject/Eject.js:216:15)
    at Object.ejectAsync (/expo-cli@3.4.1/src/commands/eject/Eject.js:102:5)
    at action (/expo-cli@3.4.1/src/commands/eject.js:5:3)
    at Command.<anonymous> (/expo-cli@3.4.1/src/exp.ts:81:7)
```

## Environment

```
  Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: 0.59.10 => 0.59.10
    npmGlobalPackages:
      expo-cli: 3.4.1
```

Phone sim version does not apply

## Reproducible Demo

```
npm install -g expo-cli
expo init <project name> # choose minimal, no to yarn
cd <project name>
cd ios
pod install
cd ..
expo eject
```

Thank you for your time, and let me know if I can provide any more info.

**Comment by zk** [comment]
My apologies, I'm new to expo and it seems like creating a new project with the 'minimal' option gives you an ejected setup.

Closing.
