### ISSUE TITLE
Error with Expo start 

### ISSUE THREAD

**Issue by springcoil** [expo/expo-cli#1227]
## Description

1-2 sentences describing the problem you're having or the feature you'd like to request
Error with the `expo start`
## Expected Behavior
It to run with the simulator.
What action did you perform, and what did you expect to happen?

I expected that ```expo start``` would get me the app running in a simulator

## Observed Behavior
```dev* $ expo start                                                                                                                                                      [23:25:19]
Starting project at /Users/peadarcoyle/withhislight
_xdl(...).ProjectUtils.readConfigJsonAsync is not a function
TypeError: _xdl(...).ProjectUtils.readConfigJsonAsync is not a function
    at configureProjectAsync (/expo-cli@3.4.1/src/commands/start.js:188:43)
    at action (/expo-cli@3.4.1/src/commands/start.js:58:34)
    at /expo-cli@3.4.1/src/commands/start.js:230:16
    at Command.<anonymous> (/expo-cli@3.4.1/src/exp.ts:81:7)```
What actually happened when you performed the above actions?

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
Error text goes here!
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:
```  Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.12.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.0 => 32.0.13
      @types/react-native: ^0.57.0 => 0.57.65
      expo: ^35.0.1 => 35.0.1
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.0 => 3.13.0
    npmGlobalPackages:
      expo-cli: 3.4.1```

Also specify:

- Phone/emulator/simulator platform, model and version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by ahkaneti** [comment]
Hi, I see that you have closed this issue, but I'm still running into it.
