### ISSUE TITLE
Expo start does not work after expo-cli update, even after reinstalling back to previous version

### ISSUE THREAD

**Issue by MCarballido** [expo/expo-cli#1250]
## Description

Today I decided to upgrade my expo-cli version to 3.8.0 from (I think) 3.4.1. When I did this an error occured during the installation and since then whenever I run `npm start` the build stops and throws another error.

I have tried a lot of things, downgraded to several versions of node and expo-cli, reinstalled node and expo-cli several times under different versions and I haven't found a solution yet.

## Console Error Message

Terminal error message:
```
> expo start

... new version alert goes here ...

Starting project at D:\Users\Manuel\Desktop\myapp\myapp
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
ConfigUtils(...).configFilenameAsync is not a function
Set EXPO_DEBUG=true in your env to view the stack trace.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Manuel\AppData\Roaming\npm-cache\_logs\2019-11-19T23_16_05_337Z-debug.log
```

## Environment

Expo CLI 3.4.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.13.1 - d:\Program Files\nodejs\npm.CMD

## Error Log file content

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'd:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Manuel\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.13.1
3 info using node@v12.7.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 info lifecycle @~start: @
7 verbose lifecycle @~start: unsafe-perm in lifecycle true
8 verbose lifecycle @~start: PATH: C:\Users\Manuel\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Users\Manuel\Desktop\myapp\myapp\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;D:\Program Files\Microsoft VS Code\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;d:\Program Files\nodejs\;C:\Users\Manuel\.windows-build-tools\python27\;C:\Users\Manuel\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\Manuel\AppData\Local\Programs\Python\Python37\;C:\Users\Manuel\AppData\Local\Microsoft\WindowsApps;C:\Users\Manuel\.dotnet\tools;C:\Users\Manuel\AppData\Local\Microsoft\WindowsApps;C:\Users\Manuel\AppData\Local\GitHubDesktop\bin;C:\Users\Manuel\AppData\Roaming\npm
9 verbose lifecycle @~start: CWD: D:\Users\Manuel\Desktop\myapp\myapp
10 silly lifecycle @~start: Args: [ '/d /s /c', 'expo start' ]
11 silly lifecycle @~start: Returned: code: 1  signal: null
12 info lifecycle @~start: Failed to exec start script
13 verbose stack Error: @ start: `expo start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Manuel\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:203:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Manuel\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:203:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid @
15 verbose cwd D:\Users\Manuel\Desktop\myapp\myapp
16 verbose Windows_NT 10.0.18362
17 verbose argv "d:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Manuel\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.7.0
19 verbose npm  v6.13.1
20 error code ELIFECYCLE
21 error errno 1
22 error @ start: `expo start`
22 error Exit status 1
23 error Failed at the @ start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by LucasLuco** [comment]
I did get it back to work with npm i -g expo-cli@3.5.0
Latest expo-cli having issue

**Comment by MCarballido** [comment]
This worked for me, thank you @LucasLuco !
