### ISSUE TITLE
[electron] Error: Cannot find module '@expo/webpack-config/addons' 

### ISSUE THREAD

**Issue by nandorojo** [expo/expo-cli#1283]
## Description 

Super excited about Expo with Electron! It looks like `yarn expo-electron` isn't working for me. I tried it in both an existing project and in a new one.

## Expected Behavior

It should run an electron project.

```es6
expo init expo-desktop
cd expo-desktop
yarn add -D @expo/electron-adapter
yarn expo-electron // error here
```

## Observed Behavior

It seems like `yarn expo-electron` gets held up at `@expo/webpack-config`. I checked my `package.json` after running it and I don't see the webpack config added.

```es6
$ yarn expo-electron

yarn expo-electron v0.27.5
$ "/Users/path/to/expo-electron/node_modules/.bin/expo-electron"
module.js:550
    throw err;
    ^

Error: Cannot find module '@expo/webpack-config/addons'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/path/to/expo-electron/node_modules/@expo/electron-adapter/build/Webpack.js:21:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
error Command failed with exit code 1.
```

## Environment

```
Expo CLI 3.9.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: yarn install v0.27.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.72s. - /usr/local/bin/yarn
      npm: 6.13.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.2/11B52 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.23 => 16.9.13 
      @types/react-native: ^0.57.65 => 0.57.65 
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.9.1
```

## Reproducible Demo -  [Link](https://github.com/nandorojo/expo-electron-issue)

(I'm not sure if this would be useful since it's just an empty project.)

## I also tried this:

```es6
npm i electron @expo/webpack-config react-native-web 
```

Created **`electron-webpack.js`**:
```es6
const { withExpoAdapter } = require("@expo/electron-adapter");

module.exports = withExpoAdapter({
  projectRoot: __dirname
  // Provide any overrides for electron-webpack: https://github.com/electron-userland/electron-webpack/blob/master/docs/en/configuration.md
});
```

```es 6
yarn expo-electron start
```

But no luck. Thanks for your help!

**Comment by EvanBacon** [comment]
Thanks for the bug report! Seems like this was missed by the tests because `webpack-config` is "installed" in the monorepo. Will fix soon!

Sorry for the inconvenience.

**Comment by nandorojo** [comment]
No worries, thanks for the update!

**Comment by nandorojo** [comment]
I saw that you merged a fix, but I think I'm still getting an error.

I updated the `expo-cli`, uninstalled all the node modules, and went through the instructions again. Here's what I got in the terminal:

```es6
Fernandos-MBP:expo-desktop Fernando$ yarn expo-electron
yarn expo-electron v0.27.5
$ "/Users/Fernando/Developer/Learning React Native/expo-desktop/node_modules/.bin/expo-electron"
/Users/Fernando/Developer/Learning React Native/expo-desktop/node_modules/@expo/electron-adapter/bin/expo-electron.js:16
  throw err;
  ^

TypeError: fs_extra_1.default.pathExistsSync is not a function
    at ensureElectronConfig (/Users/Fernando/Developer/Learning React Native/expo-desktop/node_modules/@expo/electron-adapter/build/Config.js:86:29)
    at /Users/Fernando/Developer/Learning React Native/expo-desktop/node_modules/@expo/electron-adapter/build/Config.js:93:9
    at Generator.next (<anonymous>)
    at /Users/Fernando/Developer/Learning React Native/expo-desktop/node_modules/@expo/electron-adapter/build/Config.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/Fernando/Developer/Learning React Native/expo-desktop/node_modules/@expo/electron-adapter/build/Config.js:3:12)
    at ensureMinProjectSetupAsync (/Users/Fernando/Developer/Learning React Native/expo-desktop/node_modules/@expo/electron-adapter/build/Config.js:92:12)
    at Object.<anonymous> (/Users/Fernando/Developer/Learning React Native/expo-desktop/node_modules/@expo/electron-adapter/bin/expo-electron.js:57:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
error Command failed with exit code 1.
```

**package.json**

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^35.0.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-web": "^0.11.7"
  },
  "devDependencies": {
    "@expo/electron-adapter": "0.0.0-alpha.10",
    "@types/react": "^16.8.23",
    "@types/react-native": "^0.57.65",
    "babel-preset-expo": "^7.1.0",
    "typescript": "^3.6.3"
  },
  "private": true
}

```

I went ahead and pushed this to the example repo. Is there a step I'm missing by chance?

Thanks again for your attention to this!

**Comment by nandorojo** [comment]
Nvm – I cloned my repo and re-ran will yarn instead of npm from the start and it works fine!
