### ISSUE TITLE
Remove sharp dependency from expo-cli installation

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1301]
## Background

- sharp installations cause problems/confusion in a variety of situations on various platforms and configurations (https://github.com/expo/expo-cli/issues/1297#issuecomment-561993283)
- xdl depends on image-utils currently, but doesn't actually use it
- webpack-pwa-manifest-plugin also depends on image-utils
- image-utils has an optional dependency on sharp-cli, which has a dependency on sharp

## Proposed action

I think we should remove the image-utils dependency xdl (easy) from the webpack-pwa-manifest-plugin (more complicated) or move that plugin elsewhere so it can be installed on demand rather than needing to be installed along with each expo-cli installation.

**Comment by GollyJer** [comment]
Windows 10, 64 bit. 
I get a sharp error on every install.

**Comment by EvanBacon** [comment]
@GollyJer it would helpful if you could report or share these errors. Alternatives to sharp are +8x slower.

**Comment by GollyJer** [comment]
@EvanBacon Just FYI. [This is the only combination of tools that works without error.](https://forums.expo.io/t/unable-to-start-expo/30460/2?u=gollyjer)
However, expo 3.10.2 actually installs even though `sharp` doesn't build and install; which is good.

I'm currently running 
- Windows 10, 64 bit
- Node 13.10

I think most of the expo-cli install errors, for Windows users, boil down to two issues.
1. The developer of a package doesn't have a pre-built binary released for Windows x64 and Node (newest).
2. When the a pre-built binary isn't found the build script isn't written correctly for Win64.

You can see this happening below... a prebuilt isn't found then a function call throws an error during the build process.

Thanks,
Jeremy


```bash
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/7] ⢀ waiting...
[2/7] ⢀ sharp
[-/7] ⢀ waiting...
[-/7] ⢀ waiting...
warning Error running install script for optional dependency: "C:\\Users\\Jeremy\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\sharp-cli\\node_modules\\sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: C:\\Users\\Jeremy\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\sharp-cli\\node_modules\\sharp
Output:
info sharp Using cached C:\\Users\\Jeremy\\AppData\\Roaming\\npm-cache\\_libvips\\libvips-8.7.4-win32-x64.tar.gz
info sharp Creating C:\\Users\\Jeremy\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\sharp-cli\\node_modules\\sharp\\build\\Release
info sharp Copying DLLs from C:\\Users\\Jeremy\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\sharp-cli\\node_modules\\sharp\\vendor\\lib to C:\\Users\\Jeremy\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\sharp-cli\\node_modules\\sharp\\build\\Release
prebuild-install WARN install No prebuilt binaries found (target=13.1.0 runtime=node arch=x64 libc= platform=win32)

C:\\Users\\Jeremy\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\sharp-cli\\node_modules\\sharp>if not defined npm_config_node_gyp (node \"C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@13.1.0 | win32 | x64
gyp info find Python using Python version 3.7.4 found at \"C:\\Users\\Jeremy\\Miniconda3\\python.exe\"
gyp info find VS using VS2017 (15.9.28307.905) found at:
gyp info find VS \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\\Users\\Jeremy\\Miniconda3\\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\gyp\\\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\Jeremy\\\\AppData\\\\Local\\\\Yarn\\\\Data\\\\global\\\\node_modules\\\\sharp-cli\\\\node_modules\\\\sharp\\\\build\\\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\\\Users\\\\Jeremy\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\13.1.0\\\\include\\\\node\\\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\\\Users\\\\Jeremy\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\13.1.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp',gyp info spawn args   '-Dnode_lib_file=C:\\\\\\\\Users\\\\\\\\Jeremy\\\\\\\\AppData\\\\\\\\Local\\\\\\\\node-gyp\\\\\\\\Cache\\\\\\\\13.1.0\\\\\\\\<(target_arch)\\\\\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\\\Users\\\\Jeremy\\\\AppData\\\\Local\\\\Yarn\\\\Data\\\\global\\\\node_modules\\\\sharp-cli\\\\node_modules\\\\sharp',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\\\Users\\\\Jeremy\\\\AppData\\\\Local\\\\Yarn\\\\Data\\\\global\\\\node_modules\\\\sharp-cli\\\\node_modules\\\\sharp\\\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\MSBuild\\15.0\\Bin\\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the \"/m\" switch.
  VError.cpp
  VInterpolate.cpp
  VImage.cpp
  win_delay_load_hook.cc
     Creating library C:\\Users\\Jeremy\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\sharp-cli\\node_modules\\sharp\\build\\Release\\libvips-cpp.lib and object C:\\Users\\Jeremy\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\sharp-cli\\node_modules\\sharp\\build\\Release\\libvips-cpp.exp
  libvips-cpp.vcxproj -> C:\\Users\\Jeremy\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\sharp-cli\\node_modules\\sharp\\build\\Release\\\\libvips-cpp.dll
  common.cc
  metadata.cc
  stats.cc
  operations.cc
  pipeline.cc
  sharp.cc
  utilities.cc
  win_delay_load_hook.cc
c:\\users\\jeremy\\appdata\\local\\yarn\\data\\global\\node_modules\\sharp-cli\\node_modules\\sharp\\src\\stats.cc(130): error C2661: 'v8::Object::Set': no overloaded function takes 2 arguments [C:\\Users\\Jeremy\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\sharp-cli\\node_modules\\sharp\\build\\sharp.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\MSBuild\\15.0\\Bin\\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.19037
gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"
gyp ERR! cwd C:\\Users\\Jeremy\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\sharp-cli\\node_modules\\sharp
success Installed "expo-cli@3.10.2" with binaries:
      - expo
      - expo-cli
```
