### ISSUE TITLE
Cannot chose SDK version when running `expo upgrade`

### ISSUE THREAD

**Issue by tomchinaftw** [expo/expo-cli#1314]
## Description

I run `expo upgrade`, then it asks me to choose SDK version using arrow keys, but it actually doesn't work and throw errors. 

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
```

## Expected Behavior

When it says `Choose a SDK version to upgrade to:` it should show up a list of SDK versions and allow me to choose one by using arrow keys. 

## Observed Behavior

When it says `Choose a SDK version to upgrade to:` it does not show a list of SDK versions. When I hit Enter key it throws an error. `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined`

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
$ expo upgrade
Warning! Your git working tree is dirty.
It's recommended to commit all your changes before proceeding,
so you can revert the changes made by this command if necessary.

? Would you like to proceed? Yes

? You are currently using SDK 34.0.0. Would you like to update to the latest version, 36.0.0? No

? Choose a SDK version to upgrade to:
        (node:36458) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at ListPrompt.getCurrentValue (/Users/xxx/.nvm/versions/node/v10.15.1/lib/node_modules/expo-cli/node_modules/inquirer/lib/prompts/list.js:116:53)
    at MapSubscriber._next (/Users/xxx/.nvm/versions/node/v10.15.1/lib/node_modules/expo-cli/node_modules/inquirer/node_modules/src/operators/map.ts:78:29)
    at MapSubscriber.Subscriber.next (/Users/xxx/.nvm/versions/node/v10.15.1/lib/node_modules/expo-cli/node_modules/inquirer/node_modules/src/Subscriber.ts:99:12)
    at TakeSubscriber._next (/Users/xxx/.nvm/versions/node/v10.15.1/lib/node_modules/expo-cli/node_modules/inquirer/node_modules/src/operators/take.ts:80:24)
    at TakeSubscriber.Subscriber.next (/Users/xxx/.nvm/versions/node/v10.15.1/lib/node_modules/expo-cli/node_modules/inquirer/node_modules/src/Subscriber.ts:99:12)
    at Interface.handler (/Users/xxx/.nvm/versions/node/v10.15.1/lib/node_modules/expo-cli/node_modules/inquirer/node_modules/src/observable/FromEventObservable.ts:240:32)
    at Interface.emit (events.js:194:15)
    at Interface._onLine (readline.js:290:10)
    at Interface._line (readline.js:638:8)
    at Interface._ttyWrite (readline.js:919:14)
(node:36458) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:36458) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

```
  Expo CLI 3.10.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
    IDEs:
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.3 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.1 => 3.13.0
    npmGlobalPackages:
      expo-cli: 3.10.2
```

Also specify:

- Phone/emulator/simulator platform, model and version: unrelated

## Reproducible Demo

Run `expo upgrade`, then choose to manually select SDK version.

**Comment by brentvatne** [comment]
thanks for pointing this out, sdk 36 should not have been available for upgrading, fixed this in the latest release

**Comment by dotjsNet** [comment]
Hi, 

Still not able to set version for SDK http://prnt.sc/rq6880 why expo upgrade, upgrades to version 37.0.0 while app on the app store doesn't have support for this version etc

**Comment by brentvatne** [comment]
@dotjsNet - it took some time for app store to propagate the update, but it went live last night
