### ISSUE TITLE
[electron] Can't use electron out-of-the-box with sdk 36.

### ISSUE THREAD

**Issue by yungkittty** [expo/expo-cli#1385]
## Description

I'm trying to setup expo with electron (SDK 36).

To do so, I've followed this [guide](https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/guides/using-electron.md).

Finally, I've tried to run `yarn expo-electron start`.

## Expected Behavior

It should start the electron app using the `AppEntry.js` (main field from package.json) or whatever pre-configured (index||app).(js||ts) from expo. This would ensure all the configuration of expo for web apps is also applied to electron and it would keep a universal entry point (if none special configuration).

## Observed Behavior

```
┏ Renderer -------------------

  Error: Cannot find entry file index.ts (or main.ts, or app.ts, or index.js, or main.js, or app.js)
      at computeEntryFile (/home/x/Clones/happew-boilerplate/node_modules/electron-webpack/src/main.ts:389:11)
      at WebpackConfigurator.configure (/home/x/Clones/happew-boilerplate/node_modules/electron-webpack/src/main.ts:222:29)
      at configure (/home/x/Clones/happew-boilerplate/node_modules/electron-webpack/src/main.ts:376:10)

┗ ----------------------------
```

I've looked-up the configuration of electron-webpack and it's this [function](https://github.com/electron-userland/electron-webpack/blob/master/packages/electron-webpack/src/main.ts#L379) that throw this error. From all the docs and examples provided by expo none talks about declarating a (index||app).(js||ts) file.

## Environment

```
Expo CLI 3.11.3 environment info:
    System:
      OS: Linux 4.15 elementary OS 5.1 Hera
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 13.5.0 - ~/.nvm/versions/node/v13.5.0/bin/node
      Yarn: 1.21.1 - ~/.nvm/versions/node/v13.5.0/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v13.5.0/bin/npm
    npmPackages:
      @types/react: ~16.9.0 => 16.9.17 
      @types/react-native: ~0.60.23 => 0.60.25 
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.11.3
```

## Reproducible Demo

I've this error with this [repository](https://github.com/expo/examples/tree/master/with-electron) which use the sdk 35.

**Comment by lukasluecke** [comment]
I had the same issue. Copying the file referenced as main entry point in `package.json` (`node_modules/expo/AppEntry.js`) to the project directory as `index.js` worked.

Not sure if that's something that should be fixed by the `electron-electron` setup or in `electron-webpack`. Maybe just add it to the guide for now?

**Comment by juuisle** [comment]
I had the same issue.

**Comment by liquid8d** [comment]
Had the same issue as well building on Linux, adding empty index.js worked, thanks!

FWIW, the Windows and Mac versions built fine with the same package.json referencing AppEntry.js

**Comment by Ngomana** [comment]
Where do i add the index.js file
![Screenshot from 2021-01-03 19-33-55](https://user-images.githubusercontent.com/61317733/103484882-ce1b7200-4dfa-11eb-9cb1-f54a814bb398.png)
