### ISSUE TITLE
"Error: keytool exited with non-zero code: 1" when call "expo fetch:android:upload-cert"

### ISSUE THREAD

**Issue by nastyaK** [expo/expo-cli#1391]
### Description
1. call `expo build:android -t app-bundle` 
2. select "Let Expo handle the process!"
3. call  `expo fetch:android:upload-cert`. 

**Result:**
```There is no valid Keystore defined for this app
Writing upload key to /Users/[username]/Work/APP_NAME/[APP_NAME]_upload_cert.pem
keytool exited with non-zero code: 1
Error: keytool exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/[username]/.nvm/versions/node/v10.16.0/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
    ...
    at spawnAsync (/Users/[username]/.nvm/versions/node/v10.16.0/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at Object.exportCertBase64 (/@expo/xdl@57.4.2/src/credentials/AndroidCredentials.ts:65:12)
    at fetchAndroidUploadCertAsync (/expo-cli@3.11.3/src/commands/fetch/android.js:60:30)
```
**Expected result:** the certificate exported

### Environment
**Expo CLI** 3.11.3 
**System:**
MacOS Catalina 10.15.2
**Binaries:**
npm: 6.9.0
**IDE:** WebStorm 2019.1.3 Build #WS-191.7479.14, built on May 27, 2019
**JRE:** 1.8.0_202-release-1483-b53 x86_64
**JVM:** OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by cchamikara** [comment]
@nastyaK did you able to resolve it, I have the same issue

**Comment by Hirbod** [comment]
I also have the same issue and I can't even update my App anymore, this is a huge and urgent issue. I get the error that my app has been signed with another hash... while I never did anything else then "let expo handle this"... Now this is coming back to us like a boomerang

**Comment by nastyaK** [comment]
> @nastyaK did you able to resolve it, I have the same issue

No, I haven't resolved the issue yet...

**Comment by aytaceminoglu** [comment]
Same issue here.

**Comment by katie-rose** [comment]
Same issue. Sigh.

**Comment by quinlanj** [comment]
@nastyaK  @cchamikara  @Hirbod @aytaceminoglu @katie-rose  I am unable to reproduce the error. I've run the repro steps and it's working for me (in the most recent expo-cli and the downgraded `3.11.3`). Can someone please confirm that this is still an issue for them?

**Comment by Hirbod** [comment]
This issue is fixed since months @quinlanj

**Comment by DanielOMIG** [comment]
Just as an FYI, Ran into this issue again.

Fixed by simply downloading the latest JDK.

**Comment by manoj03h** [comment]
Same issue keytool exited with non-zero code: 1
