### ISSUE TITLE
Cannot find module './clone.js'

### ISSUE THREAD

**Issue by epicfaace** [expo/expo-cli#141]
# READ THIS FIRST, PLEASE!

We're looking to keep questions on our forums and bug reports on the GitHub repo -- please choose whichever you feel is more appropriate for your issue:

- Post in our community forums (log in with your Expo developer account): https://forums.expo.io/c/help
- File a bug on the Expo CLI repo (for bugs related to the Expo CLI tools): https://github.com/expo/expo-cli/issues/new
- File a bug on the main Expo repo (for other bugs): https://github.com/expo/expo/issues/new
- Request a feature on Canny: https://expo.canny.io/feature-requests

Thanks for reporting the issue you found with Expo CLI!

# Required format for issues

Please make our job easier by filling this template out to completion.

## Description
I get this issue when I run `npm start` or `npm run ios`.

## Expected Behavior

Expected app to run properly.

## Observed Behavior

Got this error:

```

{ Error: Cannot find module './clone.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/expo-cli/node_modules/graceful-fs/graceful-fs.js:4:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3) code: 'MODULE_NOT_FOUND' }
Uncaught Error { Error: Cannot find module './clone.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/expo-cli/node_modules/graceful-fs/graceful-fs.js:4:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3) code: 'MODULE_NOT_FOUND' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1

```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

Also specify:

- Phone/emulator/simulator platform, model and version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by shahkeyur** [comment]
Same issue. I have just installed react native for the first time. I followed getting started from docs and tried to initialize project but got the same error that MODULE_NOT_FOUND. It could not find clone.js.

**Comment by ekrokowski** [comment]
This happens because graceful-fs had a bug and fs-extra is still using a wrong version of it.
To fix this temporarily with `yarn` (not working with npm), use this in package.son:
```
"resolutions": {
  "graceful-fs": "4.1.13"
},
```

**Comment by epicfaace** [comment]
@ekrokowski any solution we can use with npm?

**Comment by SimionDio** [comment]
I still have the problem, tried everything I found on the net, including the solution above.
 I uninstalled/installed gracefull-fs and fs-extra (npm/yarn).  Uninstalled/installed Expo-cli (npm/yarn) etc.
And still have the issue when running "expo start" on Windows 10. MacOsS works ok: 
`expo start
{ Error: Cannot find module 'clone'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Simion\AppData\Roaming\npm\node_modules\expo-cli\node_modules\analytics-node\lib\index.js:2:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3) code: 'MODULE_NOT_FOUND' }
Uncaught Error { Error: Cannot find module 'clone'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Simion\AppData\Roaming\npm\node_modules\expo-cli\node_modules\analytics-node\lib\index.js:2:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3) code: 'MODULE_NOT_FOUND' }`

**Comment by fson** [comment]
I'm closing this issue, since this should be fixed in later versions of `expo-cli` / `fs-extra`. Please open a new issue, if you still get this error in the latest Expo CLI version.
