### ISSUE TITLE
A error occurs when trying to run expo install

### ISSUE THREAD

**Issue by migueldamaso** [expo/expo-cli#1426]
## Description

On Ubuntu an npm error occurs when trying to run expo install

## Expected Behavior

Expected to install the packages

## Observed Behavior

The command does add the packages to package.json but when running npm install an error occurs.

```
expo install react-native-safe-area-context                    
Installing 1 SDK 36.0.0 compatible native module using npm.
> npm install

npm exited with non-zero code: 243
Error: npm exited with non-zero code: 243
    at ChildProcess.completionListener (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:313:26)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
    ...
    at Object.spawnAsync [as default] (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at NpmPackageManager.<anonymous> (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/package-manager/src/PackageManager.ts:99:31)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/expo-cli/node_modules/@expo/package-manager/build/PackageManager.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/package-manager/build/PackageManager.js:4:12)
    at NpmPackageManager._runAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/package-manager/build/PackageManager.js:89:16)
    at NpmPackageManager.<anonymous> (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/package-manager/src/PackageManager.ts:79:18)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/package-manager/build/PackageManager.js:5:58)
```

## Environment
```
  Expo CLI 3.11.5 environment info:
    System:
      OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
      Shell: 5.5.1 - /usr/bin/zsh
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.0.10 
```
Also specify:

- I am using a real android with the version 8.0.0

## Reproducible Demo

I managed to cause this error by creating a blank project and running the mentioned command

**Comment by migueldamaso** [comment]
I think it had to do with my nodejs installation because after fiddling with nodejs i managed to make it work.
