### ISSUE TITLE
Android resource compilation failed

### ISSUE THREAD

**Issue by amanijoseph87** [expo/expo-cli#1439]
I am trying to build an Android Standalone App using Expo, I follow all the instructions on this guide, everything works fine until I start to build the app for release.

I have this error.

```
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:mergeReleaseResources'.
[stderr] > java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
[stderr]   /app/turtle/workingdir/android/sdk34/android-shell-app/app/src/main/res/mipmap-mdpi/ic_launcher.png: error: failed to read PNG signature: file does not start with PNG signature.
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 1m 19s
729 actionable tasks: 729 executed
Error: ./gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
    ...
    at spawnAsync (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnAsyncThrowError (/app/turtle/node_modules/@expo/xdl/build/detach/ExponentTools.js:235:45)
    at buildShellAppAsync (/app/turtle/node_modules/@expo/xdl/build/detach/AndroidShellApp.js:881:11)
    at <anonymous>
```
The error doesn't go away even after I make sure my icon is png, even after I change the assetBundlePatternsto assets/*, I tried everything in [this answer](https://forums.expo.io/t/failed-to-read-png-signature-file-does-not-start-with-png-signature/23806), and [this one](https://stackoverflow.com/questions/46177560/failed-to-read-png-signature-file-does-not-start-with-png-signature/48590453) even if it's not expo, and [this one too](https://stackoverflow.com/questions/56688646/i-cant-build-expo-app-appmergereleaseresources) does not work because it gives this error error: unknown option '-t'.

My app.json:

```
{
  "expo": {
    "name": "Name",
    "slug": "nameslug",
    "privacy": "public",
    "sdkVersion": "34.0.0",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "cover",
      "backgroundColor": "#00a43d"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "assets/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.nameslug.company",
      "buildNumber": "1"
    },
    "android": {
      "package": "com.nameslug.company",
      "versionCode": 1
    },
    "description": "Tengeneza ankara zako kwa urahisi kwa kutumia App Hii",
    "androidStatusBar": {
      "backgroundColor": "#00a43d",
      "barStyle": "dark-content",
      "animated": true,
      "translucent": true
    }
  }
}
```

**Comment by dsokal** [comment]
Hi @amanijoseph87,
could you please send us your build id? Are you still experiencing the issue?
