### ISSUE TITLE
Uploading to AppStore failed

### ISSUE THREAD

**Issue by Janealter** [expo/expo-cli#1458]
##  Description

Uploading to AppStore failed on first Mac and on Github action, but succeeded on second Mac. What's the catch?)

## Expected Behavior

Successful uploading

## Observed Behavior

Upload fails

```
Resolving the ITC team ID...
Failed to upload the standalone app to the app store.
undefined method `[]' for nil:NilClass
Error: undefined method `[]' for nil:NilClass
    at runFastlaneAsync (/expo-cli@3.11.7/src/commands/upload/utils.ts:79:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Mac on which failed
```
Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.21.1 - ~/.nvm/versions/node/v12.10.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.9.17 => 16.9.17 
      @types/react-native: ^0.57.65 => 0.57.65 
      expo: ^36.0.0 => 36.0.0 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.0.10 => 4.0.10
```

### Mac on which succeeded
```
Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.9.17 => 16.9.17
      @types/react-native: ^0.57.65 => 0.57.65
      expo: ^36.0.0 => 36.0.0
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-navigation: ^4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.11.7
```

## Reproducible Demo

`EXPO_APPLE_ID=*** EXPO_APPLE_ID_PASSWORD=*** EXPO_DEBUG=true expo upload:ios --path ./app.ipa`

**Comment by Janealter** [comment]
Now I use `fastlane` standalone utility as a workaround for this issue

**Comment by dsokal** [comment]
Hi @Janealter,
could you please install expo-cli from the `next` tag? The command to do that is `npm i -g expo-cli@next`.
Then, could you please run `expo upload:ios` on the Mac on which you were experiencing failures?
This time you should see more detailed logs. Please share them with us :)

**Comment by saschagehlich** [comment]
As I'm facing the same issue, I followed your steps @dsokal - Here's my output:

```
Resolving the ITC team ID...
Failed to upload the standalone app to the app store.
undefined method `[]' for nil:NilClass
    /Users/saschagehlich/.config/fnm/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/resolve_itc_team_id.rb:17:in `block (2 levels) in <main>'
    /Users/saschagehlich/.config/fnm/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/resolve_itc_team_id.rb:17:in `each'
    /Users/saschagehlich/.config/fnm/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/resolve_itc_team_id.rb:17:in `find'
    /Users/saschagehlich/.config/fnm/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/resolve_itc_team_id.rb:17:in `block in <main>'
    /Users/saschagehlich/.config/fnm/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/funcs.rb:4:in `with_captured_stderr'
    /Users/saschagehlich/.config/fnm/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/resolve_itc_team_id.rb:11:in `<main>'
Error: undefined method `[]' for nil:NilClass
    /Users/saschagehlich/.config/fnm/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/resolve_itc_team_id.rb:17:in `block (2 levels) in <main>'
    /Users/saschagehlich/.config/fnm/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/resolve_itc_team_id.rb:17:in `each'
    /Users/saschagehlich/.config/fnm/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/resolve_itc_team_id.rb:17:in `find'
    /Users/saschagehlich/.config/fnm/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/resolve_itc_team_id.rb:17:in `block in <main>'
    /Users/saschagehlich/.config/fnm/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/funcs.rb:4:in `with_captured_stderr'
    /Users/saschagehlich/.config/fnm/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/resolve_itc_team_id.rb:11:in `<main>'
    at runFastlaneAsync (/expo-cli@3.11.8/src/commands/upload/utils.ts:84:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at IOSUploader._uploadToTheStore (/expo-cli@3.11.8/src/commands/upload/IOSUploader.ts:187:40)
    at IOSUploader.upload (/expo-cli@3.11.8/src/commands/upload/BaseUploader.ts:32:5)
    at /expo-cli@3.11.8/src/commands/upload.js:102:7
    at Command.<anonymous> (/expo-cli@3.11.8/src/exp.ts:81:7)
```

**Comment by kentackis123** [comment]
Hey,
never had this issue before, but now I'm trying to upload my second app on same account and have same issue as mentioned above:
```
Resolving the ITC team ID...
Failed to upload the standalone app to the app store.
undefined method `[]' for nil:NilClass
```

**Comment by dsokal** [comment]
Hi @kentackis123,
do you happen to have an account on Expo Developers Slack? Would you like to help me debug this issue? Unfortunately, it works just fine for me.

**Comment by dsokal** [comment]
This should be fixed in the next release of expo-cli. Thanks @kentackis123 for your help on Slack!
