### ISSUE TITLE
expo build:ios fails "Error: xcrun exited with non-zero code: 1" - icons PNG is flat

### ISSUE THREAD

**Issue by reactivecz** [expo/expo-cli#1512]
I am facing issue known as issue of PNG that has transparency or is not flat, or not square. 

My icons is flat, without transparency, square. Attached. app.json too.

Expo diag:
  Expo CLI 3.11.9 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: ^3.11.1 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.11.9

[app.json.txt](https://github.com/expo/expo-cli/files/4152941/app.json.txt)
![appicon](https://user-images.githubusercontent.com/54664875/73741053-c1ede700-4749-11ea-8545-b8fc8cf28b59.png)
![icon](https://user-images.githubusercontent.com/54664875/73741054-c1ede700-4749-11ea-90f3-26def7b15e82.png)
![splash](https://user-images.githubusercontent.com/54664875/73741056-c2867d80-4749-11ea-912b-62d9bff9237f.png)
Here is build log ending with error.

```
Unable to find an existing Expo CLI instance for this directory, starting a new one...
Starting Metro Bundler on port 19001.
Publishing to channel 'default'...
Building iOS bundle
Finished building JavaScript bundle in 1558ms.
Building Android bundle
Finished building JavaScript bundle in 1334ms.
Analyzing assets
Finished building JavaScript bundle in 909ms.
Finished building JavaScript bundle in 906ms.
Uploading assets
No assets changed, skipped.
Processing asset bundle patterns:
- /Users/lukas/git/florbal-score/**/*
Uploading JavaScript bundles
Published
Your URL is

https://exp.host/@reactivecz/fscore

› Closing Expo server
› Stopping Metro bundler
Feb 4 12:09:14 turtle[31057] INFO:  Using manifest: {"ios":{"icon":"./assets/icon.png","iconUrl":"https://d1wp6m56sqw74a.cloudfront.net/~assets/b205e2e055b007b197e23b3776592f71","infoPlist":{"NSCameraUsageDescription":"This app uses the camera to photo florbal players."},"supportsTablet":true,"bundleIdentifier":"cz.reactivecz.fscore"},"icon":"./assets/icon.png","name":"Florbal score","slug":"fscore","scheme":"fscore","splash":{"image":"./assets/splash.png","imageUrl":"https://d1wp6m56sqw74a.cloudfront.net/~assets/95e6e93b7fce578a0cd85b698783fb78","resizeMode":"contain","backgroundColor":"#0065ac"},"android":{"package":"cz.reactivecz.collector","permissions":["CAMERA"],"versionCode":1},"iconUrl":"https://d1wp6m56sqw74a.cloudfront.net/~assets/b205e2e055b007b197e23b3776592f71","locales":{},"privacy":"public","updates":{"fallbackToCacheTimeout":0},"version":"1.0.0","platforms":["ios","android"],"sdkVersion":"36.0.0","description":"","orientation":"portrait","dependencies":["@babel/core","@babel/runtime","buffer","expo","expo-asset","expo-barcode-scanner","expo-font","expo-permissions","prop-types","react","react-dom","react-native","react-native-device-info","react-native-gesture-handler","react-native-paper","react-native-picker-select","react-native-screens","react-native-shapes","react-native-unimodules","react-native-vector-icons","react-native-version-number","react-navigation","react-redux","redux","redux-persist","turtle-cli","uuid"],"bundledAssets":["asset_3a2ba31570920eeb9b1d217cabe58315.ttf","asset_8b12b3e16d591abc926165fa8f760e3b.json","asset_744ce60078c17d86006dd0edabcd59a7.ttf","asset_461d9bba8b6a3c91675039df12cfe6ca.json","asset_140c53a7643ea949007aa9a282153849.ttf","asset_94c4ffdcbffeb0570c635d7f8edd8a25.json","asset_6beba7e6834963f7f171d3bdd075c915.ttf","asset_648f2d510967a87880abfed9476aeb28.json","asset_b06871f281fee6b241d60582ae9369b9.ttf","asset_f1f91feb805137c9283fb766620ec5eb.json","asset_09dd345dbd4ec5a0874841d5749ac153.json","asset_0886a6b127c6057cee83f9c65c7ffd62.json","asset_2e562d4ebf15395f00bc738738f79291.ttf","asset_872545dde71de3842234bf6afe80c4cb.ttf","asset_c6aef942e3668158ec29d4adcb2e768f.ttf","asset_e20945d7c929279ef7a6f1db184a4470.ttf","asset_60668d999bbaf663420340f7bdd580d7.json","asset_b2e0fc821c6886fb3940f85a3320003e.ttf","asset_3e6805fbc794680014716b8c752f20b8.json","asset_5a293a273bee8d740a045d9922b9a9ae.ttf","asset_b582e1c8a605c3b9a1c26e09789a78d4.json","asset_a37b0c01c0baf1888ca812cc0508f6e2.ttf","asset_7e078700f0c35367a56c5bbb2047dda7.json","asset_8e7f807ef943bff1f6d3c2c6e0f3769e.ttf","asset_fdc01171a7a7ea76b187afcd162dee7d.json","asset_d2285965fe34b05465047401b8595dd0.ttf","asset_647543ebfccf6e5495434383598453d1.json","asset_5cdf883b18a5651a29a4d1ef276d2457.ttf","asset_74d124a3caeac2bea111f3ca2f2dd34a.json","asset_7d40544b395c5949f4646f5e150fe020.png","asset_cdd04e13d4ec83ff0cd13ec8dabdc341.png","asset_a132ecc4ba5c1517ff83c0fb321bc7fc.png","asset_0ea69b5077e7c4696db85dbcba75b0e1.png","asset_f5b790e2ac193b3d41015edb3551f9b8.png","asset_6165c9d7a2e729ba57b23dd93add5366.png","asset_42b47dd784a6f386f381024055b8aaa4.jpg","asset_74f8dfda7d57bcf3433b1b321fd0d815.jpg","asset_db218d575e7dfee027134d800987f8b0.jpg","asset_c67933263495ab6cb79805d85ab6048e.json","asset_f1199fdf66c974dea6d2a292a1df1e08.png","asset_778ffc9fe8773a878e9c30a6304784de.png","asset_376d6a4c7f622917c39feb23671ef71d.png","asset_c79c3606a1cf168006ad3979763c7e0c.png","asset_02bc1fa7c0313217bde2d65ccbff40c9.png","asset_35ba0eaec5a4f5ed12ca16fabeae451d.png"],"id":"@reactivecz/fscore","releaseId":"1622421c-dc0c-41d1-b711-30b19a9968f3","revisionId":"1.0.0-r.ByL0g0IMU","publishedTime":"2020-02-04T11:09:02.448Z","commitTime":"2020-02-04T11:09:02.542Z","bundleUrl":"https://d1wp6m56sqw74a.cloudfront.net/%40reactivecz%2Ffscore%2F1.0.0%2F7eb064ac4fd9ee3efe63fe27bbede595-36.0.0-ios.js","releaseChannel":"default","hostUri":"exp.host/@reactivecz/fscore"}
  platform: "ios"
  buildPhase: "reading manifest"
Feb 4 12:09:14 turtle[31057] INFO:  creating keychain...
  platform: "ios"
  buildPhase: "creating keychain"
Feb 4 12:09:14 turtle[31057] INFO:  creating new keychain...
  platform: "ios"
  buildPhase: "creating keychain"
Feb 4 12:09:18 turtle[31057] INFO:  Executing command: security show-keychain-info /private/tmp/xdl/c7815db0-473e-11ea-b4e6-7dfcf6bcdd3b.keychain
  platform: "ios"
  buildPhase: "creating keychain"
Feb 4 12:09:18 turtle[31057] INFO:  Keychain "/private/tmp/xdl/c7815db0-473e-11ea-b4e6-7dfcf6bcdd3b.keychain" timeout=360000s
  platform: "ios"
  buildPhase: "creating keychain"
  source: "stdout"
Feb 4 12:09:18 turtle[31057] INFO:  created new keychain
  platform: "ios"
  buildPhase: "creating keychain"
Feb 4 12:09:18 turtle[31057] INFO:  done creating keychain
  platform: "ios"
  buildPhase: "creating keychain"
Feb 4 12:09:18 turtle[31057] INFO:  importing distribution certificate into keychain...
  platform: "ios"
  buildPhase: "importing certificate into keychain"
Feb 4 12:09:18 turtle[31057] INFO:  importing certificate into keychain...
  platform: "ios"
  buildPhase: "importing certificate into keychain"
Feb 4 12:09:18 turtle[31057] INFO:  certificate has password
  platform: "ios"
  buildPhase: "importing certificate into keychain"
Feb 4 12:09:18 turtle[31057] INFO:  1 identity imported.
  platform: "ios"
  buildPhase: "importing certificate into keychain"
  source: "stdout"
Feb 4 12:09:18 turtle[31057] INFO:  imported certificate into keychain
  platform: "ios"
  buildPhase: "importing certificate into keychain"
Feb 4 12:09:18 turtle[31057] INFO:  done importing distribution certificate into keychain
  platform: "ios"
  buildPhase: "importing certificate into keychain"
Feb 4 12:09:20 turtle[31057] INFO:  ImageUtils: setting image functions to alternative sharp implementations
  platform: "ios"
  buildPhase: "icons setup"
Feb 4 12:09:20 turtle[31057] INFO:  configuring NSBundle...
  platform: "ios"
  buildPhase: "configuring NSBundle"
Feb 4 12:09:20 turtle[31057] INFO:  Using manifest: {"ios":{"icon":"./assets/icon.png","iconUrl":"https://d1wp6m56sqw74a.cloudfront.net/~assets/b205e2e055b007b197e23b3776592f71","infoPlist":{"NSCameraUsageDescription":"This app uses the camera to photo florbal players."},"supportsTablet":true,"bundleIdentifier":"cz.reactivecz.fscore"},"icon":"./assets/icon.png","name":"Florbal score","slug":"fscore","scheme":"fscore","splash":{"image":"./assets/splash.png","imageUrl":"https://d1wp6m56sqw74a.cloudfront.net/~assets/95e6e93b7fce578a0cd85b698783fb78","resizeMode":"contain","backgroundColor":"#0065ac"},"android":{"package":"cz.reactivecz.collector","permissions":["CAMERA"],"versionCode":1},"iconUrl":"https://d1wp6m56sqw74a.cloudfront.net/~assets/b205e2e055b007b197e23b3776592f71","locales":{},"privacy":"public","updates":{"fallbackToCacheTimeout":0},"version":"1.0.0","platforms":["ios","android"],"sdkVersion":"36.0.0","description":"","orientation":"portrait","dependencies":["@babel/core","@babel/runtime","buffer","expo","expo-asset","expo-barcode-scanner","expo-font","expo-permissions","prop-types","react","react-dom","react-native","react-native-device-info","react-native-gesture-handler","react-native-paper","react-native-picker-select","react-native-screens","react-native-shapes","react-native-unimodules","react-native-vector-icons","react-native-version-number","react-navigation","react-redux","redux","redux-persist","turtle-cli","uuid"],"bundledAssets":["asset_3a2ba31570920eeb9b1d217cabe58315.ttf","asset_8b12b3e16d591abc926165fa8f760e3b.json","asset_744ce60078c17d86006dd0edabcd59a7.ttf","asset_461d9bba8b6a3c91675039df12cfe6ca.json","asset_140c53a7643ea949007aa9a282153849.ttf","asset_94c4ffdcbffeb0570c635d7f8edd8a25.json","asset_6beba7e6834963f7f171d3bdd075c915.ttf","asset_648f2d510967a87880abfed9476aeb28.json","asset_b06871f281fee6b241d60582ae9369b9.ttf","asset_f1f91feb805137c9283fb766620ec5eb.json","asset_09dd345dbd4ec5a0874841d5749ac153.json","asset_0886a6b127c6057cee83f9c65c7ffd62.json","asset_2e562d4ebf15395f00bc738738f79291.ttf","asset_872545dde71de3842234bf6afe80c4cb.ttf","asset_c6aef942e3668158ec29d4adcb2e768f.ttf","asset_e20945d7c929279ef7a6f1db184a4470.ttf","asset_60668d999bbaf663420340f7bdd580d7.json","asset_b2e0fc821c6886fb3940f85a3320003e.ttf","asset_3e6805fbc794680014716b8c752f20b8.json","asset_5a293a273bee8d740a045d9922b9a9ae.ttf","asset_b582e1c8a605c3b9a1c26e09789a78d4.json","asset_a37b0c01c0baf1888ca812cc0508f6e2.ttf","asset_7e078700f0c35367a56c5bbb2047dda7.json","asset_8e7f807ef943bff1f6d3c2c6e0f3769e.ttf","asset_fdc01171a7a7ea76b187afcd162dee7d.json","asset_d2285965fe34b05465047401b8595dd0.ttf","asset_647543ebfccf6e5495434383598453d1.json","asset_5cdf883b18a5651a29a4d1ef276d2457.ttf","asset_74d124a3caeac2bea111f3ca2f2dd34a.json","asset_7d40544b395c5949f4646f5e150fe020.png","asset_cdd04e13d4ec83ff0cd13ec8dabdc341.png","asset_a132ecc4ba5c1517ff83c0fb321bc7fc.png","asset_0ea69b5077e7c4696db85dbcba75b0e1.png","asset_f5b790e2ac193b3d41015edb3551f9b8.png","asset_6165c9d7a2e729ba57b23dd93add5366.png","asset_42b47dd784a6f386f381024055b8aaa4.jpg","asset_74f8dfda7d57bcf3433b1b321fd0d815.jpg","asset_db218d575e7dfee027134d800987f8b0.jpg","asset_c67933263495ab6cb79805d85ab6048e.json","asset_f1199fdf66c974dea6d2a292a1df1e08.png","asset_778ffc9fe8773a878e9c30a6304784de.png","asset_376d6a4c7f622917c39feb23671ef71d.png","asset_c79c3606a1cf168006ad3979763c7e0c.png","asset_02bc1fa7c0313217bde2d65ccbff40c9.png","asset_35ba0eaec5a4f5ed12ca16fabeae451d.png"],"id":"@reactivecz/fscore","releaseId":"1622421c-dc0c-41d1-b711-30b19a9968f3","revisionId":"1.0.0-r.ByL0g0IMU","publishedTime":"2020-02-04T11:09:02.448Z","commitTime":"2020-02-04T11:09:02.542Z","bundleUrl":"https://d1wp6m56sqw74a.cloudfront.net/%40reactivecz%2Ffscore%2F1.0.0%2F7eb064ac4fd9ee3efe63fe27bbede595-36.0.0-ios.js","releaseChannel":"default","hostUri":"exp.host/@reactivecz/fscore"}
  platform: "ios"
  buildPhase: "reading manifest"
Feb 4 12:09:20 turtle[31057] INFO:  Modifying NSBundle configuration at /private/tmp/turtle/541f0932-32c7-4490-ac4b-11e253862dfb/archive/Release/ExpoKitApp.xcarchive/Products/Applications/ExpoKitApp.app...
  platform: "ios"
  buildPhase: "configuring NSBundle"
Feb 4 12:09:20 turtle[31057] INFO:  Using standalone config: { isShell: true,
  manifestUrl: 'https://exp.host:443/@reactivecz/fscore',
  releaseChannel: 'default',
  testEnvironment: 'none' }
  platform: "ios"
  buildPhase: "configuring NSBundle"
Feb 4 12:09:20 turtle[31057] INFO:  Configuring iOS Launch Screen...
  platform: "ios"
  buildPhase: "configuring NSBundle"
Feb 4 12:09:24 turtle[31057] INFO:  Bundling assets...
  platform: "ios"
  buildPhase: "configuring NSBundle"
Feb 4 12:09:25 turtle[31057] INFO:  Compiling resources...
  platform: "ios"
  buildPhase: "configuring NSBundle"
{ Error: xcrun exited with non-zero code: 1
    at ChildProcess.completionListener (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
    ...
    at spawnAsync (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnAsyncThrowError (/@expo/xdl@57.4.0/src/detach/ExponentTools.ts:132:19)
    at Object.buildAssetArchiveAsync (/@expo/xdl@57.4.0/src/detach/IosAssetArchive.ts:65:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  pid: 31131,
  output: [ '', '' ],
  stdout: '',
  stderr: '',
  status: 1,
  signal: null }
Feb 4 12:09:25 turtle[31057] INFO:  Cleaning up iOS...
  platform: "ios"
  buildPhase: "configuring NSBundle"
Feb 4 12:09:25 turtle[31057] ERROR: Error: xcrun exited with non-zero code: 1
    at ChildProcess.completionListener (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:441:20)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
    ...
    at spawnAsync (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnAsyncThrowError (/@expo/xdl@57.4.0/src/detach/ExponentTools.ts:132:19)
    at Object.buildAssetArchiveAsync (/@expo/xdl@57.4.0/src/detach/IosAssetArchive.ts:65:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  platform: "ios"
Feb 4 12:09:25 turtle[31057] INFO:  delete keychain...
  platform: "ios"
  buildPhase: "deleting keychain"
Feb 4 12:09:25 turtle[31057] INFO:  deleting keychain...
  platform: "ios"
  buildPhase: "deleting keychain"
Feb 4 12:09:30 turtle[31057] INFO:  done deleting keychain
  platform: "ios"
  buildPhase: "deleting keychain"
Feb 4 12:09:30 turtle[31057] ERROR: Failed to build standalone app
  err: Error: xcrun exited with non-zero code: 1
      at ChildProcess.completionListener (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:273:13)
      at ChildProcess.emit (events.js:182:13)
      at ChildProcess.EventEmitter.emit (domain.js:441:20)
      at maybeClose (internal/child_process.js:962:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
      ...
      at spawnAsync (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at spawnAsyncThrowError (/@expo/xdl@57.4.0/src/detach/ExponentTools.ts:132:19)
      at Object.buildAssetArchiveAsync (/@expo/xdl@57.4.0/src/detach/IosAssetArchive.ts:65:9)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  platform: "ios"
./build-ios.sh: line 18: -o: command not found
```

**Comment by antonbavykin1991** [comment]
I have same issue

**Comment by brentvatne** [comment]
i'm not seeing anything in that error log that indicates it's an issue with the icon. cc @dsokal

**Comment by reactivecz** [comment]
This issue is solved in actual version of expo. But it was been problem with icon, xcode says it when i was try to send it to app store with app loader. My bad, Affinity photo cant export png without transparency.

**Comment by brentvatne** [comment]
thanks for following up @reactivecz!
