### ISSUE TITLE
events.js:180 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by engkhsky** [expo/expo-cli#1515]
I keep getting this error when trying to expo start
```
events.js:180
   
   throw er; // Unhandled 'error' event
      ^

Error: UNKNOWN: unknown error, lstat 'D:\project\node_modules\.bin\JSONStream'
Emitted 'error' event at:
    at NodeWatcher.checkedEmitError (D:\project\node_modules\sane\src\node_watcher.js:143:12)
    at Walker.emit (events.js:203:13)
    at D:\project\node_modules\walker\lib\walker.js:52:12
    at callback (D:\project\node_modules\graceful-fs\polyfills.js:295:20)
    at FSReqCallback.oncomplete (fs.js:165:21) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'lstat',
  path: 'D:\\project\\node_modules\\.bin\\JSONStream'
}
```

**Comment by brentvatne** [comment]
you might want to try reinstalling expo-cli and the node_modules in your project. please repost issue with more information (follow issue template for guidance) if that doesn't fix it
