### ISSUE TITLE
Expo Web Build Fails

### ISSUE THREAD

**Issue by hashim-sohail** [expo/expo-cli#1528]
Expo web build fails for my project in GitHub Actions CI, while runs successfully locally

Command ran 

`expo build:web --config=./build/expo/app.json`

```
<s> [webpack.Progress] 100% 

[07:18:56]  web  Failed to compile.
[07:18:56] 
[07:18:56] ERROR in undefined(undefined,undefined):
TS5053: Option 'declaration' cannot be specified with option 'isolatedModules'.
[07:18:56] Error: ERROR in undefined(undefined,undefined):
```

when ran with `EXPO_DEBUG=true`

```
TS5053: Option 'declaration' cannot be specified with option 'isolatedModules'.
    at compiler.run (/@expo/xdl@57.4.5/src/Webpack.ts:239:23)
    at finalCallback (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:257:39)
    at hooks.done.callAsync.err (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:306:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:42:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/lib/node_modules/expo-cli/node_modules/tapable/lib/Hook.js:154:20)
    at emitRecords.err (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:304:22)
    at Compiler.emitRecords (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:489:39)
    at emitAssets.err (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:298:10)
    at hooks.afterEmit.callAsync.err (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:475:14)
    at _next0 (eval at create (/usr/local/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at _err0 (eval at create (/usr/local/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at compiler.hooks.afterEmit.tapAsync (/usr/local/lib/node_modules/expo-cli/node_modules/copy-webpack-plugin/dist/index.js:116:7)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/local/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/local/lib/node_modules/expo-cli/node_modules/tapable/lib/Hook.js:154:20)
    at asyncLib.forEachLimit.err (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:472:27)
    at /usr/local/lib/node_modules/expo-cli/node_modules/neo-async/async.js:2818:7
```

**Comment by EvanBacon** [comment]
Can't seem to repro after the Webpack 5 upgrade.
