### ISSUE TITLE
[next-adapter] react navigation stack inputRange

### ISSUE THREAD

**Issue by emac3** [expo/expo-cli#1531]
## Description

Trying Next.js with Expo for Web and React Navigation 5 throws an error on load.

## Expected Behavior

I load the app in the browser at `http://localhost:3000/` and I'd expect to see the first page.

## Observed Behavior
When I run `yarn next dev`:

```
Invariant Violation: inputRange must be monotonically increasing NaN,0
    at invariant (<my_monorepo>/node_modules/fbjs/lib/invariant.js:40:15)
    at checkValidInputRange (<my_monorepo>/packages/<my_package>/.next/server/static/development/pages/_document.js:24098:62)
    at createInterpolation (<my_monorepo>/packages/<my_package>/.next/server/static/development/pages/_document.js:23946:3)
    at new AnimatedInterpolation (<my_monorepo>/packages/<my_package>/.next/server/static/development/pages/_document.js:24116:28)
    at AnimatedValue.interpolate (<my_monorepo>/packages/<my_package>/.next/server/static/development/pages/_document.js:25388:12)
    at getProgressFromGesture (<my_monorepo>/packages/<my_package>/.next/server/static/development/pages/index.js:14820:18)
    at <my_monorepo>/packages/<my_package>/.next/server/static/development/pages/index.js:15154:24
    at Array.map (<anonymous>)
    at getDerivedStateFromProps (<my_monorepo>/packages/<my_package>/.next/server/static/development/pages/index.js:15140:30)
    at processChild (<my_monorepo>/node_modules/react-dom/cjs/react-dom-server.node.development.js:3061:63)
    at resolve (<my_monorepo>/node_modules/react-dom/cjs/react-dom-server.node.development.js:3013:5)
    at ReactDOMServerRenderer.render (<my_monorepo>/node_modules/react-dom/cjs/react-dom-server.node.development.js:3436:22)
    at ReactDOMServerRenderer.read (<my_monorepo>/node_modules/react-dom/cjs/react-dom-server.node.development.js:3395:29)
    at renderToString (<my_monorepo>/node_modules/react-dom/cjs/react-dom-server.node.development.js:3954:27)
    at render (<my_monorepo>/node_modules/next/dist/next-server/server/render.js:80:16)
    at renderPage (<my_monorepo>/node_modules/next/dist/next-server/server/render.js:291:16) {
  name: 'Invariant Violation',
  framesToPop: 1
```

## Environment

```
  Expo CLI 3.11.9 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react-native: ~0.61.4 => 0.61.5
```

- Phone/emulator/simulator platform, model and version: _Chrome 79_

## Reproducible Demo

```
import { NavigationContainer } from "@react-navigation/native";
import { createStackNavigator } from "@react-navigation/stack";
import React from "react";
import { Button, Text, View } from "react-native";

function HomeScreen({ navigation }) {
  return (
    <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
      <Text>Home Screen</Text>
      <Button
        title="Go to Details"
        onPress={() => navigation.navigate("Details")}
      />
    </View>
  );
}

function DetailsScreen({ navigation }) {
  return (
    <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
      <Text>Details Screen</Text>
      <Button title="Go back" onPress={() => navigation.navigate("Home")} />
    </View>
  );
}

const Stack = createStackNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator screenOptions={{ animationEnabled: false }}>
        <Stack.Screen name="Home" component={HomeScreen} />
        <Stack.Screen name="Details" component={DetailsScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

```

**Comment by brentvatne** [comment]
hi! this belongs on https://github.com/react-navigation/react-navigation :)
