### ISSUE TITLE
expo client:install:ios fails (xcrun exited with non-zero code: 111) simulator iOS 10.3.1

### ISSUE THREAD

**Issue by CostachescuCristinel** [expo/expo-cli#1577]
I have just installed an older version of iOS in the iOS simulator, to test against iOS 10 devices. However, when trying to install the expo client, this error comes up:

```
$ expo client:install:ios
? You are currently using SDK 36.0.0. Would you like to install client 2.14.0 released for this SDK? Yes
Uninstalling Expo client from iOS simulator.
Error running `xcrun simctl uninstall booted host.exp.Exponent`: An error was encountered processing the command (domain=LSApplicationWorkspaceErrorDomain, code=111):
The operation couldn’t be completed. (LSApplicationWorkspaceErrorDomain error 111.)

Error: xcrun exited with non-zero code: 111
    at ChildProcess.completionListener (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:428:26)
    at ChildProcess.emit (events.js:321:20)
    at maybeClose (internal/child_process.js:1028:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    ...
    at spawnAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at _xcrunAsync (/@expo/xdl@57.5.2/src/Simulator.ts:45:18)
    at _uninstallExpoAppFromSimulatorAsync (/@expo/xdl@57.5.2/src/Simulator.ts:400:11)
    at Object.upgradeExpoAsync (/@expo/xdl@57.5.2/src/Simulator.ts:423:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at /expo-cli@3.13.1/src/commands/client/index.js:297:11
    at Command.<anonymous> (/expo-cli@3.13.1/src/exp.ts:81:7) {
  pid: 18203,
  output: [
    '',
    'An error was encountered processing the command (domain=LSApplicationWorkspaceErrorDomain, code=111):\n' +
      'The operation couldn’t be completed. (LSApplicationWorkspaceErrorDomain error 111.)\n'
  ],
  stdout: '',
  stderr: 'An error was encountered processing the command (domain=LSApplicationWorkspaceErrorDomain, code=111):\n' +
    'The operation couldn’t be completed. (LSApplicationWorkspaceErrorDomain error 111.)\n',
  status: 111,
  signal: null
}
xcrun exited with non-zero code: 111
Set EXPO_DEBUG=true in your env to view the stack trace.
```

It seems from this output that the error is related to not finding an application with the specified identifier.

What can I do to fix this isssue and install the expo client ? Is there any way to manually install the expo client other than expo client:install:ios ?

**Comment by CostachescuCristinel** [comment]
Not sure what happened, after starting my Mac today, when I tried the same as yesterday it just worked and the error went away. The client installed correctly and worked just normally.

I don't think that's the solution to the issue above, but there isn't much that I can do now to help debug the issue. As I could understand from the situation, installing an additional iOS version in the simulator may require a reboot of the machine in order to work, but I can't confirm.
