### ISSUE TITLE
Error to upload app to the app store - error 500

### ISSUE THREAD

**Issue by carlosedof** [expo/expo-cli#1621]
Hello, I am trying to run command "expo upload:ios" but getting this error. Already tried to update and to downgrade my expo version and my node version, both unsuccessful. 

```
Failed to upload the standalone app to the app store.
Server error got 500
    /Users/caduolivera/.nvm/versions/node/v10.13.0/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/vendor/ruby/2.2.0/gems/fastlane-2.136.0/spaceship/lib/spaceship/connect_api/client.rb:126:in `handle_response'
    /Users/caduolivera/.nvm/versions/node/v10.13.0/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/vendor/ruby/2.2.0/gems/fastlane-2.136.0/spaceship/lib/spaceship/connect_api/client.rb:87:in `get'
    /Users/caduolivera/.nvm/versions/node/v10.13.0/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/vendor/ruby/2.2.0/gems/fastlane-2.136.0/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:12:in `get_apps'
    /Users/caduolivera/.nvm/versions/node/v10.13.0/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/vendor/ruby/2.2.0/gems/fastlane-2.136.0/spaceship/lib/spaceship/connect_api/models/app.rb:34:in `all'
    /Users/caduolivera/.nvm/versions/node/v10.13.0/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/vendor/ruby/2.2.0/gems/fastlane-2.136.0/spaceship/lib/spaceship/connect_api/models/app.rb:39:in `find'
    /Users/caduolivera/.nvm/versions/node/v10.13.0/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/vendor/ruby/2.2.0/gems/fastlane-2.136.0/pilot/lib/pilot/manager.rb:51:in `fetch_app_id'
    /Users/caduolivera/.nvm/versions/node/v10.13.0/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/vendor/ruby/2.2.0/gems/fastlane-2.136.0/pilot/lib/pilot/build_manager.rb:23:in `upload'
    /Users/caduolivera/.nvm/versions/node/v10.13.0/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/pilot_upload.rb:20:in `block in <main>'
    /Users/caduolivera/.nvm/versions/node/v10.13.0/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/funcs.rb:4:in `with_captured_stderr'
    /Users/caduolivera/.nvm/versions/node/v10.13.0/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.11.4-osx/lib/app/pilot_upload.rb:12:in `<main>'
```

**Comment by brentvatne** [comment]
this could have been an intermittent issue with the apple app store, it's hard to say! can you try again and create a new issue if it still happens? thanks!
