### ISSUE TITLE
When running `expo upload:ios` on new project we should have better error message if it fails

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#1654]
```
[17:01:09]: [DevCenter] App 'xyz.bront.newblankproject' already exists, nothing to do on the Dev Center
[17:01:10]: Creating new app 'Blank Template' on App Store Connect
Failed to upload the standalone app to the app store.
{"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Creation of apps of this type is not available"], "info"=>nil}, "statusCode"=>"ERROR"}
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.13.1-osx/lib/vendor/ruby/2.2.0/gems/fastlane-2.141.0/spaceship/lib/spaceship/client.rb:714:in `parse_response'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.13.1-osx/lib/vendor/ruby/2.2.0/gems/fastlane-2.141.0/spaceship/lib/spaceship/tunes/tunes_client.rb:296:in `create_application!'
```

This error occurred because I need to accept new agreements, so we could match against this error and let the user know that and link them to https://appstoreconnect.apple.com/agreements/#/

**Comment by EvanBacon** [comment]
Closing as `expo upload:ios` is now deprecated in favor of `eas submit` in `eas-cli`. I'll add that this particular issue is also resolved in `eas submit`.
