### ISSUE TITLE
Jest fails on Expo projects upgraded to v31

### ISSUE THREAD

**Issue by FabianOMB** [expo/expo-cli#177]
## Description
Testing with Jest fails with message "SyntaxError: Unexpected token {" on Expo projects upgraded to v31

## Expected Behavior
Tests to run 

## Observed Behavior
When running npm test on the upgraded project the following error is presented 

```
 FAIL  __tests__/App-test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/fabian/TaBort2/node_modules/expo/build/environment/logging.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { Constants } from 'expo-constants';
                                                                                                    ^

    SyntaxError: Unexpected token {

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.require (node_modules/expo/build/Expo.js:280:1)
```

## Environment
  Expo CLI 2.3.8 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.10.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.5 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
      react-navigation: ^2.18.2 => 2.18.2 
    npmGlobalPackages:
      expo-cli: 2.3.8

## Reproducible Demo

To reproduce:
1. Create new Expo project 
expo init TaBort2  (select template tabs)

2. Test - It works fine
npm test

3. Remove folder node_modules

4. Reinstall all node_modules
npm install

5. Try to run and test
npm test
=> I get an error saying that it can't find jest.
"Cannot find module '/Users/fabian/TaBort2/node_modules/jest/bin/jest.js'"

6. install jest
npm install jest --save

7. Run test again
npm test
I now get the same behavior as in the upgraded projects with error "SyntaxError: Unexpected token {"

**Comment by brentvatne** [comment]
I did this and it worked, but I used yarn instead of npm. 

```
=> I get an error saying that it can't find jest.
"Cannot find module '/Users/fabian/TaBort2/node_modules/jest/bin/jest.js'"
```

this probably means there may be some bug in the version of npm that you're using, try updating to latest. jest is indeed a dependency of jest-expo so you don't need to install it manually

**Comment by brentvatne** [comment]
I did this and it worked, but I used yarn instead of npm. 

```
=> I get an error saying that it can't find jest.
"Cannot find module '/Users/fabian/TaBort2/node_modules/jest/bin/jest.js'"
```

this probably means there may be some bug in the version of npm that you're using, try updating to latest. jest is indeed a dependency of jest-expo so you don't need to install it manually
