### ISSUE TITLE
CLI 3.17.20 - unable to build an application

### ISSUE THREAD

**Issue by lukBakTsh** [expo/expo-cli#1843]
## Description

Unable to build an application using `expo build:ios` 

## Expected Behavior

Expo CLI will handle this process automatically or you will be able to use your own certificate.

#### Let Expo handle the process 
Unable to validate distribution certificate due to insufficient Apple Credentials
Unable to validate Push Keys due to insufficient Apple Credentials
✖ Provisioning profile is expired

```
Error: The provisioning profile we have on file is no longer valid.
    at SetupIosProvisioningProfile.open (/expo-cli@3.17.20/src/credentials/views/SetupIosProvisioningProfile.ts:59:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

#### I want to upload my own file

```
The Distribution Certificate is no longer valid on the Apple Developer Portal
```

## Environment
```
Expo CLI 3.17.20 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.6 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.3.7 => 4.3.7 
    npmGlobalPackages:
      expo-cli: 3.17.20
```

**Comment by dabhitapan** [comment]
Create a new Provisioning profile in your Apple Developer Account and use your new profile...
