### ISSUE TITLE
Error while ejecting a bare project

### ISSUE THREAD

**Issue by martinheidegger** [expo/expo-cli#1853]
## Description

For a test I created a simple bare project using the expo-cli and later ejected it.
During ejection I am receiving an error mentioning a missing module.

## Expected Behavior

run without issue...

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
⠴ Installing JavaScript dependencies.Cannot find module '@expo/package-manager'
Require stack:
- /Users/m/Desktop/test-exit/node_modules/expo-cli/build/commands/eject/Eject.js
- /Users/m/Desktop/test-exit/node_modules/expo-cli/build/commands/eject.js
- /Users/m/Desktop/test-exit/node_modules/expo-cli/build/commands/index.js
- /Users/m/Desktop/test-exit/node_modules/expo-cli/build/exp.js
- /Users/m/Desktop/test-exit/node_modules/expo-cli/bin/expo.js
(node:22975) UnhandledPromiseRejectionWarning: Error: Cannot find module 'getenv'
Require stack:
- /Users/m/Desktop/test-exit/node_modules/expo-cli/build/exp.js
- /Users/m/Desktop/test-exit/node_modules/expo-cli/bin/expo.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at _getenv (/expo-cli@3.17.21/src/exp.ts:14:1)
    at Command.<anonymous> (/expo-cli@3.17.21/src/exp.ts:100:13)
(node:22975) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22975) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Environment

```
 Expo CLI 3.17.21 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.11.1 - ~/.nvm/versions/node/v12.11.1/bin/node
      npm: 6.14.1 - ~/.nvm/versions/node/v12.11.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.6
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
```

## Reproducible Demo

```shell
mkdir test-exit
cd test-exit
expo init .
expo eject
```

**Comment by brentvatne** [comment]
something is wrong with your expo-cli installation. uninstall it and reinstall

`npm uninstall -g expo-cli && npm i -g expo-cli`

**Comment by danielholmes** [comment]
I received this error when using `expo-cli` in my project's `package.json`. Looks like it needs to be a global install

**Comment by brentvatne** [comment]
ah good call. yeah it's meant to be global - this is what we recommend in all our installation guide. we're likely split up expo-cli further in a way that should address this.
