### ISSUE TITLE
(expo build:ios --non-interactive) no longer works

### ISSUE THREAD

**Issue by patpaev** [expo/expo-cli#1873]
## Description

`expo build:ios --non-interactive` no longer works, which means we are unable to trigger the builds as part of our CI process. 

in version `3.11.x` this worked, now in version `3.17.24` (current at time of filing issue) it does not. 

## Expected Behavior

`expo build:ios --non-interactive` builds an ios binary

## Observed Behavior

(screenshot for easier reading/pretty colors)

<img width="827" alt="Screen Shot 2020-04-13 at 8 18 24 PM" src="https://user-images.githubusercontent.com/6847023/79173068-7fd5c700-7dc4-11ea-95ce-c54c6181fffe.png">

(and here's the copy pasted text)

```
- Making sure project is set up correctly...
[23:55:56] Checking if there is a build in progress...

[23:55:56] Fetching available credentials
[23:55:57] Unable to validate distribution certificate due to insufficient Apple Credentials
[23:55:57] Unable to determine validity of Push Keys due to insufficient Apple Credentials
[23:55:57] CommandError: Input is required, but Expo CLI is in non-interactive mode.
Required input:
> Push Notifications Key (Key ID: (removed), Team ID: **********)
>     not used by any apps
>     ✅ Currently valid on Apple's servers. 
>  Would you like to use this Push Key?
    at prompt (/expo-cli@3.17.24/src/prompt.ts:22:11)
    at CreateOrReusePushKey.open (/expo-cli@3.17.24/src/credentials/views/IosPushCredentials.ts:281:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at CredentialsManager.run (/expo-cli@3.17.24/src/credentials/route.ts:42:12)
    at runCredentialsManager (/expo-cli@3.17.24/src/credentials/route.ts:13:10)
    at IOSBuilder.produceCredentials (/expo-cli@3.17.24/src/commands/build/ios/IOSBuilder.ts:168:7)
    at IOSBuilder.prepareCredentials (/expo-cli@3.17.24/src/commands/build/ios/IOSBuilder.ts:124:7)
    at IOSBuilder.run (/expo-cli@3.17.24/src/commands/build/ios/IOSBuilder.ts:46:7)
    at IOSBuilder.command (/expo-cli@3.17.24/src/commands/build/BaseBuilder.ts:29:7)
    at Command.<anonymous> (/expo-cli@3.17.24/src/exp.ts:85:7) {
  code: 'NON_INTERACTIVE',
  isCommandError: true
}
[23:55:58] Failed to prepare all credentials. 
The next time you build, we will automatically use the following configuration:
[23:55:58]
[23:55:58] Project Credential Configuration:
[23:55:58]   Experience: @*********/*****, bundle identifier: (removed)
[23:55:58]     Provisioning profile (ID: (removed))
[23:55:58]     Apple Team ID: **********,  Apple Team Name: (removed)
[23:55:58]
[23:55:58]   Distribution Certificate - Certificate ID: (removed)
[23:55:58]     Apple Team ID: **********,  Apple Team Name: (removed)
[23:55:58]     used by
      @*********/***** ((removed))
[23:55:58] 
[23:55:58] Set EXPO_DEBUG=true in your env to view the stack trace.

Exited with code exit status 1
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

```
  Expo CLI 3.17.24 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 10.16.3 - ~/.asdf/installs/nodejs/10.16.3/bin/node
      npm: 6.9.0 - ~/.asdf/installs/nodejs/10.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^4.1.1 => 4.1.1
    npmGlobalPackages:
      expo-cli: 3.11.7
```

## Reproducible Demo

See terminal output above.

**Comment by brentvatne** [comment]
@quinlanj is working on this.

what is going on here, as far as we can tell is that this project doesn't have any credentials associated with it. this could be because you:
1) have not done a build for it before
2) ran build with `-c` / `--clear-credentials` flag or
3) the slug or username is different from your last build

we discussed this and decided that we will automatically select credentials based on our suggestions that we usually provide. so if you have done a build before and have valid credentials stored then we will use those.

**Comment by patpaev** [comment]
hi @brentvatne and @quinlanj 

appreciate the update here 😄 

for reference, I've ran the build in interactive mode, and retried with `--non-interactive`, but am still encountering the same issue. slug & username remain the same, and have not cleared credentials either.

**Comment by brentvatne** [comment]
@patpaev - we can't reproduce this. do you have an `owner` in your app.json by chance?

**Comment by patpaev** [comment]
@brentvatne no `owner`! I can try adding this. What is the value for `owner` used for in this context?

**Comment by patpaev** [comment]
Either way, adding the `owner` appears to have fixed the issue! Thank you very much for your help.

**Comment by brentvatne** [comment]
interesting. did you a specify a different owner than the user account that you are signed in as @patpaev?

**Comment by patpaev** [comment]
@brentvatne – same owner as I was signed into the expo cli with, but it seems it needed to be added to the `app.json` to get over that last hurdle for the Push Notifications Key...

Terminal output is now: 

```
[14:16:21] Unable to validate Push Keys due to insufficient Apple Credentials
✔ Successfully performed best effort validation of Provisioning Profile.
```

(And continues successfully with the build)

**Comment by brentvatne** [comment]
@patpaev - that's intentional -- we don't want to sign in to apple in non-interactive mode. if you do the build in interactive mode then we prompt you to sign in to apple in order to verify that the push key and other credentials that we have stored are still valid on apple's side. cc @quinlanj - perhaps we can just display a message like "Skipping credentials validation in non-interactive mode"
