### ISSUE TITLE
Error request failed with status code 400

### ISSUE THREAD

**Issue by KantaP** [expo/expo-cli#1885]
Error: Request failed with status code 400
    at createError (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

 It's working until today morning

**Comment by vulle5** [comment]
Same problem here when trying to run project on a device or simulator.

**Comment by Kerenby74** [comment]
Yes, I have the same problem, although everything was okay in the morning

**Comment by kamilmateusiak** [comment]
Hi. Please check the version of your `expo-cli`. After running `npm install -g expo-cli` it started working for me (it updated to the newest v3.18.0).

**Comment by vulle5** [comment]
Started working after re-installing expo-cli with npm.

**Comment by Kerenby74** [comment]
> Hi. Please check the version of your `expo-cli`. After running `npm install -g expo-cli` it started working for me (it updated to the newest v3.18.0).

worked for me =)

**Comment by brentvatne** [comment]
indeed you need to update to a more recent version of expo-cli with `npm i -g expo-cli

we don't support old versions indefinitely and recommend that you update frequently! we're going to add a more strongly worded notice when an update is available.

**Comment by rajshekhar150** [comment]
Error: Request failed with status code 400
    at createError (node_modules\axios\lib\core\createError.js:16:15)
    at settle (node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (node_modules\axios\lib\adapters\http.js:293:11)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    I am getting same issue can anyone help in order to resolve this

**Comment by duongnv1996** [comment]
I got this message also. How to fix that, anyone help us pls
