### ISSUE TITLE
Request failed with status code 400

### ISSUE THREAD

**Issue by lucifer2355** [expo/expo-cli#1887]
I am seeing this issue now. The first time it is happening for me with the expo.

Error: Request failed with status code 400
    at createError (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by lucifer2355** [comment]
I am already trying the previous solution but the error is still showing. please help me

**Comment by aberracja** [comment]
Same here

**Comment by borasumer** [comment]
Yeah, I have the same issue on simulators with LAN, working on the actual devices though. Tried to downgrade, upgrade both the expo-cli and the sdk, no help.

**Comment by lucifer2355** [comment]
upgrade expo-cli 3.18.0
