### ISSUE TITLE
Unable to init new project

### ISSUE THREAD

**Issue by skluthe** [expo/expo-cli#1995]
## Description
I'm currently unable to initialize a new project using expo-cli. When I run expo init project I get the following error:
`Invalid "exports" main target "index.js" defined in the package config /usr/lib/node_modules/expo-cli/node_modules/is-promise/package.json`

I already tried fresh installs of nodejs, npm, and expo-cli.

## Expected Behavior
A new project to me initialized
## Observed Behavior
Get the following error: 
`Invalid "exports" main target "index.js" defined in the package config /usr/lib/node_modules/expo-cli/node_modules/is-promise/package.json`

```
Error [ERR_INVALID_PACKAGE_TARGET] [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "index.js" defined in the package config /usr/lib/node_modules/expo-cli/node_modules/is-promise/package.json
    at resolveExportsTarget (internal/modules/cjs/loader.js:538:13)
    at resolveExportsTarget (internal/modules/cjs/loader.js:577:20)
    at applyExports (internal/modules/cjs/loader.js:451:14)
    at resolveExports (internal/modules/cjs/loader.js:504:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:628:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:939:27)
    at Function.Module._load (internal/modules/cjs/loader.js:835:27)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/lib/node_modules/expo-cli/node_modules/run-async/index.js:3:17)
```

Content of the file it's complaining about:
```
{
  "_from": "is-promise@^2.1.0",
  "_id": "is-promise@2.2.0",
  "_inBundle": false,
  "_integrity": "sha512-N/4ZxZGjDLAWJQNtcq1/5AOiWTAAhDwnjlaGPaC2+p3pQ+Ka2Dl/EL29DppuoiZ8Xr1/p/9ywBGGzHRPoWKfGA==",
  "_location": "/expo-cli/is-promise",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "is-promise@^2.1.0",
    "name": "is-promise",
    "escapedName": "is-promise",
    "rawSpec": "^2.1.0",
    "saveSpec": null,
    "fetchSpec": "^2.1.0"
  },
  "_requiredBy": [
    "/expo-cli/run-async"
  ],
  "_resolved": "https://registry.npmjs.org/is-promise/-/is-promise-2.2.0.tgz",
  "_shasum": "3ebfc546cee7064c314686279cc9df7bc2724715",
  "_spec": "is-promise@^2.1.0",
  "_where": "/usr/lib/node_modules/expo-cli/node_modules/run-async",
  "author": {
    "name": "ForbesLindesay"
  },
  "bugs": {
    "url": "https://github.com/then/is-promise/issues"
  },
  "bundleDependencies": false,
  "deprecated": false,
  "description": "Test whether an object looks like a promises-a+ promise",
  "devDependencies": {
    "better-assert": "^1.0.2",
    "mocha": "^7.1.1"
  },
  "exports": {
    "import": "index.mjs",
    "require": "index.js"
  },
  "files": [
    "index.js"
  ],
  "homepage": "https://github.com/then/is-promise#readme",
  "license": "MIT",
  "main": "index.js",
  "name": "is-promise",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/then/is-promise.git"
  },
  "scripts": {
    "test": "mocha -R spec"
  },
  "type": "module",
  "version": "2.2.0"
}
```
## Environment

```
  Expo CLI 3.18.6 environment info:
    System:
      OS: Linux 5.6 Manjaro Linux
      Shell: 5.0.16 - /bin/bash
    Binaries:
      Node: 13.13.0 - /usr/bin/node
      npm: 6.14.4 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
    npmGlobalPackages:
      expo-cli: 3.18.6

```

**Comment by brentvatne** [comment]
hi there!

this was caused by an update to the `is-promise` package that broke a bunch of other tools, basically anything that depended on `inquirer` - such as `create-react-app`(https://github.com/facebook/create-react-app/issues/8896)  and `expo-cli`.

the author of `is-promise` has resolved the issue: https://github.com/then/is-promise/issues/14#issuecomment-619417917

run `npm uninstall -g expo-cli` and then `npm install -g expo-cli` to get the fix!

**Comment by skluthe** [comment]
Will do. Thank you!
