### ISSUE TITLE
Android build fail

### ISSUE THREAD

**Issue by dougg0k** [expo/expo-cli#2044]
Hi,

I have been trying to generate a Android apk, and I am getting this error shown in the Expo Build Dashboard.

```
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:generateReleaseBuildConfig'.
[stderr] > org.xml.sax.SAXParseException; systemId: file:/app/turtle/workingdir/android/sdk37/android-shell-app/app/src/main/AndroidManifest.xml; lineNumber: 320; columnNumber: 22; The value of attribute "android:value" associated with an element type "meta-data" must not contain the '<' character.
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 40s
3 actionable tasks: 3 executed
Error: ./gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    ...
    at spawnAsync (/app/turtle/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnAsyncThrowError (/app/turtle/node_modules/@expo/xdl/build/detach/ExponentTools.js:190:45)
    at buildShellAppAsync (/app/turtle/node_modules/@expo/xdl/build/detach/AndroidShellApp.js:912:11)
    at async Object.createAndroidShellAppAsync (/app/turtle/node_modules/@expo/xdl/build/detach/AndroidShellApp.js:406:5)
    at async runShellAppBuilder (/app/turtle/build/builders/android.js:79:9)
    at async Object.buildAndroid [as android] (/app/turtle/build/builders/android.js:32:28)
    at async build (/app/turtle/build/jobManager.js:158:24)
    at async processJob (/app/turtle/build/jobManager.js:103:32)
    at async Object.doJob (/app/turtle/build/jobManager.js:35:5)
    at async main (/app/turtle/build/server.js:44:13)
```

These are the only metatag in the `AndroidManifest.xml` file
```

<meta-data android:name="expo.modules.updates.EXPO_UPDATE_URL" android:value="https://exp.host/@dougg0k/app" />
<meta-data android:name="expo.modules.updates.EXPO_SDK_VERSION" android:value="37.0.0" />
<meta-data android:name="expo.modules.updates.EXPO_RELEASE_CHANNEL" android:value="default" />
```

**Comment by dougg0k** [comment]
Nevermind, it was a "<" inside a string in the `app.json` that was causing that.
