### ISSUE TITLE
Crash when idle (Error: read ECONNRESET)

### ISSUE THREAD

**Issue by sarcadass** [expo/expo-cli#2095]
## Description

When idle for few minutes the server throws: `Error: read ECONNRESET`.
It's impossible to connect to the server after that and the hot reload/rebuild is not working anymore.
This issue was already raised (#519) and closed after a fix (#1368) by @kevgrig, but the problem is still  happening even if I start the server with `expo start -c` as recommended.

Other related issue: #1023.

## Expected Behavior

- `expo start -c`
- The server does not crash after multiples minutes idled

## Observed Behavior

- `expo start -c`
- Don't touch your computer for ~5 mins
- Following error is displayed on the terminal:
<img width="486" alt="Capture d’écran 2020-05-09 à 17 45 30" src="https://user-images.githubusercontent.com/2452603/81472209-16ad6c00-9229-11ea-80fd-fc734be6aa4b.png">

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

- Following error is displayed on the remote device:
<img width="378" alt="Capture d’écran 2020-05-09 à 17 44 37" src="https://user-images.githubusercontent.com/2452603/81472204-0eedc780-9229-11ea-9370-07eefac844bf.png">

## Environment

```
  Expo CLI 3.20.3 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v10.16.0/bin/npm
    IDEs:
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-dom: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-native-web: ^0.11.7 => 0.11.7 
      react-navigation: ^4.0.10 => 4.0.10 
    npmGlobalPackages:
      expo-cli: 3.20.3
```

## Reproducible Demo

- `expo start -c`
- Don't touch your computer for 5~10 mins
- Wait for expo-cli instance to crash

## Conclusion

The bug is not critical as we just have to relaunch the expo instance with `expo start -c`. But it is a little bit annoying.

**Comment by sarcadass** [comment]
This issue did not occur again after upgrading to the latest version `expo-cli@3.20.9`.
I am closing this issue.
