### ISSUE TITLE
Authentication with Apple Developer Portal failed!

### ISSUE THREAD

**Issue by karimcambridge** [expo/expo-cli#2100]
No matter what I use cmd line, powershell (& 7), this always occurs, even if i enter the credentials myself

```
$env:EXPO_APPLE_PASSWORD='****!'; expo build:ios --clear-credentials --apple-id ****@gmail.com
⚠️  expo build:ios currently only supports managed workflow apps.
If you proceed with this command, we can run the build for you but it will not include any custom native modules or changes that you have made to your local native projects.
Unless you are sure that you know what you are doing, we recommend aborting the build and doing a native release build through Xcode.
? Would you like to proceed? Yes
? Choose the build type you would like: archive

Checking if there is a build in progress...

Configuring credentials for kar in project name
Authenticating to Apple Developer Portal...
Authentication with Apple Developer Portal failed!
spawn bash ENOENT
Error: spawn bash ENOENT
    at notFoundError (C:\Users\kar2k\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\kar2k\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\kar2k\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

```
Expo CLI 3.20.3 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 13.7.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^37.0.8 => 37.0.8
      react: ^16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
```

**Comment by karimcambridge** [comment]
Okay so maybe the documentation does say we need to use WSL or have it enabled or something.

Maybe the CLI error could suggest the same.

Fixed it by using WSL Ubuntu after hours of googling.

**Comment by asherccohen** [comment]
I'm currently having this authentication problem. I'm on a Windows 10 machine, with all latest packages (expo-cli etc) and WSL enabled.

I must say in advance that I did try to upload my .p12 the first time I ran the expo:build ios command. That said it failed because my .p12 had no password while this is required for expo servers.

I was also doing it from bash on windows, then realised I needed WSL, so after that failed i tried with --clear-credentials but apparently this only works after you've logged in to the apple portal (am I correct?). So I believe it's still trying to use my original Distribution Certificate, because I see this:

```
Fetching available credentials
? Do you have access to the Apple account that will be used for submitting this app to the App Store? No
No problem! ���
We can’t auto-generate credentials if you don’t have access to the main Apple account. 
But we can still set it up if you upload your credentials.
Unable to determine validity of Distribution Certificates.
```
As you can see I tried answering 'no' to skip Apple authentication, but it still tries to prompt me the apple id auth.

After typing the 2FA sms in the terminal I get:

```
Requesting session...
Authentication with Apple Developer Portal failed!
Failed to set up Distribution Certificate
Failed to prepare all credentials. 
The next time you build, we will automatically use the following configuration:

Project Credential Configuration:
  Experience: myAPP, bundle identifier: myAPPIdentifier
    Provisioning profile is missing. It will be generated during the next build

Reason: Unknown reason, raw: "Unauthorized Access"
Error: Reason: Unknown reason, raw: "Unauthorized Access"
```
My diagnostics:
```
  Expo CLI 3.21.5 environment info:
    System:
      OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
      Yarn: 1.22.4 - /mnt/c/Users/asher/AppData/Roaming/npm/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
    npmPackages:
      @expo/webpack-config: ^0.12.12 => 0.12.12
      expo: 37.0.7 => 37.0.7 
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: 0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.21.5
```

I tried every suggestion I found:
- wsl
- answering no to skip apple auth
- --clear-credentials
- tried with powershell

Any help would be appreciated. Tx.

**Comment by asherccohen** [comment]
Anyone having this same issue?I'm stuck and can't deliver my app to ios users.

**Comment by karimcambridge** [comment]
> Anyone having this same issue?I'm stuck and can't deliver my app to ios users.

Are you using WSL?

**Comment by bantingGamer** [comment]
This only happens to me when on windows machine. Soon as I tried it on macOS it ran perfectly.
