### ISSUE TITLE
app.config.js breaks with expo-cli@3.20.6

### ISSUE THREAD

**Issue by nbgoodall** [expo/expo-cli#2127]
## Description

Updating to expo-cli@3.20.6 breaks `app.config.js` with `expo publish`. Downgrading to 3.20.5 works fine.

Using the documented file at https://docs.expo.io/workflow/configuration/:

```
// app.config.js

const myValue = 'My App';

export default {
  name: myValue,
  version: process.env.MY_CUSTOM_PROJECT_VERSION || '1.0.0',
  // All values in extra will be passed to your app.
  extra: {
    fact: 'kittens are cool',
  },
};
```

## Observed Behavior

```
Failed to read config at: /Users/.../app/app.config.js
ConfigError: Failed to read config at: /Users/.../app/app.config.js
    at Object.getDynamicConfig (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config/src/getConfig.ts:39:9)
    at getConfig (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config/src/Config.ts:121:62)
    at action (/usr/local/lib/node_modules/expo-cli/src/commands/publish.ts:34:24)
    at /usr/local/lib/node_modules/expo-cli/src/exp.ts:317:12
    at Command.<anonymous> (/usr/local/lib/node_modules/expo-cli/src/exp.ts:82:13)
error Command failed with exit code 1.
```

## Environment

```
Expo CLI 3.20.6 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.7
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.20.6
```

## Reproducible Demo

Running expo-cli 3.20.6:
```
expo init myNewProject --template blank && cd myNewProject

echo "// app.config.js

const myValue = 'My App';

export default {
  name: myValue,
  version: process.env.MY_CUSTOM_PROJECT_VERSION || '1.0.0',
  // All values in extra will be passed to your app.
  extra: {
    fact: 'kittens are cool',
  },
};" > app.config.js

expo publish

```

**Comment by brentvatne** [comment]
I rolled back the latest to 3.20.5 until we can figure this out. Not sure what is going on here as it works in development but after building and publishing to npm I see the same issue.

**Comment by brentvatne** [comment]
thanks for pointing this out, released 3.20.8 which fixes the issue!

**Comment by dougg0k** [comment]
I still got the issue with `expo-cli` version 3.21.3

```
❯ npx expo start -c --android
Failed to read config at: /home/zephyrus/projects/my_proj_root_folder/app.config.js
ConfigError: Failed to read config at: /home/zephyrus/projects/my_proj_root_folder/app.config.js
    at Object.getDynamicConfig (/home/zephyrus/.nvm/versions/node/v12.16.2/lib/node_modules/expo-cli/node_modules/@expo/config/src/getConfig.ts:39:9)
    at getConfig (/home/zephyrus/.nvm/versions/node/v12.16.2/lib/node_modules/expo-cli/node_modules/@expo/config/src/Config.ts:121:62)
    at isWebOnly (/home/zephyrus/.nvm/versions/node/v12.16.2/lib/node_modules/expo-cli/src/commands/start.ts:65:19)
    at normalizeOptionsAsync (/home/zephyrus/.nvm/versions/node/v12.16.2/lib/node_modules/expo-cli/src/commands/start.ts:83:33)
    at /home/zephyrus/.nvm/versions/node/v12.16.2/lib/node_modules/expo-cli/src/commands/start.ts:350:41
    at /home/zephyrus/.nvm/versions/node/v12.16.2/lib/node_modules/expo-cli/src/exp.ts:315:12
    at Command.<anonymous> (/home/zephyrus/.nvm/versions/node/v12.16.2/lib/node_modules/expo-cli/src/exp.ts:80:13)
❯ npx expo --version
3.21.3
```

**Comment by jeroen-van-dijk** [comment]
Ran into this issue as well. Found a workaround.
You can change the name of `app.config.json` (or `.ts`) to something invalid `app.configgg.json` e.g. and you'll get a more convenient error message in your console

**Comment by jayu** [comment]
I also have this issue, however any of above fixes (version change, renaming) worked for me xD

**Comment by lucasvieceli** [comment]
I am in version 3.23.2 and I have the same problem

**Comment by brentvatne** [comment]
@lucasvieceli - create a new issue and fill in the issue template
