### ISSUE TITLE
Problem with project detach 

### ISSUE THREAD

**Issue by Kison** [expo/expo-cli#216]
Hi guys, I need to make a signed build for publish application into google play. But when I tried to make a build I got such error - Error: ENOENT: no such file or directory, open android\app\src\main\assets\shell-app-manifest.json

I think that the reason of above error might be error that I got when I made project detach
Detach output
```
$ expo-cli eject --eject-method expoKit
[15:46:53] Making sure project is set up correctly...
[15:46:56] Your project looks good!
[15:46:58]
Warning! We found at least one file where your project imports the Expo SDK:
....

If you choose the "plain" React Native option below, these imports will stop working.
We strongly recommend that you read this document before you proceed:
  https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md
Ejecting is permanent! Please be careful with your selection.

Validating project manifest...
Skipping iOS because you are not running macOS.
Moving Android project files...
Downloading Android code...
{ buildPhase: 'copying initial shell app files' } 'Warning: Could not copy maven to shell app directory.'
Updating Android app...
{ buildPhase: 'running shell app modifications' } 'Warning: No config file specified.'
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
(node:8780) UnhandledPromiseRejectionWarning: Error: spawn /bin/cp ENOENT
    at notFoundError (C:\Users\...\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\...\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\...\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
(node:8780) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8780) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Cleaning up Android...
Android detach is complete!

Writing ExpoKit configuration...
Installing the Expo fork of react-native...
Unable to install the Expo fork of react-native.
Please install react-native@https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz to complete detaching.
Installing 'expokit' package...
Unable to install expokit@31.0.2.
Please install manually to complete detaching.
Finished detaching your project! Look in the `android` and `ios` directories for the respective native projects. Follow the ExpoKit guide at https://docs.expo.io/versions/latest/guides/expokit.html to get your project running.
[15:47:38] Ejected successfully!
Please consider letting us know why you ejected in this survey:
  https://goo.gl/forms/iD6pl218r7fn9N0d2
```

The same error I got when I tried to make detach with `exp detach`

Env info
```
Expo CLI 2.4.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.1.0.0 AI-173.4720617
```

**Comment by tcdavis** [comment]
It seems like the error on detach is likely the issue.  What shell are you using?

**Comment by Kison** [comment]
@tcdavis, Generally I am using `git bash`.

**Comment by tcdavis** [comment]
That is probably it; git bash isn't supported. Try using cmd.exe, PowerShell or Bash (on WSL)

**Comment by Kison** [comment]
Thanks for the approximate reason, I will check it

**Comment by Kison** [comment]
I have enabled WSL for Windows and installed Ubuntu on Windows. Output from Bash (on WSL) are almost the same as without it, I guess that is not the reason of the problem.

```
Validating project manifest...
Skipping iOS because you are not running macOS.
Moving Android project files...
Downloading Android code...
{ buildPhase: 'copying initial shell app files' } 'Warning: Could not copy maven to shell app directory.'
Updating Android app...
{ buildPhase: 'running shell app modifications' } 'Warning: No config file specified.'
`sips` utility may or may not work outside of macOS
Failed to resize app icons. Your full size icon will be copied to all android/app/src/main/res directories. For best quality, we recommend providing downscaled versions.
`sips` utility may or may not work outside of macOS
`sips` utility may or may not work outside of macOS
`sips` utility may or may not work outside of macOS
`sips` utility may or may not work outside of macOS
`sips` utility may or may not work outside of macOS
Cleaning up Android...
Android detach is complete!

Writing ExpoKit configuration...
Installing the Expo fork of react-native...
Unable to install the Expo fork of react-native.
Please install react-native@https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz to complete detaching.
Installing 'expokit' package...
Unable to install expokit@31.0.2.
Please install manually to complete detaching.
Finished detaching your project! Look in the `android` and `ios` directories for the respective native projects. Follow the ExpoKit guide at https://docs.expo.io/versions/latest/guides/expokit.html to get your project running.
```

**Comment by jakubste** [comment]
Well, it's far from being "almost the same". This one looks like it succeeded without any problems. Is the build still failing?

**Comment by Kison** [comment]
Hi @jakubste, thanks for response, as you can see warnings a still same in both outputs
1. Warning: Could not copy maven to shell app directory.
2. Warning: No config file specified.

But, today I have found recommendation regarding this error
`Error: ENOENT: no such file or directory, open android\app\src\main\assets\shell-app-manifest.json`
Looks like this file should create automatically after publish. I have not checked it yet, I will let you know if it help.

**Comment by Kison** [comment]
`shell-app-manifest.json` was created after publishing from Bash  (on WSL) and build works well now. Guys thanks for your help.
