### ISSUE TITLE
Project doesn't run after installing any component library

### ISSUE THREAD

**Issue by agar98** [expo/expo-cli#2193]
## Description
Have been using `npx expo-cli init project_name` for creating my react native projects.
It was working perfectly till I updated expo-cli to version 3.21.3 from 3.20
Now, when I install any library (tried installing the following in separate projects - react navigation, react native elements, react native paper, redux), and then run `npm start`, it gives an error saying that:
"Error: react-native is not installed. Please run `npm install` or `yarn` in your project directory.
Couldn't start project. Please fix the errors and restart the project."

## Expected Behavior
Usually, after installing the libraries, I could just run `npm start` and the qr code & everything would show up. 

## Observed Behavior
But now I get an error which tells me to run 'npm install' first. After running `npm install`, `npm start` works fine, but when I open the project using expo on a device, instead of the usual `Finished building JavaScript bundle in xyz ms.` , there is a huge Stacktrace coming up 

![image](https://user-images.githubusercontent.com/43934646/83039609-6f656d00-a04f-11ea-9111-18702d6e79e5.png)

```
Error: react-native is not installed. Please run `npm install` or `yarn` in your project directory.
Couldn't start project. Please fix the errors and restart the project.
Error: Couldn't start project. Please fix the errors and restart the project.
    at startExpoServerAsync (C:\@expo\xdl@57.9.12\src\Project.ts:2089:11)
    at Object.startAsync (C:\@expo\xdl@57.9.12\src\Project.ts:2406:5)
    at action (C:\Users\adity\AppData\Roaming\npm\node_modules\expo-cli\src\commands\start.ts:181:3)
    at C:\Users\adity\AppData\Roaming\npm\node_modules\expo-cli\src\commands\start.ts:354:16
    at Command.<anonymous> (C:\Users\adity\AppData\Roaming\npm\node_modules\expo-cli\src\exp.ts:80:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\adity\AppData\Roaming\npm-cache\_logs\2020-05-27T15_18_08_998Z-debug.log
```

## Environment
Expo CLI 3.21.3 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\adity\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
    npmPackages:
      expo: ~37.0.3 => 37.0.12
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native-web: ~0.11.7 => 0.11.7

**Comment by agar98** [comment]
Alright, found the cause.
For a package I had installed yarn as well.
Now because of that, somehow expo decided to use yarn instead of npm for my projects. 
Using `expo init projectName --npm` fixed my problem.
