### ISSUE TITLE
request to https://registry.npmjs.org/expo-template-blank failed, reason: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Kannannagaraj** [expo/expo-cli#2194]
request to https://registry.npmjs.org/expo-template-blank failed, reason: unable to get local issuer certificate
FetchError: request to https://registry.npmjs.org/expo-template-blank failed, reason: unable to get local issuer certificate
    at ClientRequest.<anonymous> (C:\Users\<username>\AppData\Roaming\npm\node_modules\expo-cli\node_modules\minipass-fetch\lib\index.js:97:14)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:215:7)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

anyone having any idea?

tired below steps:

npm config set registry http://registry.npmjs.org/
npm config set strict-ssl false
NODE_TLS_REJECT_UNAUTHORIZED =0

**Comment by brentvatne** [comment]
can you try all of the solutions from https://stackoverflow.com/questions/36494336/npm-install-error-unable-to-get-local-issuer-certificate?

this is an issue with npm and your machine config and not an expo-cli issue (as far as i can tell), fwiw
