### ISSUE TITLE
Error userPackagerOpts.sourceExts is not iterable when sourceExts is not defined in app.json

### ISSUE THREAD

**Issue by davidvartanian** [expo/expo-cli#2198]
## Description
I started getting this error after upgrading my project's dependencies and npm global and local packages after about two months (from March to May 2020).
As a result, Expo was updated from v36 to v37 and plenty of dependencies were udpated as well.

## Expected Behavior
Expo commands should work normally.

## Observed Behavior
Running `expo start` started failing.

```
userPackagerOpts.sourceExts is not iterable
TypeError: userPackagerOpts.sourceExts is not iterable
    at startReactNativeServerAsync (/@expo/xdl@57.9.12/src/Project.ts:1788:80)
    at Object.startAsync (/@expo/xdl@57.9.12/src/Project.ts:2407:5)
    at action (/Users/davidvartanian/.nvm/versions/node/v12.16.2/lib/node_modules/expo-cli/src/commands/start.ts:181:3)
    at /Users/davidvartanian/.nvm/versions/node/v12.16.2/lib/node_modules/expo-cli/src/commands/start.ts:354:16
    at Command.<anonymous> (/Users/davidvartanian/.nvm/versions/node/v12.16.2/lib/node_modules/expo-cli/src/exp.ts:80:7)
```

## Environment
```
  Expo CLI 3.21.3 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.2/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.16.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.12 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ^0.11.7 => 0.11.7 
      react-navigation: ^4.3.9 => 4.3.9 
    npmGlobalPackages:
      expo-cli: 3.21.3
```

## Reproducible Demo

This code reads `userPackagerOpts.sourceExts` assuming it's an iterable.
So, just declaring it gets rid of the error. However, it shouldn't be mandatory if a fallback value was defined.
https://github.com/expo/expo-cli/blob/master/packages/xdl/src/Project.ts#L1783

**Comment by brentvatne** [comment]
what is the value of your sourceExts config?

**Comment by brentvatne** [comment]
also, i would recommend migrating away from this app.json config, we're likely going to deprecate it in favor of using metro.config.js: https://docs.expo.io/guides/customizing-metro/

**Comment by brentvatne** [comment]
fixed the error you pointed out in issue title in https://github.com/expo/expo-cli/commit/1443505800d7b0f3686c2924e606c79153a85e89 - thanks

**Comment by c316** [comment]
@brentvatne Do you know when this fix will make it to expo-cli, or what version it will be in? 

Also, for anyone coming here from Google, I reverted to 3.21.1 and it works.

**Comment by brentvatne** [comment]
it'll go in the next release. for now you can continue using the latest version but just add `"sourceExts": []` to your packagerOpts
