### ISSUE TITLE
"expo diagnostics" returns error 500

### ISSUE THREAD

**Issue by borgogelli** [expo/expo-cli#221]
Command:

expo diagnostics

Output:

  Expo CLI 2.4.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.9.0-20180706.1017 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

  Diagnostics report:
-[11:36:37] Request failed with status code 500
[11:36:37] Error: Request failed with status code 500
    at createError (...\AppData\Roaming\npm\node_modules\expo-cli\node_modules\axios\lib\core\createError.js:16:15)
    at settle (...\AppData\Roaming\npm\node_modules\expo-cli\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (...\AppData\Roaming\npm\node_modules\expo-cli\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by SynZhang** [comment]
I had a similar problem with 503 error.

![image](https://user-images.githubusercontent.com/678248/49154500-75439a80-f353-11e8-8620-a16eb38638a9.png)

**Comment by rdjpalmer** [comment]
I'm having the issue too:

```
$ EXPO_DEBUG=true expo diagnostics
[16:44:22] Generating diagnostics report...
[16:44:22] You can join our slack here: https://slack.expo.io/.

  Expo CLI 2.4.3 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.12.0 - ~/.nvm/versions/node/v10.12.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.2
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1

  Diagnostics report:
|[16:44:26] Request failed with status code 500
[16:44:26] Error: Request failed with status code 500
    at createError (/Users/rdjpalmer/.config/yarn/global/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/rdjpalmer/.config/yarn/global/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/rdjpalmer/.config/yarn/global/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by SynZhang** [comment]
The error 503 was resolved after update to 2.5.0.

**Comment by jakubste** [comment]
The logs that 500 happened obviously is not enough for us to even start thinking about this, guys. More info needed. Did you debug this? Are behind some proxy/VPN? What country are you in? 
@rdjpalmer you posted logs from version 2.4.3 and the current one is 2.5.0. What exactly you were expecting other than "please update `expo-cli`"?

**Comment by rdjpalmer** [comment]
@jakubste No proxy or VPN. I'm UK based. I'm not even sure how I would go about debugging this, so no I haven't. I only added to this issue because I was logging another issue in the main expo repo.

FWIW, I had only just upgraded `expo-cli` via `yarn global add expo-cli` and this is the version it install and it did *not* give me "please update `expo-cli`" at all

**Comment by jakubste** [comment]
Is this happening always when you run `expo diagnostics`?

**Comment by borgogelli** [comment]
Today it works as expectd. Does it mean it was a server side fault ? 
Never mind today the command works fine with Expo CLI 2.4.3.
Thank you all.
As soon as @rdjpalmer will reply back I will close the issue.

**Comment by jakubste** [comment]
Perhaps something on the server side. Or some transient error.

**Comment by rdjpalmer** [comment]
@jakubste happens 100% of the time and is still happening unfortunately. I've logged out the response:

```js
{ status: 500,
  statusText: 'Internal Server Error',
  headers:
   { server: 'nginx/1.13.12',
     date: 'Thu, 29 Nov 2018 15:07:17 GMT',
     'content-type': 'text/plain; charset=utf-8',
     'content-length': '21',
     connection: 'close',
     'strict-transport-security': 'max-age=15724800' },
  config:
   { url: 'https://exp.host/--/api/uploadDiagnostics/%5B%7B%7D%5D',
     method: 'put',
     data:
      <Buffer 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 39 36 31 38 39 35 31 34 31 35 34 39 31 38 38 33 33 33 38 31 34 39 ... >,
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type':
         'multipart/form-data; boundary=--------------------------961895141549188333814952',
        'Exp-ClientId': 'c-hbpuBCRfRSWA2Kqlj27AYw',
        'User-Agent': 'axios/0.19.0-beta.1',
        'Content-Length': 1796931 },
     transformRequest: [ [Function: transformRequest] ],
     transformResponse: [ [Function: transformResponse] ],
     timeout: 0,
     adapter: [Function: httpAdapter],
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus] },
  request:
   ClientRequest {
     _events:
      { socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: null,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'exp.host',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'exp.host',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 4555,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'exp.host',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'exp.host',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 4555,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     _header:
      'PUT /--/api/uploadDiagnostics/%5B%7B%7D%5D HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: multipart/form-data; boundary=--------------------------961895141549188333814952\r\nExp-ClientId: c-hbpuBCRfRSWA2Kqlj27AYw\r\nUser-Agent: axios/0.19.0-beta.1\r\nContent-Length: 1796931\r\nHost: exp.host\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'PUT',
     path: '/--/api/uploadDiagnostics/%5B%7B%7D%5D',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [TLSSocket],
        connection: [TLSSocket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 500,
        statusMessage: 'Internal Server Error',
        client: [TLSSocket],
        _consuming: false,
        _dumped: false,
        req: [Circular],
        responseUrl: 'https://exp.host/--/api/uploadDiagnostics/%5B%7B%7D%5D',
        redirects: [] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable:
      Writable {
        _writableState: [WritableState],
        writable: true,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 1796931,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl: 'https://exp.host/--/api/uploadDiagnostics/%5B%7B%7D%5D' },
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]:
      { accept: [Array],
        'content-type': [Array],
        'exp-clientid': [Array],
        'user-agent': [Array],
        'content-length': [Array],
        host: [Array] } },
  data: 'Internal Server Error' }
```

**Comment by jakubste** [comment]
I believe the request is failing for unauthorized users. Which is definitely not something we would want, especially with such an error code...

**Comment by rdjpalmer** [comment]
Logging in fixed it, thanks! I guess I become logged out upon upgrading the cli?

**Comment by borgogelli** [comment]
Confirmed. If I am not logged in, the error code returned is 500. It should be 401 or 403. When I am logged in, it works fine. 

Bye
