### ISSUE TITLE
Error: Cannot find module '/scripts/createManifest.js'

### ISSUE THREAD

**Issue by guiferpa** [expo/expo-cli#2232]
## Description
I getting an unexpected error when I going to build my release as signed APK.

## Command executation

```
./gradlew bundleRelease
```

## Error report
```
> Task :app:createReleaseExpoManifest FAILED
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module '/scripts/createManifest.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:createReleaseExpoManifest'.
> Process 'command 'node'' finished with non-zero exit value 1
```

## Environment
```
Expo CLI 3.21.5 environment info:
    System:
      OS: Linux 5.6 Fedora 32 (Workstation Edition) 32 (Workstation Edition)
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.16.3 - ~/.asdf/installs/nodejs/12.16.3/bin/node
      Yarn: 1.22.4 - /usr/bin/yarn
      npm: 6.14.4 - ~/.asdf/installs/nodejs/12.16.3/bin/npm
    npmPackages:
      expo: ~37.0.3 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.21.5
```

I am depends on this problem solution so much

**Comment by brentvatne** [comment]
please explain more about your project. the package.json is incomplete. the module that your project is trying to find lives in expo-updates which you seem to have removed from your package.json

**Comment by brentvatne** [comment]
going to close this but if you can re-create an issue with a reproducible example or more information we can help.

for now, the issue seems to be that the project is not configured properly.  please create a new project from a "bare" template when running `expo init` and compare your project to that.

**Comment by guiferpa** [comment]
@brentvatne  that's okay I'll try to do it.

**Comment by guiferpa** [comment]
Well, I just tried to do it and I got the same error.

**I'll step by step**

1. I executed `yarn start` server Metro Bundler
2. I executed `yarn android --deviceId emulator-5554`

Just did it. At the end I catch the same error

```json
> Task :react-native-reanimated:compileReleaseJavaWithJavac
Note: /home/guiferpa/Projects/src/github.com/bechef-tech/bechef-delivery/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/guiferpa/Projects/src/github.com/bechef-tech/bechef-delivery/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :app:createReleaseExpoManifest FAILED
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module '/scripts/createManifest.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:createReleaseExpoManifest'.
> Process 'command 'node'' finished with non-zero exit value 1
```

Now I used `expo init` from bare template, but when I got the same error the first time I was using `npx create-react-native-app <app-name>` to build the project.

I don't have any idea what it can be.

Looking for some approach I found this issue with the same problem.
https://github.com/expo/expo/issues/8547

**My package.json file**

```json
{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "@fortawesome/react-native-fontawesome": "^0.2.5",
    "expo": "~37.0.3",
    "expo-splash-screen": "^0.2.3",
    "expo-updates": "^0.2.7",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "~0.61.5",
    "react-native-elements": "^2.0.2",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-reanimated": "~1.7.0",
    "react-native-screens": "~2.2.0",
    "react-native-svg": "^12.1.0",
    "react-native-unimodules": "~0.9.0",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "jest": "~25.2.6",
    "react-test-renderer": "~16.9.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}
```

**Comment by brentvatne** [comment]
can you share your project with me privately?

**Comment by guiferpa** [comment]
@brentvatne Okay, no problem

**Comment by guiferpa** [comment]
Hey @brentvatne repo invite sent

**Comment by guiferpa** [comment]
Many thanks for attention @brentvatne but I decided to use Java Android for the project.
