### ISSUE TITLE
Restart bundler fails with "TypeError: Cannot read property 'post' of null"

### ISSUE THREAD

**Issue by fson** [expo/expo-cli#224]
## Description

Restarting the bundler from the terminal UI fails with `TypeError: Cannot read property 'post' of null`.

## Expected Behavior

Pressing `shift+r` in the terminal should restart the Expo CLI server and Metro bundler.

## Observed Behavior

The CLI crashes with the following error:
```
[15:41:23] Restarting Metro Bundler and clearing cache...
[15:41:25] Starting Metro Bundler on port 19001.
[15:41:25] Your JavaScript transform cache is empty, rebuilding (this may take a minute).

/Users/ville/Projects/expo/expo-cli/node_modules/@expo/ngrok/index.js:154
		api.post(
      ^
TypeError: Cannot read property 'post' of null
    at Timeout.retry [as _onTimeout] (/Users/ville/Projects/expo/expo-cli/node_modules/@expo/ngrok/index.js:154:7)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
```

## Environment

```
  Expo CLI 2.3.5 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.2.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 2.3.5
```
Also specify:

- Phone/emulator/simulator platform, model and version: iOS 12.1

**Comment by N1ghtly** [comment]
I am getting this as well. Did you find a solution yet?

**Comment by fson** [comment]
This issue has been fixed in the latest version of Expo CLI. You can upgrade with `npm install -g expo-cli`.
