### ISSUE TITLE
- Applying iOS configurationThe system cannot find the path specified. spawn /bin/cp ENOENT

### ISSUE THREAD

**Issue by hatim85f** [expo/expo-cli#2262]
I have that issue while I am trying to eject my expo project. for more than 3 weeks I am rounding everywhere in the web to find anything solving that with no hope 
It's very bad when I need just to use one extra library while it's not working with EXPO 

` Applying iOS configurationThe system cannot find the path specified.
spawn /bin/cp ENOENT
Error: spawn /bin/cp ENOENT
    at notFoundError (C:\Users\hatim_8pgcn2n\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\hatim_8pgcn2n\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\hatim_8pgcn2n\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)`

> Expo CLI 3.21.5 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~37.0.3 => 37.0.12
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5
      react-native-web: ~0.11.7 => 0.11.7

**Comment by brentvatne** [comment]
hi there! this is fixed and you will now receive a warning instead if this does not work, and eject will continue successfully

**Comment by hatim85f** [comment]
thank you @brentvatne  for your response actually I just upgraded to the new version couple hours ago, still didn't try to eject but I will let you know if it's done or still having the same error

**Comment by dysuryawanshi** [comment]
It's successfully ejected.
