### ISSUE TITLE
Expo commands returning 502/504s

### ISSUE THREAD

**Issue by 1337LutZ** [expo/expo-cli#2300]
I've talked to @quinlanj on the Expo Slack and she asked me to create a bug report here with my use cases.

## Description

When creating an Expo build using the expo-cli it will quite often result an `504 Gateway Timeout` error when running any `expo` related cli task.

These errors got much worse lately and are costing our developers quite some valuable development/testing time due to having manually retrigger builds that fail.

## Expected Behavior

When I run `expo "login" "--non-interactive" "-u" "$EXPO_USERNAME" "-p" "$EXPO_PASSWORD"` I expect to successfully login

When I run `expo build:ios --release-channel test --non-interactive --no-publish --apple-id $APPLE_ID` I expect it to succesfully build

When I run `expo build:android --release-channel test --non-interactive --no-publish` I expect it to sucessfully build

When I run `curl -o app.ipa "$(expo url:ipa --non-interactive)"` or `curl -o app.apk "$(expo url:apk --non-interactive)"` I expect it to sucessfully download my builds.

## Observed Behavior

**`expo "login" "--non-interactive" "-u" "$EXPO_USERNAME" "-p" "$EXPO_PASSWORD"`**
```
[13:19:21] Request failed with status code 504
[13:19:21] Error: Request failed with status code 504
    at createError (/Users/vagrant/.config/yarn/global/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/vagrant/.config/yarn/global/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/vagrant/.config/yarn/global/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**`expo build:ios --release-channel test --non-interactive --no-publish --apple-id $APPLE_ID` or `expo build:android --release-channel test --non-interactive --no-publish`**
```
[10:31:08] You can monitor the build at
 https://expo.io/dashboard/[REDACTED]/builds/XXX
[10:31:08] Waiting for build to complete.
You can press Ctrl+C to exit. It won't cancel the build, you'll be able to monitor it at the printed URL.
- 
[10:33:39] Request failed with status code 504
[10:33:39] Error: Request failed with status code 504
    at createError (/Users/vagrant/.config/yarn/global/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/vagrant/.config/yarn/global/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/vagrant/.config/yarn/global/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**`curl -o app.ipa "$(expo url:ipa --non-interactive)"` or `curl -o app.apk "$(expo url:apk --non-interactive)"`**
```
++ expo url:ipa --non-interactive
[14:22:06] Request failed with status code 504
[14:22:06] Error: Request failed with status code 504
    at createError (/Users/vagrant/.config/yarn/global/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/vagrant/.config/yarn/global/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/vagrant/.config/yarn/global/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
+ curl -o app.ipa ''
curl: (3) URL using bad/illegal format or missing URL
```

## Environment

**Output `expo diagnostics`**
```
Expo CLI 3.21.9 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.17.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.6/11N700h - /usr/bin/xcodebuild
```

**Bitrise CICD**
Stack: Xcode 11.6.x, on macOS 10.15.4
Elite machine: 4xCPU (Intel Xeon E5-1650 v2) / 8 GB RAM

## Reproducible Demo

I dont have a demo, but extensive logs and description of the used commands.

**Comment by 1337LutZ** [comment]
Sometimes we also get a `502` for a change
```
+ expo build:ios --release-channel test --non-interactive --no-publish --apple-id XXXXXX
- Making sure project is set up correctly...
[12:30:06] Request failed with status code 502
[12:30:06] Error: Request failed with status code 502
    at createError (/Users/vagrant/.config/yarn/global/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/vagrant/.config/yarn/global/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/vagrant/.config/yarn/global/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by WillemLabu** [comment]
Can confirm the same happens for me using `expo-cli@3.21.10`

Affected commands that I have tried:

- `expo login` → `502`
- `expo publish --release-channel someChannel` → `504` & `503`

Will try and downgrade `expo-cli` and update this.

**Comment by WillemLabu** [comment]
This issue seems to have been resolved.

**Comment by 1337LutZ** [comment]
I will monitor it on our 3 projects, keep you posted.

**Comment by 1337LutZ** [comment]
Yesterday I once more got a 502:
```
=======================
Login 🍏
=======================
[19:59:55] Request failed with status code 502
[19:59:55] Error: Request failed with status code 502
    at createError (/Users/vagrant/.config/yarn/global/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/vagrant/.config/yarn/global/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/vagrant/.config/yarn/global/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | Expo Login (exit code: 1)                                     | 40.62 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-script/issues             |
| Source: https://github.com/bitrise-io/steps-script                           |
+---+---------------------------------------------------------------+----------+
```

**Comment by oporter1** [comment]
@1337LutZ I am running into the same issue. Do you have any updates?

**Comment by 1337LutZ** [comment]
> @1337LutZ I am running into the same issue. Do you have any updates?

Yes, same here:
```
[06:49:07] Looking for releases...
[06:49:07] Using existing release on channel "test":
publicationId: xxx
  publishedTime: xxx
[06:49:07] Checking if this build already exists...
[06:49:36] Request failed with status code 502
[06:49:36] Error: Request failed with status code 502
    at createError (/Users/vagrant/.config/yarn/global/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/vagrant/.config/yarn/global/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/vagrant/.config/yarn/global/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
|   
```

**Comment by brentvatne** [comment]
there were some outages recently, you can always check the status at https://status.expo.io/. sorry for the trouble!

**Comment by brentvatne** [comment]
i'll actually leave this open for @quinlanj since she requested that you open it

**Comment by 1337LutZ** [comment]
> there were some outages recently, you can always check the status at https://status.expo.io/. sorry for the trouble!
> 
> you can also follow https://twitter.com/expo_status for updates

Hey Brent,
I'm well aware of the outages, but these reports were before and after the outages which were on the 24th.

This started around 2-3 weeks ago and seems a lot better after the outages on the 24th, however I do still get 502s.

Thanks for checking in.

**Comment by brentvatne** [comment]
@quinlanj is away for the weekend hopefully will have time to investigate soon! cheers

**Comment by 1337LutZ** [comment]
> @quinlanj is away for the weekend hopefully will have time to investigate soon! cheers

No rush! Have a good weekend.

**Comment by quinlanj** [comment]
hey @1337LutZ , we've applied quite a few fixes to stabilize our servers internally and are in the process of applying more over the course of the coming week. It's good to know that the rate of 502/504's have dropped off significantly after the 24th. Let's continue to keep this open over the coming week to make sure your problems go away before closing this issue :)

**Comment by 1337LutZ** [comment]
> hey @1337LutZ , we've applied quite a few fixes to stabilize our servers internally and are in the process of applying more over the course of the coming week. It's good to know that the rate of 502/504's have dropped off significantly after the 24th. Let's continue to keep this open over the coming week to make sure your problems go away before closing this issue :)

We haven't encountered any more issues regarding drop-outs. I will close this issue. When something new comes up I will create a new issue. Thanks!

**Comment by mahesh-noumena** [comment]
I am facing the same issue :(

**Comment by mithila** [comment]
![image](https://user-images.githubusercontent.com/29629/201483124-570b17fd-8241-4964-88d3-57cb515c3773.png)

I'm getting this continuously getting 502 request fail error,  any one of you have a solution for this ?

**Comment by 1992abdo** [comment]
Hello  @Mr;[1337LutZ](https://github.com/1337LutZ) I'm facing the same issue any solution please 
![error expo](https://user-images.githubusercontent.com/44400041/203546958-09434682-8079-430e-b252-030b713c323b.PNG)

**Comment by zuu-maker** [comment]
@1992abdo i have the exact same error when creating a build. Any luck?

**Comment by zuu-maker** [comment]
@1992abdo try update your expo-cli worked for me

**Comment by brentvatne** [comment]
you may occasionally encounter errors like the above when we have server uptime issues. please retry when you see these errors. we're working on improving service stability

**Comment by sunviwo** [comment]
> 1992abdo

I'm experiencing the same issue since yesterday. I wait till today to see if it would be fixed. I upgraded expo-cli but still no fix.

**Comment by 1992abdo** [comment]
I still have the same error even when I upgrade the Expo-cli

**Comment by alizaib1217** [comment]
Uploading JavaScript bundles
Request failed with status code 503
Error: Request failed with status code 503

**Comment by shcoderAlex** [comment]
The same for me 
<img width="712" alt="Screen Shot 2022-11-28 at 23 05 52" src="https://user-images.githubusercontent.com/3644760/204338533-4ea4fa3f-80a6-4620-8da9-f7d82b65eeac.png">

**Comment by akouaouchissam** [comment]
```
Building optimized bundles and generating sourcemaps...
Starting Metro Bundler
Started Metro Bundler
Android Bundling complete 148442ms

Bundle                     Size
┌ index.ios.js          4.96 MB
├ index.android.js      4.97 MB
├ index.ios.js.map      14.7 MB
└ index.android.js.map  14.8 MB

💡 JavaScript bundle sizes affect startup time. Learn more: https://expo.fyi/javascript-bundle-sizes

Analyzing assets
Saving assets
No assets changed, skipped.

Processing asset bundle patterns:
- C:\Users\User\Desktop\le-pere-restaurants\**\*

### Uploading JavaScript bundles
Request failed with status code 503
Error: Request failed with status code 503
    at createError (C:\Users\User\AppData\Roaming\npm\node_modules\expo-cli\node_modules\axios\lib\core\createError.js:16:15)   
    at settle (C:\Users\User\AppData\Roaming\npm\node_modules\expo-cli\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\User\AppData\Roaming\npm\node_modules\expo-cli\node_modules\axios\lib\adapters\    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

updating the expo-cli to the latest version using the command:
**yarn add global expo-cli**
didn't fix the issue.

**Comment by farazirfan47** [comment]
Getting same issue again and again.

**Comment by jonlee90** [comment]
HI, I'm also experiencing the same issue when I run the following command: expo publish --release-channel default
