### ISSUE TITLE
Next JS broken on fresh BareBones project (TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined)

### ISSUE THREAD

**Issue by daxfrost** [expo/expo-cli#2345]
## Description

Using the Expo CLI to setup a fresh bare bones project, with minimal typescript template, and Next JS - there is now an error generating the SSR pages for Next JS, my guess is due to an underlying dependency that is generating `undefined` where there should be a string path.

## Expected Behavior

NextJS runs as it should, and you can open your browser to view the fresh Expo project now SSR'd on the web.

**To repro, run the following commands**
```
expo init NextFontTest -t expo-template-bare-typescript
cd NextFontTest
yarn add -D @expo/next-adapter
yarn next-expo
git add .;git commit -m "commit my changes first"
yarn next dev
```

## Observed Behavior

```
➜  NextFontTest git:(master) yarn next dev
yarn run v1.22.4
$ /Users/dbooysen/Documents/dev/expo/FontTest/NextFontTest/node_modules/.bin/next dev
ready - started server on http://localhost:3000
The following changes are being made to your tsconfig.json file:
  - compilerOptions.target to be suggested value: es5 (this can be changed)
  - compilerOptions.allowJs to be suggested value: true (this can be changed)
  - compilerOptions.forceConsistentCasingInFileNames to be suggested value: true (this can be changed)
  - compilerOptions.esModuleInterop must be true (requirement for babel)
  - compilerOptions.module must be esnext (for dynamic import() support)
  - compilerOptions.isolatedModules must be true (requirement for babel)
  - compilerOptions.jsx must be preserve

> Using external babel configuration
> Location: "/Users/dbooysen/Documents/dev/expo/FontTest/NextFontTest/babel.config.js"
event - compiled successfully
wait  - compiling...
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
    at Module.require (internal/modules/cjs/loader.js:1073:3)
    at require (internal/modules/cjs/helpers.js:72:18)
    at eval (webpack-internal:///@expo/next-adapter/document:1:18)
    at Object.@expo/next-adapter/document (/Users/dbooysen/Documents/dev/expo/FontTest/NextFontTest/.next/server/static/development/pages/_document.js:127:1)
    at __webpack_require__ (/Users/dbooysen/Documents/dev/expo/FontTest/NextFontTest/.next/server/static/development/pages/_document.js:23:31)
    at eval (webpack-internal:///./pages/_document.js:2:85)
    at Module../pages/_document.js (/Users/dbooysen/Documents/dev/expo/FontTest/NextFontTest/.next/server/static/development/pages/_document.js:104:1)
    at __webpack_require__ (/Users/dbooysen/Documents/dev/expo/FontTest/NextFontTest/.next/server/static/development/pages/_document.js:23:31)
    at Object.0 (/Users/dbooysen/Documents/dev/expo/FontTest/NextFontTest/.next/server/static/development/pages/_document.js:115:18)
    at __webpack_require__ (/Users/dbooysen/Documents/dev/expo/FontTest/NextFontTest/.next/server/static/development/pages/_document.js:23:31)
    at /Users/dbooysen/Documents/dev/expo/FontTest/NextFontTest/.next/server/static/development/pages/_document.js:91:18
    at Object.<anonymous> (/Users/dbooysen/Documents/dev/expo/FontTest/NextFontTest/.next/server/static/development/pages/_document.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at loadComponents (/Users/dbooysen/Documents/dev/expo/FontTest/NextFontTest/node_modules/next/dist/next-server/server/load-components.js:1:872)
    at DevServer.findPageComponents (/Users/dbooysen/Documents/dev/expo/FontTest/NextFontTest/node_modules/next/dist/next-server/server/next-server.js:50:189)
    at DevServer.renderToHTML (/Users/dbooysen/Documents/dev/expo/FontTest/NextFontTest/node_modules/next/dist/next-server/server/next-server.js:92:197) {
  code: 'ERR_INVALID_ARG_TYPE'
}
event - build page: /next/dist/pages/_error
```

## Environment

```
➜  NextFontTest git:(master) ✗ expo diagnostics
┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (3.22.0).                │
│   You are currently using expo-cli 3.21.13                              │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘

  Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.2.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.1 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.21.13
```

## Reproducible Demo

**To repro, run the following commands**
```
expo init NextFontTest -t expo-template-bare-typescript
cd NextFontTest
yarn add -D @expo/next-adapter
yarn next-expo
git add .;git commit -m "commit my changes first"
yarn next dev
```

**Comment by daxfrost** [comment]
FYI: I noticed I can upgrade my `expo-cli` from version `3.21.13` to `3.22.0`

After running my repro steps again, the issue is the same.

```
➜  NextFontTest git:(master) ✗ expo diagnostics

  Expo CLI 3.22.0 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.2.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.1 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: ~0.62.2 => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.21.13
```

**Comment by daxfrost** [comment]
@EvanBacon I think this was broken in the `@expo/next-adapter` **2.1.18** release.

I just downgraded manually in my package.json to `2.1.17` and all works correctly as before.

- https://github.com/expo/expo-cli/pull/2336 
- https://github.com/expo/expo-cli/commit/80b9197ef77845984fa589cd53587186fbaff61a#diff-6b7364ff5528c8a3906d38c758851e06

I'm not sure yet what exactly in the above, but I suspect something in these changes, maybe Webpack itself or [the lines in here](https://github.com/expo/expo-cli/commit/80b9197ef77845984fa589cd53587186fbaff61a#diff-3ce31f0dd02b1c4a08d8fc9cef285c1aR190).

**Comment by EvanBacon** [comment]
I suspect it could also be related to this https://github.com/expo/expo-cli/pull/2346 which we will publish promptly.

**Comment by daxfrost** [comment]
@EvanBacon I updated to the release for the metro bundler esModule=false fix:

```
@expo/webpack-config@0.12.19
@expo/next-adapter@2.1.19
```

```
➜  NextFontTest git:(master) ✗ expo diagnostics                                       

  Expo CLI 3.22.1 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.2.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.1 => 38.0.8 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: ~0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.22.1
```

Verified your changes,

```
// Interop assets like Metro bundler
            esModule: false,
```

...were in place:

```
➜  NextFontTest git:(master) ✗ cat ./node_modules/@expo/webpack-config/webpack/loaders/createAllLoaders.js
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const paths_1 = require("@expo/config/paths");
const env_1 = require("../env");
const createBabelLoader_1 = __importDefault(require("./createBabelLoader"));
const createFontLoader_1 = __importDefault(require("./createFontLoader"));
const createWorkerLoader_1 = __importDefault(require("./createWorkerLoader"));
// Inline resources as Base64 when there is less reason to parallelize their download. The
// heuristic we use is whether the resource would fit within a TCP/IP packet that we would
// send to request the resource.
//
// An Ethernet MTU is usually 1500. IP headers are 20 (v4) or 40 (v6) bytes and TCP
// headers are 40 bytes. HTTP response headers vary and are around 400 bytes. This leaves
// about 1000 bytes for content to fit in a packet.
const imageInlineSizeLimit = parseInt(process.env.IMAGE_INLINE_SIZE_LIMIT || '1000');
/**
 * This is needed for webpack to import static images in JavaScript files.
 * "url" loader works like "file" loader except that it embeds assets
 * smaller than specified limit in bytes as data URLs to avoid requests.
 * A missing `test` is equivalent to a match.
 *
 * @category loaders
 */
// TODO: Bacon: Move SVG
exports.imageLoaderRule = {
    test: /\.(gif|jpe?g|png|svg)$/,
    use: {
        loader: require.resolve('url-loader'),
        options: {
            limit: imageInlineSizeLimit,
            // Interop assets like Metro bundler
            esModule: false,
            name: 'static/media/[name].[hash:8].[ext]',
        },
    },
};
/**
 * "file" loader makes sure those assets get served by WebpackDevServer.
 * When you `import` an asset, you get its (virtual) filename.
 * In production, they would get copied to the `build` folder.
 * This loader doesn't use a "test" so it will catch all modules
 * that fall through the other loaders.
 *
 * @category loaders
 */
exports.fallbackLoaderRule = {
    loader: require.resolve('file-loader'),
    // Exclude `js` files to keep "css" loader working as it injects
    // its runtime that would otherwise be processed through "file" loader.
    // Also exclude `html` and `json` extensions so they get processed
    // by webpacks internal loaders.
    // Excludes: js, jsx, ts, tsx, html, json
    exclude: [/\.(mjs|[jt]sx?)$/, /\.html$/, /\.json$/],
    options: {
        // Interop assets like Metro bundler
        esModule: false,
        name: 'static/media/[name].[hash:8].[ext]',
    },
};
/**
 * Default CSS loader.
 *
 * @category loaders
 */
exports.styleLoaderRule = {
    test: /\.(css)$/,
    use: [require.resolve('style-loader'), require.resolve('css-loader')],
};
/**
 * Create the fallback loader for parsing any unhandled file type.
 *
 * @param env
 * @category loaders
 */
function createAllLoaders(env) {
    env.projectRoot = env.projectRoot || paths_1.getPossibleProjectRoot();
    // @ts-ignore
    env.config = env.config || env_1.getConfig(env);
    // @ts-ignore
    env.locations = env.locations || env_1.getPaths(env.projectRoot, env);
    const { root, includeModule, template } = env.locations;
    return [
        getHtmlLoaderRule(template.folder),
        exports.imageLoaderRule,
        getBabelLoaderRule(env),
        createWorkerLoader_1.default(),
        createFontLoader_1.default(root, includeModule),
        exports.styleLoaderRule,
        // This needs to be the last loader
        exports.fallbackLoaderRule,
    ].filter(Boolean);
}
exports.default = createAllLoaders;
/**
 * Creates a Rule for loading application code and packages that work with the Expo ecosystem.
 * This method attempts to emulate how Metro loads ES modules in the `node_modules` folder.
 *
 * @param env partial Environment object.
 * @category loaders
 */
function getBabelLoaderRule(env) {
    var _a;
    env.projectRoot = env.projectRoot || paths_1.getPossibleProjectRoot();
    // @ts-ignore
    env.config = env.config || env_1.getConfig(env);
    env.locations = env.locations || env_1.getPaths(env.projectRoot, env);
    const { web: { build: { babel = {} } = {} } = {} } = env.config;
    // TODO: deprecate app.json method in favor of env.babel
    const { root, verbose, include = [], use } = babel;
    const babelProjectRoot = root || env.projectRoot;
    return createBabelLoader_1.default({
        projectRoot: env.locations.root,
        mode: env.mode,
        platform: env.platform,
        babelProjectRoot,
        verbose,
        include: [...include, ...(((_a = env.babel) === null || _a === void 0 ? void 0 : _a.dangerouslyAddModulePathsToTranspile) || [])],
        use,
    });
}
exports.getBabelLoaderRule = getBabelLoaderRule;
/**
 *
 * @param exclude
 * @category loaders
 */
function getHtmlLoaderRule(exclude) {
    return {
        test: /\.html$/,
        use: [require.resolve('html-loader')],
        exclude,
    };
}
exports.getHtmlLoaderRule = getHtmlLoaderRule;
//# sourceMappingURL=createAllLoaders.js.map%         
```

Yet I am still getting the same result:

```                                                                                                                                                                                                                        
➜  NextFontTest git:(master) ✗ yarn build
yarn run v1.22.4
$ next build
> Using external babel configuration
> Location: "/Users/dbooysen/Documents/dev/expo/FontTest/test3/NextFontTest/babel.config.js"
Creating an optimized production build  

Compiled successfully.


> Build error occurred
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
    at Module.require (internal/modules/cjs/loader.js:1073:3)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.kROk (/Users/dbooysen/Documents/dev/expo/FontTest/test3/NextFontTest/.next/server/static/DMLe92-DFOTu1MHU4Xbi-/pages/index.js:128:18)
    at __webpack_require__ (/Users/dbooysen/Documents/dev/expo/FontTest/test3/NextFontTest/.next/server/static/DMLe92-DFOTu1MHU4Xbi-/pages/index.js:23:31)
    at Module.RNiq (/Users/dbooysen/Documents/dev/expo/FontTest/test3/NextFontTest/.next/server/static/DMLe92-DFOTu1MHU4Xbi-/pages/index.js:112:98)
    at __webpack_require__ (/Users/dbooysen/Documents/dev/expo/FontTest/test3/NextFontTest/.next/server/static/DMLe92-DFOTu1MHU4Xbi-/pages/index.js:23:31)
    at Object.1 (/Users/dbooysen/Documents/dev/expo/FontTest/test3/NextFontTest/.next/server/static/DMLe92-DFOTu1MHU4Xbi-/pages/index.js:99:18)
    at __webpack_require__ (/Users/dbooysen/Documents/dev/expo/FontTest/test3/NextFontTest/.next/server/static/DMLe92-DFOTu1MHU4Xbi-/pages/index.js:23:31)
    at /Users/dbooysen/Documents/dev/expo/FontTest/test3/NextFontTest/.next/server/static/DMLe92-DFOTu1MHU4Xbi-/pages/index.js:91:18 {
  type: 'NodeError',
  code: 'ERR_INVALID_ARG_TYPE'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  NextFontTest git:(master) ✗ 
```

I am not super familiar with the process yet of debugging this on the underlying layers, but I will try, hopefully you have some ideas.

**Comment by georgii-ivanov** [comment]
Same issue. Nothing helps. Also downgrading next-adapter package doesn't solve the issue.
Please let me know you guys how how to fix it.

**Comment by daxfrost** [comment]
@georgii-ivanov downgrading next-adapter to `2.1.17` does correct this issue. But, still, I would like to upgrade and get this fixed.

**Comment by murbanowicz** [comment]
Do not want to spam but I hit exactly the same issue with freshly created Expo project
