### ISSUE TITLE
ERROR ITMS-90725: "SDK Version Issue. This app was built with the iOS SDK. As of June 30, 2020, all apps for iPhone or iPad must be built with the iOS 13 SDK or later, included with Xcode 11 or later."

### ISSUE THREAD

**Issue by oporter1** [expo/expo-cli#2366]
## Description

When uploading a fresh expo iOs build to the app store, I receive the following error message:

_ERROR ITMS-90725: "SDK Version Issue. This app was built with the iOS SDK. As of June 30, 2020, all apps for iPhone or iPad must be built with the iOS 13 SDK or later, included with Xcode 11 or later."
Return status of iTunes Transporter was 1: ERROR ITMS-90725: "SDK Version Issue. This app was built with the iOS SDK. As of June 30, 2020, all apps for iPhone or iPad must be built with the iOS 13 SDK or later, included with Xcode 11 or later."_

## Expected Behavior

Expected the app build to successfully upload to the app store, I believe I am on the right SDK version, I am not using XCode to build so upgrading the Xcode doesn't seem to be the right solution.

## Observed Behavior

```
ERROR ITMS-90725: "SDK Version Issue. This app was built with the iOS SDK. As of June 30, 2020, all apps for iPhone or iPad must be built with the iOS 13 SDK or later, included with Xcode 11 or later."
Return status of iTunes Transporter was 1: ERROR ITMS-90725: "SDK Version Issue. This app was built with the iOS SDK. As of June 30, 2020, all apps for iPhone or iPad must be built with the iOS 13 SDK or later, included with Xcode 11 or later."```

## Environment

package-lock,json file:
    "expo": {
      "version": "37.0.9",

package.json file:
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest",
    "postinstall": "node overwrite/migrate.js"
  },
  "jest": {
    "preset": "react-native"
  },
  "dependencies": {
    "add": "^2.0.6",
    "expo": "^37.0.0",
    "expo-cli": "^3.20.3",
    "expo-constants": "~9.0.0",
    "expo-device": "~2.1.0",
    "expo-file-system": "~8.1.0",
    "expo-image-picker": "~8.1.0",
    "expo-linear-gradient": "~8.1.0",
    "expo-location": "~8.1.0",
    "expo-permissions": "~8.1.0",
    "firebase": "7.9.0",
    "firebase-admin": "^8.10.0",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-maps": "0.26.1",
    "react-native-view-overflow": "0.0.4",
    "react-native-web": "^0.11.7",
    "react-navigation": "^3.13.0",
    "redux": "^4.0.4"
  },
  "rnpm": {
    "assets": [
      "utils/Fonts/"
    ]
  },
  "devDependencies": {
    "babel-eslint": "^10.0.3",
    "babel-plugin-module-resolver": "^3.2.0",
    "babel-preset-expo": "^8.1.0",
    "eslint": "^6.6.0",
    "eslint-config-react": "^1.1.7",
    "eslint-config-react-native": "^4.0.0",
    "eslint-import-resolver-babel-module": "^5.1.0",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-prettier": "^3.1.1",
    "eslint-plugin-react": "^7.16.0",
    "eslint-plugin-react-hooks": "0.0.0-f6b8d31a7",
    "eslint-plugin-react-native": "^3.8.1",
    "prettier": "^1.19.1"
  },
  "private": true
}


<!--

Please run `expo diagnostics` in the project folder and copy the output here:

Also specify:

- Phone/emulator/simulator platform, model and version:

 -->
Expo CLI 3.21.5 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.2 - /usr/local/bin/node
      npm: 6.12.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.9 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ^0.11.7 => 0.11.7 
      react-navigation: ^3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.21.5


## Reproducible Demo

<!--
Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.
-->

expo build:ios
expo upload:ios --app-name appname

response: 
```ERROR ITMS-90725: "SDK Version Issue. This app was built with the iOS SDK. As of June 30, 2020, all apps for iPhone or iPad must be built with the iOS 13 SDK or later, included with Xcode 11 or later."
Return status of iTunes Transporter was 1: ERROR ITMS-90725: "SDK Version Issue. This app was built with the iOS SDK. As of June 30, 2020, all apps for iPhone or iPad must be built with the iOS 13 SDK or later, included with Xcode 11 or later."```

**Comment by brentvatne** [comment]
hi! check out this issue: https://github.com/expo/expo-cli/issues/2328

>  I am not using XCode to build so upgrading the Xcode doesn't seem to be the right solution.

this actually still matters still when submitting the app. you should update to the latest version of xcode.

also, you can try using "Transporter" to upload the binary and [clicking "Verify"](https://github.com/expo/expo-cli/issues/2328#issuecomment-654411229)

**Comment by oporter1** [comment]
I am on the right version of XCode (Xcode: 11.1) which means it must be the transporter issue. I am not prompted at any point to select "Verify" when uploading the app. To troubleshoot more I ended up generating a new app specific password and building a fresh version with expo. These are the steps I am prompted with:
1. expo upload:ios --app-name drumm
2. what's your apple id? what's your apple password?
3. Downloading [========================================================] 100% 0.0
4. [13:50:22]: Login to App Store Connect (admin@drummco.com) [13:50:23]: Login successful
5. [13:50:31]: Going to upload updated app to App Store Connect
6. Please provide your Apple Developer Program account credentials. The login information you enter will be stored in your macOS Keychain. Password:
7. [13:59:20]: Going to upload updated app to App Store Connect
8. [13:59:20]: This might take a few minutes. Please don't interrupt the script.
9. [16:05:43]: [iTMSTransporter] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.installBundle(BundleContextImpl.java:149)

[16:05:43]: [iTMSTransporter] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.installBundle(BundleContextImpl.java:142)

[16:05:43]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase2.bootstrapBundles(BootstrapperPhase2.java:280)

[16:05:43]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase2.start(BootstrapperPhase2.java:126)

[16:05:43]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.startOSGiFramework(BootstrapperPhase1.java:321)

[16:05:43]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:99)

[16:05:43]: [iTMSTransporter] 	at com.apple.transporter.bootstrap.BootstrapperPhase1.bootstrap(BootstrapperPhase1.java:59)

[16:05:43]: [iTMSTransporter] 	at com.apple.transporter.launcher.Launcher.launchBootstrapper(Launcher.java:37)

[16:05:43]: [iTMSTransporter] 	... 6 more

[16:05:43]: [iTMSTransporter] Caused by: java.io.IOException: No space left on device

[16:05:43]: [iTMSTransporter] 	at java.io.FileOutputStream.writeBytes(Native Method)

[16:05:43]: [iTMSTransporter] 	at java.io.FileOutputStream.write(FileOutputStream.java:326)

[16:05:43]: [iTMSTransporter] 	at org.eclipse.osgi.storage.StorageUtil.readFile(StorageUtil.java:73)

[16:05:43]: [iTMSTransporter] 	at org.eclipse.osgi.storage.Storage.stageContent0(Storage.java:1033)

[16:05:43]: [iTMSTransporter] 	... 16 more

[16:05:43]: iTunes Transporter output above ^
[16:05:43]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
Failed to upload the standalone app to the app store.
Error uploading ipa file, for more information see above
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.141.0/pilot/lib/pilot/build_manager.rb:37:in `upload'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/pilot_upload.rb:20:in `block in <main>'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/funcs.rb:4:in `with_captured_stderr'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/pilot_upload.rb:12:in `<main>'
Error: Error uploading ipa file, for more information see above
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.141.0/pilot/lib/pilot/build_manager.rb:37:in `upload'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/pilot_upload.rb:20:in `block in <main>'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/funcs.rb:4:in `with_captured_stderr'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/pilot_upload.rb:12:in `<main>'
    at runFastlaneAsync (/usr/local/lib/node_modules/expo-cli/src/commands/upload/utils.ts:89:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)


any ideas? where would I be able to select "verify"?

**Comment by brentvatne** [comment]
i meant this transporter app: https://apps.apple.com/us/app/transporter/id1450874784?mt=12

also, be sure to use the latest version of expo-cli if you're not already.

**Comment by oporter1** [comment]
No sure what changed but I just ran it again and the app went through. Maybe it was something on the app store side...

**Comment by brentvatne** [comment]
@oporter1 - good to hear that it worked! the way that this works on apple's side is opaque to us, i wish we could do more to help on this. if you happen to recall anything that you did that may be related in between it not working just let me know :) if not, no worries

**Comment by gato333** [comment]
Also experiencing this issue today. 

Verifying first before Delivery didn't help. 

Using Xcode version 11.5
Transporter 1.1.1 (1171) 
Expo  38.0.3.8

Was working just fine a couple days ago, I'm stumped. Going to try rebuilding and see if that helps

**Comment by brentvatne** [comment]
@gato333 - updated to the latest version of xcode - xcode 12 has been released now

**Comment by gato333** [comment]
@brentvatne  Yup, your right figured that out after I dropped the comment!
Not that Apple makes it easy! 
to update XCode when more the 30GB of free space isnt enough to do a simple update 😭 . 

Can confirm after updating my OS, 
and then deleting and reinstalling Xcode (after deleting anything i could possible spare), 
I was able to build my Expo app normally and upload it via Transporter without a hitch.

**Comment by wahas-mughal** [comment]
Can we upload the build and it would get accepted before the deadline?

**Comment by wahas-mughal** [comment]
@brentvatne
