### ISSUE TITLE
expo upload:ios on github actions (using macos-latest) succeeds and fails!

### ISSUE THREAD

**Issue by renegare** [expo/expo-cli#2368]
## Description

`expo upload:ios` on github actions (using `macos-latest`) succeeds and fails!

## Expected Behavior

**I ran:** 
```
	expo upload:ios --latest --non-interactive \
		--apple-id $(APPLE_ID) \
		--apple-id-password $(APPLE_ID_PASS)
```
**I expected** the latest built app to be uploaded to itunes connect and the process to complete successfully.

## Observed Behavior

* command fails:
```
2020-07-16T14:50:35.7993480Z [14:50:35]: [32m--------------------------------------------------------------------[0m
2020-07-16T14:50:35.7994550Z [14:50:35]: [32mSuccessfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.[0m
2020-07-16T14:50:35.7995410Z [14:50:35]: [32m--------------------------------------------------------------------[0m
2020-07-16T14:50:35.8158710Z [14:50:35]: [32mSuccessfully uploaded the new binary to App Store Connect[0m
2020-07-16T14:50:35.8160500Z [14:50:35]: [33m`skip_waiting_for_build_processing` used and no `changelog` supplied - skipping waiting for build processing[0m
2020-07-16T14:50:35.8637030Z [14:50:35] Failed to upload the standalone app to the app store.
2020-07-16T14:50:35.8639080Z [14:50:35] Unexpected token N in JSON at position 0
2020-07-16T14:50:35.8648380Z [14:50:35] SyntaxError: Unexpected token N in JSON at position 0
2020-07-16T14:50:35.8648780Z     at JSON.parse (<anonymous>)
2020-07-16T14:50:35.8650070Z     at runFastlaneAsync (/Users/runner/hostedtoolcache/expo-cli/3.22.3/x64/node_modules/expo-cli/src/commands/upload/utils.ts:76:20)
2020-07-16T14:50:35.8650390Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-07-16T14:50:35.8651280Z     at IOSUploader._uploadToTheStore (/Users/runner/hostedtoolcache/expo-cli/3.22.3/x64/node_modules/expo-cli/src/commands/upload/IOSUploader.ts:225:5)
2020-07-16T14:50:35.8652530Z     at IOSUploader.upload (/Users/runner/hostedtoolcache/expo-cli/3.22.3/x64/node_modules/expo-cli/src/commands/upload/BaseUploader.ts:33:5)
2020-07-16T14:50:35.8653440Z     at /Users/runner/hostedtoolcache/expo-cli/3.22.3/x64/node_modules/expo-cli/src/commands/upload.ts:119:9
2020-07-16T14:50:35.8654480Z     at Command.<anonymous> (/Users/runner/hostedtoolcache/expo-cli/3.22.3/x64/node_modules/expo-cli/src/exp.ts:80:7)
```
* app is uploaded to app store (i consistently get a notification from testflight roughly 20mins after the build fails)

Full dump of logs:
```
[36;1mmake upload-ios[0m
2020-07-16T14:35:29.4534650Z shell: /bin/bash -e {0}
2020-07-16T14:35:29.4534910Z env:
2020-07-16T14:35:29.4535130Z   ENVIRONMENT: prod
2020-07-16T14:35:29.4535910Z   APP_CONFIG: ***

2020-07-16T14:35:29.4536870Z   FASTLANE_SESSION: ***
2020-07-16T14:35:29.4537550Z   FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ***
2020-07-16T14:35:29.4537990Z   APPLE_ID: ***
2020-07-16T14:35:29.4538320Z   APPLE_ID_PASS: ***
2020-07-16T14:35:29.4538610Z ##[endgroup]
2020-07-16T14:35:29.5113390Z expo upload:ios --latest --non-interactive \
2020-07-16T14:35:29.5120400Z 		--apple-id *** \
2020-07-16T14:35:29.5121510Z 		--apple-id-password ***
2020-07-16T14:35:31.0267830Z [14:35:31] Downloading build from https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/ios/%40***/xxxx-archive.ipa
2020-07-16T14:35:38.2459910Z 
2020-07-16T14:35:38.2559460Z [14:35:38] Resolving the ITC team ID...
2020-07-16T14:35:56.8767760Z [14:35:56] ITC team ID is XXXXX
2020-07-16T14:35:56.8768300Z [14:35:56] Ensuring the app exists on App Store Connect, this may take a while...
2020-07-16T14:36:03.9429820Z 
2020-07-16T14:36:03.9431420Z +----------------+--------------------+
2020-07-16T14:36:03.9432400Z |     [32mSummary for produce 2.146.1[0m     |
2020-07-16T14:36:03.9433090Z +----------------+--------------------+
2020-07-16T14:36:03.9433800Z | app_identifier | xxxxx              |
2020-07-16T14:36:03.9434780Z | app_name       | xxxxx              |
2020-07-16T14:36:03.9436010Z | username       | ***                |
2020-07-16T14:36:03.9436360Z | language       | English            |
2020-07-16T14:36:03.9436680Z | sku            | xxxxx              |
2020-07-16T14:36:03.9436960Z | platform       | ios                |
2020-07-16T14:36:03.9437280Z | skip_itc       | false              |
2020-07-16T14:36:03.9437560Z | skip_devcenter | false              |
2020-07-16T14:36:03.9439100Z +----------------+--------------------+
2020-07-16T14:36:03.9439220Z 
2020-07-16T14:36:03.9440120Z [14:36:03]: [32m[DevCenter] App 'xxxx' already exists, nothing to do on the Dev Center[0m
2020-07-16T14:36:13.2222010Z [14:36:13]: [32mApp 'xxxx' already exists (xxxx), nothing to do on App Store Connect[0m
2020-07-16T14:36:14.9292580Z [14:36:14] Uploading the app to Testflight, hold tight...
2020-07-16T14:36:16.0282780Z [14:36:16]: Login to App Store Connect (***)
2020-07-16T14:36:20.1802760Z [14:36:20]: Login successful
2020-07-16T14:36:22.5836780Z [14:36:22]: [32mReady to upload new build to TestFlight (App: xxxx)...[0m
2020-07-16T14:36:24.8983880Z [14:36:24]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
2020-07-16T14:36:24.8985170Z [14:36:24]: Going to upload updated app to App Store Connect
2020-07-16T14:36:24.8988030Z [14:36:24]: [32mThis might take a few minutes. Please don't interrupt the script.[0m
2020-07-16T14:42:17.9454590Z [14:42:17]: [31m[Transporter Error Output]: Failed to upload file: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20200716-5663-1r3u5wr/xxxx.itmsp/xxxx.ipa
2020-07-16T14:42:17.9455550Z [0m
2020-07-16T14:50:35.2899200Z [14:50:35]: [32miTunes Transporter successfully finished its job[0m
2020-07-16T14:50:35.4786400Z [14:50:35]: [33m[iTMSTransporter] [2020-07-16 14:50:35 UTC] <main> DBG-X: JSON-START>>{"dev-id-results":{"upload_id":"xxxx"}}<<JSON-END
2020-07-16T14:50:35.4787380Z [0m
2020-07-16T14:50:35.4788640Z [14:50:35]: [33m[iTMSTransporter] [2020-07-16 14:50:35 UTC] <main> DBG-X: Unlocking token at path /Users/runner/Library/Caches/com.apple.amp.itmstransporter/UploadTokens/Mac-xxxx_xxxx_xxxx.itmsp.token
2020-07-16T14:50:35.4789330Z [0m
2020-07-16T14:50:35.4821430Z [14:50:35]: [33m[iTMSTransporter] [2020-07-16 14:50:35 UTC] <main> DBG-X: Releasing token file lock
2020-07-16T14:50:35.4822390Z [0m
2020-07-16T14:50:35.4823680Z [14:50:35]: [33m[iTMSTransporter] [2020-07-16 14:50:35 UTC] <main> DBG-X: Removing token at path /Users/runner/Library/Caches/com.apple.amp.itmstransporter/UploadTokens/Mac-xxxx_xxxx_xxxx.itmsp.token
2020-07-16T14:50:35.4824260Z [0m
2020-07-16T14:50:35.4825630Z [14:50:35]: [33m[iTMSTransporter] [2020-07-16 14:50:35 UTC] <main>  INFO: Done performing uploadDone notification to Apple.
2020-07-16T14:50:35.4826260Z [0m
2020-07-16T14:50:35.4828090Z [14:50:35]: [33m[iTMSTransporter] [2020-07-16 14:50:35 UTC] <main>  INFO: Transporter's command line arguments are: -m upload -u *** -p **hidden value** -f /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20200716-5663-1r3u5wr/xxxx.itmsp -t DAV,Signiant -k 100000
2020-07-16T14:50:35.4828810Z [0m
2020-07-16T14:50:35.4829940Z [14:50:35]: [33m[iTMSTransporter] [2020-07-16 14:50:35 UTC] <main>  INFO: The package: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20200716-5663-1r3u5wr/xxxx.itmsp has been successfully uploaded.
2020-07-16T14:50:35.4830690Z [0m
2020-07-16T14:50:35.4831310Z [14:50:35]: [33m[iTMSTransporter] 
2020-07-16T14:50:35.4831900Z [0m
2020-07-16T14:50:35.4832500Z [14:50:35]: [33m[iTMSTransporter] 
2020-07-16T14:50:35.4833060Z [0m
2020-07-16T14:50:35.4833950Z [14:50:35]: [33m[iTMSTransporter] 
2020-07-16T14:50:35.4834550Z [0m
2020-07-16T14:50:35.4835310Z [14:50:35]: [33m[iTMSTransporter] Package Summary:
2020-07-16T14:50:35.4835900Z [0m
2020-07-16T14:50:35.4836530Z [14:50:35]: [33m[iTMSTransporter]  
2020-07-16T14:50:35.4837100Z [0m
2020-07-16T14:50:35.4837830Z [14:50:35]: [33m[iTMSTransporter] 1 packages were uploaded successfully:
2020-07-16T14:50:35.4838410Z [0m
2020-07-16T14:50:35.4839290Z [14:50:35]: [33m[iTMSTransporter] 	/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20200716-5663-1r3u5wr/xxxx.itmsp
2020-07-16T14:50:35.4839820Z [0m
2020-07-16T14:50:35.4840790Z [14:50:35]: [33m[iTMSTransporter] [2020-07-16 14:50:35 UTC] <main> DBG-X: Returning 0
2020-07-16T14:50:35.4841910Z [0m
2020-07-16T14:50:35.4842260Z [14:50:35]: iTunes Transporter output above ^
2020-07-16T14:50:35.4843350Z [14:50:35]: [31mFailed to upload file: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20200716-5663-1r3u5wr/xxxx.itmsp/xxxx.ipa
2020-07-16T14:50:35.4843970Z [0m
2020-07-16T14:50:35.4844770Z [14:50:35]: [33mAlthough errors occurred during execution of iTMSTransporter, it returned success status.[0m
2020-07-16T14:50:35.7993480Z [14:50:35]: [32m--------------------------------------------------------------------[0m
2020-07-16T14:50:35.7994550Z [14:50:35]: [32mSuccessfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.[0m
2020-07-16T14:50:35.7995410Z [14:50:35]: [32m--------------------------------------------------------------------[0m
2020-07-16T14:50:35.8158710Z [14:50:35]: [32mSuccessfully uploaded the new binary to App Store Connect[0m
2020-07-16T14:50:35.8160500Z [14:50:35]: [33m`skip_waiting_for_build_processing` used and no `changelog` supplied - skipping waiting for build processing[0m
2020-07-16T14:50:35.8637030Z [14:50:35] Failed to upload the standalone app to the app store.
2020-07-16T14:50:35.8639080Z [14:50:35] Unexpected token N in JSON at position 0
2020-07-16T14:50:35.8648380Z [14:50:35] SyntaxError: Unexpected token N in JSON at position 0
2020-07-16T14:50:35.8648780Z     at JSON.parse (<anonymous>)
2020-07-16T14:50:35.8650070Z     at runFastlaneAsync (/Users/runner/hostedtoolcache/expo-cli/3.22.3/x64/node_modules/expo-cli/src/commands/upload/utils.ts:76:20)
2020-07-16T14:50:35.8650390Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-07-16T14:50:35.8651280Z     at IOSUploader._uploadToTheStore (/Users/runner/hostedtoolcache/expo-cli/3.22.3/x64/node_modules/expo-cli/src/commands/upload/IOSUploader.ts:225:5)
2020-07-16T14:50:35.8652530Z     at IOSUploader.upload (/Users/runner/hostedtoolcache/expo-cli/3.22.3/x64/node_modules/expo-cli/src/commands/upload/BaseUploader.ts:33:5)
2020-07-16T14:50:35.8653440Z     at /Users/runner/hostedtoolcache/expo-cli/3.22.3/x64/node_modules/expo-cli/src/commands/upload.ts:119:9
2020-07-16T14:50:35.8654480Z     at Command.<anonymous> (/Users/runner/hostedtoolcache/expo-cli/3.22.3/x64/node_modules/expo-cli/src/exp.ts:80:7)
2020-07-16T14:50:35.8754750Z make: *** [upload-ios] Error 1
2020-07-16T14:50:35.8764110Z ##[error]Process completed with exit code 2.
```

## Environment

TBC - will come back with this 

## Reproducible Demo

TBC - will come back with this

**Comment by renegare** [comment]
This may be a fastlane issue. But I'd be interested to know if we could handle the error better here:
https://github.com/expo/expo-cli/blob/master/packages/expo-cli/src/commands/upload/utils.ts#L76

?

**Comment by brentvatne** [comment]
hey @renegare - thanks for the information! I agree there could be a better way to handle this error, perhaps we can wrap the JSON.parse in a try/catch and fall back to displaying the raw string if parsing fails. want to give this a go?

**Comment by brookemitchell** [comment]
Also relates to #2321

**Comment by amsimoes** [comment]
Getting the same error.

https://github.com/expo/expo-cli/issues/2321#issuecomment-651006183

"reverting back to expo-cli@3.17.24 fixes the issue."
Does this fix it?

**Comment by azurinspire** [comment]
I have same problem, putting `console.log(stderr)` after `const { stderr } = await spawnAsyncThrowError(program, args, spawnOptions);` produces:

```
No entry for terminal type "dumb";
using dumb terminal settings.
{"result":"success"}
[20:25:02] Failed to upload the standalone app to the app store.
[20:25:02] Unexpected token N in JSON at position 0
[20:25:02] SyntaxError: Unexpected token N in JSON at position 0
    at JSON.parse (<anonymous>)
    at runFastlaneAsync (/usr/local/lib/node_modules/expo-cli/build/commands/upload/utils.js:134:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at IOSUploader._uploadToTheStore (/usr/local/lib/node_modules/expo-cli/src/commands/upload/IOSUploader.ts:233:7)
    at IOSUploader.upload (/usr/local/lib/node_modules/expo-cli/src/commands/upload/BaseUploader.ts:33:5)
    at /usr/local/lib/node_modules/expo-cli/src/commands/upload.ts:120:9
    at Command.<anonymous> (/usr/local/lib/node_modules/expo-cli/src/exp.ts:79:7)
```

What I don't understand is why result is success but upload is failed? There is no new version in App Store.

**Comment by brentvatne** [comment]
@azurinspire - you may have an easier time using the [transporter app](https://apps.apple.com/us/app/transporter/id1450874784) until we improve the quality of error messages from the upload command

**Comment by azurinspire** [comment]
@brentvatne is it possible to use transporter app from CI process somehow?

**Comment by brentvatne** [comment]
not that i know of. in that context, you could install fastlane and use deliver to have it do this for you - https://docs.fastlane.tools/actions/deliver/ - this is what expo-cli does for you but you may get a better error message directly from fastlane right now

**Comment by renegare** [comment]
Apologies for the delayed response. Life in general has taken priority. I'll read through the comments and if I can submit a PR. will link it here and go from there.

Aside: I have succefully deployed to the app store and google play store since dispite this issue. So I'm confident the problem can be resolved. Possibly just a error on our side (client) than an error with the itunesconnect apis (Server).

**Comment by cannc4** [comment]
Same problem happening in CI server too. 
```
[09:04:59]: Successfully uploaded the new binary to App Store Connect
[09:04:59]: `skip_waiting_for_build_processing` used and no `changelog` supplied - skipping waiting for build processing
[09:04:59] Failed to upload the standalone app to the app store.
[09:04:59] Unexpected token N in JSON at position 0
[09:04:59] SyntaxError: Unexpected token N in JSON at position 0
    at JSON.parse (<anonymous>)
    at runFastlaneAsync (/usr/local/lib/node_modules/expo-cli/src/commands/upload/utils.ts:51:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ERROR: Job failed: exit status 1
```

**Comment by tadhglewis** [comment]
Having the same issue, uploads successfully `Successfully uploaded the new binary to App Store Connect` but fails due to json parsing issue.

**Comment by shafranRedLabs** [comment]
Same Issue Continues

**Comment by brentvatne** [comment]
i'm going to lock this because we don't plan on continuing to support using `expo upload:ios` in its current form in expo-cli. you should use transporter or fastlane directly instead.

we'll be releasing a hosted version of the upload command soon, which will be much more reliable.

**Comment by brentvatne** [comment]
`expo upload:ios` has been replaced by `eas submit` as described here https://github.com/expo/expo-cli/issues/2192#issuecomment-745626708
