### ISSUE TITLE
suddenly i restart my server it failed

### ISSUE THREAD

**Issue by coolpinkzz** [expo/expo-cli#2376]
Failed to read config at: E:\confusion\app.config.js
ConfigError: Failed to read config at: E:\confusion\app.config.js
    at Object.getDynamicConfig (C:\Users\ASUS\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\config\src\getConfig.ts:39:9)
    at getConfig (C:\Users\ASUS\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\config\src\Config.ts:121:62)
    at isWebOnly (C:\Users\ASUS\AppData\Roaming\npm\node_modules\expo-cli\src\commands\start.ts:65:19)
    at normalizeOptionsAsync (C:\Users\ASUS\AppData\Roaming\npm\node_modules\expo-cli\src\commands\start.ts:83:33)
    at C:\Users\ASUS\AppData\Roaming\npm\node_modules\expo-cli\src\commands\start.ts:350:41
    at C:\Users\ASUS\AppData\Roaming\npm\node_modules\expo-cli\src\exp.ts:315:12      
    at Command.<anonymous> (C:\Users\ASUS\AppData\Roaming\npm\node_modules\expo-cli\src\exp.ts:80:13)

**Comment by byCedric** [comment]
Hi @coolpinkzz, thanks for the issue report. Unfortunately, [without a repro](https://stackoverflow.com/help/minimal-reproducible-example) we can't help you find the issue. If you think this is an issue on our side, please open a new issue and fill in the required info from the template.

**Comment by lucasvieceli** [comment]
https://github.com/expo/expo-cli/issues/2127
