### ISSUE TITLE
iOS build failure when icon is invalid does not have useful error message

### ISSUE THREAD

**Issue by mikeRChambers610** [expo/expo-cli#2420]
Hi Expo Team,

My Expo iOS build is failing at the below location. I am not seeing any error output so I have no idea why it is failing. I have completed many build on this project with no issue before.

https://expo.io/dashboard/mikechambers610/builds/f77673e0-af6e-4a30-912b-2c64109289c9

The app is successfully published to the link below:

https://expo.io/@mikechambers610/groupaid

**Also, here is the output from running expo diagnostics.**

  Expo CLI 3.23.1 environment info:

    System:

      OS: macOS 10.15.5

      Shell: 3.2.57 - /bin/bash

    Binaries:

      Node: 10.16.3 - /usr/local/bin/node

      npm: 6.14.5 - /usr/local/bin/npm

      Watchman: 4.9.0 - /usr/local/bin/watchman

    IDEs:

      Android Studio: 3.0 AI-171.4443003

      Xcode: 11.5/11E608c - /usr/bin/xcodebuild

    npmPackages:

      expo: ^38.0.8 => 38.0.8 

      react: 16.11.0 => 16.11.0 

      react-dom: 16.11.0 => 16.11.0 

      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 

      react-native-web: ~0.11.7 => 0.11.7 

      react-navigation: ^4.4.0 => 4.4.0 

    npmGlobalPackages:

      expo-cli: 3.23.1

**Lastly, here is some watchman warnings I am getting in the expo console before running the app in the simulator. Not sure it has anything to do with the issue building to the server but adding incase it helps find the root cause. The app runs perfectly fine in the simulator though.**

ERROR
01:31
watchman warning:  opendir(/Users/mikechambers/Library/Caches/com.apple.safaridavclient) -> Operation not permitted. Marking this portion of the tree deleted
To clear this warning, run:
`watchman watch-del /Users/mikechambers ; watchman watch-project /Users/mikechambers`

ERROR
01:32
opendir(/Users/mikechambers/Library/Caches/com.apple.safaridavclient) -> Operation not permitted. Marking this portion of the tree deleted
To clear this warning, run:
`watchman watch-del /Users/mikechambers ; watchman watch-project /Users/mikechambers`

ERROR
01:32
opendir(/Users/mikechambers/Library/Caches/com.apple.safaridavclient) -> Operation not permitted. Marking this portion of the tree deleted
To clear this warning, run:
`watchman watch-del /Users/mikechambers ; watchman watch-project /Users/mikechambers`

ERROR
01:32
Error running `xcrun simctl openurl booted exp://127.0.0.1:19000`: An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=60):
The operation couldn’t be completed. Operation timed out
Operation timed out
ERROR
01:32
Error installing or running app. Error: xcrun exited with non-zero code: 60

**Comment by mikeRChambers610** [comment]
I was able to fix this by using a website to resize my icon. Once I uploaded the same 1024 x 1024 image for all of my icons the stand alone build seems to work.

This issue can be closed but it would be nice for the error output to be more direct towards the issue.

**Comment by brentvatne** [comment]
indeed it does not look very useful:

```
Configuring iOS Launch Screen...
Bundling assets...
Compiling resources...
Cleaning up iOS...
Error: xcrun exited with non-zero code: 1
    at ChildProcess.completionListener (/usr/local/turtle-js/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    ...
    at spawnAsync (/usr/local/turtle-js/node_modules/@expo/xdl/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnAsyncThrowError (/usr/local/turtle-js/node_modules/@expo/xdl/build/detach/ExponentTools.js:190:45)
    at Object.buildAssetArchiveAsync (/usr/local/turtle-js/node_modules/@expo/xdl/build/detach/IosAssetArchive.js:96:51)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.configureAsync (/usr/local/turtle-js/node_modules/@expo/xdl/build/detach/IosNSBundle.js:687:7)
    at async Object.configureAndCopyArchiveAsync (/usr/local/turtle-js/node_modules/@expo/xdl/build/detach/IosShellApp.js:365:3)
    at async Object.runShellAppBuilder [as default] (/usr/local/turtle-js/build/builders/utils/ios/shellAppBuilder.js:55:12)
    at async Object.buildArchive [as default] (/usr/local/turtle-js/build/builders/ios/archive.js:27:26)
    at async Object.iosBuilder [as ios] (/usr/local/turtle-js/build/builders/ios/index.js:29:13)
    at async build (/usr/local/turtle-js/build/jobManager.js:158:24)
    at async processJob (/usr/local/turtle-js/build/jobManager.js:103:32)
    at async Object.doJob (/usr/local/turtle-js/build/jobManager.js:35:5)
    at async main (/usr/local/turtle-js/build/server.js:44:13)
```
