### ISSUE TITLE
[uri-scheme] Using the uri-scheme commands throws an "Invariant Violation" error

### ISSUE THREAD

**Issue by IAmMarcellus** [expo/expo-cli#2434]
## Description
The "add" and "list" commands throw an "Invariant Violation" error instead of performing the expected operation.

## Expected Behavior
The commands work as intended and not throw an error.

## Observed Behavior
```
npx uri-scheme list

Aborting run
An unexpected error was encountered. Please report it as a bug:
Invariant Violation: Missing key while parsing <dict/>.
    at Object.r [as default] (/.../node_modules/uri-scheme/build/index.js:1:412186)
    at parsePlistXML (/.../node_modules/uri-scheme/build/index.js:1:213226)
    at parsePlistXML (/.../node_modules/uri-scheme/build/index.js:1:213009)
    at Object.parse (/.../node_modules/uri-scheme/build/index.js:1:212732)
    at Object.getAsync (/.../node_modules/uri-scheme/build/index.js:1:217769)
    at Object.listAsync (/.../node_modules/uri-scheme/build/index.js:1:262990)
    at Command.<anonymous> (/.../node_modules/uri-scheme/build/index.js:1:105601) {
  framesToPop: 1
}
```

## Environment
- Bare workflow
- Phone/emulator/simulator platform, model and version: N/A, the problem is with using the CLI and occurs before running the app on a platform
```
  Expo CLI 3.21.10 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.9 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: ~0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
```
## Reproducible Demo
1. Create a new project (bare workflow w/ typescript) using expo CLI
2. Try to list URIs or add a new one using uri-scheme (e.x. `npx uri-scheme list`)
3. The error should appear in your terminal

**Comment by byCedric** [comment]
It looks like there is a syntax error in your `./ios/<project>/Info.plist` file. Could you share this one?

**Comment by EvanBacon** [comment]
Closing, please feel free to reopen with the corrupted Info.plist
