### ISSUE TITLE
Tests fail in fresh project

### ISSUE THREAD

**Issue by curt-tophatter** [expo/expo-cli#2437]
## Description

Running `expo init` and choosing the `minimal` option results in a project whose tests fail immediately upon completion.

## Expected Behavior

For the tests to pass in a brand new project

## Observed Behavior

The tests fail with

```sh
yarn run v1.22.4
$ jest
 FAIL  __tests__/App.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/curthoward/Sandbox/games/Octos/node_modules/expo-status-bar/build/StatusBar.js:1
    export * from './StatusBar.types';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import { StatusBar } from 'expo-status-bar';
        | ^
      2 | import React from 'react';
      3 | import { StyleSheet, Text, View } from 'react-native';
      4 |

      at Runtime._execModule (node_modules/jest-runtime/build/index.js:1157:58)
      at Object.<anonymous> (App.js:1:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.27s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by byCedric** [comment]
Thanks for the reply! So what do you mean by "not working for me", is it failing the tests or failing to execute Jest?

**Comment by curt-tophatter** [comment]
Sorry @byCedric, I thought you were telepathic! 

It "not working" was in reference to the same error that kicked this whole ticket off being present for me after running the tests. The `SyntaxError: Unexpected token 'export'` one...

**Comment by developer-stephan** [comment]
I have the same problem...no ideas?

**Comment by EgidioCaprino** [comment]
I'm having the same problem.

```typescript
// jest.config.ts
import type { Config } from '@jest/types';

const config: Config.InitialOptions = {
  preset: 'jest-expo',
};

export default config;
```

```bash
$ yarn test
yarn run v1.22.10
$ jest
 FAIL  ./App.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/egidio/workspace/Xeno/node_modules/expo-status-bar/build/StatusBar.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './StatusBar.types';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import { StatusBar } from 'expo-status-bar';
        | ^
      2 | import React from 'react';
      3 | import { StyleSheet, Text, View } from 'react-native';
      4 | 

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1258:14)
      at Object.<anonymous> (App.tsx:1:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.609s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by EgidioCaprino** [comment]
I solved by renaming `jest.config.ts` to `jest.config.js`. Even though Jest documentation states you can use `.ts` extension, when running `jest --config jest.config.ts` I was getting this error:

> The --config option requires a JSON string literal, or a file path with one of these extensions: .js, .mjs, .cjs, .json.
