### ISSUE TITLE
Unable to build for iOS after 3.24 upgrade

### ISSUE THREAD

**Issue by wstock** [expo/expo-cli#2449]
## Description

iOS archive build fails after 3.24 upgrade with Authentication with Apple Developer Portal failed!
Reason: Unknown reason, raw: "Unauthorized Access"

## Expected Behavior

Build as per previous versions

## Observed Behavior

Access to apple account? y
Apple Id: xxxx
Password: xxxx
(verification code sent and received)
Verification code: xxxx

```
Authenticating to Apple Developer Portal...  
Available session is not valid any more. Continuing with normal login.
Authentication with Apple Developer Portal failed!
Reason: Unknown reason, raw: "Unauthorized Access"
Error: Reason: Unknown reason, raw: "Unauthorized Access"
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at authenticate (C:\Users\Will\AppData\Roaming\npm\node_modules\expo-cli\src\appleApi\authenticate.ts:47:40) 
    at Context.ensureAppleCtx (C:\Users\Will\AppData\Roaming\npm\node_modules\expo-cli\src\credentials\context.ts:81:24)
    at IOSBuilder.bestEffortAppleCtx (C:\Users\Will\AppData\Roaming\npm\node_modules\expo-cli\src\commands\build\ios\IOSBuilder.ts:97:14)
    at IOSBuilder.prepareCredentials (C:\Users\Will\AppData\Roaming\npm\node_modules\expo-cli\src\commands\build\ios\IOSBuilder.ts:153:5)
    at IOSBuilder.run (C:\Users\Will\AppData\Roaming\npm\node_modules\expo-cli\src\commands\build\ios\IOSBuilder.ts:62:7)
    at IOSBuilder.command (C:\Users\Will\AppData\Roaming\npm\node_modules\expo-cli\src\commands\build\BaseBuilder.ts:39:7)
    at Command.<anonymous> (C:\Users\Will\AppData\Roaming\npm\node_modules\expo-cli\src\exp.ts:79:7)
```

## Environment

  Expo CLI 3.24.0 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^38.0.0 => 38.0.3
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7

## Reproducible Demo

expo build:ios

**Comment by wstock** [comment]
US VPN as per here solved https://github.com/expo/expo-cli/issues/1631
