### ISSUE TITLE
Authentication with Apple Developer Portal failed! on build:ios and client:ios

### ISSUE THREAD

**Issue by blakeglucas** [expo/expo-cli#2451]
## Description

I'm trying to install a custom Expo client so I can test the background location services feature in `expo-location` (as described [here](https://docs.expo.io/guides/adhoc-builds/)). Every time I run the command `expo client:ios` and log in with the correct Apple ID and password, it errors out with a code 127 and no other indicators. I observe this same error whenever I attempt to run `expo build:ios`. I have tried with both the Account Holder Apple ID and a generic Admin Apple ID, and neither succeeds.

## Expected Behavior

I expected to be able to follow along with the link referenced in the description, however, it errors out as shown below.

## Observed Behavior

The login fails, despite providing correct credentials and having an active company account and paid developer program membership.

```
Authentication with Apple Developer Portal failed!
bash exited with non-zero code: 127
Error: bash exited with non-zero code: 127
    at ChildProcess.completionListener (C:\Users\<username>\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.cp.emit (C:\Users\<username>\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    ...
    at spawnAsync (C:\Users\<username>\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:26:19)
    at runAction (C:\Users\<username>\AppData\Roaming\npm\node_modules\expo-cli\src\appleApi\fastlane.ts:20:28)
    at authenticate (C:\Users\<username>\AppData\Roaming\npm\node_modules\expo-cli\src\appleApi\authenticate.ts:47:46)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Context.ensureAppleCtx (C:\Users\<username>\AppData\Roaming\npm\node_modules\expo-cli\src\credentials\context.ts:81:24)
    at IOSBuilder.bestEffortAppleCtx (C:\Users\<username>\AppData\Roaming\npm\node_modules\expo-cli\src\commands\build\ios\IOSBuilder.ts:97:14)
    at IOSBuilder.prepareCredentials (C:\Users\<username>\AppData\Roaming\npm\node_modules\expo-cli\src\commands\build\ios\IOSBuilder.ts:153:5)
    at IOSBuilder.run (C:\Users\<username>\AppData\Roaming\npm\node_modules\expo-cli\src\commands\build\ios\IOSBuilder.ts:62:7)
    at IOSBuilder.command (C:\Users\<username>\AppData\Roaming\npm\node_modules\expo-cli\src\commands\build\BaseBuilder.ts:39:7)
    at Command.<anonymous> (C:\Users\<username>\AppData\Roaming\npm\node_modules\expo-cli\src\exp.ts:79:7)
```

## Environment

```
Expo CLI 3.24.0 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
    npmPackages:
      expo: ^37.0.0 => 37.0.7
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: 0.61.4 => 0.61.4
      react-native-web: ^0.11.7 => 0.11.7
```

I have been pretty exclusively testing iOS builds on an iPhone X running iOS 13.6 (17G68).

## Reproducible Demo

I am not sure how to include a reproducible demo for an issue that relies on an Apple Developer Portal connection. If anyone knows how, I can update this ticket accordingly.

**Comment by brentvatne** [comment]
@byCedric is going to try to reproduce this on his machine, if he can reproduce we'll chat with @quinlanj about how to proceed as she is the most knowledgable about this area of the codebase.

if you are encountering this issue on windows, you should be able to work around it by installing wsl.

**Comment by blakeglucas** [comment]
I have WSL1 installed and working (Ubuntu 18.04). Is it possible I need to upgrade Windows 10 and install WSL2?

Also, I just tried re-enabling WSL and restarted my machine. Ran `expo client:ios` in Admin Powershell, same error as above.

**Comment by wodin** [comment]
@blakeglucas given that the paths in the error are Windows paths rather than Unix paths it looks like this is not actually running from within Ubuntu?

I have only tried out WSL briefly a few months ago, so maybe I'm wrong.

But maybe make sure you have `node`, `npm`, `expo-cli` etc. installed in Ubuntu and run `expo build:ios` from the Bash prompt.

**Comment by blakeglucas** [comment]
@wodin You're correct, I was running the command in Windows Powershell. After mucking around with Windows vs Ubuntu node installations and running `expo client:ios` in Ubuntu WSL, I get the following error
```
✔ Found custom configuration for the Expo client
Accessing credentials for blakeglucas in project <project>
Please enter your Apple Developer Program account credentials. These credentials are needed to manage certificates, keys and provisioning profiles in your Apple Developer account.
The password is only used to authenticate with Apple and never stored
Learn more here (​https://bit.ly/2VtGWhU​)
? Apple ID: <AppleID>
? Password (for <AppleID>): [hidden]
Authenticating to Apple Developer Portal...
Two-factor Authentication (6 digits code) is enabled for account '<AppleID>'
More information about Two-factor Authentication: https://support.apple.com/en-us/HT204915

If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification

Please enter the 6 digit code you received at +1 (•••) •••-••09:
<code>
Requesting session...
Authentication with Apple Developer Portal failed!
Reason: #Unknown reason, raw: "Unauthorized Access"
Error: Reason: Unknown reason, raw: "Unauthorized Access"
    at runAction (/usr/lib/node_modules/expo-cli/src/appleApi/fastlane.ts:28:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at authenticate (/usr/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:47:40)
    at Context.ensureAppleCtx (/usr/lib/node_modules/expo-cli/src/credentials/context.ts:81:24)
    at /usr/lib/node_modules/expo-cli/src/commands/client/index.ts:100:9
    at Command.<anonymous> (/usr/lib/node_modules/expo-cli/src/exp.ts:79:7)
```
Related issue: #1631 

This specific issue aside, the docs linked in the original post should probably clarify where the command(s) is/are supposed to run. I imagine that with WSL2 it can be run from Powershell, but WSL1 doesn't "combine" Windows and Linux command sets.

**Comment by blakeglucas** [comment]
As per #2449, a US VPN solved the authentication issue (it is worth noting, though, that I am already in the US and the VPN server is in my city... so I'm at a loss as to why this is needed). 

When going through the custom client flow, though, it fails if a device has not already been added to the Apple Developer Portal prior to asking if you would like to add one, but that's a new issue so I'll close this one.
