### ISSUE TITLE
Error trying to run expo upload:ios

### ISSUE THREAD

**Issue by jasuno** [expo/expo-cli#2493]
Downloading build from https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/ios/%40mixemapp17/mixemapp-7648f20a-024a-4d4a-bc39-24caae2b566e-archive.ipa
(node:18942) ExperimentalWarning: The dns.promises API is experimental
(node:18942) UnhandledPromiseRejectionWarning: Error: total required
    at new ProgressBar (/usr/local/lib/node_modules/expo-cli/node_modules/progress/lib/node-progress.js:55:49)
    at Request._got.default.stream.on.progress (/usr/local/lib/node_modules/expo-cli/src/commands/upload/utils.ts:17:13)
    at Request.emit (events.js:189:13)
    at Request._onResponse (/usr/local/lib/node_modules/expo-cli/node_modules/got/dist/source/core/index.js:689:14)
    at ClientRequest.request.once (/usr/local/lib/node_modules/expo-cli/node_modules/got/dist/source/core/index.js:817:18)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:194:15)
    at ClientRequest.origin.emit.args [as emit] (/usr/local/lib/node_modules/expo-cli/node_modules/got/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
(node:18942) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18942) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by byCedric** [comment]
Hi @jasuno, thanks for reporting this! I created a fix for this, should be resolved soon!
