### ISSUE TITLE
Error: Cannot find module 'getenv'

### ISSUE THREAD

**Issue by macuna** [expo/expo-cli#2518]
Hello,

I'm having this issue trying to run a new bare workflow project in my Mac OSX.

```  Expo CLI 3.25.0 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.9 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: ~0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.25.0
```

The steps to reproduce this 

```
 expo init --template bare-minimum TestApp
```
```
yarn ios
```

And I got the error below
```
+ DEST=/Users/martin/Library/Developer/Xcode/DerivedData/TestApp-ebhlqtibjlaiiubojfanhelaetll/Build/Products/Debug-iphonesimulator/TestApp.app
+ [[ Debug = *Debug* ]]
+ [[ ! iphonesimulator == *simulator ]]
+ [[ -n '' ]]
+ case "$CONFIGURATION" in
+ [[ iphonesimulator == *simulator ]]
+ [[ -n '' ]]
+ echo 'Skipping bundling in Debug for the Simulator (since the packager bundles for you). Use the FORCE_BUNDLING flag to change this behavior.'
Skipping bundling in Debug for the Simulator (since the packager bundles for you). Use the FORCE_BUNDLING flag to change this behavior.
+ exit 0
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'getenv'
Require stack:
- /TestApp/node_modules/@expo/image-utils/build/sharp.js
- /TestApp/node_modules/@expo/image-utils/build/Image.js
- /TestApp/node_modules/@expo/image-utils/build/index.js
- /TestApp/node_modules/@expo/config/build/ios/Icons.js
- /TestApp/node_modules/@expo/config/build/ios/index.js
- /TestApp/node_modules/@expo/config/build/index.js
- /TestApp/node_modules/@expo/metro-config/build/ExpoMetroConfig.js
- /TestApp/node_modules/expo-updates/scripts/createManifest.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/TestApp/node_modules/@expo/image-utils/build/sharp.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/TestApp/node_modules/@expo/image-utils/build/sharp.js',
    '/TestApp/node_modules/@expo/image-utils/build/Image.js',
    '/TestApp/node_modules/@expo/image-utils/build/index.js',
    '/TestApp/node_modules/@expo/config/build/ios/Icons.js',
    '/TestApp/node_modules/@expo/config/build/ios/index.js',
    '/TestApp/node_modules/@expo/config/build/index.js',
    '/TestApp/node_modules/@expo/metro-config/build/ExpoMetroConfig.js',
    '/TestApp/node_modules/expo-updates/scripts/createManifest.js'
  ]
}
Command PhaseScriptExecution failed with a nonzero exit code

GenerateDSYMFile /Users/martin/Library/Developer/Xcode/DerivedData/TestApp-ebhlqtibjlaiiubojfanhelaetll/Build/Products/Debug-iphonesimulator/TestApp.app.dSYM /Users/martin/Library/Developer/Xcode/DerivedData/TestApp-ebhlqtibjlaiiubojfanhelaetll/Build/Products/Debug-iphonesimulator/TestApp.app/TestApp (in target 'TestApp' from project 'TestApp')
    cd /TestApp/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/martin/Library/Developer/Xcode/DerivedData/TestApp-ebhlqtibjlaiiubojfanhelaetll/Build/Products/Debug-iphonesimulator/TestApp.app/TestApp -o /Users/martin/Library/Developer/Xcode/DerivedData/TestApp-ebhlqtibjlaiiubojfanhelaetll/Build/Products/Debug-iphonesimulator/TestApp.app.dSYM

warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 6.0, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'OpenSSL-Universal' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 5.0, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'CocoaAsyncSocket' from project 'Pods')
warning: no rule to process file '/TestApp/ios/Pods/Flipper-RSocket/rsocket/benchmarks/CMakeLists.txt' of type 'text' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/TestApp/ios/Pods/Flipper-RSocket/rsocket/benchmarks/README.md' of type 'net.daringfireball.markdown' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/TestApp/ios/Pods/Flipper-RSocket/rsocket/README.md' of type 'net.daringfireball.markdown' for architecture 'x86_64' (in target 'Flipper-RSocket' from project 'Pods')

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/martin/Library/Developer/Xcode/DerivedData/TestApp-ebhlqtibjlaiiubojfanhelaetll/Build/Intermediates.noindex/TestApp.build/Debug-iphonesimulator/TestApp.build/Script-00DD1BFF1BD5951E006B06BC.sh
(1 failure)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by LouisJS** [comment]
Same issue. Trying to build bare workflow app with expo-updates. Issue on Android :

```
> Task :app:createStagingReleaseExpoManifest
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'getenv'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/vagrant/git/node_modules/@expo/image-utils/build/sharp.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

> Task :app:createStagingReleaseExpoManifest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:createStagingReleaseExpoManifest'.
> Process 'command 'node'' finished with non-zero exit value 1
```

**Comment by LouisJS** [comment]
I believe [this](https://github.com/expo/expo-cli/commit/bad2c62955668ebf747dcd3096d054ec6a23262e) fix it.
But i don't know how to apply it to my repo

**Comment by macuna** [comment]
I've solved just installing getenv

```
npm install getenv
```

**Comment by LouisJS** [comment]
@macuna Well that would probably work if you build your app in local, but if you're trying to build it thanks to a service like Bitrise or Fastlane. You're definitely gonna have an issue

**Comment by byCedric** [comment]
`expo-optimize@0.1.45` was just published (thanks @brentvatne). This should now be fixed, if not let me know!

**Comment by LouisJS** [comment]
@byCedric @brentvatne I did fix the issue (i think it's related to expo/image-utils though, but anyway. It works ! Thank guys !
