### ISSUE TITLE
Cannot init bare flow 

### ISSUE THREAD

**Issue by Wellbrito29** [expo/expo-cli#2522]
im trying to init a project with expo init, with bare flow, but im getting this error : 

Error: Cannot find module 'getenv'
Require stack:
- /Users/wellbrito29/Documents/test/test/node_modules/@expo/image-utils/build/sharp.js
- /Users/wellbrito29/Documents/test/test/node_modules/@expo/image-utils/build/Image.js
- /Users/wellbrito29/Documents/test/test/node_modules/@expo/image-utils/build/index.js
- /Users/wellbrito29/Documents/test/test/node_modules/@expo/config/build/ios/Icons.js
- /Users/wellbrito29/Documents/test/test/node_modules/@expo/config/build/ios/index.js
- /Users/wellbrito29/Documents/test/test/node_modules/@expo/config/build/index.js
- /Users/wellbrito29/Documents/test/test/node_modules/@expo/metro-config/build/ExpoMetroConfig.js
- /Users/wellbrito29/Documents/test/test/node_modules/expo-updates/scripts/createManifest.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
    at Function.Module._load (internal/modules/cjs/loader.js:923:27)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/wellbrito29/Documents/test/test/node_modules/@expo/image-utils/build/sharp.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/wellbrito29/Documents/test/test/node_modules/@expo/image-utils/build/sharp.js',
    '/Users/wellbrito29/Documents/test/test/node_modules/@expo/image-utils/build/Image.js',
    '/Users/wellbrito29/Documents/test/test/node_modules/@expo/image-utils/build/index.js',
    '/Users/wellbrito29/Documents/test/test/node_modules/@expo/config/build/ios/Icons.js',
    '/Users/wellbrito29/Documents/test/test/node_modules/@expo/config/build/ios/index.js',
    '/Users/wellbrito29/Documents/test/test/node_modules/@expo/config/build/index.js',
    '/Users/wellbrito29/Documents/test/test/node_modules/@expo/metro-config/build/ExpoMetroConfig.js',
    '/Users/wellbrito29/Documents/test/test/node_modules/expo-updates/scripts/createManifest.js'
  ]
}
Command PhaseScriptExecution failed with a nonzero exit code

and expo diagnostics: 

Expo CLI 3.25.0 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.8.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.9 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: ~0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.25.0

**Comment by Wellbrito29** [comment]
i solved this : 

`yarn add getenv`
