### ISSUE TITLE
Stuck at "Installing Expo client on iOS simulator"

### ISSUE THREAD

**Issue by pilotpirxie** [expo/expo-cli#2540]
## Description
When I am trying to run an application on iOS Simulator nothing happens after "Installing Expo client on iOS simulator" log. This happens after the first successful run in the simulator. I delete the app from the simulator and close it. When I tried to run it second time (even on different virtual device) it's not running properly.

## Expected Behavior
expo start --ios
few seconds wait
open ios simulator
install the application on one of the screens

## Observed Behavior
expo start --ios
few seconds wait
open ios simulator
then nothing happens, in terminal it stuck at "-" character like below

```
Starting project at /Users/user/app
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Starting Metro Bundler.
Installing Expo client on iOS simulator
-
```

When I am stop process I got:
```
Stopping packager...

user@user-nm client % › Closing Expo server
Error running `xcrun simctl list devices --json`: 
Error installing or running app. Error: xcrun exited with signal: SIGINT
Error running `xcrun simctl list devices --json`: 
Error installing or running app. Error: xcrun exited with signal: SIGINT
setRawMode EIO
Error: setRawMode EIO
    at ReadStream.setRawMode (tty.js:77:31)
    at startWaitingForCommand (/usr/local/lib/node_modules/expo-cli/src/commands/start/TerminalUI.ts:118:11)
    at Object.startAsync (/usr/local/lib/node_modules/expo-cli/src/commands/start/TerminalUI.ts:130:3)
    at action (/usr/local/lib/node_modules/expo-cli/src/commands/start.ts:193:22)
    at /usr/local/lib/node_modules/expo-cli/src/commands/start.ts:354:16
    at Command.<anonymous> (/usr/local/lib/node_modules/expo-cli/src/exp.ts:79:7)
^C
```

## Environment
  Expo CLI 3.25.1 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.19.0 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.8 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.25.1

**Comment by pilotpirxie** [comment]
I found a solution.
https://stackoverflow.com/questions/54793345/cant-run-expo-start-on-a-expo-react-native-app-permission-problem

Installing with ``sudo`` dependencies and expo makes /Users/user/.expo directory belongs to root and for some reason, I cannot run the simulator. Removing this directory and running iOS simulator without sudo keyword solve my problem.

To reproduce solution:
```sh
# check your project directory path
pwd
# move to your user home
cd /Users/YOUR_NICKNAME/
# check if .expo is on the list
ls 
# remove .expo/ directory
sudo rm -rf .expo/
# navigate to your project once again
cd PATH_TO_YOUR_PROJECT_FROM_ABOVE
# run without sudo
yarn ios
# or
expo start --ios
```
