### ISSUE TITLE
Unexpcted string in path when using --use-submission-service on GitLab CI

### ISSUE THREAD

**Issue by johnjago** [expo/expo-cli#2599]
## Description

The command `expo upload:android --latest --key $PLAY_STORE_SERVICE_ACCOUNT --track production --use-submission-service --verbose` results in an error when running on GitLab CI/CD.

`--use-submission-service` is probably the relevant flag, but I've included the others in case they help with debugging.

When [resolving the Android package source](https://github.com/expo/expo-cli/blob/c5c59a7dc8febf9a5af36b33e06807f3aba2acf7/packages/expo-cli/src/commands/upload/submission-service/android/AndroidSubmitCommand.ts#L76), for some reason `"type":` gets inserted into the path: `/builds/company/mobile-app/"type":/package.json`.

## Expected Behavior

The correct path is `/builds/company/mobile-app/package.json`. That is, package.json is at the root of the project (app.json is too).

## Observed Behavior

```
[20:15:12] Waiting for build to complete.
You can press Ctrl+C to exit. It won't cancel the build, you'll be able to monitor it at the printed URL.
- 
✔ Build finished.
[20:39:24] Successfully built standalone app: https://expo.io/artifacts/19813790-0039-40be-a52a-05ee9bb20052
[20:39:26] The expected package.json path: /builds/company/mobile-app/"type":/package.json does not exist
[20:39:26] ConfigError: The expected package.json path: /builds/company/mobile-app/"type":/package.json does not exist
    at Object.getRootPackageJsonPath (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config/src/Modules.ts:63:11)
    at getPackageJsonAndPath (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config/src/Config.ts:152:27)
    at getConfig (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config/src/Config.ts:94:42)
    at getExpoConfig (/usr/local/lib/node_modules/expo-cli/src/commands/upload/submission-service/utils/config.ts:22:27)
    at AndroidSubmitCommand.resolveAndroidPackageSource (/usr/local/lib/node_modules/expo-cli/src/commands/upload/submission-service/android/AndroidSubmitCommand.ts:81:17)
    at AndroidSubmitCommand.getAndroidSubmissionOptions (/usr/local/lib/node_modules/expo-cli/src/commands/upload/submission-service/android/AndroidSubmitCommand.ts:48:39)
    at AndroidSubmitCommand.runAsync (/usr/local/lib/node_modules/expo-cli/src/commands/upload/submission-service/android/AndroidSubmitCommand.ts:42:36)
    at /usr/local/lib/node_modules/expo-cli/src/commands/upload.ts:58:7
    at Command.<anonymous> (/usr/local/lib/node_modules/expo-cli/src/exp.ts:302:7)
```

## Environment

This error occurs when running on a continous integration platform in the Docker image `node:14`.

It does not occur when I run it on my local computer:

```
  Expo CLI 3.26.2 environment info:
    System:
      OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 14.9.0 - /usr/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 6.14.8 - /usr/bin/npm
    npmPackages:
      expo: ^37.0.12 => 37.0.12 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.26.2
```

## Reproducible Demo

Sorry, not quite sure how to set up a repro for this because it would require setting up a demo app to be published to the Google Play Store.

**Comment by EvanBacon** [comment]
`expo upload:android` is now deprecated in favor of `eas submit -p android`.
