### ISSUE TITLE
expo init command fails with error message : Unexpected end of JSON input

### ISSUE THREAD

**Issue by subhrm** [expo/expo-cli#263]
## Description

`expo init` command fails with the following error message  `npm ERR! Unexpected end of JSON input while parsing near '...er","version":"1.1.0"'` . Complete console output pasted below.

## Expected Behavior

it should have run successfully.

## Observed Behavior

Complete terminal output :

```
srm@ZZ580:~/Documents/my_play_ground$ expo init alphabets-app
? Choose a template: expo-template-blank
[23:21:43] Extracting project files...
[23:21:44] Customizing project...
[23:21:44] Initialized a git repository.
[23:21:44] Installing dependencies...
npm ERR! Unexpected end of JSON input while parsing near '...er","version":"1.1.0"'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/srm/.npm/_logs/2018-12-17T17_52_52_297Z-debug.log
[23:22:52] Process exited with non-zero code: 1
[23:22:52] Error: Process exited with non-zero code: 1
    at ChildProcess.child.on (/usr/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/build/spawnAsync.js:39:21)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

```
 Expo CLI 2.6.14 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/bin/node
      npm: 6.5.0 - /usr/bin/npm
    npmGlobalPackages:
      expo-cli: 2.6.14
```

Also specify:

- Phone/emulator/simulator platform, model and version: n/a

## Reproducible Demo

Run `expo init`

**Comment by subhrm** [comment]
[2018-12-17T17_52_52_297Z-debug.log](https://github.com/expo/expo-cli/files/2687410/2018-12-17T17_52_52_297Z-debug.log)
Please find attached the log file.

**Comment by ide** [comment]
This looks like it could be a transient error (look at the npm logs), try again?

**Comment by subhrm** [comment]
It was probably due to a corrupted package tarball. `npm cache clean --force` followed by `npm install` fixed the issue.
