### ISSUE TITLE
use expo build: ios final return Request failed with status code 502

### ISSUE THREAD

**Issue by tesshsu** [expo/expo-cli#2650]
Hi ,
I had use expo build:ios, everything goes find until to Build in progress...
then show :
`Request failed with status code 502
Error: Request failed with status code 502
    at createError (/Users/TESSHSU/.nvm/versions/node/v12.13.0/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/TESSHSU/.nvm/versions/node/v12.13.0/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/TESSHSU/.nvm/versions/node/v12.13.0/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)`

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo/react-native-action-sheet": "^3.8.0",
    "@expo/vector-icons": "10.2.0",
    "@ptomasroos/react-native-multi-slider": "^2.2.0",
    "@react-native-community/datetimepicker": "^2.1.0",
    "@react-native-community/masked-view": "0.1.5",
    "@react-native-community/slider": "^2.0.8",
    "abortcontroller-polyfill": "^1.4.0",
    "axios": "^0.19.1",
    "buffer": "^5.4.3",
    "expo": "^36.0.0",
    "expo-av": "~8.0.0",
    "expo-blur": "~8.0.0",
    "expo-cli": "^3.25.1",
    "expo-constants": "~8.0.0",
    "expo-facebook": "~8.0.0",
    "expo-file-system": "~8.0.0",
    "expo-font": "~8.0.0",
    "expo-image-picker": "~8.0.1",
    "expo-intent-launcher": "^8.0.0",
    "expo-linear-gradient": "~8.0.0",
    "expo-location": "~8.0.0",
    "expo-permissions": "~8.0.0",
    "formik": "^2.1.1",
    "global": "^4.4.0",
    "moment": "^2.24.0",
    "prop-types": "^15.7.2",
    "qs": "^6.9.1",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-action-sheet": "^2.2.0",
    "react-native-appearance": "~0.3.1",
    "react-native-elements": "^2.0.0",
    "react-native-expo-image-cache": "^4.1.0",
    "react-native-fbsdk": "^2.0.0",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-grid-list": "^1.1.0",
    "react-native-mime-types": "^2.2.1",
    "react-native-path": "^0.0.5",
    "react-native-reanimated": "^1.4.0",
    "react-native-redash": "^10.1.1",
    "react-native-safe-area-context": "0.6.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-shared-element": "^0.5.6",
    "react-native-svg": "9.13.3",
    "react-native-switch-selector": "^2.0.4",
    "react-native-tab-view": "^2.11.0",
    "react-native-web": "~0.11.7",
    "react-navigation": "4",
    "react-navigation-drawer": "2",
    "react-navigation-hooks": "^1.1.0",
    "react-navigation-shared-element": "^2.1.0",
    "react-navigation-stack": "2",
    "react-navigation-tabs": "^2.6.2",
    "react-redux": "^7.1.3",
    "redux": "^4.0.4",
    "redux-persist": "^6.0.0",
    "redux-promise": "^0.6.0",
    "redux-thunk": "^2.3.0",
    "sentry-expo": "3.0.0",
    "socket.io-client": "^2.3.0",
    "uid": "^1.0.0",
    "use-debounce": "^3.3.0",
    "use-google-autocomplete": "^0.1.0",
    "use-memo-one": "^1.1.1",
    "yup": "^0.28.1"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "babel-eslint": "^10.0.1",
    "babel-preset-expo": "~8.0.0",
    "eslint": "^5.16.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.17.2",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.13.0",
    "eslint-plugin-react-hooks": "^2.3.0",
    "eslint-plugin-react-native": "^3.7.0"
  },
  "private": true
}

I search some issue about this but seems not have quiet answer
Appreicate the help!!

**Comment by tesshsu** [comment]
Resolved by just do the process again, tks
