### ISSUE TITLE
Cannot upload android push FCM key

### ISSUE THREAD

**Issue by ZUBAT** [expo/expo-cli#2703]
## Description
Tried to run `expo push:android:upload --api-key <api key>`, got An unknown error occurred.

## Expected Behavior
Expected the execution to complete successfully.

## Observed Behavior
Output from command:

```
Accessing credentials for zubat in project browser-pwa
An unknown error occurred.

```
## Environment
```
expo diagnostics

  Expo CLI 3.27.10 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 14.4.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.13.0 - C:\Users\Yury.Golyandin\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~39.0.2 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.13
    Expo Workflow: managed

```

**Comment by ZUBAT** [comment]
@cruzach You asked me to mention if there is a similar problem in #851 https://github.com/expo/expo-cli/issues/851#issuecomment-512890652

**Comment by m-jachym** [comment]
While using **credentials:manager**

`? What do you want to do? Update FCM Api Key
? FCM Api Key AAAAxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

ApiV2Error: An unknown error occurred.
    at ApiV2Client._requestAsync (C:\@expo\xdl@57.9.33\src\ApiV2.ts:244:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ApiClient.updateFcmKeyApi (C:\Users\marek\AppData\Local\Yarn\Data\global\node_modules\expo-cli\src\credentials\api\AndroidApiV2Wrapper.ts:22:12)
    at AndroidApi.updateFcmKey (C:\Users\marek\AppData\Local\Yarn\Data\global\node_modules\expo-cli\src\credentials\api\AndroidApi.ts:51:5)
    at UpdateFcmKey.open (C:\Users\marek\AppData\Local\Yarn\Data\global\node_modules\expo-cli\src\credentials\views\AndroidPushCredentials.ts:28:5)
    at CredentialsManager.run (C:\Users\marek\AppData\Local\Yarn\Data\global\node_modules\expo-cli\src\credentials\route.ts:41:12)
    at runCredentialsManagerStandalone (C:\Users\marek\AppData\Local\Yarn\Data\global\node_modules\expo-cli\src\credentials\route.ts:7:3)
    at C:\Users\marek\AppData\Local\Yarn\Data\global\node_modules\expo-cli\src\commands\credentials.ts:36:7
    at Command.<anonymous> (C:\Users\marek\AppData\Local\Yarn\Data\global\node_modules\expo-cli\src\exp.ts:79:7) {
  code: 'INTERNAL_SERVER_ERROR',
  details: undefined,
  serverStack: undefined,
  _isApiError: true
}
`

**Comment by m-jachym** [comment]
@ZUBAT Have you found any solution? It's not working for me in just created new projects, but works in one old project 😕

**Comment by ZUBAT** [comment]
Now checked everything works. Apparently there was a temporary glitch
