### ISSUE TITLE
Failed to find the instance of sharp used by the global sharp-cli package

### ISSUE THREAD

**Issue by lostchopstik** [expo/expo-cli#2708]
## Description

When attempting to run 'expo eject' for the first time I get an error during the process right after "Installed JavaScript dependencies". I have been running managed for a few months and have never had any issues running the project. I need to eject at this point due to some unavoidable needs.

## Expected Behavior

My managed workflow should successfully convert to a bare workflow.

## Observed Behavior

An error occurs as follows:

```
Failed to find the instance of sharp used by the global sharp-cli package.
Error: Failed to find the instance of sharp used by the global sharp-cli package.
    at Object.findSharpInstanceAsync (C:\Users\xxx\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\image-utils\src\sharp.ts:169:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ eject: `expo eject`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ eject script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2020-09-25T16_36_23_720Z-debug.log
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run eject" terminated with exit code: 1.
```

The log file generated shows:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'eject'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.1
4 verbose run-script [ 'preeject', 'eject', 'posteject' ]
5 info lifecycle @~preeject: @
6 info lifecycle @~eject: @
7 verbose lifecycle @~eject: unsafe-perm in lifecycle true
8 verbose lifecycle @~eject: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\xxx\source\repos\EMF.Mobile.Pray4One\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\PuTTY\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Plantronics\Spokes3G\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Yarn\bin\;C:\Users\xxx\AppData\Local\Microsoft\WindowsApps;C:\Users\xxx\AppData\Local\GitHubDesktop\bin;C:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\xxx\.dotnet\tools;C:\Users\xxx\AppData\Roaming\npm;C:\Users\xxx\.dotnet\tools;C:\Users\xxx\AppData\Local\Microsoft\WindowsApps;C:\Users\xxx\AppData\Local\Yarn\bin
9 verbose lifecycle @~eject: CWD: C:\Users\xxx\source\repos\EMF.Mobile.Pray4One
10 silly lifecycle @~eject: Args: [ '/d /s /c', 'expo eject' ]
11 silly lifecycle @~eject: Returned: code: 1  signal: null
12 info lifecycle @~eject: Failed to exec eject script
13 verbose stack Error: @ eject: `expo eject`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:223:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:223:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid @
15 verbose cwd C:\Users\xxx\source\repos\EMF.Mobile.Pray4One
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "eject"
18 verbose node v12.14.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error @ eject: `expo eject`
22 error Exit status 1
23 error Failed at the @ eject script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

## Environment

Expo CLI 3.27.10 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ~38.0.9 => 38.0.10
      react: ~16.13.1 => 16.11.0
      react-dom: ~16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
    Expo Workflow: managed

**Comment by brentvatne** [comment]
- do you have sharp-cli installed?
- does it work if you run `npx expo-optimize`?

as for the hashAssetFiles link - thanks for the heads up - fixed in https://github.com/expo/expo-cli/commit/a605574f56c0c9e0bf87eccf4b96ed634ca5d332

**Comment by lostchopstik** [comment]
@brentvatne thanks for replying.

I do have sharp-cli. I performed `npm uninstall -g sharp-cli` and then reinstalled with `npm install -g sharp-cli` with no luck there.

The optimize task does work:
```
PS C:\Users\xxx\source\repos\<myproject>> npx expo-optimize
npx: installed 1 in 1.324s

This will overwrite the original assets.

› Optimizing assets...
› Checking src\assets\bg-header.png
› Saved 105 kB
› Checking src\assets\favicon.png
 › Skipping: Original was 872 B smaller.
› Checking src\assets\icon.png
› Saved 10.3 kB
› Checking src\assets\launch-rest.png
› Saved 11.5 kB
› Checking src\assets\p4o-logo-horizontal.png
› Saved 5.95 kB

› Finished compressing assets. 133 kB saved.
```

**Comment by rusagent** [comment]
I actually have exactly the same problem.

**Comment by Anis-Ghliss** [comment]
I have the same problem when I run expo eject

**Comment by lostchopstik** [comment]
No change in the problem after updating to Expo CLI 3.27.12

**Comment by brentvatne** [comment]
hey @lostchopstik - thanks for the info. we need to do a pass over and add some integration tests for the eject command on windows. for now you can work around this by using linux (via wsl would work) or macos to eject. we'll likely look at this next week, but we'd also welcome contributions. https://github.com/expo/expo-cli/blob/master/CONTRIBUTING.md

**Comment by Thunermay** [comment]
This is still not working on windows...
sharp-cli is freshly installed and all of the above didnt help



rn: 63.4
expo: 40.0.1
expo-cli: 4.3.2

**Comment by brentvatne** [comment]
@Thunermay - can you run `sharp --help`?

**Comment by Thunermay** [comment]
@brentvatne I've just used the project from the friend. Now it is working. But thanks for the kind help!

**Comment by ArticB** [comment]
I'm having this issue right now. Any fixes yet ?

**Comment by brentvatne** [comment]
@ArticB - did you install `sharp-cli`? what output do you get from `sharp --help`?

**Comment by ArticB** [comment]
yes I did install it.

OUTPUT:
'sharp-cli' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Thunermay** [comment]
@ArticB  Try installing it again or restart your Computer, otherwise it will not be recognized.
Or did you install it globally? If not pass the "-g" flag when installing.

**Comment by ArticB** [comment]
Restarting did the trick thanks. 👍 😃

**Comment by mjboroski** [comment]
I fixed this with `npm uninstall -g sharp && npm install -g sharp`

**Comment by soroshzzz26** [comment]
it didnt work i tried everything

**Comment by EvanBacon** [comment]
One thing worth noting is that we used to install sharp by default, but so many windows users had trouble installing expo-cli that we split it out into an optional global package that would fallback to jimp. This is an issue with sharp since it uses native packages that sometimes don't install correctly on windows. Open to any ideas on how we can improve stability.
