### ISSUE TITLE
expo login returning a 401 http code for expo-cli 3.27.12 with valid credentials

### ISSUE THREAD

**Issue by kanenathan213** [expo/expo-cli#2738]
## Description

When using `expo-cli` 3.27.12, `expo login` returns a 401 response.

## Expected Behavior

`expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD` results in `Success. You are now logged in as <EXPO USERNAME>.`

## Observed Behavior

Running `expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD` (with a set of credentials that works on the web login and with `expo-cli@3.24.0`), an error is outputted and login does not succeed

```
$ expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
Fetching the user profile failed
Request failed with status code 401
Request failed with status code 401
Error: Request failed with status code 401
    at createError (/Users/nkane/Projects/frontend/product-ui/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/nkane/Projects/frontend/product-ui/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/nkane/Projects/frontend/product-ui/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

This occurs both running as a bash script and an npm script in our `package.json`

## Environment

```
Expo CLI 3.27.12 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.5.3 - /Users/nkane/.rvm/rubies/ruby-2.4.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 23, 25, 26, 27
        Build Tools: 23.0.1, 26.0.0, 28.0.3
        System Images: android-22 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.18 => 0.12.18
      expo: ^38.0.0 => 38.0.8
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ^0.13.4 => 0.13.4
    Expo Workflow: managed
```

Downgrading to `expo-cli@3.24.0` fixes the issue

## Reproducible Demo

(not sure how to provide this)

**Comment by EvanBacon** [comment]
Looks like the server was down temporarily (404 error)

**Comment by kanenathan213** [comment]
I can still reliably reproduce this error with `expo-cli@3.27.12`, and can successful login by downgrading to `expo-cli@3.24.0`, so it appears this is a client-side issue.
