### ISSUE TITLE
can't install expo-cli

### ISSUE THREAD

**Issue by EnzoArg** [expo/expo-cli#2743]
hi, I can´t install expo-cli on windows 10, I need help. Please
```
$ npm cache clean --force

npm WARN using --force I sure hope you know what you are doing.

$ npm install -g expo-cli
npm WARN deprecated @hapi/joi@17.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/traveling-fastlane-darwin@1.15.1 (node_modules\expo-cli\node_modules\@expo\traveling-fastlane-darwin):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha512-7sjG83+o9BT4MVPNq2UVqy1Oyg3n47FpEIDxc0M9CQvbC1WgYsAKloOJ85g5GRXZAjqzPOPUZF+lBhGbOwmQvg== integrity checksum failed when using sha512: wanted sha512-7sjG83+o9BT4MVPNq2UVqy1Oyg3n47FpEIDxc0M9CQvbC1WgYsAKloOJ85g5GRXZAjqzPOPUZF+lBhGbOwmQvg== but got sha512-qo+sf0UUn7eUSg/kEQxhMgdL8wmwuxdSD36nckPcXbM+kN0P62nBRHHGFcG2TqL4O/3duyeia8YndpfEnORwJA==. (4438471 bytes)

npm ERR! Unexpected end of JSON input while parsing near '...^6.26.0","copy-to-cli'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pc\AppData\Roaming\npm-cache\_logs\2020-10-01T14_13_25_851Z-debug.log

```

The file log

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'expo-cli'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.4
4 verbose npm-session 5a19134bf11a1504
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/expo-cli 722ms
8 http fetch GET 200 https://registry.npmjs.org/expo-cli/-/expo-cli-3.27.12.tgz 552ms
9 silly pacote tag manifest for expo-cli@latest fetched in 1311ms
10 timing stage:loadCurrentTree Completed in 1327ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule expo-cli@3.27.12 checking installable status
18 http fetch GET 200 https://registry.npmjs.org/@expo%2fbunyan 1070ms
19 http fetch GET 200 https://registry.npmjs.org/@expo%2fspawn-async 1137ms
20 http fetch GET 200 https://registry.npmjs.org/@expo%2fpackage-manager 1144ms
21 http fetch GET 200 https://registry.npmjs.org/@expo%2fsimple-spinner 1144ms
22 http fetch GET 200 https://registry.npmjs.org/@expo%2fjson-file 1379ms
23 http fetch GET 200 https://registry.npmjs.org/@expo/spawn-async/-/spawn-async-1.5.0.tgz 239ms
24 http fetch GET 200 https://registry.npmjs.org/@expo%2fconfig 1389ms
25 http fetch GET 200 https://registry.npmjs.org/@expo%2fplist 1384ms
26 http fetch GET 200 https://registry.npmjs.org/@expo/simple-spinner/-/simple-spinner-1.0.2.tgz 238ms
27 http fetch GET 200 https://registry.npmjs.org/@expo/bunyan/-/bunyan-3.0.2.tgz 325ms
28 silly pacote version manifest for @expo/spawn-async@1.5.0 fetched in 1394ms
29 silly resolveWithNewModule @expo/spawn-async@1.5.0 checking installable status
30 silly pacote version manifest for @expo/simple-spinner@1.0.2 fetched in 1397ms
31 silly resolveWithNewModule @expo/simple-spinner@1.0.2 checking installable status
32 silly pacote version manifest for @expo/bunyan@3.0.2 fetched in 1409ms
33 silly resolveWithNewModule @expo/bunyan@3.0.2 checking installable status
34 http fetch GET 200 https://registry.npmjs.org/@hapi%2fjoi 312ms
35 http fetch GET 200 https://registry.npmjs.org/@expo/config/-/config-3.3.8.tgz 336ms
36 silly pacote version manifest for @expo/config@3.3.8 fetched in 1738ms
37 silly resolveWithNewModule @expo/config@3.3.8 checking installable status
38 http fetch GET 200 https://registry.npmjs.org/base32.js 51ms
39 http fetch GET 200 https://registry.npmjs.org/base32.js/-/base32.js-0.1.0.tgz 53ms
40 http fetch GET 200 https://registry.npmjs.org/@hapi/joi/-/joi-17.1.1.tgz 131ms
41 silly pacote version manifest for base32.js@0.1.0 fetched in 116ms
42 silly resolveWithNewModule base32.js@0.1.0 checking installable status
43 silly pacote range manifest for @hapi/joi@^17.1.1 fetched in 458ms
44 warn deprecated @hapi/joi@17.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
45 silly resolveWithNewModule @hapi/joi@17.1.1 checking installable status
46 http fetch GET 200 https://registry.npmjs.org/boxen 45ms
47 http fetch GET 200 https://registry.npmjs.org/chalk 61ms
48 http fetch GET 200 https://registry.npmjs.org/boxen/-/boxen-4.1.0.tgz 49ms
49 silly pacote version manifest for boxen@4.1.0 fetched in 100ms
50 silly resolveWithNewModule boxen@4.1.0 checking installable status
51 http fetch GET 200 https://registry.npmjs.org/chalk/-/chalk-4.1.0.tgz 48ms
52 silly pacote range manifest for chalk@^4.0.0 fetched in 116ms
53 silly resolveWithNewModule chalk@4.1.0 checking installable status
54 http fetch GET 200 https://registry.npmjs.org/cli-table3 46ms
55 http fetch GET 200 https://registry.npmjs.org/clipboardy 56ms
56 http fetch GET 200 https://registry.npmjs.org/cli-table3/-/cli-table3-0.6.0.tgz 86ms
57 silly pacote range manifest for cli-table3@^0.6.0 fetched in 158ms
58 silly resolveWithNewModule cli-table3@0.6.0 checking installable status
59 http fetch GET 200 https://registry.npmjs.org/@expo/package-manager/-/package-manager-0.0.33.tgz 981ms
60 silly pacote version manifest for @expo/package-manager@0.0.33 fetched in 2138ms
61 silly resolveWithNewModule @expo/package-manager@0.0.33 checking installable status
62 http fetch GET 200 https://registry.npmjs.org/babel-runtime 843ms
63 http fetch GET 200 https://registry.npmjs.org/command-exists 169ms
64 http fetch GET 200 https://registry.npmjs.org/commander 199ms
65 http fetch GET 200 https://registry.npmjs.org/clipboardy/-/clipboardy-2.3.0.tgz 373ms
66 http fetch GET 200 https://registry.npmjs.org/command-exists/-/command-exists-1.2.9.tgz 128ms
67 http fetch GET 200 https://registry.npmjs.org/commander/-/commander-2.17.1.tgz 70ms
68 http fetch GET 200 https://registry.npmjs.org/babel-runtime/-/babel-runtime-6.26.0.tgz 161ms
69 silly pacote version manifest for clipboardy@2.3.0 fetched in 443ms
70 silly resolveWithNewModule clipboardy@2.3.0 checking installable status
71 silly pacote range manifest for command-exists@^1.2.8 fetched in 312ms
72 silly resolveWithNewModule command-exists@1.2.9 checking installable status
73 silly pacote version manifest for babel-runtime@6.26.0 fetched in 1022ms
74 silly resolveWithNewModule babel-runtime@6.26.0 checking installable status
75 silly pacote version manifest for commander@2.17.1 fetched in 289ms
76 silly resolveWithNewModule commander@2.17.1 checking installable status
77 http fetch GET 200 https://registry.npmjs.org/@expo/json-file/-/json-file-8.2.24.tgz 1043ms
78 silly pacote version manifest for @expo/json-file@8.2.24 fetched in 2437ms
79 silly resolveWithNewModule @expo/json-file@8.2.24 checking installable status
80 http fetch GET 200 https://registry.npmjs.org/env-editor 62ms
81 http fetch GET 200 https://registry.npmjs.org/dateformat 70ms
82 http fetch GET 200 https://registry.npmjs.org/delay-async 69ms
83 http fetch GET 200 https://registry.npmjs.org/concat-stream 75ms
84 http fetch GET 200 https://registry.npmjs.org/@expo/plist/-/plist-0.0.10.tgz 1107ms
85 silly pacote version manifest for @expo/plist@0.0.10 fetched in 2507ms
86 silly resolveWithNewModule @expo/plist@0.0.10 checking installable status
87 http fetch GET 200 https://registry.npmjs.org/delay-async/-/delay-async-1.2.0.tgz 56ms
88 http fetch GET 200 https://registry.npmjs.org/env-editor/-/env-editor-0.4.1.tgz 65ms
89 http fetch GET 200 https://registry.npmjs.org/dateformat/-/dateformat-3.0.3.tgz 60ms
90 http fetch GET 200 https://registry.npmjs.org/es6-error 53ms
91 silly pacote version manifest for delay-async@1.2.0 fetched in 140ms
92 silly resolveWithNewModule delay-async@1.2.0 checking installable status
93 silly pacote range manifest for env-editor@^0.4.1 fetched in 142ms
94 silly resolveWithNewModule env-editor@0.4.1 checking installable status
95 http fetch GET 200 https://registry.npmjs.org/concat-stream/-/concat-stream-1.6.2.tgz 69ms
96 silly pacote version manifest for dateformat@3.0.3 fetched in 148ms
97 silly resolveWithNewModule dateformat@3.0.3 checking installable status
98 http fetch GET 200 https://registry.npmjs.org/envinfo 141ms
99 silly pacote version manifest for concat-stream@1.6.2 fetched in 162ms
100 silly resolveWithNewModule concat-stream@1.6.2 checking installable status
101 http fetch GET 200 https://registry.npmjs.org/es6-error/-/es6-error-3.2.0.tgz 52ms
102 http fetch GET 200 https://registry.npmjs.org/figures 50ms
103 http fetch GET 200 https://registry.npmjs.org/getenv 47ms
104 silly pacote version manifest for es6-error@3.2.0 fetched in 118ms
105 silly resolveWithNewModule es6-error@3.2.0 checking installable status
106 http fetch GET 200 https://registry.npmjs.org/envinfo/-/envinfo-7.5.0.tgz 98ms
107 silly pacote version manifest for envinfo@7.5.0 fetched in 247ms
108 silly resolveWithNewModule envinfo@7.5.0 checking installable status
109 http fetch GET 200 https://registry.npmjs.org/glob 145ms
110 http fetch GET 200 https://registry.npmjs.org/fs-extra 186ms
111 http fetch GET 200 https://registry.npmjs.org/figures/-/figures-3.2.0.tgz 148ms
112 http fetch GET 200 https://registry.npmjs.org/getenv/-/getenv-0.7.0.tgz 147ms
113 silly pacote version manifest for figures@3.2.0 fetched in 211ms
114 silly resolveWithNewModule figures@3.2.0 checking installable status
115 silly pacote version manifest for getenv@0.7.0 fetched in 208ms
116 silly resolveWithNewModule getenv@0.7.0 checking installable status
117 http fetch GET 200 https://registry.npmjs.org/indent-string 170ms
118 http fetch GET 200 https://registry.npmjs.org/glob/-/glob-7.1.6.tgz 152ms
119 silly pacote version manifest for glob@7.1.6 fetched in 315ms
120 silly resolveWithNewModule glob@7.1.6 checking installable status
121 http fetch GET 200 https://registry.npmjs.org/fs-extra/-/fs-extra-9.0.0.tgz 180ms
122 http fetch GET 200 https://registry.npmjs.org/invariant 167ms
123 silly pacote version manifest for fs-extra@9.0.0 fetched in 382ms
124 silly resolveWithNewModule fs-extra@9.0.0 checking installable status
125 http fetch GET 200 https://registry.npmjs.org/inquirer 291ms
126 http fetch GET 200 https://registry.npmjs.org/indent-string/-/indent-string-4.0.0.tgz 223ms
127 silly pacote version manifest for indent-string@4.0.0 fetched in 411ms
128 silly resolveWithNewModule indent-string@4.0.0 checking installable status
129 http fetch GET 200 https://registry.npmjs.org/invariant/-/invariant-2.2.4.tgz 172ms
130 http fetch GET 200 https://registry.npmjs.org/@expo%2feas-build-job 3127ms
131 http fetch GET 200 https://registry.npmjs.org/keychain 175ms
132 silly pacote version manifest for invariant@2.2.4 fetched in 351ms
133 silly resolveWithNewModule invariant@2.2.4 checking installable status
134 http fetch GET 200 https://registry.npmjs.org/got 558ms
135 http fetch GET 200 https://registry.npmjs.org/@expo%2fresults 3190ms
136 http fetch GET 200 https://registry.npmjs.org/js-yaml 297ms
137 http fetch GET 200 https://registry.npmjs.org/inquirer/-/inquirer-5.2.0.tgz 121ms
138 silly pacote version manifest for inquirer@5.2.0 fetched in 434ms
139 silly resolveWithNewModule inquirer@5.2.0 checking installable status
140 http fetch GET 200 https://registry.npmjs.org/klaw-sync 121ms
141 http fetch GET 200 https://registry.npmjs.org/leven 96ms
142 http fetch GET 200 https://registry.npmjs.org/keychain/-/keychain-1.3.0.tgz 103ms
143 silly pacote version manifest for keychain@1.3.0 fetched in 285ms
144 silly resolveWithNewModule keychain@1.3.0 checking installable status
145 http fetch GET 200 https://registry.npmjs.org/got/-/got-11.7.0.tgz 130ms
146 http fetch GET 200 https://registry.npmjs.org/klaw-sync/-/klaw-sync-6.0.0.tgz 104ms
147 http fetch GET 200 https://registry.npmjs.org/leven/-/leven-3.1.0.tgz 98ms
148 silly pacote range manifest for got@^11.1.4 fetched in 704ms
149 silly resolveWithNewModule got@11.7.0 checking installable status
150 silly pacote version manifest for klaw-sync@6.0.0 fetched in 243ms
151 silly resolveWithNewModule klaw-sync@6.0.0 checking installable status
152 silly pacote range manifest for leven@^3.1.0 fetched in 210ms
153 silly resolveWithNewModule leven@3.1.0 checking installable status
154 http fetch GET 200 https://registry.npmjs.org/js-yaml/-/js-yaml-3.14.0.tgz 209ms
155 silly pacote range manifest for js-yaml@^3.13.1 fetched in 516ms
156 silly resolveWithNewModule js-yaml@3.14.0 checking installable status
157 http fetch GET 200 https://registry.npmjs.org/md5-file 178ms
158 http fetch GET 200 https://registry.npmjs.org/lodash 220ms
159 http fetch GET 200 https://registry.npmjs.org/npm-package-arg 117ms
160 http fetch GET 200 https://registry.npmjs.org/ora 146ms
161 http fetch GET 200 https://registry.npmjs.org/@expo/results/-/results-1.0.0.tgz 573ms
162 silly pacote range manifest for @expo/results@^1.0.0 fetched in 3783ms
163 silly resolveWithNewModule @expo/results@1.0.0 checking installable status
164 http fetch GET 200 https://registry.npmjs.org/pngjs 379ms
165 http fetch GET 200 https://registry.npmjs.org/md5-file/-/md5-file-5.0.0.tgz 374ms
166 silly pacote range manifest for md5-file@^5.0.0 fetched in 571ms
167 silly resolveWithNewModule md5-file@5.0.0 checking installable status
168 http fetch GET 200 https://registry.npmjs.org/npm-package-arg/-/npm-package-arg-6.1.0.tgz 381ms
169 silly pacote version manifest for npm-package-arg@6.1.0 fetched in 504ms
170 silly resolveWithNewModule npm-package-arg@6.1.0 checking installable status
171 http fetch GET 200 https://registry.npmjs.org/ora/-/ora-3.4.0.tgz 459ms
172 http fetch GET 200 https://registry.npmjs.org/pacote 609ms
173 silly pacote version manifest for ora@3.4.0 fetched in 627ms
174 silly resolveWithNewModule ora@3.4.0 checking installable status
175 http fetch GET 200 https://registry.npmjs.org/progress 243ms
176 http fetch GET 200 https://registry.npmjs.org/qrcode-terminal 446ms
177 http fetch GET 200 https://registry.npmjs.org/pacote/-/pacote-11.1.11.tgz 456ms
178 silly pacote range manifest for pacote@^11.1.0 fetched in 1083ms
179 silly resolveWithNewModule pacote@11.1.11 checking installable status
180 http fetch GET 200 https://registry.npmjs.org/progress/-/progress-2.0.3.tgz 605ms
181 http fetch GET 200 https://registry.npmjs.org/pngjs/-/pngjs-3.4.0.tgz 840ms
182 http fetch GET 200 https://registry.npmjs.org/prompts 865ms
183 http fetch GET 200 https://registry.npmjs.org/@expo/eas-build-job/-/eas-build-job-0.1.0.tgz 1555ms
184 silly pacote version manifest for progress@2.0.3 fetched in 897ms
185 silly resolveWithNewModule progress@2.0.3 checking installable status
186 silly pacote version manifest for pngjs@3.4.0 fetched in 1271ms
187 silly resolveWithNewModule pngjs@3.4.0 checking installable status
188 http fetch GET 200 https://registry.npmjs.org/lodash/-/lodash-4.17.15.tgz 1253ms
189 silly pacote range manifest for @expo/eas-build-job@^0.1.0 fetched in 4693ms
190 silly resolveWithNewModule @expo/eas-build-job@0.1.0 checking installable status
191 silly pacote version manifest for lodash@4.17.15 fetched in 1480ms
192 silly resolveWithNewModule lodash@4.17.15 checking installable status
193 http fetch GET 200 https://registry.npmjs.org/qrcode-terminal/-/qrcode-terminal-0.11.0.tgz 438ms
194 silly pacote version manifest for qrcode-terminal@0.11.0 fetched in 891ms
195 silly resolveWithNewModule qrcode-terminal@0.11.0 checking installable status
196 http fetch GET 200 https://registry.npmjs.org/react-dev-utils 950ms
197 http fetch GET 200 https://registry.npmjs.org/@expo%2fdev-tools 5043ms
198 silly fetchPackageMetaData error for @expo/dev-tools@0.13.50 Unexpected end of JSON input while parsing near '...^6.26.0","copy-to-cli'
199 http fetch GET 200 https://registry.npmjs.org/semver 624ms
200 silly fetchPackageMetaData error for semver@5.5.0 Unexpected end of JSON input while parsing near '...er-5.0.3.tgz"}},"5.1.'
201 http fetch GET 200 https://registry.npmjs.org/@expo%2fxdl 3788ms
202 silly fetchPackageMetaData error for @expo/xdl@58.0.11 Unexpected end of JSON input while parsing near '...-error":"4.1.1","expr'
203 http fetch GET 200 https://registry.npmjs.org/untildify 333ms
204 http fetch GET 200 https://registry.npmjs.org/uuid 352ms
205 http fetch GET 200 https://registry.npmjs.org/untildify/-/untildify-3.0.3.tgz 109ms
206 silly pacote version manifest for untildify@3.0.3 fetched in 454ms
207 silly resolveWithNewModule untildify@3.0.3 checking installable status
208 http fetch GET 200 https://registry.npmjs.org/uuid/-/uuid-8.3.0.tgz 139ms
209 silly pacote range manifest for uuid@^8.0.0 fetched in 500ms
210 silly resolveWithNewModule uuid@8.3.0 checking installable status
211 http fetch GET 200 https://registry.npmjs.org/wordwrap 189ms
212 http fetch GET 200 https://registry.npmjs.org/validator 570ms
213 http fetch GET 200 https://registry.npmjs.org/wordwrap/-/wordwrap-1.0.0.tgz 123ms
214 silly pacote version manifest for wordwrap@1.0.0 fetched in 321ms
215 silly resolveWithNewModule wordwrap@1.0.0 checking installable status
216 http fetch GET 200 https://registry.npmjs.org/validator/-/validator-10.5.0.tgz 160ms
217 silly pacote version manifest for validator@10.5.0 fetched in 742ms
218 silly resolveWithNewModule validator@10.5.0 checking installable status
219 http fetch GET 200 https://registry.npmjs.org/@expo%2ftraveling-fastlane-darwin 846ms
220 http fetch GET 200 https://registry.npmjs.org/@expo%2ftraveling-fastlane-linux 1004ms
221 http fetch GET 200 https://registry.npmjs.org/strip-ansi 2487ms
222 http fetch GET 200 https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.0.tgz 40ms
223 silly pacote range manifest for strip-ansi@^6.0.0 fetched in 2540ms
224 silly resolveWithNewModule strip-ansi@6.0.0 checking installable status
225 http fetch GET 200 https://registry.npmjs.org/react-dev-utils/-/react-dev-utils-10.2.1.tgz 2517ms
226 silly pacote range manifest for react-dev-utils@~10.2.1 fetched in 3481ms
227 silly resolveWithNewModule react-dev-utils@10.2.1 checking installable status
228 http fetch GET 200 https://registry.npmjs.org/slash 10285ms attempt #2
229 http fetch GET 200 https://registry.npmjs.org/tar 10400ms attempt #2
230 http fetch GET 200 https://registry.npmjs.org/terminal-link 10364ms attempt #2
231 http fetch GET 200 https://registry.npmjs.org/tar/-/tar-6.0.5.tgz 99ms
232 http fetch GET 200 https://registry.npmjs.org/terminal-link/-/terminal-link-2.1.1.tgz 98ms
233 http fetch GET 200 https://registry.npmjs.org/tempy 10501ms attempt #2
234 silly pacote range manifest for tar@^6.0.5 fetched in 10514ms
235 silly resolveWithNewModule tar@6.0.5 checking installable status
236 silly pacote range manifest for terminal-link@^2.1.1 fetched in 10474ms
237 silly resolveWithNewModule terminal-link@2.1.1 checking installable status
238 http fetch GET 200 https://registry.npmjs.org/prompts/-/prompts-2.3.2.tgz 10554ms attempt #2
239 http fetch GET 200 https://registry.npmjs.org/tempy/-/tempy-0.3.0.tgz 39ms
240 silly pacote range manifest for prompts@^2.3.2 fetched in 11427ms
241 silly resolveWithNewModule prompts@2.3.2 checking installable status
242 silly pacote range manifest for tempy@^0.3.0 fetched in 10546ms
243 silly resolveWithNewModule tempy@0.3.0 checking installable status
244 http fetch GET 200 https://registry.npmjs.org/slash/-/slash-1.0.0.tgz 297ms
245 silly pacote version manifest for slash@1.0.0 fetched in 10597ms
246 silly resolveWithNewModule slash@1.0.0 checking installable status
247 silly fetchPackageMetaData error for @expo/traveling-fastlane-darwin@1.15.1 sha512-7sjG83+o9BT4MVPNq2UVqy1Oyg3n47FpEIDxc0M9CQvbC1WgYsAKloOJ85g5GRXZAjqzPOPUZF+lBhGbOwmQvg== integrity checksum failed when using sha512: wanted sha512-7sjG83+o9BT4MVPNq2UVqy1Oyg3n47FpEIDxc0M9CQvbC1WgYsAKloOJ85g5GRXZAjqzPOPUZF+lBhGbOwmQvg== but got sha512-qo+sf0UUn7eUSg/kEQxhMgdL8wmwuxdSD36nckPcXbM+kN0P62nBRHHGFcG2TqL4O/3duyeia8YndpfEnORwJA==. (4438471 bytes)
248 http fetch GET 200 https://registry.npmjs.org/@expo/traveling-fastlane-linux/-/traveling-fastlane-linux-1.15.1.tgz 110092ms attempt #3
249 silly pacote version manifest for @expo/traveling-fastlane-linux@1.15.1 fetched in 111118ms
250 silly resolveWithNewModule @expo/traveling-fastlane-linux@1.15.1 checking installable status
251 timing stage:rollbackFailedOptional Completed in 1ms
252 timing stage:runTopLevelLifecycles Completed in 118319ms
253 warn optional SKIPPING OPTIONAL DEPENDENCY: @expo/traveling-fastlane-darwin@1.15.1 (node_modules\expo-cli\node_modules\@expo\traveling-fastlane-darwin):
254 warn optional SKIPPING OPTIONAL DEPENDENCY: sha512-7sjG83+o9BT4MVPNq2UVqy1Oyg3n47FpEIDxc0M9CQvbC1WgYsAKloOJ85g5GRXZAjqzPOPUZF+lBhGbOwmQvg== integrity checksum failed when using sha512: wanted sha512-7sjG83+o9BT4MVPNq2UVqy1Oyg3n47FpEIDxc0M9CQvbC1WgYsAKloOJ85g5GRXZAjqzPOPUZF+lBhGbOwmQvg== but got sha512-qo+sf0UUn7eUSg/kEQxhMgdL8wmwuxdSD36nckPcXbM+kN0P62nBRHHGFcG2TqL4O/3duyeia8YndpfEnORwJA==. (4438471 bytes)
255 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...^6.26.0","copy-to-cli'
255 verbose stack     at JSON.parse (<anonymous>)
255 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
255 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
255 verbose stack     at runMicrotasks (<anonymous>)
255 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
256 verbose cwd R:\Desarrollos Atucha\Proyecto SARO\04-SAROApp
257 verbose Windows_NT 10.0.18363
258 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "expo-cli"
259 verbose node v12.18.4
260 verbose npm  v6.14.6
261 error Unexpected end of JSON input while parsing near '...^6.26.0","copy-to-cli'
262 verbose exit [ 1, true ]
```

**Comment by EvanBacon** [comment]
try this: "npm cache clean --force"
