### ISSUE TITLE
did a certificate expire?

### ISSUE THREAD

**Issue by conceptualspace** [expo/expo-cli#2754]
## Description

Get a certificate error when connecting to metro bundler on my LAN. Also noticed my queued builds seem to be frozen in the cloud, possibly related. 

## Expected Behavior

expect expo to connect and start the app

## Observed Behavior

Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12)

## Environment

  Expo CLI 3.27.13 environment info:
    System:
      OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 12.18.4 - /usr/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 6.14.8 - /usr/bin/npm
    npmPackages:
      expo: ^39.0.3 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.2.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.14 
    npmGlobalPackages:
      expo-cli: 3.27.13
    Expo Workflow: managed

## Reproducible Demo

run `expo start`
scan QR code in expo app
get error above

**Comment by conceptualspace** [comment]
and now its working. well then :)
