### ISSUE TITLE
Build number does not get updated if you build with --no-publish

### ISSUE THREAD

**Issue by divonelnc** [expo/expo-cli#2759]
When building a new iOS or Android build using `expo build:[ios/android] --no-publish`, the build version is not updated to match the one in `app.json`.

I just updated to SDK 39 and I would like to update the build for my users in production. The problem is that if I publish when I build, I am afraid it will create issues for users on the SDK 38 that is currently online.

## Expected Behavior
I should be able to build with the `--no-publish` flag on then upload the build.

## Observed Behavior

When attempting to manually update the android build, I get the error: `You need to use a different version code for your APK or Android App Bundle because you already have one with version code 32.`, even though my version code is 34.

When calling `expo upload:ios` I get the error:  “Redundant Binary Upload. You’ve already uploaded a build with build number ‘0.1.2’", event though my app.json has version `0.1.4` set for iOs.

```
[11:05:10]: [Transporter Error Output]: ERROR ITMS-90189: "Redundant Binary Upload. You've already uploaded a build with build number '0.1.2' for version number '0.1.2'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4)."
[11:05:10]: Transporter transfer failed.
[11:05:10]: 
[11:05:10]: ERROR ITMS-90189: "Redundant Binary Upload. You've already uploaded a build with build number '0.1.2' for version number '0.1.2'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4)."
[11:05:11]: [iTMSTransporter] [2020-10-05 11:05:10 CEST] <main> DBG-X:   parameter ErrorMessage = ERROR ITMS-90189: "Redundant Binary Upload. You've already uploaded a build with build number '0.1.2' for version number '0.1.2'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4).

[11:05:11]: [iTMSTransporter]  (1102)

[11:05:11]: [iTMSTransporter] [2020-10-05 11:05:10 CEST] <main> DBG-X:   parameter ShouldUseRESTAPIs = false

[11:05:11]: [iTMSTransporter] [2020-10-05 11:05:10 CEST] <main> ERROR: ERROR ITMS-90189: "Redundant Binary Upload. You've already uploaded a build with build number '0.1.2' for version number '0.1.2'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4)."

[11:05:11]: [iTMSTransporter] [2020-10-05 11:05:10 CEST] <main> DBG-X: The error code is: 1102

[11:05:11]: [iTMSTransporter] [2020-10-05 11:05:10 CEST] <main>  INFO: Done performing authentication.

[11:05:11]: [iTMSTransporter] 

[11:05:11]: [iTMSTransporter] 

[11:05:11]: [iTMSTransporter] 

[11:05:11]: [iTMSTransporter] Package Summary:

[11:05:11]: [iTMSTransporter]  

[11:05:11]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:

[11:05:11]: [iTMSTransporter]   /var/folders/m4/1gr32hln0w7cfpvlmrq4s5mh0000gn/T/d20201005-2422-8h6tn2/1528692531.itmsp - Error Messages:

[11:05:11]: [iTMSTransporter]           ERROR ITMS-90189: "Redundant Binary Upload. You've already uploaded a build with build number '0.1.2' for version number '0.1.2'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4)."

[11:05:11]: [iTMSTransporter] [2020-10-05 11:05:10 CEST] <main> DBG-X: Returning 1

[11:05:11]: iTunes Transporter output above ^
[11:05:11]: ERROR ITMS-90189: "Redundant Binary Upload. You've already uploaded a build with build number '0.1.2' for version number '0.1.2'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4)."
Return status of iTunes Transporter was 1: ERROR ITMS-90189: "Redundant Binary Upload. You've already uploaded a build with build number '0.1.2' for version number '0.1.2'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4)."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
Failed to upload the standalone app to the App Store.
We recommend using Transporter.app (​https://apps.apple.com/us/app/transporter/id1450874784​) instead of the expo upload:ios command if you have any trouble with it.
Error uploading ipa file, for more information see above
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.146.1/pilot/lib/pilot/build_manager.rb:37:in `upload'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/pilot_upload.rb:20:in `block in <main>'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/funcs.rb:4:in `with_captured_stderr'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/pilot_upload.rb:12:in `<main>'
Error: Error uploading ipa file, for more information see above
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.146.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.146.1/pilot/lib/pilot/build_manager.rb:37:in `upload'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/pilot_upload.rb:20:in `block in <main>'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/funcs.rb:4:in `with_captured_stderr'
    /usr/local/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/pilot_upload.rb:12:in `<main>'
    at runFastlaneAsync (/usr/local/lib/node_modules/expo-cli/src/commands/upload/utils.ts:64:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at IOSUploader._uploadToTheStore (/usr/local/lib/node_modules/expo-cli/src/commands/upload/IOSUploader.ts:196:5)
    at IOSUploader.upload (/usr/local/lib/node_modules/expo-cli/src/commands/upload/BaseUploader.ts:36:5)
    at /usr/local/lib/node_modules/expo-cli/src/commands/upload.ts:125:9
    at Command.<anonymous> (/usr/local/lib/node_modules/expo-cli/src/exp.ts:331:7)
```

## Environment

```
  Expo CLI 3.27.13 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 10.15.3 - E:\nodejs\node.EXE
      Yarn: 1.22.0 - E:\Yarn\bin\yarn.CMD
      npm: 6.14.5 - E:\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29
        Build Tools: 29.0.0, 29.0.3
        System Images: android-29 | Google APIs Intel x86 Atom
    npmPackages:
      expo: ^39.0.0 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: ^16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.11 => 0.11.7
    Expo Workflow: managed
```

## Reproducible Demo

N/A. You would need to build any app with a certain version number, upload it to Testflight, update the version, build with the --no-publish flag, and try to upload again.

**Comment by byCedric** [comment]
Hi @divonelnc, if you run `expo build:* --no-publish` it pulls in your _last published version_ to make the standalone app for. You can't use the updated configuration or project if you haven't published it yet. There are several options to avoid mixing with your current app, like [release channels](https://docs.expo.io/distribution/advanced-release-channels/). But you don't have to worry about that if you upgraded the SDK, as [mentioned in this part](https://docs.expo.io/distribution/advanced-release-channels/#what-version-of-the-app-will-my).

Hope this helps!

**Comment by bit-scrambler** [comment]
When I create a new build I have to hardcode the release-channel bound to it. As you said, in order to set a new buildNumber as requested by the App Store, I have to publish.
The problem is that, doing so, I will release new features to existing users via OTA before the AppStore approve the new build. Isn't it an issue?
Or is there a way to switch the release channel attached to binary by code?

**Comment by brentvatne** [comment]
@bit-scrambler - the build number is read from the release that you published to the release channel that the build is targeting.

so if you ran `expo publish --release-channel my-channel` and then later `expo build:ios --release-channel my-channel --no-publish` it would use whatever build number was set when you ran publish for that channel most recently. or, `expo build:ios --release-channel my-channel` if you want to do both of these at once.

**Comment by dakairus** [comment]
@brentvatne that certainly doesn't work. I got an app which I need to upgrade from SDK 37 to 39 to solve a bug which currently is only in Android (due to a dependency problem), but don't update the IOS version. I know the best approach is to upgrade both apps at same time, but we are still few weeks away to finish the details of the ios app to go into SDK 39 and the Android error is currently critical to solve ASAP.

Due to above situation I can run expo publish --release-channel production (otherwise I can screw the ios app), and running expo build:android --release-channel production --no-publish is not working properly, because it keeps building the app with SDK 37 instead of 39. Is there a way how to make the expo publish to be platform selective?

**Comment by brentvatne** [comment]
you won't 'screw up' the ios app by publishing to the production channel because a binary that is built with sdk 37 will not pull in an update for sdk 39

**Comment by JTambunt** [comment]
For anyone still running into this issue, my workaround was to expo:publish the live production version with the newer updated version number, then build the latest version with --no-publish.

Example: Live production is 2.1.0 using release-channel 'production'. An updated version with breaking app.json changes is 2.2.0. update live production version to 2.2.0 in app.json and publish `expo:publish --release-channel production`. Checkout the latest updated version and run `expo:build:ios --no-publish --release-channel production` The new build will have v2.2.0 and can be uploaded through transporter.

I had to do this because I wasn't upgrading a new sdk version but had breaking changes I didn't want to release until approved by the app stores.
