### ISSUE TITLE
Expo CLI missing required Node version

### ISSUE THREAD

**Issue by goldylucks** [expo/expo-cli#2760]
I ran the following commands as in the documentation to get started:

```
$ yarn global add expo-cli
$ expo init myNewProject
$ cd myNewProject
$ expo start 
```

Got the following errors

```
Error: Invalid sdkVersion. Valid options are 7.0.0, 8.0.0, 9.0.0, 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 22.0.0, 23.0.0, 24.0.0, 25.0.0, 26.0.0, 27.0.0, 28.0.0, 29.0.0, 30.0.0, 31.0.0, 32.0.0, 33.0.0, 34.0.0, 35.0.0, 36.0.0, 37.0.0, 38.0.0, 39.0.0
error: unknown option `--assetExts'

Metro Bundler process exited with code 1
```

Than I added `"sdkVersion": "39.0.0",` to `app.json.expo`, ran `$ expo start` again and the second error still remains:

```
error: unknown option `--assetExts'

Metro Bundler process exited with code 1
```

my `app.json` is:

```
{
  "name": "reactNativeExpo",
  "displayName": "React Native Expo",
  "expo": {
    "name": "reactNativeExpo",
    "slug": "expo-template-bare",
    "version": "1.0.0",
    "sdkVersion": "39.0.0",
    "assetBundlePatterns": ["**/*"]
  }
}

```

My system info
```
$ yarn global list expo
yarn global v1.21.1
info "expo-cli@3.27.13" has binaries:
   - expo
   - expo-cli

$ npm -v
6.14.8

$ node -v
v12.0.0
```

Again this is a fresh installation, I haven't done anything except the steps I outlined above.

Any help is appreciated :)

**Comment by goldylucks** [comment]
Running `$ EXPO_DEBUG=true expo start` gives the following:

```
Metro Bundler process exited with code 1
Error: Metro Bundler process exited with code 1
    at ChildProcess.<anonymous> (/@expo/xdl@56.2.7/src/Project.ts:1804:16)
    at Object.onceWrapper (events.js:284:20)
    at ChildProcess.emit (events.js:196:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
```

**Comment by goldylucks** [comment]
upgrading node to 12.13.0 did the trick. I think this should be documented and preferably displayed in the terminal when running `expo start` with an incompatible node version.

**Comment by brentvatne** [comment]
we do validate the node version. i think something else was wrong with the node installation on your machine, it's hard to say what exactly.

```
╭─~/code/my-react-app ‹master›
╰─$ node --version                                                                                                      130 ↵
v12.0.0
╭─~/code/my-react-app ‹master›
╰─$ expo start
ERROR: Node.js v12.0.0 is no longer supported.

expo-cli supports following Node.js versions:
* >=10.13.0 <11.0.0 (Maintenance LTS)
* >=12.13.0 <13.0.0 (Active LTS)
* >=14.0.0  <15.0.0 (Current Release)
```

**Comment by brentvatne** [comment]
if you do end up finding more information about what went wrong, i'd be curious to know :) but the issue topic is already solved so i'm closing
