### ISSUE TITLE
Unexpected key "EXUpdatesEnabled" while parsing <dict/>.

### ISSUE THREAD

**Issue by pushpankar** [expo/expo-cli#2783]
Hello, I am trying to publish app but I am getting following error. 
``` 
Learn more about JavaScript bundle sizes: https://expo.fyi/javascript-bundle-sizes

Analyzing assets
Saving assets
No assets changed, skipped.

Processing asset bundle patterns:
- /home/pushpankar/Projects/wordbee-expo/**/*

Uploading JavaScript bundles
Unexpected key "EXUpdatesEnabled" while parsing <dict/>.
Invariant Violation: Unexpected key "EXUpdatesEnabled" while parsing <dict/>.
    at Object.invariant [as default] (/home/pushpankar/.npm-new-global/lib/node_modules/expo-cli/node_modules/invariant/invariant.js:40:15)
    at parsePlistXML (/home/pushpankar/.npm-new-global/lib/node_modules/expo-cli/node_modules/@expo/plist/src/parse.ts:124:18)
    at parsePlistXML (/home/pushpankar/.npm-new-global/lib/node_modules/expo-cli/node_modules/@expo/plist/src/parse.ts:107:22)
    at Object.parse (/home/pushpankar/.npm-new-global/lib/node_modules/expo-cli/node_modules/@expo/plist/src/parse.ts:78:15)
    at Object.modifyAsync (/@expo/xdl@58.0.13/src/detach/IosPlist.ts:46:20)
    at _maybeConfigureExpoUpdatesEmbeddedAssetsAsync (/@expo/xdl@58.0.13/src/EmbeddedAssets.ts:298:20)
    at Object.configureAsync (/@expo/xdl@58.0.13/src/EmbeddedAssets.ts:33:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.publishAsync (/@expo/xdl@58.0.13/src/Project.ts:739:3)
    at action (/home/pushpankar/.npm-new-global/lib/node_modules/expo-cli/src/commands/publish.ts:80:18)
```

**Comment by AdamJNavarro** [comment]
Hey @pushpankar, can you share your environment information as the issue template asked for? Also, please try publishing on a brand new project to see if this is project specific.

Cheers,
Adam

**Comment by pushpankar** [comment]
Sorry for the incomplete information. I implemented code push so can reproduce it. 

Thank you very much for your attention.
