### ISSUE TITLE
read ECONNRESET Error: read ECONNRESET at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)

### ISSUE THREAD

**Issue by adityakmr7** [expo/expo-cli#2816]
I am trying to build my expo app but every time i run `expo build:android` it gives me error.

## Observed Behavior

```
read ECONNRESET
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
```

## Environment

  `"expo": "~39.0.2",`

## Reproducible Demo
```

C:\Users\adity\Desktop\dev\daivjnaya-brahmin>expo build:android
√ Choose the build type you would like: » apk
Checking if there is a build in progress...

Accessing credentials for adityakmr088 in project daivjnaya-brahmin

- Expo SDK: 39.0.0
- Release channel: default
- Workflow: Managed

Building optimized bundles and generating sourcemaps...
Starting Metro Bundler.
Building iOS bundle
Building Android bundle
Finished building JavaScript bundle in 75058ms.
Building source maps
Finished building JavaScript bundle in 62318ms.
Finished building JavaScript bundle in 439ms.
Finished building JavaScript bundle in 310ms.
Building asset maps
Finished building JavaScript bundle in 4114ms.
Finished building JavaScript bundle in 4092ms.

Bundle                     Size
┌ index.ios.js          2.35 MB
├ index.android.js      2.36 MB
├ index.ios.js.map      8.01 MB
└ index.android.js.map  8.02 MB

Learn more about JavaScript bundle sizes: https://expo.fyi/javascript-bundle-sizes

Analyzing assets
Saving assets
uploading \assets\images\profile.png
uploading \assets\images\shake.png
uploading \assets\images\sun.png
uploading \assets\images\img-2.png
uploading \assets\images\card-image.png
read ECONNRESET
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
```

**Comment by ezrogha** [comment]
Hi @adityakmr7, Did you find a solution to this error?

**Comment by adityakmr7** [comment]
@ezrogha yeah I turned off my firewall and after that when I ran `expo build:android` it worked fine.
