### ISSUE TITLE
Failed to construct transformer:  Error: Call retries were exceeded

### ISSUE THREAD

**Issue by FinnFrotscher** [expo/expo-cli#2819]
Since yesterday, I can't load the app for development anymore.
When I run `EXPO_COFENSTER_ENV=development expo start --clear`, the process starts and I can access the webinterface, but once I load the app on my iPhone the process takes a while an then throws an error.
I see the jest is the source, but I dont have jest anywhere in my repo. 
I have the same issue when using an android phone.

Error Message:
```
Failed to construct transformer:  Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/Users/finnfrotscher/code/cofenster/monorepo/node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)
    at ChildProcessWorker.onExit (/Users/finnfrotscher/code/cofenster/monorepo/node_modules/jest-worker/build/workers/ChildProcessWorker.js:263:12)
    at ChildProcess.emit (events.js:310:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
  type: 'WorkerError'
}
```

Diagnostics:
```
  Expo CLI 3.28.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.3 - /var/folders/ym/08mhwl8174df_zdlw2m_j6280000gn/T/yarn--1603273907277-0.9162526909549922/node
      Yarn: 1.22.10 - /var/folders/ym/08mhwl8174df_zdlw2m_j6280000gn/T/yarn--1603273907277-0.9162526909549922/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.16.3/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    Expo Workflow: managed
```

**Comment by FinnFrotscher** [comment]
Yesterday, my mac installed the `10.15.7` update.
