### ISSUE TITLE
Cannot login through expo-cli

### ISSUE THREAD

**Issue by JimmyDaddy** [expo/expo-cli#284]
## Description

nodejs: v11.0
expo: v2.6.14
OS: MAC

```
[11:47:35] Cannot read property 'error' of undefined
[11:47:35] TypeError: Cannot read property 'error' of undefined
    at /xdl@52.0.13/src/User.js:127:21
    at Generator.next (<anonymous>)
    at step (/Users/jimmydaddy/.nvm/versions/node/v11.0.0/lib/node_modules/expo-cli/node_modules/xdl/build/User.js:96:191)
    at /Users/jimmydaddy/.nvm/versions/node/v11.0.0/lib/node_modules/expo-cli/node_modules/xdl/build/User.js:96:361
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

![7d77d9e2-1723-4c9b-823b-ffe8300a37a5](https://user-images.githubusercontent.com/16460813/50580104-f2e45400-0e85-11e9-9960-3562d82e835e.png)

**Comment by JimmyDaddy** [comment]
https://github.com/expo/expo-cli/blob/4ca741c6d1ab571930337c0a127c81f644373e6c/packages/xdl/src/User.js#L123
