### ISSUE TITLE
expo export requires sdkVersion in bare workflow

### ISSUE THREAD

**Issue by hehex9** [expo/expo-cli#2858]
## Description

As stated in the [updating-your-app](https://docs.expo.io/bare/updating-your-app/#served-update-requirements)
> sdkVersion is required only if runtimeVersion is not provided.

But when I try `expo export` without `sdkVersion` in app.json, it gives me an error:

```
Cannot determine which native SDK version your project uses because the module `expo` is not installed. Please install it with `yarn add expo` and try again
```

app.json:

```json
{
  "name": "HelloWorld",
  "expo": {
    "runtimeVersion": "1"
  }
}
```

(btw, I tried to add `skipSDKVersionRequirement: true` to the `commands/export.ts` but not working)

It seems like the `sdkVersion` is checked everywhere, so if i understand it right, this field is required in a bare workflow while exporting, but not required in the response of `EXPO_UPDATE_URL` if runtimeVersion is provided?

And if sdkVersion (set to 39.0.0 and will never change it due to this problem) and runtimeVersion are both provided in the response of `EXPO_UPDATE_URL`, will there be any problem?

## Expected Behavior

no error

## Observed Behavior

```
Cannot determine which native SDK version your project uses because the module `expo` is not installed. Please install it with `yarn add expo` and try again.
ConfigError: Cannot determine which native SDK version your project uses because the module `expo` is not installed. Please install it with `yarn add expo` and try again.
    at Object.getExpoSDKVersion (/Users/xxx/.config/yarn/global/node_modules/@expo/config/src/Project.ts:23:9)
    at ensureConfigHasDefaultValues (/Users/xxx/.config/yarn/global/node_modules/@expo/config/src/Config.ts:433:18)
    at fillAndReturnConfig (/Users/xxx/.config/yarn/global/node_modules/@expo/config/src/Config.ts:112:10)
    at getConfig (/Users/xxx/.config/yarn/global/node_modules/@expo/config/src/Config.ts:149:10)
    at validateAsync (/@expo/xdl@58.0.18/src/project/Doctor.ts:438:24)
    at Object.validateWithoutNetworkAsync (/@expo/xdl@58.0.18/src/project/Doctor.ts:419:10)
    at /Users/xxx/.config/yarn/global/node_modules/expo-cli/src/exp.ts:648:36
    at Command.<anonymous> (/Users/xxx/.config/yarn/global/node_modules/expo-cli/src/exp.ts:332:7)
```

## Environment

```
  Expo CLI 3.28.4 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.7 - ~/.nvm/versions/node/v12.16.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /Users/xxx/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29
        Build Tools: 28.0.3, 29.0.0, 29.0.2
        System Images: android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.13.1 => 16.13.1
      react-native: 0.63.3 => 0.63.3
    Expo Workflow: bare
```

## Reproducible Demo

```
npx react-native init demo
echo '{"name":"demo","expo":{"runtimeVersion":"1"}}' > app.json
expo export --public-url https://expo.github.io/self-hosting-example
```

**Comment by EvanBacon** [comment]
This is fundamentally not an issue anymore because the new Expo CLI (`npx expo export`) is installed with the `expo` package, meaning the SDK Version is always available.
