### ISSUE TITLE
Cannot get a valid ios build from `expo build:ios`

### ISSUE THREAD

**Issue by jrobber** [expo/expo-cli#287]
## Description

Cannot get a valid ios build from `expo build:ios`.   That exact same icon, with that same path, was working on version 26.  But since 26 is only a few releases away from being unsupported I thought it was time to upgrade.

## Expected Behavior

I expect the build to succeed and give me a URL to the new build

## Observed Behavior

What actually happened when you performed the above actions?

```
Error: Failed to resize image: AppIcon1024x1024.png. (Error: Input file is missing or of an unsupported image format)
    at /usr/local/turtle-js/node_modules/xdl/build/detach/IosIcons.js:104:21
    at Generator.throw (<anonymous>)
    at step (/usr/local/turtle-js/node_modules/xdl/build/detach/IosIcons.js:173:191)
    at /usr/local/turtle-js/node_modules/xdl/build/detach/IosIcons.js:173:402
    at <anonymous>
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

```
  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.6 => 31.0.6
      react: 16.7.0 => 16.7.0
      react-native: 0.57.8 => 0.57.8
      react-navigation: ^2.2.4 => 2.18.3
    npmGlobalPackages:
      expo-cli: 2.6.14
```

Also specify:

- Phone/emulator/simulator platform, model and version:

`expo build:ios`

package.json dependencies :
```
},
  "dependencies": {
    "@babel/core": "^7.2.2",
    "@expo/vector-icons": "^9.0.0",
    "@fortawesome/free-brands-svg-icons": "^5.6.3",
    "@fortawesome/pro-light-svg-icons": "^5.6.3",
    "@fortawesome/pro-regular-svg-icons": "^5.6.3",
    "@fortawesome/pro-solid-svg-icons": "^5.6.3",
    "@ptomasroos/react-native-multi-slider": "^0.0.14",
    "ajv": "^6.6.2",
    "apisauce": "^1.0.1",
    "expo": "^31.0.6",
    "expo-font": "^2.0.0",
    "expo-location": "^2.0.0",
    "graphql": "^14.0.2",
    "graphql-tag": "^2.10.0",
    "lodash": "^4.17.11",
    "moment": "^2.23.0",
    "native-base": "^2.4.2",
    "numeral": "^2.0.6",
    "react": "16.7.0",
    "react-native": "0.57.8",
    "react-native-calendars": "^1.21.0",
    "react-native-camera": "^1.4.3",
    "react-native-camera-roll-picker": "^1.2.3",
    "react-native-fontawesome-pro": "^2.0.1",
    "react-native-gridview": "^0.1.2",
    "react-native-keyboard-aware-scroll-view": "^0.5.0",
    "react-native-modal": "^5.4.0",
    "react-native-reanimated": "^1.0.0-alpha.11",
    "react-native-svg": "8.0.8",
    "react-navigation": "^2.2.4",
    "react-redux": "^5.1.1",
    "redux": "^4.0.1",
    "socket.io-client": "^2.2.0"
  },
  "resolutions": {
    "react-native-svg": "8.0.8"
  }
```

App.json
```
{
  "expo": {
    "sdkVersion": "31.0.0",
    "name": "company",
    "description": "Generic description",
    "icon": "./src/assets/icons/AppIcon.debug.appiconset/icon-AppStore.png",
    "version": "0.5.0",
    "slug": "company",
    "orientation": "portrait",
    "android": {
      "package": "com.company",
      "permissions": ["CAMERA_ROLL"]
    },
    "ios": {
      "bundleIdentifier": "com.company.company"
    },
    "primaryColor": "#35BAEF",
    "assetBundlePatterns": ["src/assets/*"]
  }
}
```

**Comment by dsokal** [comment]
Hey,
Please change `"assetBundlePatterns": ["src/assets/*"]` to `"assetBundlePatterns": ["src/assets/**/*"]` and run build again.
