### ISSUE TITLE
Error when ejecting: "Could not locate a valid AppDelegate at root"

### ISSUE THREAD

**Issue by RoseAndres** [expo/expo-cli#2932]
## Description

I'm trying to eject an app  I just started working on from expo because we want to add/play around with some BlueTooth functionality and I am running into an error when I run `npm run eject` or `expo eject`.

## Expected Behavior

I ran `npm run eject`, expecting it to eject the app and be ready to go with no additional config or issues. When prompted for an package names I provided `com.orgname.mobile` for both.  
I also ran `expo eject` after the first attempt failed, in case the expo command did something slightly different.

## Observed Behavior

```
✔ Created native projects | /android, /ios already created
✔ Added Metro bundler configuration.
✔ Updated package.json and added index.js entry point for iOS and Android.
- Removed "main": "node_modules/expo/AppEntry.js" from package.json because we recommend using index.js as main instead.

🧶 Using Yarn to install packages. You can pass --npm to use npm instead.

✔ Cleaned JavaScript dependencies.
✔ Installed JavaScript dependencies.
Could not locate a valid AppDelegate at root: "/Users/dre/Unabridged/Projects/blutapp-mobile"
Please report this as an issue on https://github.com/expo/expo-cli/issues
Error: Could not locate a valid AppDelegate at root: "/Users/dre/Unabridged/Projects/blutapp-mobile"
Please report this as an issue on https://github.com/expo/expo-cli/issues
    at getAppDelegate (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config/src/ios/Paths.ts:18:11)
    at Object.getSourceRoot (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config/src/ios/Paths.ts:36:23)
    at Object.getProjectName (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config/src/ios/utils/Xcodeproj.ts:28:28)
    at evalModsAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config/src/plugins/mod-compiler.ts:33:52)
    at compileModsAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config/src/plugins/mod-compiler.ts:17:16)
    at configureIOSProjectAsync (/usr/local/lib/node_modules/expo-cli/src/commands/apply/configureIOSProjectAsync.ts:23:9)
    at configureIOSStepAsync (/usr/local/lib/node_modules/expo-cli/src/commands/eject/Eject.ts:194:3)
    at Object.ejectAsync (/usr/local/lib/node_modules/expo-cli/src/commands/eject/Eject.ts:99:5)
    at action (/usr/local/lib/node_modules/expo-cli/src/commands/eject.ts:44:5)
    at Command.<anonymous> (/usr/local/lib/node_modules/expo-cli/src/exp.ts:332:7)
```

## Environment

Running on Macbook Pro (2019).
Note: This is what the output is when I ran `expo diagnostics` 1) before ejecting and 2) after discarding changed files from the failed eject and then re-running `npm install`:

```
Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.19.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /Users/dre/.rvm/gems/ruby-2.7.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2
        System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.4
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: bare
```

**Comment by brentvatne** [comment]
see https://github.com/expo/expo-cli/issues/2894

you have existing ios and android directories that do not contain ios and android projects, and that's where we need to put them
