### ISSUE TITLE
"Not Found" error when trying to use expo upload:ios

### ISSUE THREAD

**Issue by ErickTamayo** [expo/expo-cli#2947]
## Description

When trying to upload the ios build with `expo upload:ios` I get an error instead. Using Node `12.19.0` and latest version of expo. This happens in my local machine (`macOS Catalina`) and as a Github Action running latest macos

## Expected Behavior

Be able to upload ios upload build to TestFlight

## Observed Behavior

```
➜  (REDACTED) git:(main) ✗ expo upload:ios
Please enter your Apple Developer Program account credentials. These credentials are needed to manage
certificates, keys and provisioning profiles in your Apple Developer account.
The password is only used to authenticate with Apple and never stored on Expo servers
Learn more: https://bit.ly/2VtGWhU
? Apple ID: (REDACTED)
Using password from your local Keychain. Learn more https://docs.expo.io/distribution/security#keychain
Accessing credentials for ericktamayo in project (REDACTED)
Downloading build from https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/ios/%40ericktamayo/(REDACTED)-071d8170-2331-4e5b-ad13-9524f7d6e86d-archive.ipa
[================================================================] 100% 0.0s
Resolving the ITC team ID...
ITC team ID is 117846896
Ensuring the app exists on App Store Connect, this may take a while...

+----------------+-----------------------------+
|         Summary for produce 2.146.1          |
+----------------+-----------------------------+
| app_identifier | com.ericktamayo.(REDACTED)  |
| app_name       | (REDACTED)                  |
| username       | (REDACTED)                  |
| language       | English                     |
| sku            | 1606324803                  |
| platform       | ios                         |
| skip_itc       | false                       |
| skip_devcenter | false                       |
+----------------+-----------------------------+

[10:20:04]: [DevCenter] App 'com.ericktamayo.(REDACTED)' already exists, nothing to do on the Dev Center
[10:20:07]: Creating new app '(REDACTED)' on App Store Connect
Failed to upload the standalone app to the App Store.
We recommend using Transporter.app (​https://apps.apple.com/us/app/transporter/id1450874784​) instead of the expo upload:ios command if you have any trouble with it.
{"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"}
    (REDACTED)/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.146.1/spaceship/lib/spaceship/client.rb:714:in `parse_response'
    (REDACTED)/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.146.1/spaceship/lib/spaceship/tunes/tunes_client.rb:296:in `create_application!'
    (REDACTED)/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.146.1/spaceship/lib/spaceship/tunes/application.rb:96:in `create!'
    (REDACTED)/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.146.1/produce/lib/produce/itunes_connect.rb:29:in `create_new_app'
    (REDACTED)/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.146.1/produce/lib/produce/itunes_connect.rb:15:in `run'
    (REDACTED)/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.146.1/produce/lib/produce/manager.rb:12:in `start_producing'
    (REDACTED)/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/app_produce.rb:20:in `block in <main>'
    (REDACTED)/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/funcs.rb:4:in `with_captured_stderr'
    (REDACTED)/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/app_produce.rb:11:in `<main>'
Error: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"}
    (REDACTED)/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.146.1/spaceship/lib/spaceship/client.rb:714:in `parse_response'
    (REDACTED)/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.146.1/spaceship/lib/spaceship/tunes/tunes_client.rb:296:in `create_application!'
    (REDACTED)/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.146.1/spaceship/lib/spaceship/tunes/application.rb:96:in `create!'
    (REDACTED)/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.146.1/produce/lib/produce/itunes_connect.rb:29:in `create_new_app'
    (REDACTED)/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.146.1/produce/lib/produce/itunes_connect.rb:15:in `run'
    (REDACTED)/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.146.1/produce/lib/produce/manager.rb:12:in `start_producing'
    (REDACTED)/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/app_produce.rb:20:in `block in <main>'
    (REDACTED)/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/funcs.rb:4:in `with_captured_stderr'
    (REDACTED)/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/app_produce.rb:11:in `<main>'
    at runFastlaneAsync ((REDACTED)/node_modules/expo-cli/src/commands/upload/utils.ts:64:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at IOSUploader._uploadToTheStore ((REDACTED)/node_modules/expo-cli/src/commands/upload/IOSUploader.ts:181:7)
    at IOSUploader.upload ((REDACTED)/node_modules/expo-cli/src/commands/upload/BaseUploader.ts:36:5)
    at (REDACTED)/node_modules/expo-cli/src/commands/upload.ts:125:9
    at Command.<anonymous> ((REDACTED)/node_modules/expo-cli/src/exp.ts:332:7)
```

The error specifically is this one

```
{"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"}
```

I was digging a bit more before creating the issue and found that this is probably related to this:

https://github.com/fastlane/fastlane/issues/16739

## Environment

```
  Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.19.1 - ~/.nvm/versions/node/v12.19.1/bin/node
      npm: 6.14.8 - ~/.nvm/versions/node/v12.19.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 3.28.6
    Expo Workflow: managed
```

## Reproducible Demo

I'll try to make a repo later

**Comment by EvanBacon** [comment]
Fastlane has a number of issues like this and we're investigating removing it. I'd recommend using transporter until we get it resolved.

**Comment by EvanBacon** [comment]
We've deprecated `expo upload:ios` in favor of `eas-cli`s `eas submit -p ios` which does not use Fastlane.
