### ISSUE TITLE
XDLError: ValidationError: "scheme" is not allowed

### ISSUE THREAD

**Issue by pioNavarro** [expo/expo-cli#2951]
## Description

I'm having this error "XDLError: ValidationError: "scheme" is not allowed" when running the expo start.

## Observed Behavior

```
XDLError: ValidationError: "scheme" is not allowed
    at constructUrlAsync (/@expo/xdl@57.9.35/src/UrlUtils.ts:189:13)
    at Object.constructBundleUrlAsync (/@expo/xdl@57.9.35/src/UrlUtils.ts:19:10)
    at /@expo/xdl@57.9.35/src/Project.ts:2037:25
```

## Environment

Expo CLI 3.26.2 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.4 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.4 => 39.0.5 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-navigation: ^3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.26.2

This is the package I am using:
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "test": "node ./node_modules/jest/bin/jest.js --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@babel/core": "^7.12.9",
    "@expo/samples": "2.1.1",
    "@expo/vector-icons": "^10.2.1",
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/netinfo": "5.9.6",
    "accordion-collapse-react-native": "^0.1.9",
    "expo": "^39.0.4",
    "expo-asset": "~8.2.0",
    "expo-av": "~8.6.0",
    "expo-camera": "~9.0.0",
    "expo-cli": "^3.26.2",
    "expo-constants": "~9.2.0",
    "expo-contacts": "~8.5.0",
    "expo-device": "~2.3.0",
    "expo-document-picker": "~8.4.0",
    "expo-file-system": "~9.2.0",
    "expo-font": "~8.3.0",
    "expo-image-manipulator": "~8.3.0",
    "expo-image-picker": "~9.1.1",
    "expo-keep-awake": "~8.3.0",
    "expo-mail-composer": "~8.4.0",
    "expo-media-library": "~9.2.1",
    "expo-permissions": "~9.3.0",
    "expo-screen-orientation": "~2.0.0",
    "expo-sharing": "~8.4.1",
    "expo-sms": "~8.3.1",
    "expo-svg-uri": "^1.3.1",
    "expo-video-player": "^1.6.1",
    "expo-web-browser": "~8.5.0",
    "i18n-js": "^3.8.0",
    "install": "^0.12.2",
    "moment": "^2.29.1",
    "moment-timezone": "^0.5.32",
    "native-base": "^2.13.14",
    "react": "16.13.1",
    "react-moment": "^0.9.7",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz",
    "react-native-contacts": "^4.0.3",
    "react-native-datepicker": "^1.7.2",
    "react-native-dropdown-autocomplete": "^1.0.18",
    "react-native-elements": "^1.2.7",
    "react-native-gesture-handler": "~1.7.0",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-material-dialog": "^0.7.7",
    "react-native-modal-dropdown-updated": "^0.6.3",
    "react-native-netinfo": "^1.1.0",
    "react-native-paper": "^4.3.1",
    "react-native-picker-select": "^6.6.0",
    "react-native-progress": "^4.1.2",
    "react-native-render-html": "^4.2.4",
    "react-native-scrollable-tab-view": "^1.0.0",
    "react-native-svg": "12.1.0",
    "react-native-svg-charts": "^5.4.0",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-tab-view": "^2.15.2",
    "react-native-touchable-scale": "^2.1.1",
    "react-native-underline-tabbar": "^1.3.6",
    "react-native-viewpager": "^0.2.13",
    "react-native-webview": "10.7.0",
    "react-navigation": "^3.13.0",
    "react-navigation-drawer": "^1.4.0",
    "rn-range-slider": "^1.3.3",
    "yarn": "^1.22.10"
  },
  "devDependencies": {
    "babel-preset-expo": "^8.3.0",
    "jest-expo": "^39.0.0",
    "schedule": "^0.4.0"
  },
  "private": true
}

```

## Reproducible Demo

I'm running it on Android and iOS

**Comment by brentvatne** [comment]
please install the latest version of expo-cli

**Comment by pioNavarro** [comment]
> please install the latest version of expo-cli

I tried installing the latest version and still an error.

![image](https://user-images.githubusercontent.com/51459273/100279336-4cd1f380-2fa1-11eb-809e-7e564ad2ec7d.png)


```
 Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.4 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.5.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.4 => 39.0.5 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-navigation: ^3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
can you share your app.json?

**Comment by pioNavarro** [comment]
Here's my app.sjon

```
{
    "expo": {
      "name": "Company",
      "slug": "comp-main-expo-init",
      "privacy": "public",
      "platforms": [
        "ios",
        "android"
      ],
      "version": "5.8.31",
      "orientation": "portrait",
      "splash": {
        "image": "./assets/images/splash.png",
        "resizeMode": "cover",
        "backgroundColor": "#ffffff"
      },
      "icon": "./assets/images/icon.png",
      "updates": {
        "fallbackToCacheTimeout": 0
      },
      "assetBundlePatterns": [
        "**/*"
      ],
      "ios": {
        "bundleIdentifier": "com.comp.main",
        "requireFullScreen": true,
        "supportsTablet": true,
        "infoPlist": {
          "NSCameraUsageDescription": "comp app need to access your camera roll so you could upload a selfie with your friend or update your profile.",
          "NSContactsUsageDescription": "By clicking 'Ok', you are allowing this app to upload your contact to Naxum server, Once you have synced your contacts you can choose which individual relationships you would like to invite to Naxum, nothing is sent to your contacts until you choose to share with them individually.",
          "NSPhotoLibraryUsageDescription": "Naxum app needs permission to your picture gallery to upload prospect pictures or update your profile."
        }
      },
      "android": {
        "package": "com.naxum.main",
        "versionCode": 81
      },
      "notification": {
        "icon": "./assets/images/icon.png",
        "color": "#ffffff",
        "iosDisplayInForeground": true
     },
      "description": "This is the official app of Naxum"
    }
  }
  
```

**Comment by brentvatne** [comment]
can you try removing the `.expo` directory? `rm -rf .expo` in your project

**Comment by pioNavarro** [comment]
> can you try removing the `.expo` directory? `rm -rf .expo` in your project

Thank you!!! You just saved me. it's now working

**Comment by brentvatne** [comment]
hm, i wonder how your project ended up with a scheme property in `.expo`... odd.

**Comment by Abhishek12345679** [comment]
> hm, i wonder how your project ended up with a scheme property in `.expo`... odd.

happened to me too when i used a cloned repo

**Comment by roykathurima** [comment]
> hm, i wonder how your project ended up with a scheme property in `.expo`... odd.

I had this when I upgraded then downgraded my version of expo-client

**Comment by PathikSaubhagyam** [comment]
> can you try removing the `.expo` directory? `rm -rf .expo` in your project

Thank you!!! You just saved me. it's now working

**Comment by evansuong** [comment]
Probably happened to me when I installed expo-cli within my project directory instead of gobally

**Comment by brentvatne** [comment]
the latest version of expo-cli should resolve this, and also yeah please install globally

**Comment by Rajan-Savaliya-spt** [comment]
rm -rf .expo This is work for me

**Comment by devPinheiro** [comment]
> can you try removing the `.expo` directory? `rm -rf .expo` in your project

This solved it for me.
Thank you.

**Comment by WilbertJanney** [comment]
Removing the local project dependency for expo-cli fixes it for me. That seems to be the correct way to go about it, instead of removing the .expo folder.

**Comment by brentvatne** [comment]
@WilbertJanney @devPinheiro @Rajan-Savaliya-spt - also updating to the latest expo-cli should resolve it

**Comment by crisBoi** [comment]
> 
> 
> can you try removing the `.expo` directory? `rm -rf .expo` in your project

can you explain. Why it works after removing .expo?
