### ISSUE TITLE
Registering keeps failing on password confirmation step

### ISSUE THREAD

**Issue by byCedric** [expo/expo-cli#2970]
## Description

When registering a new account, I used `$ EXPO_STAGING=1 expo ...`, the password confirmation prompt always fails. It's related to [us fetching previous answers](https://github.com/expo/expo-cli/blob/22507a1891a40c131d9c5873925ec8e4cef5dcd4/packages/expo-cli/src/accounts.ts#L363), but [that doesn't seem to be provided](https://github.com/terkelg/prompts/blob/972fbb2d43c7b1ee5058800f441daaf51f2c240f/lib/elements/text.js#L71).

## Expected Behavior

Succeeds when I confirm the password successfully.

## Observed Behavior

```
(node:22935) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'password' of undefined
    at TextPrompt.validate [as validator] (/Users/cedric/Projects/expo/expo-cli/packages/expo-cli/src/accounts.ts:369:73)
    at TextPrompt.validate (/Users/cedric/Projects/expo/expo-cli/node_modules/prompts/lib/elements/text.js:71:28)
    at TextPrompt.submit (/Users/cedric/Projects/expo/expo-cli/node_modules/prompts/lib/elements/text.js:81:16)
    at ReadStream.keypress (/Users/cedric/Projects/expo/expo-cli/node_modules/prompts/lib/elements/prompt.js:32:16)
    at ReadStream.emit (events.js:315:20)
    at emitKeys (internal/readline/utils.js:345:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1144:36)
    at ReadStream.emit (events.js:327:22)
    at addChunk (_stream_readable.js:309:12)
```

## Environment

```
  Expo CLI 4.0.3 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.0.11 - ~/.nvm/versions/node/v14.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 20.0, macOS 11.0, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 21, 26, 28, 29, 30
        Build Tools: 26.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.2
        System Images: android-21 | Google APIs ARM EABI v7a, android-22 | Intel x86 Atom_64, android-22 | Google APIs ARM EABI v7a, android-23 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
        Android NDK: 21.3.6528147
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.0/12A8189h - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.12.45 => 0.12.46
      expo: ^40.0.0-beta.1 => 40.0.0-beta.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed
```

## Reproducible Demo

- Try to register

**Comment by byCedric** [comment]
Looks like a limitation from `prompts`, maybe we should add a custom element for password confirmation?

**Comment by byCedric** [comment]
An [issue for this functionality was created](https://github.com/terkelg/prompts/issues/273), but there is no PR yet.
