### ISSUE TITLE
Error when connecting to device using tunnel in expo app android

### ISSUE THREAD

**Issue by kshitijzutshi** [expo/expo-cli#2987]
My node version is V14.15.1, 
NPM : 6.14.8
expo: 4.0.7
I have tried most methods found on forums but this error still persists. I am looking for a solution to this roadblock. Please help.

```
Tunnel ready.
info Launching Dev Tools...
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [ '/c', 'start', '""', '/b', 'http://localhost:19001/debugger-ui' ]
}
```

![image](https://user-images.githubusercontent.com/13203059/100996743-6ebe0e00-357f-11eb-9110-9c5a2e0d7db7.png)

![image](https://user-images.githubusercontent.com/13203059/100996794-7f6e8400-357f-11eb-8300-ed699e59c752.png)

**Comment by kshitijzutshi** [comment]
This is happening when i am trying to scan the QR code on android. I can only open code in tunnel mode.
