### ISSUE TITLE
bash exited with non-zero code: 4294967295 on build:ios

### ISSUE THREAD

**Issue by oliuradu** [expo/expo-cli#2999]
## Description
Error when i try to run the command expo build:ios
I made an upgrade from expo 36 to expo 39 recently.

## Expected Behavior
Reinstalled node_modules.
Reinstalled expo-cli

## Observed Behavior

```
Authentication with Apple Developer Portal failed!
bash exited with non-zero code: 4294967295
Error: bash exited with non-zero code: 4294967295
    at ChildProcess.completionListener (C:\Users\Mix Desktop\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:418:26)
    at ChildProcess.emit (events.js:311:20)
    at ChildProcess.cp.emit (C:\Users\Mix Desktop\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    ...
    at spawnAsync (C:\Users\Mix Desktop\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:26:19)
    at runAction (C:\Users\Mix Desktop\AppData\Roaming\npm\node_modules\expo-cli\src\appleApi\fastlane.ts:20:28)
    at authenticate (C:\Users\Mix Desktop\AppData\Roaming\npm\node_modules\expo-cli\src\appleApi\authenticate.ts:49:46)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Context.ensureAppleCtx (C:\Users\Mix Desktop\AppData\Roaming\npm\node_modules\expo-cli\src\credentials\context.ts:81:24)
    at IOSBuilder.bestEffortAppleCtx (C:\Users\Mix Desktop\AppData\Roaming\npm\node_modules\expo-cli\src\commands\build\ios\IOSBuilder.ts:95:14)
    at IOSBuilder.prepareCredentials (C:\Users\Mix Desktop\AppData\Roaming\npm\node_modules\expo-cli\src\commands\build\ios\IOSBuilder.ts:151:5)
    at IOSBuilder.run (C:\Users\Mix Desktop\AppData\Roaming\npm\node_modules\expo-cli\src\commands\build\ios\IOSBuilder.ts:62:7)
    at IOSBuilder.command (C:\Users\Mix Desktop\AppData\Roaming\npm\node_modules\expo-cli\src\commands\build\BaseBuilder.ts:39:7)
    at Command.<anonymous> (C:\Users\Mix Desktop\AppData\Roaming\npm\node_modules\expo-cli\src\exp.ts:346:7)
```

## Environment

`  Expo CLI 4.0.8 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Mix Desktop\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6308749
    npmPackages:
      expo: ^39.0.0 => 39.0.5
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.18
    Expo Workflow: managed`

## App.json

`{
  "expo": {
    "name": "My app",
    "slug": "app",
    "platforms": ["ios", "android", "web"],
    "version": "1.0.4",
    "orientation": "default",
    "icon": "./assets/images/icon.png",
    "scheme": "myapp",
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#181726"
    },
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "gtm-managing-services",
            "project": "myapp",
            "authToken": "XXXxxxXXXxxxxXXXxxxXXXxx"
          }
        }
      ]
    },
    "updates": {
      "enabled": true,
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "bundleIdentifier": "XXX.XXXX.XXXXXX",
      "buildNumber": "1",
      "supportsTablet": false,
      "requireFullScreen": true
    },
    "android": {
      "package": "com.jump.carfix",
      "versionCode": 1,
      "googleServicesFile": "./google-services.json",
      "softwareKeyboardLayoutMode": "pan"
    },
    "web": {
      "favicon": "./assets/images/favicon.png"
    },
    "packagerOpts": {
      "config": "metro.config.js",
      "sourceExts": ["expo.ts", "expo.tsx", "expo.js", "expo.jsx", "ts", "tsx", "js", "jsx", "json", "wasm", "svg"]
    },
    "description": ""
  }
}
`

**Comment by schaetz** [comment]
I have the same issue and have not found a solution to this so far.

There is a related thread on StackOverflow:
https://stackoverflow.com/q/60403093/4602192

**Comment by Muzzamilkorai** [comment]
Facing the same issue, any help will be appreciated

**Comment by EvanBacon** [comment]
I've removed Fastlane in the latest version `expo-cli@4.1.0`. Authentication is now done in JS and surfaces more error information (also it is more stable). If the problem persists on `^4.1.0`, please open a new issue.
