### ISSUE TITLE
[expo install expo-splash-screen] not able to finish

### ISSUE THREAD

**Issue by davidedc97** [expo/expo-cli#3024]
## Description

Running "expo install expo-splash-screen" fails, even on a new empty project. I also tried with "npm install", "npm install expo-splash-screen --save", but same result. Last release of expo-splash-screen at the moment of this issue is ^0.8.1

## Environment
I'm on a native Windows 10 environment.

Expo diagnostic output:

Expo CLI 4.0.13 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.3
        System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ~40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

## Observed Behavior

Here is the full output when running "expo install expo-splash-screen" in the console:

```
Installing 1 SDK 40.0.0 compatible native module using npm.
> npm install
npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path C:\Users\Davide\Uni\michelapp_mobile2\Michelapp\node_modules\@expo\configure-splash-screen\node_modules\core-js
npm ERR! dest C:\Users\Davide\Uni\michelapp_mobile2\Michelapp\node_modules\@expo\configure-splash-screen\node_modules\.core-js.DELETE
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Davide\Uni\michelapp_mobile2\Michelapp\node_modules\@expo\configure-splash-screen\node_modules\core-js' -> 'C:\Users\Davide\Uni\michelapp_mobile2\Michelapp\node_modules\@expo\configure-splash-screen\node_modules\.core-js.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Davide\AppData\Roaming\npm-cache\_logs\2020-12-13T21_35_40_717Z-debug.log

npm exited with non-zero code: 4294963238
Error: npm exited with non-zero code: 4294963238
    at ChildProcess.completionListener (C:\Users\Davide\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.cp.emit (C:\Users\Davide\AppData\Roaming\npm\node_modules\expo-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    ...
    at Object.spawnAsync [as default] (C:\Users\Davide\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\spawn-async\src\spawnAsync.ts:26:19)
    at NpmPackageManager._runAsync (C:\Users\Davide\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\package-manager\src\NodePackageManagers.ts:157:31)
    at NpmPackageManager.addAsync (C:\Users\Davide\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\package-manager\src\NodePackageManagers.ts:100:18)
    at installAsync (C:\Users\Davide\AppData\Roaming\npm\node_modules\expo-cli\src\commands\install.ts:129:3)
    at Command.<anonymous> (C:\Users\Davide\AppData\Roaming\npm\node_modules\expo-cli\src\exp.ts:346:7)
```

**Comment by brentvatne** [comment]
this is a bug with npm and/or your machine. you can google "npm install ENOENT: no such file or directory, rename"
