### ISSUE TITLE
yarn expo eject: Error: Cannot find module './CommandError'

### ISSUE THREAD

**Issue by charlex** [expo/expo-cli#3050]
## Description

Running `yarn expo eject` results in a ./CommandError module not found error.

## Environment

```
 ❯ yarn expo diagnostics                                                                                                          [17:07:34]
yarn run v1.22.4
$ /redacted/node_modules/.bin/expo diagnostics

  Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.5.0 - /var/folders/9g/jxh_z07d5wvdzfrr47tvxrfh0000gn/T/yarn--1609711654714-0.4959008239243432/node
      Yarn: 1.22.4 - /var/folders/9g/jxh_z07d5wvdzfrr47tvxrfh0000gn/T/yarn--1609711654714-0.4959008239243432/yarn
      npm: 7.3.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 28
        System Images: android-29 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare
```

## Expected Behavior

An ejection.

## Observed Behavior

Output:

```
 ❯ yarn expo eject                                                                            [16:50:26]
yarn run v1.22.4
$ /redacted/node_modules/.bin/expo eject
Warning! Your git working tree is dirty.
It's recommended to commit all your changes before proceeding, so you can revert the changes made by this command if necessary.

✔ Would you like to proceed? … yes

✔ Created native projects
✔ Added Metro bundler configuration.
✔ Updated package.json and added index.js entry point for iOS and Android.

🧶 Using Yarn to install packages. You can pass --npm to use npm instead.

✔ Cleaned JavaScript dependencies.
⠼ Installing JavaScript dependencies.Error: Cannot find module './CommandError'
Require stack:
- /redacted/node_modules/expo-cli/build/exp.js
- /redacted/node_modules/expo-cli/bin/expo.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at _CommandError (/redacted/node_modules/expo-cli/src/exp.ts:34:1)
    at Command.<anonymous> (/redacted/node_modules/expo-cli/src/exp.ts:352:26)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
>>> elapsed time 11s
```

Git status:

```
 ❯ git status                                                                                                                     [17:05:52]
On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .gitignore
	modified:   package.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	android/
	index.js
	ios/
	metro.config.js
```

## Reproducible Demo

Sorry, I tried to start a codesandbox, but I don't know how to reproduce an ejection.

**Comment by anback** [comment]
+1

**Comment by EvanBacon** [comment]
Not sure exactly how this syntax works at all, but expo-cli currently only supports global installs.

**Comment by brentvatne** [comment]
closing because we recommend global installs ([see installation instructions](https://docs.expo.io/#quick-start)) and don't guarantee that commands like `eject` will work for local installs.

if you downgrade to expo-cli@3 and eject you are going to have other problems, so i would not recommend it

**Comment by slorber** [comment]
wondering why you recommend global installs? Isn't it a potential source of issues for users managing multiple expo apps, some of them older?

**Comment by brentvatne** [comment]
@slorber - we recommend that users always use the latest version of expo-cli, so it should not be a problem. backwards compat is built into the cli
