### ISSUE TITLE
Running expo build:ios produces 500 createError

### ISSUE THREAD

**Issue by njsokol** [expo/expo-cli#309]
Thanks for reporting the issue you found with Expo CLI!

## Description

I am trying to get a build running using `expo build:ios` but am experiencing a 500 error. I pushed a build last night (~12 hours ago) without any issues. Performing the same command and after running `npm install -g expo-cli` don't seem to resolve the issue.

## Expected Behavior

Running the `expo build:ios` should not error out.

## Observed Behavior

```
[13:55:00] Uploading assets
[13:55:01] No assets changed, skipped.
[13:55:01] Processing asset bundle patterns:
[13:55:01] - /Users/me/workspace/project/**/*
[13:55:01] Uploading JavaScript bundles
[13:55:09] Request failed with status code 500
[13:55:09] Error: Request failed with status code 500
    at createError (/Users/me/.nvm/versions/node/v8.14.0/lib/node_modules/expo-cli/node_modules/xdl/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/me/.nvm/versions/node/v8.14.0/lib/node_modules/expo-cli/node_modules/xdl/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/me/.nvm/versions/node/v8.14.0/lib/node_modules/expo-cli/node_modules/xdl/node_modules/axios/lib/adapters/http.js:236:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

## Environment

```
$ expo diagnostics

  Expo CLI 2.6.14 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.14.0 - ~/.nvm/versions/node/v8.14.0/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v8.14.0/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.2 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.0 => 3.0.8 
    npmGlobalPackages:
      expo-cli: 2.6.14
```

## Reproducible Demo

Should be any project.

**Comment by njsokol** [comment]
Error was found to be an outage for expo. When the systems came back online, everything started working again. https://github.com/expo/expo/issues/1715
