### ISSUE TITLE
@expo/vector-icons are not working after adding metro.config.js file in project root folder

### ISSUE THREAD

**Issue by Gangeshwar3** [expo/expo-cli#3115]
```
const {getDefaultConfig} = require('metro-config');

module.exports = (async () => {
  const {
      resolver: { sourceExts, assetExts }
  } = await getDefaultConfig()
  return {
      transformer: {
          getTransformOptions: async () => ({
              transform: {
                  experimentalImportSupport: false,
                  inlineRequires: false
              }
          })
      },
      resolver: {
        sourceExts,
        assetExts: [...assetExts, 'hcscript']
      }
    }
})()
```

## Description
I added the lines in metro.config.js file to run highcharts in android and ios, after adding this the expo/vector-icons are showing in cross symbol, i also tried installing react-native-vector-icons and link with react-native nothing works for me. What to do in this scenario can someone please help me on this? 

## Environment
    "expo": "^40.0.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
 Pixel_4_API_29

## Expected Behavior

Need to show the icons properly

## Observed Behavior
icons are showing cross symbol attaching a scrren below.

![Screenshot from 2021-01-23 15-47-18](https://user-images.githubusercontent.com/39775325/105575851-a46bc000-5d94-11eb-94b8-8fb9bb07f1ed.png)

**Comment by brentvatne** [comment]
see this guide for how to customize metro: https://docs.expo.io/guides/customizing-metro/

note that you need to use @expo/metro-config

**Comment by Gangeshwar3** [comment]
i have used @expo/metro-config,
but it throws the error like Cannot find module '@expo/metro-config', then i installed through npm i @expo/metro-config again i throws another error like  The "path" argument must be of type string. Received type undefined. What to do in this case.

**Comment by Gangeshwar3** [comment]
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:1039:7)
    at getDynamicConfigFilePath (/home/gangeshwarvollala/Mosaik/ewp-mobile/ewp-web-mobile/node_modules/@expo/config/src/Config.ts:307:29)
    at getConfigFilePaths (/home/gangeshwarvollala/Mosaik/ewp-mobile/ewp-web-mobile/node_modules/@expo/config/src/Config.ts:285:24)
    at Object.getConfig (/home/gangeshwarvollala/Mosaik/ewp-mobile/ewp-web-mobile/node_modules/@expo/config/src/Config.ts:93:17)
    at getDefaultConfig (/home/gangeshwarvollala/Mosaik/ewp-mobile/ewp-web-mobile/node_modules/@expo/metro-config/src/ExpoMetroConfig.ts:35:19)
    at /home/gangeshwarvollala/Mosaik/ewp-mobile/ewp-web-mobile/metro.config.js:6:13
    at Object.<anonymous> (/home/gangeshwarvollala/Mosaik/ewp-mobile/ewp-web-mobile/metro.config.js:21:3)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)

**Comment by brentvatne** [comment]
you need to pass in project root to the config. it's on the docs page 😅 

```
const { getDefaultConfig } = require('@expo/metro-config');

const defaultConfig = getDefaultConfig(__dirname);

module.exports = {
  resolver: {
    assetExts: [...defaultConfig.resolver.assetExts, 'db'],
  },
};
```
