### ISSUE TITLE
I'm not able to login with my credential but I'm able to

### ISSUE THREAD

**Issue by vipin733** [expo/expo-cli#319]
acOS mojave
10.14

SDK-32
I'm not able to login with my credential but I'm able to . login apple developer account
 
```
Flypurs-MacBook-xxxxxxx  xxxxxxxx$ expo build:ios
[16:38:26] Making sure project is set up correctly...
[16:38:29] Your project looks good!
[16:38:32] Checking if current build exists...

[16:38:33] No currently active or previous builds for this project.
[16:38:33] If you get errors about

'Maximum number of certificates generated' or 'duplicate profiles'

then consider using the flags --revoke-apple-dist-certs, --revoke-apple-push-certs,
and --revoke-apple-provisioning-profile or go to developer.apple.com
and revoke those credentials manually

? How would you like to upload your credentials?
 Expo handles all credentials, you can still provide overrides

We need your Apple ID/password to manage certificates and
provisioning profiles from your Apple Developer account.

Note: Expo does not keep your Apple ID or your Apple password.
    
? What's your Apple ID? office@xxxx.com
? Password? [hidden]
[16:41:03] Validating Credentials...
Available session is not valid any more. Continuing with normal login.

[16:41:06] Error while gathering & validating credentials
[16:41:06] Error: Reason:Invalid credentials, raw:"Invalid username and password combination. Used 'office@flypur.com' as the username."
[16:41:06] Reason:Invalid credentials, raw:"Invalid username and password combination. Used 'office@flypur.com' as the username."
[16:41:06] Error: Reason:Invalid credentials, raw:"Invalid username and password combination. Used 'office@xxxx.com' as the username."
    at Object._callee4$ (/expo-cli@2.6.14/src/commands/build/auth.js:135:11)
    at tryCatch (/usr/local/lib/node_modules/expo-cli/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/expo-cli/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/expo-cli/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/lib/node_modules/expo-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/expo-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
````

I'm stuck

**Comment by vipin733** [comment]
problem solved its from apple side, now its fixed
