### ISSUE TITLE
expo build:ios in CI

### ISSUE THREAD

**Issue by mymattcarroll** [expo/expo-cli#3193]
**Summary**

Now that apple require 2FA on accounts, I started getting this error while running `expo build:io`

```
EXPO_APPLE_PASSWORD=supersecretpassword EXPO_IOS_DIST_P12_PASSWORD=supersecretpassword npx expo build:ios --apple-id email@example.com --team-id MYTEAMID --dist-p12-path ./certificate.p12 --push-id MYPUSHID --push-p8-path ./key.p8 --provisioning-profile-path ./app.mobileprovision --no-wait --non-interactive --clear-credentials --release-channel v15

[15:38:11] Checking if there is a build in progress...

[15:38:12] Accessing credentials on behalf of oneblinkdevelopers in project io-oneblink-cpmobile-blinkopolis

✖ Logging in...
[15:38:14] Authentication with Apple Developer Portal failed!
[15:38:14] Need to acknowledge to Apple's Apple ID and Privacy statement. Please manually log into https://appleid.apple.com (or https://appstoreconnect.apple.com) to acknowledge the statement.
[15:38:14] Error: Need to acknowledge to Apple's Apple ID and Privacy statement. Please manually log into https://appleid.apple.com (or https://appstoreconnect.apple.com) to acknowledge the statement.
    at attemptLoginRequestAsync (/Users/mattcarroll/Documents/sources/gitlab/civicplus/cp-mobile/node_modules/@expo/apple-utils/build/index.js:1:751320)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.loginWithUserCredentialsAsync (/Users/mattcarroll/Documents/sources/gitlab/civicplus/cp-mobile/node_modules/@expo/apple-utils/build/index.js:1:750492)
    at loginWithUserCredentialsAsync (/Users/mattcarroll/Documents/sources/gitlab/civicplus/cp-mobile/node_modules/expo-cli/src/appleApi/authenticate.ts:133:22)
    at loginAsync (/Users/mattcarroll/Documents/sources/gitlab/civicplus/cp-mobile/node_modules/expo-cli/src/appleApi/authenticate.ts:92:12)
    at authenticateAsync (/Users/mattcarroll/Documents/sources/gitlab/civicplus/cp-mobile/node_modules/expo-cli/src/appleApi/authenticate.ts:152:23)
    at Context.ensureAppleCtx (/Users/mattcarroll/Documents/sources/gitlab/civicplus/cp-mobile/node_modules/expo-cli/src/credentials/context.ts:85:24)
    at IOSBuilder.bestEffortAppleCtx (/Users/mattcarroll/Documents/sources/gitlab/civicplus/cp-mobile/node_modules/expo-cli/src/commands/build/ios/IOSBuilder.ts:83:14)
    at IOSBuilder.prepareCredentials (/Users/mattcarroll/Documents/sources/gitlab/civicplus/cp-mobile/node_modules/expo-cli/src/commands/build/ios/IOSBuilder.ts:151:5)
    at IOSBuilder.run (/Users/mattcarroll/Documents/sources/gitlab/civicplus/cp-mobile/node_modules/expo-cli/src/commands/build/ios/IOSBuilder.ts:62:7)
```

After enabling 2FA and running the same command we are prompted for 2FA:

```
EXPO_APPLE_PASSWORD=supersecretpassword EXPO_IOS_DIST_P12_PASSWORD=supersecretpassword npx expo build:ios --apple-id email@example.com --team-id MYTEAID --dist-p12-path ./Certificates.p12 --push-id MYPUSHID --push-p8-path ./key.p8 --provisioning-profile-path ./app.mobileprovision --no-wait  --non-interactive --clear-credentials --release-channel v15

[15:41:53] Checking if there is a build in progress...

[15:41:54] Accessing credentials on behalf of oneblinkdevelopers in project io-oneblink-cpmobile-blinkopolis

✔ Logged in, verify your Apple account to continue
Two-factor Authentication (6 digit code) is enabled for email@example.com. Learn more: https://support.apple.com/en-us/HT204915

? How do you want to validate your account? › device / sms
```

This is not going to work in CI.

I then tried to skip the credentials check to avoid having to log in to the apple developer account using this command and got this error:

```
EXPO_APPLE_PASSWORD=supersecretpassword EXPO_IOS_DIST_P12_PASSWORD=supersecretpassword npx expo build:ios --apple-id email@example.com --team-id MYTEAMID --dist-p12-path ./certificate.p12 --push-id MYPUSHID --push-p8-path ./key.p8 --provisioning-profile-path ./app.mobileprovision --no-wait  --non-interactive --clear-credentials --release-channel v15 --skip-credentials-check
[15:48:35] --skip-credentials-check and --clear-credentials can't be used together
```

So I remove the `--clear-credentials` flag and success, it worked, until it didn't...

```
EXPO_APPLE_PASSWORD=supersecretpassword EXPO_IOS_DIST_P12_PASSWORD=supersecretpassword npx expo build:ios --apple-id email@example.com --team-id MYTEAMID --dist-p12-path ./certificate.p12 --push-id MYPUSHID --push-p8-path ./key.p8 --provisioning-profile-path ./app.mobileprovision --non-interactive --release-channel v15 --skip-credentials-check           

[15:51:57] Checking if there is a build in progress...

[15:51:58] Accessing credentials on behalf of oneblinkdevelopers in project io-oneblink-cpmobile-blinkopolis
[15:51:58] Skipping credentials check...

[15:51:58] - Expo SDK: 40.0.0
[15:51:58] - Release channel: v15
[15:51:58] - Workflow: Managed

[15:51:58] Building optimized bundles and generating sourcemaps...
[15:52:00] Starting Metro Bundler
[15:52:07] Finished building JavaScript bundle in 6760ms.
[15:52:07] 
[15:52:07] Bundle                     Size
┌ index.ios.js          2.99 MB
├ index.android.js      2.99 MB
├ index.ios.js.map      8.72 MB
└ index.android.js.map  8.72 MB
[15:52:07] 
[15:52:07] 💡 JavaScript bundle sizes affect startup time. Learn more: https://expo.fyi/javascript-bundle-sizes
[15:52:07] 
[15:52:07] Analyzing assets
[15:52:07] Saving assets
[15:52:08] No assets changed, skipped.
[15:52:08] 
Processing asset bundle patterns:
[15:52:08] - /Users/mattcarroll/Documents/sources/gitlab/civicplus/cp-mobile/**/*
[15:52:08] 
[15:52:08] Uploading JavaScript bundles
[15:52:20] Publish complete

[15:52:20] 📝  Manifest: https://exp.host/@oneblinkdevelopers/io-oneblink-cpmobile-blinkopolis/index.exp?release-channel=v15&sdkVersion=40.0.0 Learn more: https://expo.fyi/manifest-url
[15:52:20] ⚙️   Project page: https://expo.io/@oneblinkdevelopers/io-oneblink-cpmobile-blinkopolis?release-channel=v15 Learn more: https://expo.fyi/project-page

[15:52:20] Checking if this build already exists...

[15:52:22] Build started, it may take a few minutes to complete.
[15:52:22] You can check the queue length at https://expo.io/turtle-status

[15:52:22] You can monitor the build at

 https://expo.io/accounts/oneblinkdevelopers/builds/3078f73b-4a36-4d3c-a360-285279cf5360

[15:52:22] Waiting for build to complete.
You can press Ctrl+C to exit. It won\'t cancel the build, you\'ll be able to monitor it at the printed URL.
✖ Build failed.
[15:52:53] Standalone build failed!
```

After looking at expo dashboard, looks like the apple credentials were not uploaded at all, see screen shot below.

**Environment**

```
npx expo diagnostics

  Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.5.1 - /usr/local/bin/zsh
    Binaries:
      Node: 14.15.1 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.14.11 - ~/.npm-packages/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 30.0.2
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
    Expo Workflow: managed
```

**Please specify your device/emulator/simulator platform, model and version**

just running the build command, cant get to device...

**Error output**

`EXPO_DEBUG=true` did not add any extra logging.

**Reproducible demo or steps to reproduce from a blank project**

Not sure a snack is applicable here. Cannot run the build command on a Snack.

1. Create managed project with expo cli.
2. Run the publish command to get project in expo dashboard.
2. Run the commands above.

![image](https://user-images.githubusercontent.com/16235788/106991757-fc5dea00-67ca-11eb-8ac9-1931ac1449ae.png)

**Comment by marcotuliocnd** [comment]
same problem here

**Comment by mymattcarroll** [comment]
I just realised I did not explicitly state my expectations when running `expo build:ios` from CI.

I would like to be able to run the following command:

```
EXPO_APPLE_PASSWORD=supersecretpassword EXPO_IOS_DIST_P12_PASSWORD=supersecretpassword npx expo build:ios --apple-id email@example.com --team-id MYTEAMID --dist-p12-path ./certificate.p12 --push-id MYPUSHID --push-p8-path ./key.p8 --provisioning-profile-path ./app.mobileprovision --non-interactive --release-channel v15 --skip-credentials-check
```

And have my distribution p12 certificate, my provisioning profile file, and my push notifications p8 file all upserted (i.e. create if there is nothing there, and replace if there is something there) onto the expo servers. It seems at the moment, there is no way to upsert these files without going through the apple credentials validation process. Is this correct? If so, is it intentional? Should I be able to upsert my apple credentials without having them validated? In my opinion, yes. Is there a technical reason this cannot be done?

**Comment by mymattcarroll** [comment]
After having a look at the code for the `expo build:ios` command it seems that I have misunderstood the intent of `--skip-credentials-check`. I would like to propose a new flag called `--skip-credentials-validation`. Which would allow a developer to upload new credentials without them being validated. This would allow the command to be used in CI without needing to pass Apple credentials.

**Comment by mymattcarroll** [comment]
Turns out this feature already exists by just not passing the `--apple-id` flag. For anyone that lands here, this is the command we will be using going forward:

```
EXPO_IOS_DIST_P12_PASSWORD= supersecretpassword expo build:ios --team-id MYTEAMID --dist-p12-path ./certificate.p12 --push-id MYPUSHID --push-p8-path ./key.p8 --provisioning-profile-path ./app.mobileprovision --non-interactive --release-channel v15 --clear-credentials
```

**Comment by imhazige** [comment]
do you mean `skip-credentials-check`? I see it solve the build problem, but for upload, this will not work.

**Comment by mymattcarroll** [comment]
> do you mean `skip-credentials-check`?

If you pass the `--skip-credentials-check` flag, the `--dist-p12-path`, `--push-p8-path`, and `--provisioning-profile-path` flags are ignored, hence you need to leave that out to have your credentials upserted on every build. This is the desired result for us, as we have those files passed to the command from CI and we update them manually in App Store Connect when they expire. This may not be desired for your project/processes.

> I see it solve the build problem, but for upload, this will not work.

Correct.

This will only solve the problem for the `expo build:ios` command. As you can run a build without logging into an Apple account. You can not upload an `.ipa` file without an authenticated Apple session. Our team will be waiting for `eas submit` to be stable for Expo managed projects. Until then we are manually uploading `.ipa` files using the Transporter app.
