### ISSUE TITLE
Could not locate a valid AppDelegate at root: "/Users/..." ERROR when running `expo eject --npm`

### ISSUE THREAD

**Issue by williamdespard** [expo/expo-cli#3251]
I'm getting the following console error when running `expo eject --npm` with my expo managed project:

```
Could not locate a valid AppDelegate at root: "/Users/williamdespard/Desktop/app"
Please report this as an issue on https://github.com/expo/expo-cli/issues
UnexpectedError: Could not locate a valid AppDelegate at root: "/Users/williamdespard/Desktop/app"
Please report this as an issue on https://github.com/expo/expo-cli/issues
    at getAppDelegate (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:26:11)
    at Object.getSourceRoot (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:48:23)
    at Object.getProjectName (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/utils/Xcodeproj.ts:31:28)
    at getIosNamedProjectPath (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Icons.ts:173:23)
    at setIconsAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Icons.ts:108:31)
    at /usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Icons.ts:16:13
    at action (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/core-plugins.ts:118:29)
    at interceptingMod (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/core-plugins.ts:190:12)
    at action (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/compiler-plugins.ts:282:29)
    at interceptingMod (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/core-plugins.ts:190:12)
    at evalModsAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:75:32)
    at compileModsAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:17:10)
    at configureManagedProjectAsync (/usr/local/lib/node_modules/expo-cli/src/commands/apply/configureProjectAsync.ts:115:12)
    at prebuildAsync (/usr/local/lib/node_modules/expo-cli/src/commands/eject/Eject.ts:146:25)
    at Object.ejectAsync (/usr/local/lib/node_modules/expo-cli/src/commands/eject/Eject.ts:78:19)
    at actionAsync (/usr/local/lib/node_modules/expo-cli/src/commands/eject.ts:46:5)
```

**Comment by brentvatne** [comment]
1. what version of expo-cli?
2. can you share a reproducible example project, where we can run this command and see the same result?

**Comment by williamdespard** [comment]
1. Expo 4.1.6
2. I've given you read access to the project in question (https://github.com/Twnsquare/app)
3. Expo CLI 4.1.6 environment info:
    ```
System:
      OS: macOS 11.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 15.8.0 - /usr/local/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 7.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: bare
```

**Comment by brentvatne** [comment]
the problem is that you have an ios directory already, so we skip creating it when ejecting. also notice that having an ios directory makes expo-cli detect your project as bare workflow.

you can resolve your issue by deleting the ios directory and then running expo eject

**Comment by brentvatne** [comment]
```
╭─~/code/app ‹master›
╰─$ rm -rf ios
╭─~/code/app ‹master›
╰─$ gs
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    ios/.expo/README.md
	deleted:    ios/.expo/settings.json
	modified:   package-lock.json

no changes added to commit (use "git add" and/or "git commit -a")
╭─~/code/app ‹master›
╰─$ expo eject --npm
Warning! Your git working tree is dirty.
It's recommended to commit all your changes before proceeding, so you can revert the changes made by this command if necessary.

✔ Would you like to proceed? … yes

📝  Android package Learn more.

✔ What would you like your Android package name to be? … com.notbrent.app

📝  iOS Bundle Identifier Learn more.

✔ What would you like your iOS bundle identifier to be? … com.notbrent.app

✔ Created native projects
✔ Added Metro bundler configuration.
✔ Updated package.json and added index.js entry point for iOS and Android.
› Removed "main": "node_modules/expo/AppEntry.js" from package.json because we recommend using index.js as main instead.

📦 Using npm to install packages.
✔ Cleaned JavaScript dependencies.
✔ Installed JavaScript dependencies.
⠙ Config syncing
Using node to generate images. This is much slower than using native packages.
› Optionally you can stop the process and try again after successfully running `npm install -g sharp-cli`.

✔ Config synced

✔ Installed pods and initialized Xcode workspace.

⚠️  The app has 2 packages that require extra setup before building:
› expo-av: https://github.com/expo/expo/tree/master/packages/expo-av
› expo-file-system: https://github.com/expo/expo/tree/master/packages/expo-file-system

➡️  Next steps
› 💡 You may want to run npx @react-native-community/cli doctor to help install any tools that your app may need to run your native projects.
› 🔑 Download your Android keystore (if you're not sure if you need to, just run the command and see): expo fetch:android:keystore
› 📁 The property assetBundlePatterns does not have the same effect in the bare workflow.
  Learn more.

☑️  When you are ready to run your project
To compile and run your project in development, execute one of the following commands:
› npm run ios
› npm run android
› npm run web
```
