### ISSUE TITLE
When push notifications to Android, Error is "ProviderError: There was an unknown error with the FCM server. See this error's details for more information."

### ISSUE THREAD

**Issue by qax2333** [expo/expo-cli#3254]
Use expo-server-sdk-java to push notifications,  the error in  the Console is 
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot deserialize value of type `io.github.jav.exposerversdk.enums.TicketError` from String "ProviderError": value not one of declared Enum instance names: [DeviceNotRegistered]
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.github.jav.exposerversdk.ExpoPushTicket["details"]->io.github.jav.exposerversdk.ExpoPushTicket$Details["error"])
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)

Test in the expo official test site, the error is "ProviderError: There was an unknown error with the FCM server. See this error's details for more information."

Before  It worked once, But when I switch to other firebase project, The above error occurred.

**Comment by brentvatne** [comment]
hi there! it looks like there is already an issue for this error on expo-server-sdk-java: https://github.com/jav/expo-server-sdk-java/issues/31
