### ISSUE TITLE
create-react-native not working after ejecting project

### ISSUE THREAD

**Issue by sarveshcchauhan** [expo/expo-cli#326]
after ejecting 
npm run android 
is not woking displays error and stops

```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\my-app\node_modules\react-native\local-cli\cliEntr
y.js:11:41)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (D:\my-app\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (D:\my-app\node_modules\pirates\lib\index.js:88
:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

**Comment by Tassfighter** [comment]
did you install the expokit? see [(link)](https://github.com/expo/expo-cli/issues/321)

**Comment by AdamJNavarro** [comment]
Hey @sarveshcchauhan,

Can you try using the expo-cli and running expo start --android to see if it works properly?

Cheers,
Adam

**Comment by taboca** [comment]
I also had the same situation 

```
nvm use 8.6 
npm install -g expo-cli
expo init MyTestApp
cd MyTestApp
expo eject 
```

Then after the above problem, I gave it a try installing 

```
npm i @babel/runtime --save-dev 
``` 

And it worked a bit more however it failed because index.js is missing.

**Comment by sarveshcchauhan** [comment]
> Hey @sarveshcchauhan,
> 
> Can you try using the expo-cli and running expo start --android to see if it works properly?
> 
> Cheers,
> Adam
Have try using expo cli but it just works on expo and on expo app inside emulator but not directly on emulator

**Comment by sarveshcchauhan** [comment]
> I also had the same situation
> 
> ```
> nvm use 8.6 
> npm install -g expo-cli
> expo init MyTestApp
> cd MyTestApp
> expo eject 
> ```
> Then after the above problem, I gave it a try installing
> 
> ```
> npm i @babel/runtime --save-dev 
> ```
> And it worked a bit more however it failed because index.js is missing.
Followed Your steps as well as @Tassfighter  but after that It displays me following errors
check the image 
![aaaa](https://user-images.githubusercontent.com/18181752/52334642-318da100-2a26-11e9-9a5a-43e713d4d2ea.jpg)

**Comment by sarveshcchauhan** [comment]
I have used following cmd to create
```
npm install -g expo-cli
expo init AwesomeProject
cd AwesomeProject
expo eject
npm install
npm install --save-dev @babel/core @babel/runtime
npm i expo

```

after running this I get following errors
![rn](https://user-images.githubusercontent.com/18181752/52334848-c2647c80-2a26-11e9-8444-c1e4023caa25.jpg)

**Comment by Tassfighter** [comment]
@sarveshcchauhan you only installed expo `npm i expo` but not the expokit `npm i expokit`.

**Comment by sarveshcchauhan** [comment]
@Tassfighter  Please refer to the 2nd Comment I have tried your solution of installing expokit

**Comment by Tassfighter** [comment]
@sarveshcchauhan could you post your build output from Android Studio, pls.

**Comment by sarveshcchauhan** [comment]
@Tassfighter  Build was successfull but getting errors on Run look the below errors

`W/AsyncCondition: Could not find listener for key: openOptimisticExperienceActivity
                  Could not find listener for key: openExperienceActivity
D/SoLoader: init exiting
E/AppLoader: Error fetching cached manifest, falling back to default timeout: Could not load manifest. Are you sure this experience has been published?
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.mypackage, PID: 3780
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mypackage/host.exp.exponent.MainActivity}: java.lang.IllegalArgumentException: unexpected url: http:
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                   Caused by: java.lang.IllegalArgumentException: unexpected url: http:
                      at expolib_v1.okhttp3.Request$Builder.url(Request.java:142)
                      at host.exp.exponent.kernel.ExponentUrls.addExponentHeadersToUrl(ExponentUrls.java:45)
                      at host.exp.exponent.kernel.ExponentUrls.addExponentHeadersToManifestUrl(ExponentUrls.java:57)
                      at host.exp.exponent.ExponentManifest.fetchManifest(ExponentManifest.java:212)
                      at host.exp.exponent.ExponentManifest.fetchManifest(ExponentManifest.java:196)
                      at host.exp.exponent.AppLoader.fetchRemoteManifest(AppLoader.java:193)
                      at host.exp.exponent.AppLoader.startTimerAndFetchRemoteManifest(AppLoader.java:189)
                      at host.exp.exponent.AppLoader.startTimerAndFetchRemoteManifest(AppLoader.java:183)
                      at host.exp.exponent.AppLoader.access$800(AppLoader.java:20)
                      at host.exp.exponent.AppLoader$3.onError(AppLoader.java:160)
                      at host.exp.exponent.ExponentManifest.fetchCachedManifest(ExponentManifest.java:288)
                      at host.exp.exponent.AppLoader.start(AppLoader.java:91)
                      at host.exp.exponent.experience.DetachActivity.onCreate(DetachActivity.java:96)
                      at android.app.Activity.performCreate(Activity.java:6975)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                      at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6541) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
D/Exponent: Loaded exp.host status page.
E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
`
![android build](https://user-images.githubusercontent.com/18181752/52338158-9b5e7880-2a2f-11e9-86b4-aa7549e07f09.jpg)

**Comment by Tassfighter** [comment]
I'll guess you found your problem: 

> FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE

Is your local `google-service.json` synced with your Firebase project?

**Comment by sarveshcchauhan** [comment]
Have created a fresh project why should I use firebase configuration

**Comment by sarveshcchauhan** [comment]
Well thanks everyone found out the solution 
Check [https://github.com/taboca/working-example-react-native-ejected-jest-appium-e2e](url)
Follow only the Part 1 
Everything is now working  
Thanks @taboca
