### ISSUE TITLE
Eject failed when app.json name in Chinese. (Could not locate a valid AppDelegate at root)

### ISSUE THREAD

**Issue by CacaoRick** [expo/expo-cli#3260]
**Summary**

Eject failed with Error: `Could not locate a valid AppDelegate at root.`
When `app.json`'s name field use Chinese word.

(Project not include ios and android folder before eject run.)

**Environment**
```
  Expo CLI 4.2.1 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.8.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /opt/homebrew/bin/yarn
      npm: 7.5.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.2.1
    Expo Workflow: bare
```

**Please specify your device/emulator/simulator platform, model and version**

`Mac mini (M1, 2020)`

**Error output**
```
❯ yarn eject
yarn run v1.22.10
$ expo eject
Your git working tree is clean
To revert the changes after this command completes, you can run the following:
  git clean --force && git reset --hard

📝  Android package Learn more.

✔ What would you like your Android package name to be? … com.dimorderapp.nametest

📝  iOS Bundle Identifier Learn more.

✔ What would you like your iOS bundle identifier to be? … com.dimorderapp.nametest

✔ Created native projects
✔ Added Metro bundler configuration.
✔ Updated package.json and added index.js entry point for iOS and Android.
› Removed "main": "node_modules/expo/AppEntry.js" from package.json because we recommend using index.js as main instead.

🧶 Using Yarn to install packages. Pass --npm to use npm instead.
✔ Cleaned JavaScript dependencies.
✔ Installed JavaScript dependencies.
⠋ Config syncing
Using node to generate images. This is much slower than using native packages.
› Optionally you can stop the process and try again after successfully running `npm install -g sharp-cli`.

Could not locate a valid AppDelegate at root: "/Users/rick/projects/nametest"
Please report this as an issue on https://github.com/expo/expo-cli/issues
UnexpectedError: Could not locate a valid AppDelegate at root: "/Users/rick/projects/nametest"
Please report this as an issue on https://github.com/expo/expo-cli/issues
    at getAppDelegate (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:26:11)
    at Object.getSourceRoot (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:48:23)
    at Object.getProjectName (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/utils/Xcodeproj.ts:31:28)
    at getIosNamedProjectPath (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Icons.ts:173:23)
    at setIconsAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Icons.ts:108:31)
    at /usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Icons.ts:16:13
    at action (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/core-plugins.ts:118:29)
    at interceptingMod (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/core-plugins.ts:190:12)
    at action (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/compiler-plugins.ts:282:29)
    at interceptingMod (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/core-plugins.ts:190:12)
    at evalModsAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:75:32)
    at compileModsAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:17:10)
    at configureManagedProjectAsync (/usr/local/lib/node_modules/expo-cli/src/commands/eject/configureProjectAsync.ts:117:12)
    at prebuildAsync (/usr/local/lib/node_modules/expo-cli/src/commands/eject/prebuildAsync.ts:83:25)
    at ejectAsync (/usr/local/lib/node_modules/expo-cli/src/commands/eject/ejectAsync.ts:23:19)
    at actionAsync (/usr/local/lib/node_modules/expo-cli/src/commands/eject.ts:47:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Reproducible demo or steps to reproduce from a blank project**

When not edit app.json's name, eject is work find:
```
expo init app
cd app
yarn eject
```

But using Chinese name in app.json eject will failed:
```
expo init nametest
cd nametest

# Edit app.json name to some Chinese. (I use: "測試")

yarn eject
```

**Comment by CacaoRick** [comment]
Relative: #3116 #2932

**Comment by brentvatne** [comment]
thanks for reporting, we'll take care of this soon

**Comment by EvanBacon** [comment]
fixed in https://github.com/expo/expo-cli/pull/3758
