### ISSUE TITLE
BUG | @expo/next-adapter@2.1.62 error with the new resolve-from dependency

### ISSUE THREAD

**Issue by louisgv** [expo/expo-cli#3283]
### Summary

I just updated @expo/next-adapter to the latest version and it broke `next dev`. My next project is under a hoisted lerna project, but I doubt that was the reason as it was working with previous version.

### Environment

node 14.15.0

### Please specify your device/emulator/simulator platform, model and version

Windows, Chrome

### Error output

TypeError: resolve_from_1.default.silent is not a function
    at Object.getAliases (P:\Projects\--\node_modules\@expo\webpack-config\webpack\env\alias.js:21:32)
    at Object.withUnimodules (P:\Projects\--\node_modules\@expo\webpack-config\webpack\addons\withUnimodules.js:28:62)
    at Object.webpack (P:\Projects\
--\node_modules\@expo\next-adapter\build\withExpo.js:9:41)
    at getBaseWebpackConfig (P:\Projects\--\node_modules\next\dist\build\webpack-config.js:139:416)
    at async Promise.all (index 0)
    at async HotReloader.start (P:\Projects\--\node_modules\next\dist\server\hot-reloader.js:14:1997)
    at async DevServer.prepare (P:\Projects\--\node_modules\next\dist\server\next-dev-server.js:15:414)
    at async P:\Projects\--\node_modules\next\dist\cli\next-dev.js:22:1

### Reproducible demo or steps to reproduce from a blank project

+ Setup lerna (4.0): https://github.com/lerna/lerna
+ Setup a nextjs project as a module
+ Follow the manual step of https://docs.expo.io/guides/using-nextjs/ to enable expo
+ Use `lerna bootstrap --hoist`
+ `next dev` throws the error above

After further investigation on what's changed, I found that in the latest version of @expo/next-adapter, a new dependency was introduced to resolve module: `resolve-from`:

https://github.com/expo/expo-cli/pull/3141

And `resolve-from` has the `.silent` method:

https://www.npmjs.com/package/resolve-from

Which I think might be the cause of this bug.

**Comment by EvanBacon** [comment]
Would you be open to starting a PR with your findings?

**Comment by louisgv** [comment]
@EvanBacon Will do over the weekends

**Comment by louisgv** [comment]
The solution I found for lerna was to hoist all but @expo:

`lerna bootstrap --hoist --nohoist=@expo/*`

And it works 👍
