### ISSUE TITLE
No cert available to make provision profile against, Make sure you were able to make a certificate prior to this step

### ISSUE THREAD

**Issue by simsketch** [expo/expo-cli#329]
## Description

I am unable to compile an ipa in order to resubmit my app.

## Expected Behavior

`expo ios:build`, with a number of different combinations (`-c` flag, etc.)

## Observed Behavior

`Error: Reason: No cert available to make provision profile against, raw: "Make sure you were able to make a certificate prior to this step"`

```
IMGBASE-2015-01:greenlight bocaops$ expo build:ios
[12:08:19] Checking if there is build in progress...

[12:08:19] If you get errors about

'Maximum number of certificates generated' or 'duplicate profiles'

then consider using the flags --revoke-apple-dist-certs, --revoke-apple-push-certs,
and --revoke-apple-provisioning-profile or go to developer.apple.com
and revoke those credentials manually

? How would you like to upload your credentials?
 Expo handles all credentials, you can still provide overrides

We need your Apple ID/password to manage certificates and
provisioning profiles from your Apple Developer account.

Note: Expo does not keep your Apple ID or your Apple password.

? What's your Apple ID? simsketch@yahoo.com
? Password? [hidden]
[12:08:27] Validating Credentials...
[12:08:29] Only 1 team associated with your account, using Team ID: 8836WUYZD5
? Will you provide your own Distribution Certificate? Let Expo handle the process
? Will you provide your own Push Certificate? Let Expo handle the process
? Would you like to reuse Distribution Certificate from another app? Used in apps: @simsketch/gl (Serial number: 1A518956591D38B9, Certificate ID: U7ZGCAB
7U5)
[12:08:43] Error while gathering & validating credentials
[12:08:43] Error: Reason: No cert available to make provision profile against, raw: "Make sure you were able to make a certificate prior to this step"
[12:08:43] Reason: No cert available to make provision profile against, raw: "Make sure you were able to make a certificate prior to this step"
[12:08:43] Error: Reason: No cert available to make provision profile against, raw: "Make sure you were able to make a certificate prior to this step"
    at IOSBuilder._throwIfFailureWithReasonDump (/expo-cli@2.7.0/src/commands/build/IOSBuilder.js:679:13)
    at IOSBuilder._callee6$ (/expo-cli@2.7.0/src/commands/build/IOSBuilder.js:357:10)
    at tryCatch (/usr/local/lib/node_modules/expo-cli/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/expo-cli/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/expo-cli/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/lib/node_modules/expo-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/expo-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
IMGBASE-2015-01:greenlight bocaops$
```

## Environment

```
IMGBASE-2015-01:greenlight bocaops$ expo diagnostics

  Expo CLI 2.7.0 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.8.0 - /usr/local/bin/node
      Yarn: 1.2.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10L213o - /usr/bin/xcodebuild
    npmPackages:
      expo: 29.0.0 => 29.0.0
      react: 16.3.1 => 16.3.1
      react-native: https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz => 0.55.4
      react-navigation: ^2.9.3 => 2.11.2
    npmGlobalPackages:
      expo-cli: 2.7.0
```

I've tried deleting and regenerating certs and profiles, but I am concerned if I delete the wrong thing, that I won't be able to republish my app...but if I have my private key in my keychain, that should be all i need to recreate a certificate signing request, p12 file, provisioning profile, etc.? If starting from scratch will still allow me to update my currently live app, i'm happy to do that...any guidance is greatly appreciated.

If only I had left the `fallbackToCacheTimeout` at 30, I might not ever have to worry about republishing...oh well!

**Comment by simsketch** [comment]
I haven't been able to find anyone with this specific error, in either Expo Forum or Github Issues. I've had this problem for months and thought maybe an expo update would resolve it but I've run out of time and I need to come up with any solution.

**Comment by simsketch** [comment]
I have certificates in my account, not sure if I should try deleting them all and starting over.

![image](https://user-images.githubusercontent.com/3129129/51790769-70d70a80-2167-11e9-9c73-266c6221fe01.png)

**Comment by simsketch** [comment]
I was able to get the ipa to compile. My mistake was in attempting to reuse my Distribution certificate in this line:

```
[12:33:40] Revoked 1 existing certs on developer.apple.com
? Will you provide your own Distribution Certificate? Let Expo handle the process
? Will you provide your own Push Certificate? Let Expo handle the process
? Would you like to reuse Distribution Certificate from another app? Used in apps: @simsketch/gl (Serial number: 1A518956591D38B9, Certificate ID: U7ZGCAB
7U5)
```

and once i said, no create a new one, it compiled!
