### ISSUE TITLE
Cannot eject from app to ExpoKit: UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by moritz-tk** [expo/expo-cli#336]
I cannot eject from the app. 
```
How would you like to eject your app?
  Read more: https://docs.expo.io/versions/latest/expokit/eject ExpoKit
Skipping iOS because you are not running macOS.
(node:27955) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_isCommandError' of null
    at Command._callee$ (/expo-cli@2.7.0/src/exp.js:76:15)
    at tryCatch (/home/work/.nvm/versions/node/v10.15.0/lib/node_modules/expo-cli/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/work/.nvm/versions/node/v10.15.0/lib/node_modules/expo-cli/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as throw] (/home/work/.nvm/versions/node/v10.15.0/lib/node_modules/expo-cli/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/home/work/.nvm/versions/node/v10.15.0/lib/node_modules/expo-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/work/.nvm/versions/node/v10.15.0/lib/node_modules/expo-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:27955) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27955) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
expo-cli: 2.7.0
node: 10.15.0
npm: 6.4.1
OS: Fedora 29

**Comment by AdamJNavarro** [comment]
Hey @moritz-tk,

We are aware of this issue and we'll keep you updated when we know more.

Cheers,

Adam
