### ISSUE TITLE
Using yarn@1.22.x maybe causes error while bundling

### ISSUE THREAD

**Issue by Slapbox** [expo/expo-cli#3419]
We recently upgraded from `yarn@1.21.1` to `1.22.10` and we're seeing this cryptic error when running `expo start`.

```
Building JavaScript bundle [========================================================        ] 88%Error: ENOENT: no such file or directory, open 'fs.js'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at formatBundlingError (C:\projects\myApp\node_modules\metro\src\lib\formatBundlingError.js:93:10)
    at Server.<anonymous> (C:\projects\myApp\node_modules\metro\src\Server.js:907:36)
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (C:\projects\myApp\node_modules\metro\src\Server.js:99:24)
    at _throw (C:\projects\myApp\node_modules\metro\src\Server.js:122:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

A full reinstall of `node_modules` from scratch didn't help, nor did `expo start -c`. It's at that point I remembered we'd upgraded yarn and tried downgrading and it worked. After that I've tried re-running `yarn` with the `1.22.x` branch and it seems to work fine, but I do think that the change in Yarn version was to blame as I ruled out everything else I could think of.

**Comment by brentvatne** [comment]
could be a yarn bug? not sure what we can do here

**Comment by brentvatne** [comment]
fwiw i use yarn 1.22.10 and have for a long time and don't have this problem, so it may be some unrelated change

**Comment by Slapbox** [comment]
> fwiw i use yarn 1.22.10

With that in mind, closing this unless I find further reason to believe that it's the cause. Dependency management is such a tangled topic even after all these years of improvements. Thanks for your replies @brentvatne!
