### ISSUE TITLE
Cannot read property 'test' of undefined TypeError: Cannot read property 'test' of undefined

### ISSUE THREAD

**Issue by alexandrius** [expo/expo-cli#3424]
Getting error below every time something's wrong I get error in the code or transformer fail because of error

```
TransformError SyntaxError: /Users/alexanderpataridze/Documents/Development/Toptal/stillwhite-app/src/screens/authorized/profile/editProfile.js: Unexpected token, expected "," (9:3)

   7 |    ExpandedTextInput,
   8 |    Loader
>  9 |    ShoulderTouchable,
     |    ^
  10 | } from 'components';
  11 | import dayjs from 'dayjs';
  12 | import { LinearGradient } from 'expo-linear-gradient';
Error getting device logs: TypeError: Cannot read property 'test' of undefined TypeError: Cannot read property 'test' of undefined
    at logStackTrace (/Users/alexanderpataridze/.config/yarn/global/node_modules/expo-cli/src/exp.ts:567:25)
    at logWithLevel (/Users/alexanderpataridze/.config/yarn/global/node_modules/expo-cli/src/exp.ts:606:11)
    at Object.write (/Users/alexanderpataridze/.config/yarn/global/node_modules/expo-cli/src/exp.ts:672:13)
    at Logger._emit (/Users/alexanderpataridze/.config/yarn/global/node_modules/@expo/bunyan/lib/bunyan.js:928:22)
    at Logger.error (/Users/alexanderpataridze/.config/yarn/global/node_modules/@expo/bunyan/lib/bunyan.js:1053:24)
    at handleDeviceLogs (/Users/alexanderpataridze/.config/yarn/global/node_modules/xdl/node_modules/@expo/dev-server/src/middleware/clientLogsMiddleware.ts:81:21)
    at /Users/alexanderpataridze/.config/yarn/global/node_modules/xdl/node_modules/@expo/dev-server/src/middleware/clientLogsMiddleware.ts:28:7
    at call (/Users/alexanderpataridze/.config/yarn/global/node_modules/connect/index.js:239:7)
    at next (/Users/alexanderpataridze/.config/yarn/global/node_modules/connect/index.js:183:5)
    at /Users/alexanderpataridze/.config/yarn/global/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/Users/alexanderpataridze/.config/yarn/global/node_modules/body-parser/node_modules/raw-body/index.js:224:16)
    at done (/Users/alexanderpataridze/.config/yarn/global/node_modules/body-parser/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/Users/alexanderpataridze/.config/yarn/global/node_modules/body-parser/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by alexandrius** [comment]
Have an error of having same key in the list. Get "Cannot read property 'test' of undefined TypeError: Cannot read property 'test' of undefined". Basically any error log causes `Cannot read property 'test'`
```
Warning: Encountered two children with the same key, `6`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
Error getting device logs: TypeError: Cannot read property 'test' of undefined TypeError: Cannot read property 'test' of undefined
    at logStackTrace (/Users/alexanderpataridze/.config/yarn/global/node_modules/expo-cli/src/exp.ts:567:25)
    at logWithLevel (/Users/alexanderpataridze/.config/yarn/global/node_modules/expo-cli/src/exp.ts:606:11)
    at Object.write (/Users/alexanderpataridze/.config/yarn/global/node_modules/expo-cli/src/exp.ts:672:13)
    at Logger._emit (/Users/alexanderpataridze/.config/yarn/global/node_modules/@expo/bunyan/lib/bunyan.js:928:22)
    at Logger.error (/Users/alexanderpataridze/.config/yarn/global/node_modules/@expo/bunyan/lib/bunyan.js:1053:24)
    at handleDeviceLogs (/Users/alexanderpataridze/.config/yarn/global/node_modules/xdl/node_modules/@expo/dev-server/src/middleware/clientLogsMiddleware.ts:81:21)
    at /Users/alexanderpataridze/.config/yarn/global/node_modules/xdl/node_modules/@expo/dev-server/src/middleware/clientLogsMiddleware.ts:28:7
    at call (/Users/alexanderpataridze/.config/yarn/global/node_modules/connect/index.js:239:7)
    at next (/Users/alexanderpataridze/.config/yarn/global/node_modules/connect/index.js:183:5)
    at /Users/alexanderpataridze/.config/yarn/global/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/Users/alexanderpataridze/.config/yarn/global/node_modules/body-parser/node_modules/raw-body/index.js:224:16)
    at done (/Users/alexanderpataridze/.config/yarn/global/node_modules/body-parser/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/Users/alexanderpataridze/.config/yarn/global/node_modules/body-parser/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
TypeError: Cannot read property 'test' of undefined
    at logStackTrace (/Users/alexanderpataridze/.config/yarn/global/node_modules/expo-cli/src/exp.ts:567:25)
    at logWithLevel (/Users/alexanderpataridze/.config/yarn/global/node_modules/expo-cli/src/exp.ts:606:11)
    at Object.write (/Users/alexanderpataridze/.config/yarn/global/node_modules/expo-cli/src/exp.ts:672:13)
    at Logger._emit (/Users/alexanderpataridze/.config/yarn/global/node_modules/@expo/bunyan/lib/bunyan.js:928:22)
    at Logger.error (/Users/alexanderpataridze/.config/yarn/global/node_modules/@expo/bunyan/lib/bunyan.js:1053:24)
    at handleDeviceLogs (/Users/alexanderpataridze/.config/yarn/global/node_modules/xdl/node_modules/@expo/dev-server/src/middleware/clientLogsMiddleware.ts:81:21)
    at /Users/alexanderpataridze/.config/yarn/global/node_modules/xdl/node_modules/@expo/dev-server/src/middleware/clientLogsMiddleware.ts:28:7
    at call (/Users/alexanderpataridze/.config/yarn/global/node_modules/connect/index.js:239:7)
    at next (/Users/alexanderpataridze/.config/yarn/global/node_modules/connect/index.js:183:5)
    at /Users/alexanderpataridze/.config/yarn/global/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/Users/alexanderpataridze/.config/yarn/global/node_modules/body-parser/node_modules/raw-body/index.js:224:16)
    at done (/Users/alexanderpataridze/.config/yarn/global/node_modules/body-parser/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/Users/alexanderpataridze/.config/yarn/global/node_modules/body-parser/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    
```

**Comment by alexandrius** [comment]
`/Users/alexanderpataridze/.config/yarn/global/node_modules/expo-cli/src/exp.ts`
doesn't exist which is weird.

**Comment by EvanBacon** [comment]
Maybe try installing with `npm i -g expo-cli` instead of yarn

**Comment by alexandrius** [comment]
@EvanBacon You are absolutely right! Haven't used npm in a while

**Comment by maniac-tech** [comment]
I am facing a similar issue:

```
Error getting device logs: TypeError: Cannot read property 'test' of undefined TypeError: Cannot read property 'test' of undefined
    at logStackTrace (/Users/abhishekjain/Abhishek/development/wallet-native/node_modules/expo-cli/src/exp.ts:568:25)
    at logWithLevel (/Users/abhishekjain/Abhishek/development/wallet-native/node_modules/expo-cli/src/exp.ts:601:11)
    at Object.write (/Users/abhishekjain/Abhishek/development/wallet-native/node_modules/expo-cli/src/exp.ts:673:13)
    at Logger._emit (/Users/abhishekjain/Abhishek/development/wallet-native/node_modules/@expo/bunyan/lib/bunyan.js:928:22)
    at Logger.warn (/Users/abhishekjain/Abhishek/development/wallet-native/node_modules/@expo/bunyan/lib/bunyan.js:1053:24)
    at handleDeviceLogs (/Users/abhishekjain/Abhishek/development/wallet-native/node_modules/@expo/dev-server/src/middleware/clientLogsMiddleware.ts:81:21)
    at /Users/abhishekjain/Abhishek/development/wallet-native/node_modules/@expo/dev-server/src/middleware/clientLogsMiddleware.ts:28:7
    at call (/Users/abhishekjain/Abhishek/development/wallet-native/node_modules/connect/index.js:239:7)
    at next (/Users/abhishekjain/Abhishek/development/wallet-native/node_modules/connect/index.js:183:5)
    at /Users/abhishekjain/Abhishek/development/wallet-native/node_modules/@expo/dev-server/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/Users/abhishekjain/Abhishek/development/wallet-native/node_modules/@expo/dev-server/node_modules/raw-body/index.js:224:16)
    at done (/Users/abhishekjain/Abhishek/development/wallet-native/node_modules/@expo/dev-server/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/Users/abhishekjain/Abhishek/development/wallet-native/node_modules/@expo/dev-server/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

@EvanBacon  I tried `npm i -g expo-cli` but to no luck.

**Comment by SumantaBee** [comment]
yarn version of expo stopped working recently. Use the npm one instead. and use yarn for dependencies

**Comment by lock9** [comment]
I have the same issue and installing expo with npm didn't solve the issue. My log is full of this error.

**Comment by EvanBacon** [comment]
Ensure you don't have expo-cli installed locally in the project and run `yarn global remove expo-cli` to remove it from yarn if you previously installed it globally with yarn.
