### ISSUE TITLE
Can't login because of "undefined" value for header "Exponent-Client"

### ISSUE THREAD

**Issue by weidtn** [expo/expo-cli#3462]
When trying to `expo login` and inserting my credentials, I get the following Error after entering the password:

```
[11:22:57] Invalid value "undefined" for header "Exponent-Client"
[11:22:57] TypeError [ERR_HTTP_INVALID_HEADER_VALUE] [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Exponent-Client"
    at ClientRequest.setHeader (node:_http_outgoing:566:3)
    at new ClientRequest (node:_http_client:251:14)
    at Object.request (node:https:313:10)
    at RedirectableRequest._performRequest (/usr/lib/node_modules/expo-cli/node_modules/follow-redirects/index.js:269:24)
    at new RedirectableRequest (/usr/lib/node_modules/expo-cli/node_modules/follow-redirects/index.js:61:8)
    at Object.request (/usr/lib/node_modules/expo-cli/node_modules/follow-redirects/index.js:460:14)
    at dispatchHttpRequest (/usr/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:195:25)
    at new Promise (<anonymous>)
    at httpAdapter (/usr/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:46:10)
    at dispatchRequest (/usr/lib/node_modules/expo-cli/node_modules/axios/lib/core/dispatchRequest.js:52:10)
    at ApiV2Client._requestAsync (/usr/lib/node_modules/expo-cli/node_modules/xdl/src/ApiV2.ts:232:18)
```

`expo diagnostics`:

```
  Expo CLI undefined environment info:
    System:
      OS: Linux 5.12 Manjaro Linux
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 15.0.1 - ~/.nvm/versions/node/v15.0.1/bin/node
      Yarn: 1.22.10 - /usr/bin/yarn
      npm: 7.0.3 - ~/.nvm/versions/node/v15.0.1/bin/npm
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed
```

**Comment by brentvatne** [comment]
what version of expo-cli are you using?

**Comment by weidtn** [comment]
I have a fresh install of version 4.4.3-1 from [AUR.](https://aur.archlinux.org/packages/expo-cli/)

**Comment by weidtn** [comment]
When installing with `npm`it works.
