### ISSUE TITLE
Error when ejecting: "Could not locate a valid AppDelegate at root: "/Volumes/Storage/space/printio/mobile_app""

### ISSUE THREAD

**Issue by alexander3um** [expo/expo-cli#3463]
### Desctiption

My issue is very similar to this one https://github.com/expo/expo-cli/issues/2932 except removing ios and android folders doesn't help. I also tried removing .expo folder, removing node_modules and installing the dependencies again, but it wouldn't help either.

I'm doing that with --npm, but ejecting with yarn seems to throw the same error.

```
✔ Created native projects
✔ Added Metro config.
✔ Updated package.json and added index.js entry point for iOS and Android.
› Removed "main": "node_modules/expo/AppEntry.js" from package.json because we recommend using index.js as main instead.

📦 Using npm to install packages.
✔ Cleaned JavaScript dependencies.
✔ Installed JavaScript dependencies.
Could not locate a valid AppDelegate at root: "/Volumes/Storage/space/printio/mobile_app"
Please report this as an issue on https://github.com/expo/expo-cli/issues
UnexpectedError: Could not locate a valid AppDelegate at root: "/Volumes/Storage/space/printio/mobile_app"
Please report this as an issue on https://github.com/expo/expo-cli/issues
    at getAppDelegate (/Users/3um/.nvm/versions/node/v14.16.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:26:11)
    at Object.getSourceRoot (/Users/3um/.nvm/versions/node/v14.16.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:48:23)
    at Object.getProjectName (/Users/3um/.nvm/versions/node/v14.16.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/utils/Xcodeproj.ts:32:28)
    at getIosNamedProjectPath (/Users/3um/.nvm/versions/node/v14.16.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Icons.ts:173:23)
    at setIconsAsync (/Users/3um/.nvm/versions/node/v14.16.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Icons.ts:108:31)
    at /Users/3um/.nvm/versions/node/v14.16.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Icons.ts:16:13
    at action (/Users/3um/.nvm/versions/node/v14.16.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/core-plugins.ts:118:29)
    at interceptingMod (/Users/3um/.nvm/versions/node/v14.16.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/core-plugins.ts:190:12)
    at action (/Users/3um/.nvm/versions/node/v14.16.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/compiler-plugins.ts:317:29)
    at interceptingMod (/Users/3um/.nvm/versions/node/v14.16.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/core-plugins.ts:190:12)
    at evalModsAsync (/Users/3um/.nvm/versions/node/v14.16.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:75:32)
    at compileModsAsync (/Users/3um/.nvm/versions/node/v14.16.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:17:10)
    at configureManagedProjectAsync (/Users/3um/.nvm/versions/node/v14.16.0/lib/node_modules/expo-cli/src/commands/eject/configureProjectAsync.ts:166:12)
    at prebuildAsync (/Users/3um/.nvm/versions/node/v14.16.0/lib/node_modules/expo-cli/src/commands/eject/prebuildAsync.ts:89:25)
    at ejectAsync (/Users/3um/.nvm/versions/node/v14.16.0/lib/node_modules/expo-cli/src/commands/eject/ejectAsync.ts:23:19)
    at actionAsync (/Users/3um/.nvm/versions/node/v14.16.0/lib/node_modules/expo-cli/src/commands/eject.ts:47:5)
    at Command.<anonymous> (/Users/3um/.nvm/versions/node/v14.16.0/lib/node_modules/expo-cli/src/exp.ts:350:7)
```

### expo diagnostics

I ran diagnostics after ejecting.

```
  Expo CLI 4.4.3 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.0/bin/yarn
      npm: 7.6.3 - ~/.nvm/versions/node/v14.16.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: bare
```

**Comment by alexander3um** [comment]
Should have been more attentive, the name field in app.json was in Cyrillic which makes it the same issue as this one https://github.com/expo/expo-cli/issues/3260
