### ISSUE TITLE
Unexpected token ... after running expo init AwesomeProject

### ISSUE THREAD

**Issue by thehme** [expo/expo-cli#347]
## Description

Getting `Unexpected token ...` when starting a new project, regardless of the options combinations I choose.

## Expected Behavior

Be able to create a new React Native project called "AwesomeProject".

## Observed Behavior

Did the following:

`npm install -g expo-cli`
`expo init AwesomeProject`

Picking blank + managed/advanced or tabs + managed/advanced options outputs the following error:

```
[21:59:30] Unexpected token ...
[21:59:30] Set EXPO_DEBUG=true in your env to view the stack trace.
```

Upon enabling debug mode, the error is further detailed as:

```
[22:21:27] Unexpected token ...
[22:21:27] /usr/local/lib/node_modules/expo-cli/node_modules/enquirer/index.js:24
    this.answers = { ...answers };
                     ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at _load_enquirer (/expo-cli@2.7.1/src/commands/init.js:4:1)
```

## Environment

Folder `AwesomeProject` is never created. No phone specs at this time. However, my computer specs are:

- MacOS Mojave 10.14.2
- node v8.2.1

## Reproducible Demo

To reproduce the problem, simply attempt to create a project.

`npm install -g expo-cli`
`expo init AwesomeProject`

**Comment by swang** [comment]
You need to install a version above v8.6*. The spread operator did not exist in node until then.

**Comment by thehme** [comment]
thanks @swang this ins't clear in the first page of the docs for some reason 

https://facebook.github.io/react-native/docs/getting-started.html
