### ISSUE TITLE
Exception with debug remote enabled: TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by colinux** [expo/expo-cli#3473]
I'm getting an error when expo-cli is trying to format a stack when debug remote is enabled.

```
Error getting device logs: TypeError: Cannot read property 'replace' of undefined TypeError: Cannot read property 'replace' of undefined
    at matchFileNameOrURLFromStackTrace (/Users/colin/.config/yarn/global/node_modules/expo-cli/src/utils/matchFileNameOrURLFromStackTrace.ts:16:42)
    at logStackTrace (/Users/colin/.config/yarn/global/node_modules/expo-cli/src/exp.ts:564:31)
    at logWithLevel (/Users/colin/.config/yarn/global/node_modules/expo-cli/src/exp.ts:600:11)
    at Object.write (/Users/colin/.config/yarn/global/node_modules/expo-cli/src/exp.ts:672:13)
    at Logger._emit (/Users/colin/.config/yarn/global/node_modules/@expo/bunyan/lib/bunyan.js:928:22)
    at Logger.warn (/Users/colin/.config/yarn/global/node_modules/@expo/bunyan/lib/bunyan.js:1053:24)
    at handleDeviceLogs (/Users/colin/.config/yarn/global/node_modules/@expo/dev-server/src/middleware/clientLogsMiddleware.ts:81:21)
    at /Users/colin/.config/yarn/global/node_modules/@expo/dev-server/src/middleware/clientLogsMiddleware.ts:28:7
    at call (/Users/colin/.config/yarn/global/node_modules/connect/index.js:239:7)
    at next (/Users/colin/.config/yarn/global/node_modules/connect/index.js:183:5)
    at /Users/colin/.config/yarn/global/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/Users/colin/.config/yarn/global/node_modules/raw-body/index.js:224:16)
    at done (/Users/colin/.config/yarn/global/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/Users/colin/.config/yarn/global/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

I've found the faulting line in my trace is 
`http://localhost:19000/debugger-ui/debuggerWorker.aca173c4.js:4:901 in parcelRequire<.sYUN</onmessage</<`
which doesn't contain any `?`, so it's failing here : https://github.com/expo/expo-cli/blob/292a5e96172efb96879c485914d4bec71eea07b6/packages/expo-cli/src/utils/matchFileNameOrURLFromStackTrace.ts#L14-L16

My code run with Expo 40

**Comment by nightness** [comment]
Expo 41 too

**Comment by brentvatne** [comment]
can you share a minimal reproducible example project?

**Comment by Macht59** [comment]
@EvanBacon, is the fix going to be merged into some future releases?
