### ISSUE TITLE
request to https://registry.npmjs.org/expo-template-blank-typescript failed, reason: unable to verify the first certificate

### ISSUE THREAD

**Issue by cracktechnicalinterview** [expo/expo-cli#3526]
request to https://registry.npmjs.org/expo-template-blank failed, reason: unable to verify the first certificate
FetchError: request to https://registry.npmjs.org/expo-template-blank failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/expo-cli/node_modules/minipass-fetch/lib/index.js:97:14)
    at ClientRequest.emit (events.js:376:20)
    at ClientRequest.emit (domain.js:470:12)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:376:20)
    at TLSSocket.emit (domain.js:470:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

**Comment by byCedric** [comment]
Hi @cracktechnicalinterview, see this response: https://github.com/expo/expo/issues/13102#issuecomment-851385662
