### ISSUE TITLE
build:ios TypeError: Cannot read property of undefined

### ISSUE THREAD

**Issue by Zas82** [expo/expo-cli#3529]
Anyone else running into this issue when trying to 'expo build:ios'?

Starting Metro Bundler
TypeError: Cannot read property 'length' of undefined
    at ..\node_modules\metro\src\Assets.js:295:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (..\node_modules\metro\src\Assets.js:52:24)
    at _next (..\node_modules\metro\src\Assets.js:72:9)
    at ..\node_modules\metro\src\Assets.js:77:7
    at new Promise (<anonymous>)
    at ..\node_modules\metro\src\Assets.js:69:12
    at _applyAssetDataPlugins (..\node_modules\metro\src\Assets.js:308:33)
    at applyAssetDataPlugins (..\node_modules\metro\src\Assets.js:284:33)

Could use suggestions.
Running expo 4.5.0

**Comment by byCedric** [comment]
Hi @Zas82, could you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? Without that, we can't help you debug this issue.

**Comment by EvanBacon** [comment]
I believe the issue to be this one https://github.com/expo/expo-cli/pull/3923 which means the fix is merged.
