### ISSUE TITLE
Expo Bare Workflow Enable Debug - App Crash

### ISSUE THREAD

**Issue by sathishk2030** [expo/expo-cli#3548]
In bare workflow project, when enabling debug in phone/simulator using ctrl + m, the App crashing in android.

Steps to reproduce:

1. Create new project using (expo init sampleproject) and select typescript minimal under bare workflow (last option),
2.  Run yarn android and Press ctrl + m in app and select debug in the menu
3. App crashes

[https://forums.expo.io/t/bare-workflow-enable-debug-js-app-crash/53221](https://forums.expo.io/t/bare-workflow-enable-debug-js-app-crash/53221)

[https://stackoverflow.com/questions/67846851/expo-bare-workflow-enable-debug-app-crash](https://stackoverflow.com/questions/67846851/expo-bare-workflow-enable-debug-app-crash)

{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "expo": "~41.0.1",
    "expo-updates": "~0.5.4",
    "expo-splash-screen": "~0.10.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.4",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-reanimated": "~2.1.0",
    "react-native-screens": "~3.0.0",
    "react-native-unimodules": "~0.13.3",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.63.2",
    "babel-preset-expo": "~8.3.0",
    "jest-expo": "~41.0.0",
    "typescript": "~4.0.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}

No changes made to any file in the project.

**Comment by EvanBacon** [comment]
I can repro this, the error message is:
```log
    --------- beginning of crash
2021-06-15 16:32:41.729 14792-14911/com.bacon.yolo31 E/AndroidRuntime: FATAL EXCEPTION: mqt_js
    Process: com.bacon.yolo31, PID: 14792
    java.lang.AssertionError: No source URL loaded, have you initialised the instance?
        at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:35)
        at com.facebook.react.modules.debug.SourceCodeModule.getTypedExportedConstants(SourceCodeModule.java:39)
        at com.facebook.fbreact.specs.NativeSourceCodeSpec.getConstants(NativeSourceCodeSpec.java:35)
        at com.facebook.react.bridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:129)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
2021-06-15 16:32:41.729 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.checkbox.ReactCheckBoxManager
2021-06-15 16:32:41.731 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
2021-06-15 16:32:41.733 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
2021-06-15 16:32:41.734 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
2021-06-15 16:32:41.734 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
2021-06-15 16:32:41.735 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
2021-06-15 16:32:41.737 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollContainerViewManager
2021-06-15 16:32:41.743 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
2021-06-15 16:32:41.743 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
2021-06-15 16:32:41.744 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
2021-06-15 16:32:41.746 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
2021-06-15 16:32:41.746 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
2021-06-15 16:32:41.747 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
2021-06-15 16:32:41.749 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
2021-06-15 16:32:41.749 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
2021-06-15 16:32:41.750 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
2021-06-15 16:32:41.750 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
2021-06-15 16:32:41.751 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
2021-06-15 16:32:41.751 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
2021-06-15 16:32:41.752 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
2021-06-15 16:32:41.753 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
2021-06-15 16:32:41.754 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
2021-06-15 16:32:41.755 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
2021-06-15 16:32:41.755 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextShadowNode
2021-06-15 16:32:41.758 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
2021-06-15 16:32:41.760 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
2021-06-15 16:32:41.766 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
2021-06-15 16:32:41.771 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
2021-06-15 16:32:41.771 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
2021-06-15 16:32:41.773 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
2021-06-15 16:32:41.773 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
2021-06-15 16:32:41.773 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
2021-06-15 16:32:41.774 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.gesturehandler.react.RNGestureHandlerRootViewManager
2021-06-15 16:32:41.774 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.gesturehandler.react.RNGestureHandlerButtonViewManager
2021-06-15 16:32:41.774 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.ScreenContainerViewManager
2021-06-15 16:32:41.778 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.ScreenViewManager
2021-06-15 16:32:41.785 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.ScreenStackViewManager
2021-06-15 16:32:41.786 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.ScreenStackHeaderConfigViewManager
2021-06-15 16:32:41.786 14792-14907/com.bacon.yolo31 W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.swmansion.rnscreens.ScreenStackHeaderSubviewManager
2021-06-15 16:32:41.787 14792-14907/com.bacon.yolo31 D/SoLoader: init exiting
2021-06-15 16:32:41.790 14792-14792/com.bacon.yolo31 E/unknown:ReactInstanceManager: destroyRootView called
2021-06-15 16:32:41.790 14792-14792/com.bacon.yolo31 E/unknown:ReactInstanceManager: destroyRootView called, unmountReactApplication
2021-06-15 16:32:41.792 14792-14907/com.bacon.yolo31 A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 14907 (create_react_co), pid 14792 (om.bacon.yolo31)
2021-06-15 16:32:41.801 14792-14911/com.bacon.yolo31 I/Process: Sending signal. PID: 14792 SIG: 9
```

**Comment by EvanBacon** [comment]
This appears to be related to TurboModules (which do not support remote JS debugging) https://github.com/facebook/react-native/issues/31379#issuecomment-831875677

**Comment by jack-sparroow** [comment]
If the you have created a debug-build and then it is crashing on physical device then 

<a href="https://github.com/expo/expo/issues/17460#issuecomment-1280632486"> See my Comment <a/>
