### ISSUE TITLE
Build iOS unavailable

### ISSUE THREAD

**Issue by Boyban** [expo/expo-cli#3556]
Since today,

We could not build app from expo build:ios command.

We obtained the whole HTML corresponding of the scrapped page done by Expo (maybe ?)

**Error: Cannot extract key "teams" from response data of type string: <!DOCTYPE html>**

at Object.parseAppStoreResponse (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:576165)
    at getTeamsAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:1028926)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.selectTeamAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:1029233)
    at Object.validateSessionAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:761522)
    at Object.loginWithUserCredentialsAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:750827)
    at loginWithUserCredentialsAsync (/usr/local/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:133:22)
    at loginAsync (/usr/local/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:92:12)
    at authenticateAsync (/usr/local/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:152:23)
    at Context.ensureAppleCtx (/usr/local/lib/node_modules/expo-cli/src/credentials/context.ts:85:24)
    at IOSBuilder.bestEffortAppleCtx (/usr/local/lib/node_modules/expo-cli/src/commands/build/ios/IOSBuilder.ts:95:14)
    at IOSBuilder.prepareCredentials (/usr/local/lib/node_modules/expo-cli/src/commands/build/ios/IOSBuilder.ts:151:5)
    at IOSBuilder.run (/usr/local/lib/node_modules/expo-cli/src/commands/build/ios/IOSBuilder.ts:62:7)
    at IOSBuilder.command (/usr/local/lib/node_modules/expo-cli/src/commands/build/BaseBuilder.ts:43:7)
    at Command.<anonymous> (/usr/local/lib/node_modules/expo-cli/src/exp.ts:350:7)

**Comment by brentvatne** [comment]
are you using the latest version of expo-cli?

**Comment by Boyban** [comment]
Yes just updated few hours ago

**Comment by brentvatne** [comment]
can you try running the command again with the `EXPO_APP_STORE_DEBUG=1` environment variable set and share the output here?

**Comment by brentvatne** [comment]
i just looked at the response and saw:

```
	<meta name="omni_page" content="Maintenance" />
	<meta name="Description" content="We’ll be back soon.">
```

looks like apple servers are down right now, probably related to wwdc. you can run `expo build:ios --skip-credentials-check` to work around that

**Comment by Boyban** [comment]
Okay thanks a lot !
