### ISSUE TITLE
npm exited with non-zero code: 243

### ISSUE THREAD

**Issue by UzbekDeveloper** [expo/expo-cli#3613]
npm exited with non-zero code: 243
Error: npm exited with non-zero code: 243
    at ChildProcess.completionListener (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:514:26)
    at ChildProcess.emit (node:events:394:28)
    at ChildProcess.emit (node:domain:470:12)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    ...
    at Object.spawnAsync [as default] (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at NpmPackageManager._runAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/package-manager/src/NodePackageManagers.ts:166:31)
    at NpmPackageManager.addAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/package-manager/src/NodePackageManagers.ts:105:18)
    at installAsync (/usr/local/lib/node_modules/expo-cli/src/commands/install.ts:115:3)
    at Command.<anonymous> (/usr/local/lib/node_modules/expo-cli/src/exp.ts:350:7)

**Comment by brentvatne** [comment]
we need more information than this. https://stackoverflow.com/help/how-to-ask

**Comment by shalithasuranga** [comment]
I got the same error as above on Ubuntu with `expo install`. Solved by installing Node with `nvm`

**Comment by AnzenKodo** [comment]
I also got this error in Ubuntu and solved by @shalithasuranga solution by install Node with `nvm`.
