### ISSUE TITLE
uri-scheme tool crashes on 'empty' url type entry

### ISSUE THREAD

**Issue by kbrandwijk** [expo/expo-cli#3625]
If you happen to have an empty url type in your iOS project (as in, clicked the + sign once on url types accidentally, but didn't enter anything) then the cli will crash ugly.

```text
npx: installed 1 in 1.207s

Aborting run
An unexpected error was encountered. Please report it as a bug:
TypeError: Cannot read property 'includes' of undefined
    at /Users/*****/.npm/_npx/48240/lib/node_modules/uri-scheme/build/index.js:1:418895
    at Array.some (<anonymous>)
    at Object.hasScheme (/Users/kim/.npm/_npx/48240/lib/node_modules/uri-scheme/build/index.js:1:418862)
    at Object.addAsync (/Users/kim/.npm/_npx/48240/lib/node_modules/uri-scheme/build/index.js:1:481738)
    at Object.addAsync (/Users/kim/.npm/_npx/48240/lib/node_modules/uri-scheme/build/index.js:1:486127)
    at async Command.<anonymous> (/Users/kim/.npm/_npx/48240/lib/node_modules/uri-scheme/build/index.js:1:477579)
```

**Comment by kbrandwijk** [comment]
I have tracked this down to this line:

https://github.com/expo/expo-cli/blob/8f551d89859a42ce0dfcf357b14988f3c924e5ff/packages/config-plugins/src/ios/Scheme.ts#L91

I'll come up with a PR for this.
