### ISSUE TITLE
Failed to construct transformer:  TypeError: semver is not a function

### ISSUE THREAD

**Issue by arif7576** [expo/expo-cli#3658]
Failed to construct transformer:  TypeError: semver is not a function
    at Object.<anonymous> (D:\Web\Mobile\test\vueTransformerPlugin.js:6:31)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)

**Comment by trajano** [comment]
Should be part of vue-native https://github.com/GeekyAnts/vue-native-core/issues/327
