### ISSUE TITLE
expo login: error 500

### ISSUE THREAD

**Issue by ronnac** [expo/expo-cli#3712]
### Summary

I execute "expo login" and I get an error 500 message (cf below)
I am behind a proxy.
The installation of expo went fine.

### Environment

error Couldn't find a package.json file in "/home/users/myusername"

### Please specify your device/emulator/simulator platform, model and version

n/A

### Error output

expo-cli login
✔ Username/Email Address: … XXXXXXX
✔ Password: … ***********
Request failed with status code 500
Error: Request failed with status code 500
    at createError (/home/users/myusername/.npm/_npx/7ce4565c73d8cd04/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/users/myusername/.npm/_npx/7ce4565c73d8cd04/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/users/myusername/.npm/_npx/7ce4565c73d8cd04/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1331:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

### Reproducible demo or steps to reproduce from a blank project

expo login

**Comment by quinlanj** [comment]
@ronnac is this issue still happening for you? Trying to figure out if this is a transient server issue or something that is reproducible

**Comment by ronnac** [comment]
Thanks for coming back to me. It looks like this was a firewall issue. 
-------- Original message --------From: Quinlan Jung ***@***.***> Date: 23/08/21  20:56  (GMT+01:00) To: expo/expo-cli ***@***.***> Cc: Nick Römer ***@***.***>, Mention ***@***.***> Subject: Re: [expo/expo-cli] expo login: error 500 (#3712) 
@ronnac is this issue still happening for you? Trying to figure out if this is a transient server issue or something that is reproducible

**Comment by quinlanj** [comment]
ah ok! thank you so much for the quick reply. We'll close this issue out then :)
