### ISSUE TITLE
PWA fails to compile due to GenerateSW plugin configuration keys being renamed

### ISSUE THREAD

**Issue by 3x071c** [expo/expo-cli#3718]
### Summary

I tried enabling PWA support by exporting and modifying the webpack configuration as described in [the docs](https://github.com/expo/fyi/blob/master/enabling-web-service-workers.md). It appears that a plugin in the configuration, GenerateSW, has renamed some configuration keys which they perceive as racist (`Blacklist` -> `Denylist` etc.), breaking compilation. This might be related to PR #2023, which reverted the correct naming of the new configuration options.

### Environment

```
  Expo CLI 4.8.1 environment info:
    System:
      OS: Linux 5.13 Arch Linux
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 16.5.0 - /usr/bin/node
      npm: 7.19.1 - /usr/bin/npm
    npmPackages:
      @expo/webpack-config: ^0.13.1 => 0.13.1 
      expo: ~42.0.1 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.8.1
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

N/A

### Error output

```
✖ Expo Webpack
  Compiled with some errors in 25.16s

Failed to compile.

Please check your GenerateSW plugin configuration:
navigateFallbackBlacklist has been renamed navigateFallbackDenylist.
Error: Please check your GenerateSW plugin configuration:
navigateFallbackBlacklist has been renamed navigateFallbackDenylist.
    at <project>/node_modules/xdl/build/Webpack.js:353:21
    at finalCallback (<project>/node_modules/webpack/lib/Compiler.js:257:39)
    at <project>/node_modules/webpack/lib/Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (<project>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (<project>/node_modules/tapable/lib/Hook.js:154:20)
    at <project>/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (<project>/node_modules/webpack/lib/Compiler.js:499:39)
    at <project>/node_modules/webpack/lib/Compiler.js:298:10
    at <project>/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (<project>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at AsyncSeriesHook.lazyCompileHook (<project>/node_modules/tapable/lib/Hook.js:154:20)
    at <project>/node_modules/webpack/lib/Compiler.js:482:27
    at <project>/node_modules/neo-async/async.js:2818:7
    at done (<project>/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (<project>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at <project>/node_modules/webpack/lib/Compiler.js:464:33
```

### Reproducible demo or steps to reproduce from a blank project

 1. Create a new expo project:
```sh
$ expo init example
```
 2. Follow [the instructions](https://github.com/expo/fyi/blob/master/enabling-web-service-workers.md) to enable PWA support:
```sh
$ expo customize:web # select webpack.config.js
$ echo "
const createExpoWebpackConfigAsync = require("@expo/webpack-config");

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(
    {
      ...env,
      // Passing true will enable the default Workbox + Expo SW configuration.
      offline: true,
    },
    argv
  );
  // Customize the config before returning it.
  return config;
};
" > webpack.config.js
```
 3. Run `expo build:web` and watch it all fall apart :sob:

**Comment by EvanBacon** [comment]
We'll be removing this functionality from the webpack-config in favor of manually adding workbox webpack plugin to your project locally, you can get a head start on this now by leaving offline disabled and following this: https://expo.fyi/enabling-web-service-workers

**Comment by EvanBacon** [comment]
Closing this because workbox will be dropped in the next version
