### ISSUE TITLE
Failed to locate the ios/*.xcodeproj/project.pbxproj files when running "expo run:ios"

### ISSUE THREAD

**Issue by Cosmicoda** [expo/expo-cli#3772]
### Summary

When I ran "expo run:ios" the first time it was interrupted while installing packages and when I tried to run it again I received the error below.

Maybe I need to manually cleanup some leftover files after the first run was interrupted?

I cleanup my git repo after some of the new files/folders were created but I still have the same issue.

### Environment

Expo CLI 4.10.0 environment info:
    System:
      OS: macOS 11.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 7.18.1 - ~/.nvm/versions/node/v12.22.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.4 
    npmGlobalPackages:
      expo-cli: 4.10.0
    Expo Workflow: bare

Note: not sure why workflow is bare as I'm using managed workflow

### Please specify your device/emulator/simulator platform, model and version

n/a

### Error output

UnexpectedError: Failed to locate the ios/*.xcodeproj/project.pbxproj files relative to path "<PROJECT PATH>".
    at getAllPBXProjectPaths (/Users/<USER>/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:127:11)
    at Object.getPBXProjectPath (/Users/<USER>/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:135:29)
    at getPbxproj (/Users/<USER>/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/utils/Xcodeproj.ts:318:29)
    at getRunnableSchemesFromXcodeproj (/Users/<USER>/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/BuildScheme.ts:38:19)
    at /Users/meisty/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/src/commands/utils/profileMethod.ts:16:21
    at resolveOptionsAsync (/Users/<USER>/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/src/commands/run/ios/resolveOptionsAsync.ts:141:5)
    at actionAsync (/Users/<USER>/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/src/commands/run/ios/runIos.ts:49:17)

### Reproducible demo or steps to reproduce from a blank project

run "expo run:ios"
interrupt the execution of the script when installing the packages
run again "expo run:ios"

**Comment by EvanBacon** [comment]
Ya `expo run:ios` runs a quicker version of `expo prebuild -p ios`, if you run that command over again, it'll check your project and prompt you to clean up the corrupted project before generating native code.

**Comment by Cosmicoda** [comment]
> Ya `expo run:ios` runs a quicker version of `expo prebuild -p ios`, if you run that command over again, it'll check your project and prompt you to clean up the corrupted project before generating native code.

@EvanBacon 
Thanks for your response. I tried to run the command "expo rebuild -p ios" but I got the error below:

✔ Created native project | /ios already created
✔ Added Metro config.
✔ Updated package.json and added index.js entry point for iOS and Android.
🧶 Using Yarn to install packages. Pass --npm to use npm instead.
✔ Cleaned JavaScript dependencies.
✔ Installed JavaScript dependencies.
[ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "/PROJECT_PATH"
Please report this as an issue on https://github.com/expo/expo-cli/issues
UnexpectedError: [ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "/Users/USERS/PROJECT"
Please report this as an issue on https://github.com/expo/expo-cli/issues
    at getAppDelegateFilePath (/Users/USER/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:26:11)
    at getAppDelegate (/Users/USER/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:63:20)
    at Object.getSourceRoot (/Users/USER/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:68:23)
    at getProjectName (/Users/USER/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/utils/Xcodeproj.ts:33:28)
    at getIosNamedProjectPath (/Users/USER/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:172:23)
    at setIconsAsync (/Users/USER/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:107:31)
    at /Users/USER/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:15:13
    at action (/Users/USER/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:214:29)
    at interceptingMod (/Users/USER/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:100:27)
    at action (/Users/USER/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/createBaseMod.ts:73:27)
    at interceptingMod (/Users/USER/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:100:21)
    at evalModsAsync (/Users/USER/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:182:25)
    at compileModsAsync (/Users/USER/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:92:10)
    at configureManagedProjectAsync (/Users/USER/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/src/commands/eject/configureProjectAsync.ts:64:12)
    at prebuildAsync (/Users/USER/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/src/commands/eject/prebuildAsync.ts:89:25)
    at actionAsync (/Users/USER/.nvm/versions/node/v12.22.1/lib/node_modules/expo-cli/src/commands/prebuildAsync.ts:32:3)
