### ISSUE TITLE
v42 upgrade broke project

### ISSUE THREAD

**Issue by ottob** [expo/expo-cli#3780]
### Summary

I ran `expo upgrade` to upgrade from v41 to v42. The project started fine with v41.

Instead of starting as expected with expo run, I got the error below.

I tried to remove node_modules and re-run yarn. It made no difference.

### Solution
Fixed it by running `expo install expo-splash-screen` as hinted to here https://github.com/expo/expo/issues/10569#issuecomment-765888862

Maybe expo-splash-screen should have been installed by `expo upgrade` if I had a custom `splash` setting in app.json?

### Environment

expo-cli is v4.10.0

I have a custom splash image in app.json
```
"splash": {
      "image": "./assets/logo_splash.png",
      "backgroundColor": "#e0e9eb"
    },
```

Im not using `expo-splash-screen` or `expo-app-loading` in my project.

### Please specify your device/emulator/simulator platform, model and version

iOS simulator 12.5.1

### Error output

```
yarn run v1.22.5
$ node_modules/.bin/ts-node --project projects/tsconfig.json projects/runTask.ts --task start-native
Configured care with development environment
$ ./node_modules/.bin/expo start
[12:17:38] Starting project at /Users/ottob/myproj/apps/care-native
[12:17:39] Developer tools running on http://localhost:19002
[12:17:42] Cannot find module 'jsonfile/utils'
Require stack:
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/node_modules/fs-extra/lib/json/output-json.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/node_modules/fs-extra/lib/json/index.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/node_modules/fs-extra/lib/index.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/build/ios/index.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/build/index.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/config-plugins/build/android/SplashScreen.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/config-plugins/build/android/index.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/config-plugins/build/index.js
- /Users/ottob/myproj/node_modules/@expo/config/build/plugins/withConfigPlugins.js
- /Users/ottob/myproj/node_modules/@expo/config/build/Config.js
- /Users/ottob/myproj/node_modules/@expo/config/build/index.js
- /Users/ottob/myproj/node_modules/@expo/metro-config/build/ExpoMetroConfig.js
- /Users/ottob/myproj/node_modules/expo-yarn-workspaces/index.js
- /Users/ottob/myproj/apps/care-native/metro.config.js
- /Users/ottob/myproj/node_modules/cosmiconfig/node_modules/import-fresh/index.js
- /Users/ottob/myproj/node_modules/cosmiconfig/dist/loaders.js
- /Users/ottob/myproj/node_modules/cosmiconfig/dist/createExplorer.js
- /Users/ottob/myproj/node_modules/cosmiconfig/dist/index.js
- /Users/ottob/myproj/node_modules/metro-config/src/loadConfig.js
- /Users/ottob/myproj/node_modules/metro-config/src/index.js
- /Users/ottob/myproj/node_modules/metro/src/commands/build.js
- /Users/ottob/myproj/node_modules/metro/src/index.js
- /Users/ottob/.config/yarn/global/node_modules/@expo/dev-server/build/MetroDevServer.js
- /Users/ottob/.config/yarn/global/node_modules/xdl/build/start/startDevServerAsync.js
- /Users/ottob/.config/yarn/global/node_modules/xdl/build/internal.js
- /Users/ottob/.config/yarn/global/node_modules/xdl/build/index.js
- /Users/ottob/.config/yarn/global/node_modules/expo-cli/build/exp.js
- /Users/ottob/.config/yarn/global/node_modules/expo-cli/bin/expo.js
[12:17:42] Error: Cannot find module 'jsonfile/utils'
Require stack:
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/node_modules/fs-extra/lib/json/output-json.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/node_modules/fs-extra/lib/json/index.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/node_modules/fs-extra/lib/index.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/build/ios/index.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/build/index.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/config-plugins/build/android/SplashScreen.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/config-plugins/build/android/index.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/config-plugins/build/index.js
- /Users/ottob/myproj/node_modules/@expo/config/build/plugins/withConfigPlugins.js
- /Users/ottob/myproj/node_modules/@expo/config/build/Config.js
- /Users/ottob/myproj/node_modules/@expo/config/build/index.js
- /Users/ottob/myproj/node_modules/@expo/metro-config/build/ExpoMetroConfig.js
- /Users/ottob/myproj/node_modules/expo-yarn-workspaces/index.js
- /Users/ottob/myproj/apps/care-native/metro.config.js
- /Users/ottob/myproj/node_modules/cosmiconfig/node_modules/import-fresh/index.js
- /Users/ottob/myproj/node_modules/cosmiconfig/dist/loaders.js
- /Users/ottob/myproj/node_modules/cosmiconfig/dist/createExplorer.js
- /Users/ottob/myproj/node_modules/cosmiconfig/dist/index.js
- /Users/ottob/myproj/node_modules/metro-config/src/loadConfig.js
- /Users/ottob/myproj/node_modules/metro-config/src/index.js
- /Users/ottob/myproj/node_modules/metro/src/commands/build.js
- /Users/ottob/myproj/node_modules/metro/src/index.js
- /Users/ottob/.config/yarn/global/node_modules/@expo/dev-server/build/MetroDevServer.js
- /Users/ottob/.config/yarn/global/node_modules/xdl/build/start/startDevServerAsync.js
- /Users/ottob/.config/yarn/global/node_modules/xdl/build/internal.js
- /Users/ottob/.config/yarn/global/node_modules/xdl/build/index.js
- /Users/ottob/.config/yarn/global/node_modules/expo-cli/build/exp.js
- /Users/ottob/.config/yarn/global/node_modules/expo-cli/bin/expo.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/node_modules/fs-extra/lib/json/output-json.js:3:23)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
(node:34976) UnhandledPromiseRejectionWarning: Error: Command failed: cd ./apps/care-native && yarn start
[12:17:42] Cannot find module 'jsonfile/utils'
Require stack:
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/node_modules/fs-extra/lib/json/output-json.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/node_modules/fs-extra/lib/json/index.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/node_modules/fs-extra/lib/index.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/build/ios/index.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/build/index.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/config-plugins/build/android/SplashScreen.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/config-plugins/build/android/index.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/config-plugins/build/index.js
- /Users/ottob/myproj/node_modules/@expo/config/build/plugins/withConfigPlugins.js
- /Users/ottob/myproj/node_modules/@expo/config/build/Config.js
- /Users/ottob/myproj/node_modules/@expo/config/build/index.js
- /Users/ottob/myproj/node_modules/@expo/metro-config/build/ExpoMetroConfig.js
- /Users/ottob/myproj/node_modules/expo-yarn-workspaces/index.js
- /Users/ottob/myproj/apps/care-native/metro.config.js
- /Users/ottob/myproj/node_modules/cosmiconfig/node_modules/import-fresh/index.js
- /Users/ottob/myproj/node_modules/cosmiconfig/dist/loaders.js
- /Users/ottob/myproj/node_modules/cosmiconfig/dist/createExplorer.js
- /Users/ottob/myproj/node_modules/cosmiconfig/dist/index.js
- /Users/ottob/myproj/node_modules/metro-config/src/loadConfig.js
- /Users/ottob/myproj/node_modules/metro-config/src/index.js
- /Users/ottob/myproj/node_modules/metro/src/commands/build.js
- /Users/ottob/myproj/node_modules/metro/src/index.js
- /Users/ottob/.config/yarn/global/node_modules/@expo/dev-server/build/MetroDevServer.js
- /Users/ottob/.config/yarn/global/node_modules/xdl/build/start/startDevServerAsync.js
- /Users/ottob/.config/yarn/global/node_modules/xdl/build/internal.js
- /Users/ottob/.config/yarn/global/node_modules/xdl/build/index.js
- /Users/ottob/.config/yarn/global/node_modules/expo-cli/build/exp.js
- /Users/ottob/.config/yarn/global/node_modules/expo-cli/bin/expo.js
[12:17:42] Error: Cannot find module 'jsonfile/utils'
Require stack:
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/node_modules/fs-extra/lib/json/output-json.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/node_modules/fs-extra/lib/json/index.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/node_modules/fs-extra/lib/index.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/build/ios/index.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/build/index.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/config-plugins/build/android/SplashScreen.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/config-plugins/build/android/index.js
- /Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/config-plugins/build/index.js
- /Users/ottob/myproj/node_modules/@expo/config/build/plugins/withConfigPlugins.js
- /Users/ottob/myproj/node_modules/@expo/config/build/Config.js
- /Users/ottob/myproj/node_modules/@expo/config/build/index.js
- /Users/ottob/myproj/node_modules/@expo/metro-config/build/ExpoMetroConfig.js
- /Users/ottob/myproj/node_modules/expo-yarn-workspaces/index.js
- /Users/ottob/myproj/apps/care-native/metro.config.js
- /Users/ottob/myproj/node_modules/cosmiconfig/node_modules/import-fresh/index.js
- /Users/ottob/myproj/node_modules/cosmiconfig/dist/loaders.js
- /Users/ottob/myproj/node_modules/cosmiconfig/dist/createExplorer.js
- /Users/ottob/myproj/node_modules/cosmiconfig/dist/index.js
- /Users/ottob/myproj/node_modules/metro-config/src/loadConfig.js
- /Users/ottob/myproj/node_modules/metro-config/src/index.js
- /Users/ottob/myproj/node_modules/metro/src/commands/build.js
- /Users/ottob/myproj/node_modules/metro/src/index.js
- /Users/ottob/.config/yarn/global/node_modules/@expo/dev-server/build/MetroDevServer.js
- /Users/ottob/.config/yarn/global/node_modules/xdl/build/start/startDevServerAsync.js
- /Users/ottob/.config/yarn/global/node_modules/xdl/build/internal.js
- /Users/ottob/.config/yarn/global/node_modules/xdl/build/index.js
- /Users/ottob/.config/yarn/global/node_modules/expo-cli/build/exp.js
- /Users/ottob/.config/yarn/global/node_modules/expo-cli/bin/expo.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/ottob/myproj/node_modules/@expo/config/node_modules/@expo/configure-splash-screen/node_modules/fs-extra/lib/json/output-json.js:3:23)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
error Command failed with exit code 1.

    at ChildProcess.exithandler (child_process.js:390:12)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:470:12)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:470:12)
    at Pipe.<anonymous> (net.js:675:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:34976) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:34976) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 9.09s.
```

### Reproducible demo or steps to reproduce from a blank project

N/A

**Comment by EvanBacon** [comment]
Yes this was an unfortunate bug in NPM that we've since resolved. It seems that when a module is reused 3 layers deep `node_modules/foo/node_modules/bar/node_modules/alpha` then things start to behave unexpectedly. To resolve this we've manually removed the extra packages from `@expo/configure-splash-screen`, and remove `@expo/configure-splash-screen` from `@expo/config`.

Sorry for any inconvenience this may have caused you.
