### ISSUE TITLE
Expo build failing for IOS

### ISSUE THREAD

**Issue by fessor10** [expo/expo-cli#3788]
### Summary

I'm trying to build for ios and I kept on getting errors, I also found out our certificates were expired. We have now revoked our access and deleted all our keys, profiles and certificate from the apple developer account and the expo:build wont work.

### Environment

```bash
Expo CLI 4.10.1 environment info:
    System:
      OS: macOS 11.5.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.2 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.19.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.12.63 => 0.12.82
      expo: ^41.0.0 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.10.1
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

Expo CLI 4.10.1

### Error output

```bash
✖ Failed to register bundle identifier [REDACTED]
Failed to prepare all credentials.
The next time you build, we will automatically use the following configuration:

Project Credential Configuration:
  Experience: [REDACTED], bundle identifier: [REDACTED]
    Provisioning profile is missing. It will be generated during the next build

Received an internal server error from App Store Connect / Developer Portal, please try again later
Error: Received an internal server error from App Store Connect / Developer Portal, please try again later
    at ProvisioningClientAPI.parseResponse (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:831727)
    at ProvisioningClientAPI.requestAndParseAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:830585)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at ProvisioningClientAPI.fetchAllModelsAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:830123)
    at Function.findAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:886352)
    at ensureBundleIdExistsWithNameAsync (/usr/local/lib/node_modules/expo-cli/src/appleApi/ensureAppExists.ts:44:16)
    at IOSBuilder.produceCredentials (/usr/local/lib/node_modules/expo-cli/src/commands/build/ios/IOSBuilder.ts:240:7)
    at IOSBuilder.prepareCredentials (/usr/local/lib/node_modules/expo-cli/src/commands/build/ios/IOSBuilder.ts:155:7)
    at IOSBuilder.run (/usr/local/lib/node_modules/expo-cli/src/commands/build/ios/IOSBuilder.ts:62:7)
    at IOSBuilder.command (/usr/local/lib/node_modules/expo-cli/src/commands/build/BaseBuilder.ts:43:7)
```

### Reproducible demo or steps to reproduce from a blank project

`expo build:ios --release-channel=production`

**Comment by fessor10** [comment]
@EvanBacon Please any help with this?

**Comment by samuelvisscher** [comment]
I'm having this same error, upon running the above with `EXPO_APP_STORE_DEBUG=1`, I'm seeing the following:

```
⠋ Syncing capabilitiesPATCH https://developer.apple.com/services-account/v1/bundleIds/[_bundle id removed_]
⠼ Syncing capabilitiesError: Request failed with status code 502 (PATCH https://developer.apple.com/services-account/v1/bundleIds/[_bundle id removed_])
✖ Failed to sync capabilities [_app name removed_]
Failed to prepare all credentials. 
The next time you build, we will automatically use the following configuration:
```

**Comment by brentvatne** [comment]
@samuelvisscher - use `EXPO_NO_CAPABILITY_SYNC=1 eas build` for now. there appears to be an issue with Apple's APIs, starting on Friday night. we'll investigate further tomorrow

@fessor10 - this appears to be an issue on Apple's side, we'll investigate further tomorrow if it's not resolved. you can likely work around this for now by generating credentials manually, uploading them to Expo, and then running `expo build:ios --skip-credentials-check`

**Comment by fessor10** [comment]
@brentvatne This persists, I think it's an Apple issue tho. Can you please kindly investigate this and know if you can come up with a fix. Thanks

**Comment by EvanBacon** [comment]
@fessor10 it's an Apple server issue, there's nothing we can do but wait for now.

**Comment by abury** [comment]
Is this still an issue? Fastlane is showing this as resolved: https://github.com/fastlane/fastlane/issues/19264#issuecomment-904318685

**Comment by Calvin-Drawbridge** [comment]
@abury Yes this still seems to be an issue. Getting the following:

> × Failed to fetch Apple provisioning profiles
Failed to setup credentials.
    Error: Received an internal server error from App Store Connect / Developer Portal, please try again later

**Comment by marcinczenko** [comment]
also getting this:

```bash
⠹ Getting Provisioning Profile info from Apple's Servers...
✖ Failed to fetch Apple provisioning profiles
Failed to set up Provisioning Profile
Failed to prepare all credentials. 
The next time you build, we will automatically use the following configuration:
```

**Comment by olliebennett** [comment]
Also still experiencing this (repeatedly) right now. Mine seems to fail on a different endpoint vs. above;

```
➜  my-app git:(master) EXPO_APP_STORE_DEBUG=1 eas build --platform ios
-- Enabled debug logging --
✔ Linked to project @example/my-app
✔ Using remote iOS credentials (Expo server)

If you provide your Apple account credentials we will be able to generate all necessary build credentials and fully validate them.
This is optional, but without Apple account access you will need to provide all the values manually and we can only run minimal validation on them.
✔ Do you want to log in to your Apple account? … yes

› Log in to your Apple Developer account to continue
✔ Apple ID: … myname@example.com
› Restoring session /Users/myname/.app-store/auth/myname@example.com/cookie
POST https://developer.apple.com/services-account/REDACTED_123/account/listTeams.action
200 OK (POST https://developer.apple.com/services-account/REDACTED_123/account/listTeams.action)
› Team Example Company Inc. (REDACTED_TEAM_ID)
GET https://appstoreconnect.apple.com/olympus/v1/session
200 OK (GET https://appstoreconnect.apple.com/olympus/v1/session)
› Provider Example Company Inc. (REDACTED_COMPANY_ID)
✔ Logged in Local session
POST https://developer.apple.com/services-account/REDACTED_123/account/listTeams.action
200 OK (POST https://developer.apple.com/services-account/REDACTED_123/account/listTeams.action)
⠋ Linking bundle identifier co.examplePOST https://developer.apple.com/services-account/v1/bundleIds
⠦ Linking bundle identifier co.example200 OK (POST https://developer.apple.com/services-account/v1/bundleIds)
✔ Bundle identifier registered co.example
⠋ Syncing capabilitiesPOST https://developer.apple.com/services-account/v1/bundleIds/REDACTED_BUNDLE_ID/bundleIdCapabilities
⠼ Syncing capabilities200 OK (POST https://developer.apple.com/services-account/v1/bundleIds/REDACTED_BUNDLE_ID/bundleIdCapabilities)
✔ Synced capabilities: No updates
⠋ Syncing capabilities identifiersPOST https://developer.apple.com/services-account/v1/merchantIds
⠦ Syncing capabilities identifiers200 OK (POST https://developer.apple.com/services-account/v1/merchantIds)
PATCH https://developer.apple.com/services-account/v1/bundleIds/REDACTED_BUNDLE_ID
⠴ Syncing capabilities identifiers200 OK (PATCH https://developer.apple.com/services-account/v1/bundleIds/REDACTED_BUNDLE_ID)
✔ Synced capability identifiers: Linked: merchant.co.example
⠋ Fetching Apple distribution certificatesPOST https://developer.apple.com/services-account/v1/certificates
⠹ Fetching Apple distribution certificates200 OK (POST https://developer.apple.com/services-account/v1/certificates)
✔ Fetched Apple distribution certificates
⠋ Fetching Apple provisioning profilesPOST https://developer.apple.com/services-account/v1/bundleIds
⠼ Fetching Apple provisioning profiles200 OK (POST https://developer.apple.com/services-account/v1/bundleIds)
POST https://developer.apple.com/services-account/v1/bundleIds/REDACTED_BUNDLE_ID/profiles
⠦ Fetching Apple provisioning profiles200 OK (POST https://developer.apple.com/services-account/v1/bundleIds/REDACTED_BUNDLE_ID/profiles)
POST https://developer.apple.com/services-account/v1/profiles/REDACTED_PROFILE_ID/bundleId
⠏ Fetching Apple provisioning profiles200 OK (POST https://developer.apple.com/services-account/v1/profiles/REDACTED_PROFILE_ID/bundleId)
POST https://developer.apple.com/services-account/v1/profiles/REDACTED_PROFILE_ID/certificates
⠙ Fetching Apple provisioning profilesError: Request failed with status code 502 (POST https://developer.apple.com/services-account/v1/profiles/REDACTED_PROFILE_ID/certificates)
✖ Failed to fetch Apple provisioning profiles
Failed to setup credentials.
    Error: Received an internal server error from App Store Connect / Developer Portal, please try again later
➜  my-app git:(master) 
```

Not sure if there's anything we can do to workaround these endpoints (which I appreciate are somewhat dependent on Apple's API functioning)!

**Comment by EvanBacon** [comment]
If anyone here can repro this while using charles proxy with the envar `EXPO_APP_STORE_USE_PROXY=1` that would be helpful as I can add the exact error response to the integration tests. 

I've opened a branch which I think has a fix in place, but as I said, I cannot repro. If someone would be willing to try this branch https://github.com/expo/expo-cli/pull/3798 and let me know if they still encounter the issue, that would be greatly appreciated.

**Comment by olliebennett** [comment]
I just tried but the issue is seemingly resolved - I can no longer reproduce it either. Sorry!
