### ISSUE TITLE
withIosDangerousBaseMod: Could not locate a valid AppDelegate at root

### ISSUE THREAD

**Issue by mrosendin** [expo/expo-cli#3833]
I'm trying to use `eas build` so I can upload a new version to the app store with `eas submit`. I'm seeing this message in the terminal:

```
 Waiting for build to complete. You can press Ctrl+C to exit.
✖ Build failed

🍎 iOS build failed:
Unknown error. Please see logs.
```

And the Expo build details show the error in the Prebuild stage.

```
Prebuilding managed project
- Creating native project directories (./ios and ./android) and updating .gitignore
✔ Created native project | /ios already created
- Adding Metro bundler config
✔ Added Metro config.
- Updating your package.json scripts, dependencies, and main file
✔ Updated package.json and added index.js entry point for iOS and Android.
[15:07:38] › Removed "main": "node_modules/expo/AppEntry.js" from package.json because we recommend using index.js as main instead.
- Config syncing
[stderr] [15:07:38] [ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "/Users/expo/workingdir/build"
[stderr] Please report this as an issue on https://github.com/expo/expo-cli/issues
[stderr] [15:07:38] UnexpectedError: [ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "/Users/expo/workingdir/build"
[stderr] Please report this as an issue on https://github.com/expo/expo-cli/issues
[stderr]     at getAppDelegateFilePath (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/ios/Paths.ts:26:11)
[stderr]     at getAppDelegate (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/ios/Paths.ts:63:20)
[stderr]     at Object.getSourceRoot (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/ios/Paths.ts:68:23)
[stderr]     at getProjectName (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/ios/utils/Xcodeproj.ts:32:28)
[stderr]     at getIosNamedProjectPath (/usr/local/eas-build-worker/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:172:23)
[stderr]     at setIconsAsync (/usr/local/eas-build-worker/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:107:31)
[stderr]     at /usr/local/eas-build-worker/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:15:13
[stderr]     at action (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/plugins/withMod.ts:214:29)
[stderr]     at interceptingMod (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/plugins/withMod.ts:100:27)
[stderr]     at action (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/plugins/createBaseMod.ts:73:27)
[stderr]     at interceptingMod (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/plugins/withMod.ts:100:21)
[stderr]     at evalModsAsync (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:182:25)
[stderr]     at compileModsAsync (/usr/local/eas-build-worker/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:92:10)
[stderr]     at configureManagedProjectAsync (/usr/local/eas-build-worker/node_modules/expo-cli/src/commands/eject/configureProjectAsync.ts:64:12)
[stderr]     at prebuildAsync (/usr/local/eas-build-worker/node_modules/expo-cli/src/commands/eject/prebuildAsync.ts:89:25)
[stderr]     at actionAsync (/usr/local/eas-build-worker/node_modules/expo-cli/src/commands/prebuildAsync.ts:32:3)
node exited with non-zero code: 1
```

**Comment by EvanBacon** [comment]
Can you confirm that this error occurs when you run `expo prebuild` in your project locally (be sure to do it on a new branch so you can revert the changes)?

**Comment by mrosendin** [comment]
```
% expo prebuild
┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (4.11.0).                │
│   You are currently using expo-cli 4.10.1                               │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
✔ Created native projects | /android, /ios already created | gitignore already synced
⚠️  Skipped Metro config updates:
› Existing Metro config found; not overwriting.
› You will need to extend the default @expo/metro-config in your Metro config.
  Learn more.

✔ Updated package.json and added index.js entry point for iOS and Android.
🧶 Using Yarn to install packages. Pass --npm to use npm instead.
✔ Cleaned JavaScript dependencies.
✔ Installed JavaScript dependencies.
✔ Config synced
✔ Installed pods and initialized Xcode workspace.
```

**Comment by EvanBacon** [comment]
It doesn't appear that the issue is happening locally, perhaps something is wrong with the gitignore and all of the project files aren't being uploaded?

**Comment by mrosendin** [comment]
This is no longer an issue for me, not sure why, perhaps due to upgrading `eas`.
