### ISSUE TITLE
Expo cli upgrade 4.12.0 not displaying on android devices

### ISSUE THREAD

**Issue by mdarke1** [expo/expo-cli#3868]
Having followed upgrade I am now no longer able to run expo on android emulator or android physical device, as the app locks on the splash screen after bundling has been completed. 

I get to stage on CLI where it displays the following:
Android Bundling complete 26215ms
Android Running app on sdk_gphone_x86

I'm using storybook and the items are displaying on server on expo load. 

I am also using reanimated2.

Prior to the upgrade the app was working fine on both emulator and physical device.

Measures undertaken so far that have not worked:

1) Deleted/ reinitiated emulator 
2) Reinstalled expo sdk on emulator
3) Deleted and reinstalled expo-go from GooglePlayStore
4) Deleted and reinstalled all node modules

My logCat on android emulator details:
   --------- beginning of system
2021-09-22 17:11:20.443 549-579/? W/BroadcastQueue: Skipping deliver [background] BroadcastRecord{ae3a47a u-1 android.net.conn.CONNECTIVITY_CHANGE} to ReceiverList{f66642b 7447 (unknown name)/2000/u-1 remote:15b069c}: process gone or crashing
2021-09-22 17:11:20.458 549-2357/? I/ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=host.exp.exponent/.experience.HomeActivity} from uid 2000
2021-09-22 17:11:20.458 549-571/? D/EventSequenceValidator: Transition from ACTIVITY_FINISHED to INTENT_STARTED
2021-09-22 17:11:20.476 7447-7447/? I/Monkey: Events injected: 1
2021-09-22 17:11:20.483 549-571/? D/CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10154; state: DISABLED
2021-09-22 17:11:20.486 549-571/? D/EventSequenceValidator: Transition from INTENT_STARTED to ACTIVITY_LAUNCHED
2021-09-22 17:11:20.487 549-569/? W/InputReader: Device virtio_input_multi_touch_9 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.487 549-569/? W/InputReader: Device virtio_input_multi_touch_10 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.487 549-569/? W/InputReader: Device virtio_input_multi_touch_7 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.487 549-569/? W/InputReader: Device virtio_input_multi_touch_4 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.487 549-569/? W/InputReader: Device virtio_input_multi_touch_11 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.487 549-569/? W/InputReader: Device virtio_input_multi_touch_5 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.487 549-569/? W/InputReader: Device virtio_input_multi_touch_2 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.487 549-569/? W/InputReader: Device virtio_input_multi_touch_6 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.487 549-569/? W/InputReader: Device virtio_input_multi_touch_3 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.487 549-569/? W/InputReader: Device virtio_input_multi_touch_8 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.487 549-580/? D/CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10154; state: ENABLED
2021-09-22 17:11:20.500 549-569/? W/InputReader: Device virtio_input_multi_touch_9 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.500 549-569/? W/InputReader: Device virtio_input_multi_touch_10 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.500 549-569/? W/InputReader: Device virtio_input_multi_touch_7 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.500 549-569/? W/InputReader: Device virtio_input_multi_touch_4 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.501 549-569/? W/InputReader: Device virtio_input_multi_touch_11 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.501 549-569/? W/InputReader: Device virtio_input_multi_touch_5 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.501 549-569/? W/InputReader: Device virtio_input_multi_touch_2 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.501 549-569/? W/InputReader: Device virtio_input_multi_touch_6 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.501 549-569/? W/InputReader: Device virtio_input_multi_touch_3 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.501 549-569/? W/InputReader: Device virtio_input_multi_touch_8 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.509 287-287/? D/Zygote: Forked child process 7462
2021-09-22 17:11:20.517 317-345/? D/goldfish-address-space: claimShared: Ask to claim region [0x3f0000000 0x3f0965000]
2021-09-22 17:11:20.520 7447-7447/? I/Monkey: ## Network stats: elapsed time=41ms (0ms mobile, 0ms wifi, 41ms not connected)
2021-09-22 17:11:20.538 549-580/? W/ActivityManager: Slow operation: 57ms so far, now at startProcess: done updating battery stats
2021-09-22 17:11:20.538 549-580/? W/ActivityManager: Slow operation: 58ms so far, now at startProcess: building log message
2021-09-22 17:11:20.538 549-580/? I/ActivityManager: Start proc 7462:host.exp.exponent/u0a154 for pre-top-activity {host.exp.exponent/host.exp.exponent.experience.HomeActivity}
2021-09-22 17:11:20.538 549-580/? W/ActivityManager: Slow operation: 58ms so far, now at startProcess: starting to update pids map
2021-09-22 17:11:20.539 549-580/? W/ActivityManager: Slow operation: 59ms so far, now at startProcess: done updating pids map
2021-09-22 17:11:20.547 7462-7462/? W/st.exp.exponen: Unexpected CPU variant for X86 using defaults: x86
2021-09-22 17:11:20.551 7447-7447/? I/app_process: System.exit called, status: 0
2021-09-22 17:11:20.551 7447-7447/? I/AndroidRuntime: VM exiting with result code 0.
2021-09-22 17:11:20.561 7462-7462/? E/st.exp.exponen: Not starting debugger since process cannot load the jdwp agent.
2021-09-22 17:11:20.589 549-2357/? W/InputReader: Device virtio_input_multi_touch_9 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.589 549-2357/? W/InputReader: Device virtio_input_multi_touch_10 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.589 549-2357/? W/InputReader: Device virtio_input_multi_touch_7 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.589 549-2357/? W/InputReader: Device virtio_input_multi_touch_4 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.589 549-2357/? W/InputReader: Device virtio_input_multi_touch_11 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.589 549-2357/? W/InputReader: Device virtio_input_multi_touch_5 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.589 549-2357/? W/InputReader: Device virtio_input_multi_touch_2 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.589 549-2357/? W/InputReader: Device virtio_input_multi_touch_6 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.589 549-2357/? W/InputReader: Device virtio_input_multi_touch_3 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.589 549-2357/? W/InputReader: Device virtio_input_multi_touch_8 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.590 549-2357/? W/InputReader: Device virtio_input_multi_touch_9 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.590 549-2357/? W/InputReader: Device virtio_input_multi_touch_10 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.590 549-2357/? W/InputReader: Device virtio_input_multi_touch_7 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.590 549-2357/? W/InputReader: Device virtio_input_multi_touch_4 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.590 549-2357/? W/InputReader: Device virtio_input_multi_touch_11 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.590 549-2357/? W/InputReader: Device virtio_input_multi_touch_5 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.590 549-2357/? W/InputReader: Device virtio_input_multi_touch_2 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.590 549-2357/? W/InputReader: Device virtio_input_multi_touch_6 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.590 549-2357/? W/InputReader: Device virtio_input_multi_touch_3 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.590 549-2357/? W/InputReader: Device virtio_input_multi_touch_8 is associated with display ADISPLAY_ID_NONE.
2021-09-22 17:11:20.618 7462-7462/? I/st.exp.exponen: The ClassLoaderContext is a special shared library.
2021-09-22 17:11:20.634 7462-7462/? D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2021-09-22 17:11:20.635 7462-7462/? D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2021-09-22 17:11:20.638 7462-7462/? I/MultiDex: VM with version 2.1.0 has multidex support
2021-09-22 17:11:20.638 7462-7462/? I/MultiDex: Installing application
2021-09-22 17:11:20.638 7462-7462/? I/MultiDex: VM has multidex support, MultiDex support library is disabled.
2021-09-22 17:11:20.693 549-571/? D/EventSequenceValidator: inc AccIntentStartedEvents to 1
2021-09-22 17:11:20.693 549-571/? D/EventSequenceValidator: inc AccIntentStartedEvents to 2
2021-09-22 17:11:20.693 433-701/? W/iorapd: Overwriting transition from kActivityLaunched to kIntentStarted into kActivityLaunchCancelled
2021-09-22 17:11:20.694 549-971/? I/ActivityTaskManager: START u0 {act=android.intent.action.VIEW dat=exp://xxxx flg=0x10000000 cmp=host.exp.exponent/.LauncherActivity} from uid 2000
2021-09-22 17:11:20.702 549-571/? D/EventSequenceValidator: dec AccIntentStartedEvents to 1
2021-09-22 17:11:20.702 7488-7496/? I/cmd: oneway function results will be dropped but finished with status OK and parcel size 4
2021-09-22 17:11:20.703 433-701/? W/iorapd: Rejecting transition from kActivityLaunchCancelled to kIntentFailed
2021-09-22 17:11:20.714 7462-7462/? I/FirebaseInitProvider: FirebaseApp initialization successful
2021-09-22 17:11:20.724 7462-7462/? I/FacebookInitProvider: Failed to auto initialize the Facebook SDK
    A valid Facebook app id must be set in the AndroidManifest.xml or set by calling FacebookSdk.setApplicationId before initializing the sdk.
        at com.facebook.FacebookSdk.sdkInitialize(FacebookSdk.java:39)
        at com.facebook.FacebookSdk.sdkInitialize(FacebookSdk.java:9)
        at com.facebook.internal.FacebookInitProvider.onCreate(FacebookInitProvider.java:1)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7239)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-09-22 17:11:20.762 175-175/? I/servicemanager: Notifying apexservice they have clients: 1
2021-09-22 17:11:20.846 7462-7462/? E/f: Failed to clear legacy OkHttp cache
    java.io.IOException: not a readable directory: /data/user/0/host.exp.exponent/files/okhttp
        at okhttp3.internal.io.FileSystem$1.deleteContents(FileSystem.java:7)
        at okhttp3.internal.cache.DiskLruCache.delete(DiskLruCache.java:2)
        at okhttp3.Cache.delete(Cache.java:1)
        at host.exp.exponent.u.f.b(ExponentNetwork.java:4)
        at host.exp.exponent.u.f.<init>(ExponentNetwork.java:7)
        at host.exp.exponent.q.a.<init>(NativeModuleDepsProvider.java:7)
        at host.exp.exponent.q.a.c(NativeModuleDepsProvider.java:2)
        at j.a.a.b.<init>(Exponent.java:7)
        at j.a.a.b.m(Exponent.java:2)
        at host.exp.exponent.i.onCreate(ExpoApplication.java:9)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-09-22 17:11:20.886 7462-7500/? D/FBAudienceNetwork: SDK dex loading time: 128
2021-09-22 17:11:20.894 7462-7462/? D/SoLoader: init start
2021-09-22 17:11:20.894 7462-7462/? D/SoLoader: adding system library source: /vendor/lib
2021-09-22 17:11:20.894 7462-7462/? D/SoLoader: adding system library source: /system/lib
2021-09-22 17:11:20.895 7462-7462/? D/SoLoader: adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/~~6IeMdMfgn8vU6268-yI7qg==/host.exp.exponent-HvbmjAFoQfssLuZI1NtJgg==/lib/x86 flags = 0]
2021-09-22 17:11:20.896 7462-7462/? D/SoLoader: adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/host.exp.exponent/lib-main flags = 1]
2021-09-22 17:11:20.896 7462-7462/? D/SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
2021-09-22 17:11:20.896 7462-7462/? D/SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2]
2021-09-22 17:11:20.896 7462-7462/? D/SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/~~6IeMdMfgn8vU6268-yI7qg==/host.exp.exponent-HvbmjAFoQfssLuZI1NtJgg==/lib/x86 flags = 0]
2021-09-22 17:11:20.896 7462-7462/? D/SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/host.exp.exponent/lib-main flags = 1]
2021-09-22 17:11:20.899 7462-7462/? I/fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/host.exp.exponent/lib-main
2021-09-22 17:11:20.900 7462-7462/? D/SoLoader: init finish: 4 SO sources prepared
2021-09-22 17:11:20.900 7462-7462/? D/SoLoader: init exiting
2021-09-22 17:11:21.024 7462-7504/? E/com.amplitude.api.DeviceInfo: Encountered an error connecting to Google Play Services
    java.lang.NoSuchMethodException: com.google.android.gms.ads.x.a.getAdvertisingIdInfo [class android.content.Context]
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getMethod(Class.java:1693)
        at com.amplitude.api.DeviceInfo$CachedInfo.getAndCacheGoogleAdvertisingId(DeviceInfo.java:2)
        at com.amplitude.api.DeviceInfo$CachedInfo.getAdvertisingId(DeviceInfo.java:3)
        at com.amplitude.api.DeviceInfo$CachedInfo.<init>(DeviceInfo.java:3)
        at com.amplitude.api.DeviceInfo$CachedInfo.<init>(DeviceInfo.java:1)
        at com.amplitude.api.DeviceInfo.getCachedInfo(DeviceInfo.java:2)
        at com.amplitude.api.DeviceInfo.prefetch(DeviceInfo.java:1)
        at com.amplitude.api.AmplitudeClient$1.run(AmplitudeClient.java:10)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2021-09-22 17:11:21.057 7462-7504/? W/com.amplitude.api.DeviceInfo: Google Play Services not available

Any ideas why this is persisting on the new upgrade?

Many thanks

  Expo CLI 4.12.0 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    npmPackages:
      expo: ^42.0.3 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18

**Comment by brentvatne** [comment]
try downgrading to expo-cli@4.11.0 to see if your project will run as you remember: `npm i -g expo-cli@4.11.0`

**Comment by mdarke1** [comment]
Thanks Brent. My apologies - after scaling back the cli to previous versions I found the issue still existed in a fetchFonts async load that was not completing. Disappointingly I was unable to pin point the exact cause, (especially as it was a function that had not changed in months), but closing the issue now.

Thanks for your help.
