### ISSUE TITLE
`run-android` doesn't work with Java 16

### ISSUE THREAD

**Issue by Invertisment** [expo/expo-cli#3873]
### Summary

I get an error when I try to run (expo ejected) on android device when I use `java-16-openjdk` and `android/gradle/wrapper/gradle-wrapper.properties` has `gradle 6.3` in it.

Expo version `42.0.1`
Java version: `java-16-openjdk`

If I change the gradle version to 7.0 then I get a different error because `maven` plugin is deprecated in that version. But that version starts to support Java 16. 

### Environment

java 16
    "expo": "~42.0.1",
    "react-native": "~0.63.4",

### Please specify your device/emulator/simulator platform, model and version

virtual device, API 28

### Error output

Top of the log:
```
yarn react-native run-android --no-packager
yarn run v1.22.4
$ /home/..../project/node_modules/.bin/react-native run-android --no-packager
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1383 file(s) to forward-jetify. Using 4 workers...
info Installing the app...
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Settings file '/home/..../project/android/settings.gradle'

* What went wrong:
Could not compile settings file '/home/..../project/android/settings.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 60
  
  java.lang.IllegalArgumentException: Unsupported class file major version 60
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)
  	at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
  	at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
  	at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
  	at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
  	at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
  	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClassNullable(AsmReferenceResolver.java:57)
  	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClass
```

### Reproducible demo or steps to reproduce from a blank project

I didn't try to create minimal case because I don't have time for it.
I think it should crash every time you want to compile the project with Java 16.
So:
1. install java 16
2. run on android

I use ejected workflow and expo 42 on a new project, if it helps.

The impact is not large, it would be great to be able to use newest tools. That's it.

**Comment by brentvatne** [comment]
you can follow the instructions here for setting up the environment: https://reactnative.dev/docs/0.63/environment-setup#installing-dependencies

jdk 8 is recommended
