### ISSUE TITLE
Error when running expo build:ios - Authentication with Apple Developer Portal failed! Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by ODINSLAYER09** [expo/expo-cli#3949]
### Summary

I have a company managed Apple ID and am using a Macbook with M1 chip. When I try to run expo build:ios, I enter my credentials and I get the error below:

```

Authentication with Apple Developer Portal failed!
Cannot read property 'trim' of undefined
TypeError: Cannot read property 'trim' of undefined
    at /Users/user/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:1031509
    at Array.map (<anonymous>)
    at new ServiceError (/Users/user/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:1031500)
    at assertServiceErrors (/Users/user/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:873662)
    at attemptLoginRequestAsync (/Users/user/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:873227)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.loginWithUserCredentialsAsync (/Users/user/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:871709)
    at loginWithUserCredentialsAsync (/Users/user/.npm-global/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:133:22)
    at loginAsync (/Users/user/.npm-global/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:92:12)
    at authenticateAsync (/Users/user/.npm-global/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:152:23)
```

However, when I try to use my personal Apple ID, I'm getting a 403 error which is at least I know that I don't have access to the organization, which is expected. I'm wondering what the issue could be as the error message when using my company Apple ID is a bit vague.

### Environment

```
  Expo CLI 4.12.10 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.5 - /usr/local/bin/node
      npm: 7.24.1 - ~/.npm-global/bin/npm
    SDKs:
      Android SDK:
        API Levels: 31
        Build Tools: 31.0.0
        System Images: android-31 | Google APIs ARM 64 v8a
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.16.0 => 0.16.0 
      expo: ^42.0.3 => 42.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.12.10
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

Macbook Pro with M1 chip

### Error output

```

$ EXPO_DEBUG=true expo build:ios
✔ Choose the build type you would like: › archive

Checking if there is a build in progress...

Accessing credentials on behalf of priojet in project priojet
✔ Do you have access to the Apple account that will be used for submitting this app to the App Store? … yes

› Log in to your Apple Developer account to continue
✔ Apple ID: … Apple@ID
› The password is only used to authenticate with Apple and never stored on EAS servers
  Learn more: https://bit.ly/2VtGWhU
✔ Password (forApple@ID): … ************
› Saving Apple ID password to the local Keychain
  Learn more: https://docs.expo.dev/distribution/security#keychain
✖ Logging in...
Authentication with Apple Developer Portal failed!
Cannot read property 'trim' of undefined
TypeError: Cannot read property 'trim' of undefined
    at /Users/user/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:1031509
    at Array.map (<anonymous>)
    at new ServiceError (/Users/user/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:1031500)
    at assertServiceErrors (/Users/user/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:873662)
    at attemptLoginRequestAsync (/Users/user/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:873227)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.loginWithUserCredentialsAsync (/Users/user/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:871709)
    at loginWithUserCredentialsAsync (/Users/user/.npm-global/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:133:22)
    at loginAsync (/Users/user/.npm-global/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:92:12)
    at authenticateAsync (/Users/user/.npm-global/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:152:23)

```

### Reproducible demo or steps to reproduce from a blank project

Just run this command on the terminal:

expo build:ios -t archive

**Comment by brentvatne** [comment]
it seems we didn't handle that error well, but apple must not be returning an expected response.

try `EXPO_DEBUG=1 EXPO_APP_STORE_DEBUG=1 expo build:ios -t archive` and share the output

**Comment by ODINSLAYER09** [comment]
@EvanBacon I'm still getting the error after upgrading expo-cli. 

Running this command gives me the following logs:
```

$ EXPO_DEBUG=1 EXPO_APP_STORE_DEBUG=1 expo build:ios -t archive
- Making sure project is set up correctly...

Checking if there is a build in progress...

Accessing credentials on behalf of priojet in project priojet
✔ Do you have access to the Apple account that will be used for submitting this app to the App Store? … yes
-- Enabled debug logging --

› Log in to your Apple Developer account to continue
✔ Apple ID: … Apple@ID
› Using password for Apple@ID from your local Keychain
  Learn more: https://docs.expo.dev/distribution/security#keychain
⠋ Logging in...POST https://idmsa.apple.com/appleauth/auth/signin
⠙ Logging in...Error: Request failed with status code 403 (POST https://idmsa.apple.com/appleauth/auth/signin)
✖ Logging in...
Authentication with Apple Developer Portal failed!
Cannot read property 'trim' of undefined
TypeError: Cannot read property 'trim' of undefined
    at /Users/user/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:1031509
    at Array.map (<anonymous>)
    at new ServiceError (/Users/user/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:1031500)
    at assertServiceErrors (/Users/user/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:873662)
    at attemptLoginRequestAsync (/Users/user/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:873227)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.loginWithUserCredentialsAsync (/Users/user/.npm-global/lib/node_modules/expo-cli/node_modules/@expo/apple-utils/build/index.js:1:871709)
    at loginWithUserCredentialsAsync (/Users/user/.npm-global/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:133:22)
    at loginAsync (/Users/user/.npm-global/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:92:12)
    at authenticateAsync (/Users/user/.npm-global/lib/node_modules/expo-cli/src/appleApi/authenticate.ts:152:23)
```
Not sure if this helps but was building the app tried with an Apple ID that has 2FA works? My company Apple ID is connected to Azure AD that enforces 2FA whenever it is used but I'm not sure if that works with programmatic builds or scripts.
