### ISSUE TITLE
"expo prebuild" not support custom entry file

### ISSUE THREAD

**Issue by nicolas-godefroy-dev** [expo/expo-cli#3950]
### Summary

On a expo managed app with `expo-yarn-workspaces` 

When i build the app with `EAS` or when i run `expo prebuild`

This error is raised
```
warning: the transform cache was reset.
Error: The resource `/build/workingdir/build/apps/customer-mobile/index.js` was not found.
    at /build/workingdir/build/node_modules/metro/src/IncrementalBundler.js:457:26
    at gotStat (fs.js:1864:21)
    at FSReqCallback.oncomplete (fs.js:183:21)
info Run CLI with --verbose flag for more details.
[stderr] error The resource `/build/workingdir/build/apps/customer-mobile/index.js` was not found.
```

### Environment

```
 Expo CLI 4.12.10 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.1 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
      Watchman: 2021.10.18.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.0 => 43.0.1 
      react-native: 0.64.2 => 0.64.2 
    npmGlobalPackages:
      expo-cli: 4.12.10
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

EAS / Simulator: iOS 15 iPhone 13

### Error output

```
warning: the transform cache was reset.
Error: The resource `/build/workingdir/build/apps/customer-mobile/index.js` was not found.
    at /build/workingdir/build/node_modules/metro/src/IncrementalBundler.js:457:26
    at gotStat (fs.js:1864:21)
    at FSReqCallback.oncomplete (fs.js:183:21)
info Run CLI with --verbose flag for more details.
[stderr] error The resource `/build/workingdir/build/apps/customer-mobile/index.js` was not found.
```

### Reproducible demo or steps to reproduce from a blank project

Reproducible by create an expo managed app without `index.js` file
Run `expo prebuild`

add an custom [entryPoint](https://docs.expo.dev/versions/latest/config/app/#entrypoint) by add `expo.entryPoint` in `app.json` not work also

**Comment by brentvatne** [comment]
heya, this is documented here: https://docs.expo.dev/build-reference/migrating/#custom--main--entry-point-in

we hope to have a good solution for it in sdk 44

**Comment by EvanBacon** [comment]
A proper fix for this would require only using expo-dev-client in development, which isn't always the case for many projects. In SDK 45 the production Android case should be fixed in this PR https://github.com/expo/expo/pull/14934

We probably won't implement a full fix for iOS until we have a versioned CLI.
