### ISSUE TITLE
Fetching the user profile failed

### ISSUE THREAD

**Issue by noelzappy** [expo/expo-cli#3983]
### Summary

I'm behind a proxy, I have followed the configuration  from [https://docs.expo.dev/guides/troubleshooting-proxies/](HERE), yet when I do `expo login` I get the following error 
```
Fetching the user profile failed
Request failed with status code 400
Request failed with status code 400
Error: Request failed with status code 400
    at createError (/home/zappy/.nvm/versions/node/v14.18.0/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/zappy/.nvm/versions/node/v14.18.0/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/zappy/.nvm/versions/node/v14.18.0/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

```

![image](https://user-images.githubusercontent.com/38583057/140691373-d8416ae8-6089-4bfd-89af-6479f2ef551c.png)

### Environment

`Expo CLI 4.12.12 environment info:
    System:
      OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v14.18.0/bin/yarn
      npm: 8.1.1 - ~/.nvm/versions/node/v14.18.0/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    npmPackages:
      expo: ^43.0.0 => 43.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
      react-navigation: ^4.0.10 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.12.12
    Expo Workflow: managed
`

### Please specify your device/emulator/simulator platform, model and version

Ubuntu 20.04

### Error output

`Fetching the user profile failed
Request failed with status code 400
Request failed with status code 400
Error: Request failed with status code 400
    at createError (/home/zappy/.nvm/versions/node/v14.18.0/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/zappy/.nvm/versions/node/v14.18.0/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/zappy/.nvm/versions/node/v14.18.0/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
`

### Reproducible demo or steps to reproduce from a blank project

`expo login`

**Comment by brentvatne** [comment]
i believe this was an intermittent server issue, please try again and if the issue persists then let me know

**Comment by noelzappy** [comment]
Ok

**Comment by noelzappy** [comment]
The issue persists. It's not resolved.

**Comment by brentvatne** [comment]
can you try deleting the `~/.expo` directory?
