### ISSUE TITLE
NextJS dynamic import doesn't work 

### ISSUE THREAD

**Issue by AMSTKO** [expo/expo-cli#3986]
### Summary

I would like to load a component dynamically using dynamic import from NextJS (https://nextjs.org/docs/advanced-features/dynamic-import).

On the server side rendering NextJS render the expected html well with my dynamic component,

![image](https://user-images.githubusercontent.com/408968/140975616-686c038c-c881-4083-8339-4f538b72fb25.png)

But there is an error,

![image](https://user-images.githubusercontent.com/408968/140975648-e0e1e649-0776-4e21-941a-dd1e313514b5.png)

The error goes away if I remove the **withExpo** plugins from my **next.config.js** configuration.

I didn't have this error with an older stack (next 10.0.9, @expo/next-adapter 2.1.69) and dynamic importer worked well.

### Environment

expo: ~43.0.0 => 43.0.2
react: 17.0.1 => 17.0.1
react-dom: 17.0.1 => 17.0.1
react-native: 0.64.2 => 0.64.2
react-native-web: 0.17.1 => 0.17.1
expo-cli: 4.12.12
@expo/next-adapter: 3.1.7

### Please specify your device/emulator/simulator platform, model and version

Node: 16.13.0

### Reproducible demo or steps to reproduce from a blank project

- Blank project

```JS
const MyDynamicComponent = dynamic(() => import('../components/MyDynamicComponent'))

export default function App() {
  return (
    <View style={styles.container}>
      <Text style={styles.text}>Welcome to Expo + Next.js 👋</Text>
      <MyDynamicComponent/>
    </View>
  );
}
```

```JS
const MyDynamicComponent = () => {
  return (
    <View>
      <Text>I'm a component 👋</Text>
    </View>
  );
}

export default MyDynamicComponent;
```

- npx next dev
- Open http://localhost:3000/
- See error in console log

**Comment by bhaveshspyhunt** [comment]
nfo  - automatically enabled Fast Refresh for 1 custom loader
error - HookWebpackError: Cannot read property 'replace' of undefined
HookWebpackError: Cannot read property 'replace' of undefined
    at makeWebpackError (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:41630:9)
    at D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:25321:12
    at eval (eval at create (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:140036:10), <anonymous>:12:1)
    at fn (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:22742:17)
    at Hook.eval [as callAsync] (eval at create (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:140036:10), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:139838:14)
    at cont (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:25318:34)
    at D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:25366:10
    at symbolIterator (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\neo-async\async.js:1:14443)
    at done (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\neo-async\async.js:1:14823)
-- inner error --
TypeError: Cannot read property 'replace' of undefined
    at PagesManifestPlugin.createAssets (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\build\webpack\plugins\pages-manifest-plugin.js:35:47)
    at D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\build\webpack\plugins\pages-manifest-plugin.js:47:22
    at fn (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:22740:10)
    at Hook.eval [as callAsync] (eval at create (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:140036:10), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:139838:14)
    at cont (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:25318:34)
    at D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:25366:10
    at symbolIterator (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\neo-async\async.js:1:14443)
    at done (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\neo-async\async.js:1:14823)
    at D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\neo-async\async.js:1:9429
caused by plugins in Compilation.hooks.processAssets
TypeError: Cannot read property 'replace' of undefined
    at PagesManifestPlugin.createAssets (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\build\webpack\plugins\pages-manifest-plugin.js:35:47)
    at D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\build\webpack\plugins\pages-manifest-plugin.js:47:22
    at fn (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:22740:10)
    at Hook.eval [as callAsync] (eval at create (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:140036:10), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:139838:14)
    at cont (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:25318:34)
    at D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:25366:10
    at symbolIterator (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\neo-async\async.js:1:14443)
    at done (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\neo-async\async.js:1:14823)
    at D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\neo-async\async.js:1:9429
error - HookWebpackError: Cannot read property 'replace' of undefined
HookWebpackError: Cannot read property 'replace' of undefined
    at makeWebpackError (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:41630:9)
    at D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:25321:12
    at eval (eval at create (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:140036:10), <anonymous>:12:1)
    at fn (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:22742:17)
    at Hook.eval [as callAsync] (eval at create (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:140036:10), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:139838:14)
    at cont (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:25318:34)
    at D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:25366:10
    at symbolIterator (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\neo-async\async.js:1:14443)
    at done (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\neo-async\async.js:1:14823)
-- inner error --
TypeError: Cannot read property 'replace' of undefined
    at PagesManifestPlugin.createAssets (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\build\webpack\plugins\pages-manifest-plugin.js:35:47)
    at D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\build\webpack\plugins\pages-manifest-plugin.js:47:22
    at fn (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:22740:10)
    at Hook.eval [as callAsync] (eval at create (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:140036:10), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:139838:14)
    at cont (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:25318:34)
    at D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:25366:10
    at symbolIterator (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\neo-async\async.js:1:14443)
    at done (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\neo-async\async.js:1:14823)
    at D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\neo-async\async.js:1:9429
caused by plugins in Compilation.hooks.processAssets
TypeError: Cannot read property 'replace' of undefined
    at PagesManifestPlugin.createAssets (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\build\webpack\plugins\pages-manifest-plugin.js:35:47)
    at D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\build\webpack\plugins\pages-manifest-plugin.js:47:22
    at fn (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:22740:10)
    at Hook.eval [as callAsync] (eval at create (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:140036:10), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:139838:14)
    at cont (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:25318:34)
    at D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\webpack\bundle5.js:25366:10
    at symbolIterator (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\neo-async\async.js:1:14443)
    at done (D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\neo-async\async.js:1:14823)
    at D:\bhavesh_projects\whitelabel-app\node_modules\next\dist\compiled\neo-async\async.js:1:9429
