### ISSUE TITLE
Error running npx install-expo-modules

### ISSUE THREAD

**Issue by Albermonte** [expo/expo-cli#3999]
### Summary

Trying to install Expo modules on a new app, I'm using [rnn-starter](https://github.com/kanzitelli/rnn-starter). Just created a new project, test it was working and then tried to add Expo modules via `npx install-expo-modules`

### Environment

```
expo diagnostics        

  Expo CLI 4.13.0 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 23, 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.1, 30.0.2, 30.0.3, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom
        Android NDK: 23.0.7599858
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    npmPackages:
      react: ^17.0.2 => 17.0.2
      react-native: ^0.66.1 => 0.66.1
    Expo Workflow: bare
```

### Please specify your device/emulator/simulator platform, model and version

-

### Error output

```
npx install-expo-modules
npx: installed 123 in 6.853s
√ Expo modules minimum iOS requirement is 12.0. This tool will change your iOS deployment target to 12.0. Do you want to continue? ... yes
› Updating your project...
Uncaught Error Error: [android.mainApplication]: withAndroidMainApplicationBaseMod: Unable to find ReactNativeHost new instance code block.
    at addReactNativeHostWrapperIfNeeded (C:\Users\alber\AppData\Roaming\npm-cache\_npx\23500\node_modules\install-expo-modules\build\index.js:2:1441989)
    at setModulesMainApplication (C:\Users\alber\AppData\Roaming\npm-cache\_npx\23500\node_modules\install-expo-modules\build\index.js:2:1441513)
    at C:\Users\alber\AppData\Roaming\npm-cache\_npx\23500\node_modules\install-expo-modules\build\index.js:2:1441331
    at action (C:\Users\alber\AppData\Roaming\npm-cache\_npx\23500\node_modules\install-expo-modules\build\index.js:2:1204278)
    at interceptingMod (C:\Users\alber\AppData\Roaming\npm-cache\_npx\23500\node_modules\install-expo-modules\build\index.js:2:1202742)
    at action (C:\Users\alber\AppData\Roaming\npm-cache\_npx\23500\node_modules\install-expo-modules\build\index.js:2:1179856)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async interceptingMod (C:\Users\alber\AppData\Roaming\npm-cache\_npx\23500\node_modules\install-expo-modules\build\index.js:2:1202736)
    at async evalModsAsync (C:\Users\alber\AppData\Roaming\npm-cache\_npx\23500\node_modules\install-expo-modules\build\index.js:2:1186217)
    at async Object.compileModsAsync (C:\Users\alber\AppData\Roaming\npm-cache\_npx\23500\node_modules\install-expo-modules\build\index.js:2:1184935)
```

### Reproducible demo or steps to reproduce from a blank project

Init a new app:
`npx cli-rn new App -t rnn`

Install Expo modules:
`npx install-expo-modules`

**Comment by Kudo** [comment]
hi there! i am sorry we didn't support react-native-navigation in the meantime. you can still look into the manual installation guide: https://docs.expo.dev/bare/installing-expo-modules/#manual-installation
i think the major difference is that RNN has the [`NavigationReactNativeHost`](https://github.com/kanzitelli/rnn-starter/blob/cfb2dc24136d8f0aa5b0b7f44aab589c7bcf5db6/android/app/src/main/java/com/rnnstarter/MainApplication.java#L27). you could still try to wrap it like 
```java
new ReactNativeHostWrapper(this, new NavigationReactNativeHost(this) ...);
```

let us know if that works for you. thanks!

**Comment by Albermonte** [comment]
Switching to `React Navigation (v6)` did the trick

**Comment by Kudo** [comment]
thanks for your confirmation. maybe there's more steps to make expo and rnn work together. 🤔

**Comment by LeeJunhui** [comment]
> Switching to `React Navigation (v6)` did the trick
> 
> > i think the major difference is that RNN has the NavigationReactNativeHost. you could still try to wrap it like
> 
> That didn't work, more errors were popping

Hello，did rnn v7 work with the latest expo? I faced with the same issue on running npx install-expo-modules

**Comment by Kudo** [comment]
i'm sorry that it looks like not supported still.

**Comment by barakoles** [comment]
Hi there. Any news on this? I'm using a package that depends on expo, and the project uses RNN. I'm unable to run the command to install and can't roll back to react-navigation
