### ISSUE TITLE
[installNodeDependenciesAsync] Error on eas build PREBUILD stage

### ISSUE THREAD

**Issue by SrBrahma** [expo/expo-cli#4002]
### Summary

It happens on EAS build, but as the error happens inside `installNodeDependenciesAsync`, that is from this lib, I am posting it here.

I already had build a few times my EAS android apk project. But, I **think** this is the first time after setting my monorepo (yarn-workspace + expo-yarn-workspaces). While the monorepo was working before, today I had to rebuild it again to add a new package. It doesn't matter the new package, because I removed it and the following error keeps happening:

I call my `eas build --profile development --platform android --local` script, and on PREBUILD stage it throws an error without any further explanation. Already tried with `--clear-cache` flag, no change.

I had `npm i -g eas-cli-local-build-plugin` as I saw in an issue, but it only has added the `[PREBUILD] ✖ Something went wrong installing JavaScript dependencies, check your yarn logfile or run yarn install again manually.` message. But, I can't find any yarn log to track down the error. Maybe it isn't calling the postinstall script that expo-yarn-workspaces requires?

I can `yarn install` without any issues. I don't have a clue on why this is happening.

### Environment

Expo CLI 4.13.0 environment info:
    System:
      OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 14.18.0 - ~/n/bin/node
      Yarn: 3.1.0 - ~/n/bin/yarn
      npm: 8.1.3 - ~/n/bin/npm
      Watchman: 4.9.0 - /home/linuxbrew/.linuxbrew/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 28, 29, 30
        Build Tools: 29.0.2, 30.0.3
        System Images: android-28 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7042882
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Happens on cli build.

### Error output

// [...] Other INSTALL_DEPENDENCIES messages
[INSTALL_DEPENDENCIES] ➤ YN0007: │ app-f43f79@workspace:app must be built because it never has been before or the last one failed
[INSTALL_DEPENDENCIES] ➤ YN0007: │ core-js@npm:3.6.5 must be built because it never has been before or the last one failed
[INSTALL_DEPENDENCIES] ➤ YN0007: │ protobufjs@npm:6.11.2 must be built because it never has been before or the last one failed
[INSTALL_DEPENDENCIES] ➤ YN0000: └ Completed in 54s 145ms
[INSTALL_DEPENDENCIES] ➤ YN0000: Done with warnings in 1m 5s
[READ_APP_CONFIG] Using app configuration:
[READ_APP_CONFIG] {
  "packagerOpts": {
    "projectRoots": [
      "",
      "../firebase/functions/src/shared"
    ]
  },
  "name": "Ahive",
  "slug": "Ahive",
  "version": "1.0.0",
  "orientation": "portrait",
  "icon": "./assets/icon.png",
  "scheme": "ahive",
  "userInterfaceStyle": "light",
  "splash": {
    "image": "./assets/splash.png",
    "resizeMode": "cover",
    "backgroundColor": "#ffc138"
  },
  "updates": {
    "fallbackToCacheTimeout": 0
  },
  "assetBundlePatterns": [
    "**/*"
  ],
  "androidNavigationBar": {
    "backgroundColor": "#ffc138"
  },
  "ios": {
    "supportsTablet": true,
    "bundleIdentifier": "com.tekhni.ahive"
  },
  "android": {
    "softwareKeyboardLayoutMode": "pan",
    "package": "com.tekhni.ahive"
  },
  "web": {
    "favicon": "./assets/favicon.png",
    "build": {
      "babel": {
        "include": [
          "react-router-native"
        ]
      }
    }
  },
  "sdkVersion": "43.0.0",
  "platforms": [
    "ios",
    "android",
    "web"
  ],
  "currentFullName": "@srbrahma/Ahive",
  "originalFullName": "@srbrahma/Ahive"
}
[PREBUILD] - Creating native project directories (./ios and ./android) and updating .gitignore
[PREBUILD] ✔ Created native project
[PREBUILD] - Adding Metro bundler config
[PREBUILD] ⚠️  Skipped Metro config updates:
[PREBUILD] › Existing Metro config found; not overwriting.
[PREBUILD] › You will need to extend the default @expo/metro-config in your Metro config.
[PREBUILD]   Learn more: https://docs.expo.dev/guides/customizing-metro
[PREBUILD] - Updating your package.json scripts, dependencies, and main file
[PREBUILD] ✔ Updated package.json and added index.js entry point for iOS and Android
[PREBUILD] [18:17:23] 🧶 Using Yarn to install packages. Pass --npm to use npm instead.
[PREBUILD] - Installing JavaScript dependencies
[PREBUILD] ✖ Something went wrong installing JavaScript dependencies, check your yarn logfile or run yarn install again manually.
[PREBUILD] 
Error: /home/hb/n/lib/node_modules/eas-cli-local-build-plugin/node_modules/expo-cli/bin/expo.js exited with non-zero code: 1
    at ChildProcess.completionListener (/home/hb/n/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
    ...
    at Object.spawnAsync [as default] (/home/hb/n/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at Object.spawn [as default] (/home/hb/n/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/turtle-spawn/dist/index.js:17:42)
    at LocalExpoCliEjectProvider.runEject (/home/hb/n/lib/node_modules/eas-cli-local-build-plugin/dist/eject.js:21:37)
    at ejectProject (/home/hb/n/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/builders/android.js:76:29)
    at /home/hb/n/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/builders/android.js:21:19
    at BuildContext.runBuildPhase (/home/hb/n/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/context.js:44:34)
    at Object.androidBuilder (/home/hb/n/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/builders/android.js:20:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.buildAndroidAsync (/home/hb/n/lib/node_modules/eas-cli-local-build-plugin/dist/android.js:43:27)
    at async Object.buildAsync (/home/hb/n/lib/node_modules/eas-cli-local-build-plugin/dist/build.js:23:32)

Build failed
/home/hb/n/lib/node_modules/eas-cli-local-build-plugin/node_modules/expo-cli/bin/expo.js exited with non-zero code: 1

### Reproducible demo or steps to reproduce from a blank project

I don't really know how could I setup a demo for it. I ain't sure what is causing it to isolate the issue.

**Comment by SrBrahma** [comment]
The following is my metro.config.js

<details>
const { createMetroConfiguration } = require('expo-yarn-workspaces');
const { getDefaultConfig } = require('@expo/metro-config');
const path = require('path');

module.exports = {
  // v For eas build, it was complaining it wasn't extending @expo/metro-config.
  // based on https://docs.expo.dev/guides/customizing-metro/#adding-more-file-extensions-to--assetexts
  ...getDefaultConfig(__dirname),
  ...createMetroConfiguration(__dirname),
};
</details>

**Comment by SrBrahma** [comment]
Maybe related to https://github.com/expo/expo-cli/issues/3950, as `expo-yarn-workspaces` changes main to `"__generated__/AppEntry.js"`?

If so, what can I do as workaround until the fix? I am on the final stages of my test release, so I am kinda afraid and confused on how to deal with this :/

**Comment by SrBrahma** [comment]
I have fixed by leaving expo-yarn-workspaces and following https://github.com/byCedric/eas-monorepo-example/ with a few changes to fit my project. I will leave this open as a suggestion to improve the error message in

```
[PREBUILD] - Installing JavaScript dependencies
[PREBUILD] ✖ Something went wrong installing JavaScript dependencies, check your yarn logfile or run yarn install again manually.
[PREBUILD] 
```
