### ISSUE TITLE
[install-expo-modules] Cannot find target at Podfile - targetName

### ISSUE THREAD

**Issue by wbroek** [expo/expo-cli#4016]
### Summary

Adding the new Expo modules to my iOS project by running `npx install-expo-modules` in the root folder.
When run the first question **Expo modules minimum iOS requirement is 12.0. This tool will change your iOS deployment target to 12.0. Do you want to continue?** is show and when pressed Y(es) you will get the error: 
```
Uncaught Error Error: [ios.dangerous]: withIosDangerousBaseMod: Cannot find target at Podfile - targetName[MyApp]
    at updatePodfile (/Users/wouter/stack/Projects/Clinicards/MyApp/node_modules/install-expo-modules/build/index.js:2:1449368)
    at /Users/wouter/stack/Projects/Clinicards/MyApp/node_modules/install-expo-modules/build/index.js:2:1448904
    at async action (/Users/wouter/stack/Projects/Clinicards/MyApp/node_modules/install-expo-modules/build/index.js:2:1204272)
    at async interceptingMod (/Users/wouter/stack/Projects/Clinicards/MyApp/node_modules/install-expo-modules/build/index.js:2:1202736)
    at async interceptingMod (/Users/wouter/stack/Projects/Clinicards/MyApp/node_modules/install-expo-modules/build/index.js:2:1202736)
    at async action (/Users/wouter/stack/Projects/Clinicards/MyApp/node_modules/install-expo-modules/build/index.js:2:1179850)
    at async interceptingMod (/Users/wouter/stack/Projects/Clinicards/MyApp/node_modules/install-expo-modules/build/index.js:2:1202736)
    at async evalModsAsync (/Users/wouter/stack/Projects/Clinicards/MyApp/node_modules/install-expo-modules/build/index.js:2:1186217)
    at async Object.compileModsAsync (/Users/wouter/stack/Projects/Clinicards/MyApp/node_modules/install-expo-modules/build/index.js:2:1184935)
    at async runAsync (/Users/wouter/stack/Projects/Clinicards/MyApp/node_modules/install-expo-modules/build/index.js:2:1437878)
```

After some research I found that ` install-expo-modules` fetched the [project name](https://github.com/expo/expo-cli/blob/b5b75ad43a072e2e7ea0e2b1656d4d6b463ee8cc/packages/install-expo-modules/src/plugins/ios/withIosModulesPodfile.ts#L6) of the Xcode project and looks in the pod file for that project name
But my project is called differently than my targets and scheme in Xcode so also in my pod file they are name differently.
Project: MyApp
Targets: MyApp production
Podfile: target 'MyApp production' do
<img width="200" alt="image" src="https://user-images.githubusercontent.com/73628/142214386-c8e8aed8-467f-40f5-8012-d71aef50113e.png">

### Environment

Expo CLI 4.12.12 environment info:
    System:
      OS: macOS 11.6.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - /usr/local/opt/node@14/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/opt/node@14/bin/npm
      Watchman: 2021.10.18.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 23, 25, 26, 27, 28, 29, 30
        Build Tools: 25.0.2, 25.0.3, 26.0.3, 27.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
        System Images: android-29 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom_64
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.2 => 17.0.2 
      react-native: 0.66.3 => 0.66.3 
    npmGlobalPackages:
      expo-cli: 4.12.12
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

iOS

### Error output

Uncaught Error Error: [ios.dangerous]: withIosDangerousBaseMod: Cannot find target at Podfile - targetName[MyApp]
    at updatePodfile (/Users/wouter/stack/Projects/Clinicards/MyApp/node_modules/install-expo-modules/build/index.js:2:1449368)
    at /Users/wouter/stack/Projects/Clinicards/MyApp/node_modules/install-expo-modules/build/index.js:2:1448904
    at async action (/Users/wouter/stack/Projects/Clinicards/MyApp/node_modules/install-expo-modules/build/index.js:2:1204272)
    at async interceptingMod (/Users/wouter/stack/Projects/Clinicards/MyApp/node_modules/install-expo-modules/build/index.js:2:1202736)
    at async interceptingMod (/Users/wouter/stack/Projects/Clinicards/MyApp/node_modules/install-expo-modules/build/index.js:2:1202736)
    at async action (/Users/wouter/stack/Projects/Clinicards/MyApp/node_modules/install-expo-modules/build/index.js:2:1179850)
    at async interceptingMod (/Users/wouter/stack/Projects/Clinicards/MyApp/node_modules/install-expo-modules/build/index.js:2:1202736)
    at async evalModsAsync (/Users/wouter/stack/Projects/Clinicards/MyApp/node_modules/install-expo-modules/build/index.js:2:1186217)
    at async Object.compileModsAsync (/Users/wouter/stack/Projects/Clinicards/MyApp/node_modules/install-expo-modules/build/index.js:2:1184935)
    at async runAsync (/Users/wouter/stack/Projects/Clinicards/MyApp/node_modules/install-expo-modules/build/index.js:2:1437878)

### Reproducible demo or steps to reproduce from a blank project

- npx react-native init MyApp
- open project in Xcode
- rename target "MyApp" to "MyApp production"
<img width="197" alt="image" src="https://user-images.githubusercontent.com/73628/142213798-285adb76-71a9-4e99-a33f-2ffc341ac9ef.png">
- adjust `Podfile` and rename "MyApp" to "MyApp production" (and run npx pod-install)
- run `npx install-expo-modules`

**Comment by Kudo** [comment]
hi there! thanks for reporting this issue to us. i am hesitant to provide a fix for this nevertheless. the reason is that there's too much possibility for customization. apps may have multiple targets and we may to differentiate which are the app targets. even in Podfile, there's also the `abstract_target`. so my thought is about to support classic react-native. otherwise we recommend to use the [manual installation](https://docs.expo.dev/bare/installing-expo-modules/#manual-installation). how do you think about this?

**Comment by wbroek** [comment]
Hi @Kudo
thank you for your response and thought maybe there a quick fix to see the targets but you are right there are multiple ways for customisation and it will take too much to support them all. Supporting the classic/default React Native works (tested that too).
Fixed it by using the manual insulation so can confirm that works. Will close the issue and have it as reference for every one else

**Comment by Kudo** [comment]
thanks @wbroek! welcome for any other feedback for install-expo-modules.
