### ISSUE TITLE
yarn pod-install not retrying with repo-update when it could resolve problem by updating

### ISSUE THREAD

**Issue by mikehardy** [expo/expo-cli#4051]
### Summary

When pod repo is out of date and pod install fails with string `pod repo update` in pod error, pod-install does not detect it and just hard fails instead of attempting to fix.

I'm aware of the work here - I took a quick spelunk through the code to see if I could snipe it -
https://github.com/expo/expo-cli/pull/3399/files#diff-81dde81e701f92cc29f402f4c34fc9d752a1dafcf20741a87034333f5b2b6130R207

But for some reason stdout and stderr were empty strings

### Environment

macos big sur
pod 1.11.2
yarn 1.22.17
all else as from the template cloned out

### Please specify your device/emulator/simulator platform, model and version

it's a CLI thing, just pod install

### Error output

You can see empty stdout/stderr strings, so there's nothing to look in to find `pod repo update` string, even though the error from cocoapods is clearly showing it on console prior to the failure.

Looks like a failure to capture streams somehow?

```
$ pod-install --repo-update
Scanning for pods...
1.11.2
> pod install
RNFBAnalytics: Using default Firebase/Analytics with Ad Ids. May require App Tracking Transparency. Not allowed for Kids apps.
RNFBAnalytics: You may set variable `$RNFirebaseAnalyticsWithoutAdIdSupport=true` in Podfile to use analytics without ad ids.
Using firebase.json from '/Users/mike/work/Invertase/react-native-firebase-authentication-example/template/firebase.json'
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Adding a custom script phase for Pod RNFBCrashlytics: [RNFB] Crashlytics Configuration
Auto-linking React Native modules for target `ProjectName`: RNAppleAuthentication, RNCMaskedView, RNFBAnalytics, RNFBApp, RNFBAuth, RNFBCrashlytics, RNFBPerf, RNGestureHandler, RNGoogleSignin, RNLocalize, RNScreens, RNVectorIcons, react-native-fbsdk-next, react-native-pager-view, and react-native-safe-area-context
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
RNFBAnalytics: Using default Firebase/Analytics with Ad Ids. May require App Tracking Transparency. Not allowed for Kids apps.
RNFBAnalytics: You may set variable `$RNFirebaseAnalyticsWithoutAdIdSupport=true` in Podfile to use analytics without ad ids.
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] CocoaPods could not find compatible versions for pod "Firebase/Performance":
  In Podfile:
    RNFBPerf (from `../node_modules/@react-native-firebase/perf`) was resolved to 13.1.0, which depends on
      Firebase/Performance (= 8.10.0)

None of your spec sources contain a spec satisfying the dependency: `Firebase/Performance (= 8.10.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Aborting run
An unexpected error was encountered. Please report it as a bug:
CocoaPodsError: Command `pod install` failed.
└─ Cause: pod exited with non-zero code: 31
    at CocoaPodsPackageManager._installAsync (/Users/mike/work/Invertase/react-native-firebase-authentication-example/template/node_modules/pod-install/build/index.js:2:92213)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async CocoaPodsPackageManager.installAsync (/Users/mike/work/Invertase/react-native-firebase-authentication-example/template/node_modules/pod-install/build/index.js:2:90176)
    at async runAsync (/Users/mike/work/Invertase/react-native-firebase-authentication-example/template/node_modules/pod-install/build/index.js:2:106198)
    at async /Users/mike/work/Invertase/react-native-firebase-authentication-example/template/node_modules/pod-install/build/index.js:2:106284 {
  code: 'COMMAND_FAILED',
  cause: Error: pod exited with non-zero code: 31
      at ChildProcess.h (/Users/mike/work/Invertase/react-native-firebase-authentication-example/template/node_modules/pod-install/build/index.js:2:1073)
      at Object.onceWrapper (events.js:520:26)
      at ChildProcess.emit (events.js:400:28)
      at maybeClose (internal/child_process.js:1058:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
      ...
      at Object.spawnAsync [as default] (/Users/mike/work/Invertase/react-native-firebase-authentication-example/template/node_modules/pod-install/build/index.js:2:558)
      at CocoaPodsPackageManager._runAsync (/Users/mike/work/Invertase/react-native-firebase-authentication-example/template/node_modules/pod-install/build/index.js:2:92995)
      at CocoaPodsPackageManager._installAsync (/Users/mike/work/Invertase/react-native-firebase-authentication-example/template/node_modules/pod-install/build/index.js:2:90499)
      at CocoaPodsPackageManager.installAsync (/Users/mike/work/Invertase/react-native-firebase-authentication-example/template/node_modules/pod-install/build/index.js:2:90187)
      at runAsync (/Users/mike/work/Invertase/react-native-firebase-authentication-example/template/node_modules/pod-install/build/index.js:2:106206)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async /Users/mike/work/Invertase/react-native-firebase-authentication-example/template/node_modules/pod-install/build/index.js:2:106284 {
    pid: 52289,
    output: [ '', '' ],
    stdout: '',
    stderr: '',
    status: 31,
    signal: null
  },
  isPackageManagerError: true
}

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproducible demo or steps to reproduce from a blank project

```bash
git clone https://github.com/invertase/react-native-firebase-authentication-example 
cd react-native-firebase-authentication-emplate
yarn
yarn ios:pods
```

Note: you need to have a case where your repo does not include firebase-ios-sdk cocoapods 8.10.0 release, *or* you can force the test by editing the Podfile and adding a non-existent future version via override 

> sed -i -e $'s/  target \'ProjectNameTests\' do/  $FirebaseSDKVersion = \'8.42.0\'\\\n  target \'ProjectNameTests\' do/' ios/Podfile

With an override like that it should attempt to install the non-existent version, it should throw the error suggesting an update might fix, and in my environment at least pod-install just exits 1

This auto-fix capability was the main benefit of pod-install over time (after first install) so it would be great if it worked

**Comment by mikehardy** [comment]
For the avoidance of doubt, simply running `pod install --repo-update` did resolve it for me, on a valid version.

**Comment by mikehardy** [comment]
Winter holidays really slowed things down but just wanted to confirm that your fix did the trick @EvanBacon when firebase-ios-sdk did a release just yesterday which normally triggers this Podfile.lock / incompatible versions / need to pod update snarl. pod-install handled it perfectly this time - thanks!
