### ISSUE TITLE
PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by buffaloDeveloper** [expo/expo-cli#4067]
### Summary

I get this error in Expo Android, but not on Expo Web.  I don't have any console.log statements that could trigger this.

### Environment

Expo CLI 5.0.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - /usr/local/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 8.3.0 - /usr/local/bin/npm
      Watchman: 2021.09.27.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^43.0.0 => 43.0.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.0
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Google Pixel 3

### Error output

PayloadTooLargeError: request entity too large
    at readStream (/usr/local/lib/node_modules/expo-cli/node_modules/raw-body/index.js:155:17)
    at getRawBody (/usr/local/lib/node_modules/expo-cli/node_modules/raw-body/index.js:108:12)
    at read (/usr/local/lib/node_modules/expo-cli/node_modules/body-parser/lib/read.js:77:3)
    at jsonParser (/usr/local/lib/node_modules/expo-cli/node_modules/body-parser/lib/types/json.js:135:5)
    at call (/usr/local/lib/node_modules/expo-cli/node_modules/connect/index.js:239:7)
    at next (/usr/local/lib/node_modules/expo-cli/node_modules/connect/index.js:183:5)
    at remoteDevtoolsCorsMiddleware (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/dev-server/src/middleware/remoteDevtoolsCorsMiddleware.ts:31:3)
    at call (/usr/local/lib/node_modules/expo-cli/node_modules/connect/index.js:239:7)
    at next (/usr/local/lib/node_modules/expo-cli/node_modules/connect/index.js:183:5)
    at serveStatic (/usr/local/lib/node_modules/expo-cli/node_modules/serve-static/index.js:75:16)
    at call (/usr/local/lib/node_modules/expo-cli/node_modules/connect/index.js:239:7)
    at next (/usr/local/lib/node_modules/expo-cli/node_modules/connect/index.js:183:5)
    at call (/usr/local/lib/node_modules/expo-cli/node_modules/connect/index.js:248:3)
    at next (/usr/local/lib/node_modules/expo-cli/node_modules/connect/index.js:183:5)
    at next (/usr/local/lib/node_modules/expo-cli/node_modules/connect/index.js:161:14)
    at next (/usr/local/lib/node_modules/expo-cli/node_modules/connect/index.js:161:14)

### Reproducible demo or steps to reproduce from a blank project

Not doing anything crazy here.  Just rendering a victory chart.

```
import * as React from "react";
import { VictoryTheme, VictoryChart, VictoryAxis, VictoryLine, VictoryScatter, createContainer, LineSegment, VictoryLabel } from 'victory';
import { useThemeContext } from 'nextga-app-provider';

const VictoryCustomCursor = createContainer("cursor");

function TradeChart (props) {

  const { theme, Layout } = useThemeContext();

  return (
    <VictoryChart
      /**********
         The width/height values are not enforced as static measures
         but to create a scaling ratio of x to y; so adjust to fit,
         and let it scale naturally in its container
      **********/
      style={{
        parent: {
          border: `1px solid ${theme.colors.border}`
        },
        background: {
          fill: theme.colors.card
        }
      }}
      width={Layout.window.width*.9}
      height={Layout.window.height*.5}
      padding={{ top: 0, bottom: 40, left: 65, right: 2 }}
      theme={VictoryTheme.material}
      animate={{ duration: 2000, easing: "quadInOut" }}
      containerComponent={
        <VictoryCustomCursor 
          cursorLabel={({ datum }) => `${datum.y.toLocaleString()}`}
          cursorLabelComponent={<VictoryLabel style={[{fill: theme.colors.text}]}/>}
          cursorComponent={
            <LineSegment 
              style={{ stroke: theme.colors.primary }}
            />
          }
        />
      }
      domainPadding={{ x: 25 }}
      scale={{ x: "time" }}
    >
      <VictoryAxis style={{grid: { stroke: 'transparent' }}} />
      <VictoryAxis dependentAxis style={{grid: { stroke: 'transparent' }}} />
      <VictoryScatter
        style={{ data: { fill: "green", fillOpacity: 0.8, } }}
        data={props.buys}
      />
      <VictoryScatter
        style={{ data: { fill: "red", fillOpacity: 0.8, } }}
        data={props.sells}
      />
      <VictoryLine
        interpolation="linear"
        style={{
          data: { stroke: "#000000" },
          parent: { border: `1px solid ${theme.colors.border}` }
        }}
        data={props.price}
      />
    </VictoryChart>
  )
}

export default TradeChart;
```

**Comment by EvanBacon** [comment]
This is expected behavior that happens when console log sends a message that is too large.

**Comment by buffaloDeveloper** [comment]
It was something different this time.  I was using "victory" from victory charts, which is just for the web.  They have another package called "victory-native" for android/ios.
