### ISSUE TITLE
Windows 11 - Debugger not working

### ISSUE THREAD

**Issue by kadirguloglu** [expo/expo-cli#4101]
### Summary

I am using windows 11. debug remote not working

### Environment

Command failed: wmic os get Caption
'wmic' is not recognized as an internal or external command,
operable program or batch file.

Error: Command failed: wmic os get Caption
'wmic' is not recognized as an internal or external command,
operable program or batch file.

    at b (C:\Users\teah_\AppData\Roaming\npm\node_modules\expo-cli\node_modules\envinfo\dist\envinfo.js:1:95241)
    at Function.e.exports.sync (C:\Users\teah_\AppData\Roaming\npm\node_modules\expo-cli\node_modules\envinfo\dist\envinfo.js:1:97104)
    at e.exports (C:\Users\teah_\AppData\Roaming\npm\node_modules\expo-cli\node_modules\envinfo\dist\envinfo.js:1:93458)
    at e.exports (C:\Users\teah_\AppData\Roaming\npm\node_modules\expo-cli\node_modules\envinfo\dist\envinfo.js:1:92605)
    at C:\Users\teah_\AppData\Roaming\npm\node_modules\expo-cli\node_modules\envinfo\dist\envinfo.js:1:91355
    at async Promise.all (index 0)
    at actionAsync (C:\Users\teah_\AppData\Roaming\npm\node_modules\expo-cli\src\commands\info\diagnosticsAsync.ts:41:16)
- 🔍 Creating Diagnostics

### Please specify your device/emulator/simulator platform, model and version

Android Emulator - Pixel_2_API_26:5554

### Error output

info Launching Dev Tools...
C:\Users\teah_\Desktop\Project\BotMobil\node_modules\metro-hermes-compiler\src\emhermesc.js:81
          throw ex;
          ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [ '/c', 'start', '""', '/b', 'http://localhost:19000/debugger-ui' ]
}

### Reproducible demo or steps to reproduce from a blank project

info Launching Dev Tools...
C:\Users\teah_\Desktop\Project\BotMobil\node_modules\metro-hermes-compiler\src\emhermesc.js:81
          throw ex;
          ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [ '/c', 'start', '""', '/b', 'http://localhost:19000/debugger-ui' ]
}

**Comment by kbrandwijk** [comment]
Related: https://winaero.com/microsoft-removed-the-wmic-tool-from-windows-11-dev-builds/
`wmic` is no longer available.
