### ISSUE TITLE
npx expo-optimize fails

### ISSUE THREAD

**Issue by CCCoderDE** [expo/expo-cli#4128]
### Summary

expo-optimize fails and tells me to report this as a bug, which I am doing here :) 

### Environment

$ expo diagnostics
- 🔍 Creating Diagnostics
[18:22:17] 
  Expo CLI 5.0.3 environment info:
    System:
      OS: Linux 4.15 Alpine Linux
      Shell: 1.33.1 - /bin/ash
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
    npmPackages:
      expo: ^44.0.4 => 44.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.66.4 => 0.66.4 
      react-native-web: 0.17.5 => 0.17.5 
    npmGlobalPackages:
      eas-cli: 0.43.0
      expo-cli: 5.0.3
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

ubuntu 18.04.6 lts, docker with node:lts-alpine (gitlab runner)

### Error output

$ npx expo-optimize
This will overwrite the original assets.
› Optimizing assets...
› Creating .expo-shared/assets.json in the project's root directory.
› This file is autogenerated and should not be edited directly.
› You should commit this to git so that asset state is shared between collaborators.
Aborting run
An unexpected error was encountered. Please report it as a bug:
Error: sharp exited with signal: SIGSEGV
    at ChildProcess.m (/usr/local/lib/node_modules/expo-optimize/build/index.js:2:18893)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    ...
    at Object.spawnAsync [as default] (/usr/local/lib/node_modules/expo-optimize/build/index.js:2:18421)
    at Object.sharpAsync (/usr/local/lib/node_modules/expo-optimize/build/index.js:2:1949503)
    at async optimizeImageAsync (/usr/local/lib/node_modules/expo-optimize/build/index.js:2:2017576)
    at async /usr/local/lib/node_modules/expo-optimize/build/index.js:2:2020117 {
  pid: 563,
  output: [ '', '' ],
  stdout: '',
  stderr: '',
  status: null,
  signal: 'SIGSEGV'
}

### Reproducible demo or steps to reproduce from a blank project

I don't know, the log tells me to report it, so I am doing it here. I just run expo-optimize on my project and a few weeks ago the same build worked perfectly

**Comment by CCCoderDE** [comment]
It seems that this is caused to the alpine image. When using a non-alpine docker image, it works. Is this intended/known?
