### ISSUE TITLE
updating expo-cli from 2.11.6 to 2.11.7 or 2.11.9 on OSX: throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by lc3t35** [expo/expo-cli#413]
## Observed Behavior

When updating expo-cli from 2.11.6 to 2.11.7, 

````
% npm install -g expo-cli
events.js:183░░░░░░⸩ ⠙ extract:faye-websocket: sill extract semver@5.6.0
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
events.js:183░░░░░░⸩ ⠹ extract:@expo/webpack-config: sill extract debug@4.1.1
      throw er; // Unhandled 'error' event
...
Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/workbox-sw-2505eb92/README.md'
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/brotli-webpack-plugin-e7e5a61c/yarn.lock'
WARN tar ENOENT: no such file or directory, lstat '/Users/laurent/.npm-global/lib/node_modules/.staging/@expo/dev-tools-fddbc793/build/client'
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/workbox-cache-expiration-be516240/build/workbox-cache-expiration.dev.js.map'
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/fs-extra-410be959/lib/remove/rimraf.js'
WARN tar ENOENT: no such file or directory, lstat '/Users/laurent/.npm-global/lib/node_modules/.staging/fs-extra-410be959/lib/util'
WARN tar ENOENT: no such file or directory, lstat '/Users/laurent/.npm-global/lib/node_modules/.staging/fs-extra-410be959/lib/util'
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/workbox-navigation-preload-4fd8338d/_version.mjs'
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/workbox-navigation-preload-4fd8338d/browser.mjs'
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/workbox-navigation-preload-4fd8338d/disable.mjs'
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/workbox-navigation-preload-4fd8338d/enable.mjs'
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/workbox-navigation-preload-4fd8338d/index.mjs'
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/workbox-navigation-preload-4fd8338d/README.md'
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/webpack-bundle-analyzer-99da071c/public/viewer.js.map'
npm WARN ts-pnp@1.0.1 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/traveling-fastlane-linux@1.8.0 (node_modules/expo-cli/node_modules/@expo/traveling-fastlane-linux):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cancel after 1 retries!

npm ERR! cancel after 1 retries!
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/workbox-routing-fa80e1a1/build/workbox-routing.prod.js'
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/workbox-routing-fa80e1a1/build/workbox-routing.prod.js.map'
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/workbox-webpack-plugin-8bb39ee0/build/lib/resolve-webpack-url.js'
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/workbox-webpack-plugin-8bb39ee0/build/lib/sanitize-config.js'
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/workbox-webpack-plugin-8bb39ee0/build/lib/stringify-manifest.js'
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/workbox-webpack-plugin-8bb39ee0/build/lib/warn-about-config.js'
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/react-dev-utils-9c7ed52b/typescriptFormatter.js'
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/react-dev-utils-9c7ed52b/WatchMissingNodeModulesPlugin.js'
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/react-dev-utils-9c7ed52b/WebpackDevServerUtils.js'
````

## Environment

````
Expo CLI 2.11.6 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      Yarn: 1.13.0 - ~/.yarn/bin/yarn
      npm: 5.7.1 - ~/.npm-global/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: 32.0.6 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.3.2 => 3.3.2 
    npmGlobalPackages:
      expo-cli: 2.11.6
````

**Comment by lc3t35** [comment]
It is still the same from 2.11.6 to 2.11.9 : 
````
npm install -g expo-cli
events.js:183░░░░░░⸩ ⠹ extract:is-fullwidth-code-point: sill extract fs-extra@4
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
events.js:183░░░░░░⸩ ⠼ extract:workbox-streams: sill extract sockjs@0.3.19
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
events.js:183░░░░░░⸩ ⠸ extract:webpack-manifest-plugin: sill extract acorn@6.1.
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:553:10)
    at ReadEntry.entry.on (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Users/laurent/.npm-global/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/@expo/traveling-fastlane-linux-3c13c298/traveling-fastlane-1.7.1-linux-x86_64/lib/ruby/bin.real/thin'
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/@expo/traveling-fastlane-linux-3c13c298/traveling-fastlane-1.7.1-linux-x86_64/lib/ruby/bin.real/unicorn'
WARN tar ENOENT: no such file or directory, open '/Users/laurent/.npm-global/lib/node_modules/.staging/@expo/traveling-fastlane-linux-3c13c298/traveling-fastlane-1.7.1-linux-x86_64/lib/ruby/bin.real/unicorn_rails'
WARN tar ENOENT: no such file or directory, lstat '/Users/laurent/.npm-global/lib/node_modules/.staging/@expo/traveling-fastlane-linux-3c13c298/traveling-fastlane-1.7.1-linux-x86_64/lib'
....
````

**Comment by lc3t35** [comment]
here is the log, but found no relevant information to investigate ...
[2019-03-17T08_41_09_722Z-debug.log](https://github.com/expo/expo-cli/files/2974950/2019-03-17T08_41_09_722Z-debug.log)

**Comment by lc3t35** [comment]
@charliecruzan pointed on the [expo forum](https://forums.expo.io/t/cannot-update-expo-cli-to-2-11-9-on-osx/20639) that it's working fine with npm 6.9.0.
I've succeeded to update with `yarn global add expo-cli@latest`
```
success Installed "expo-cli@2.11.9" with binaries:
      - expo
      - expo-cli
✨  Done in 368.75s.
$ expo-cli --version
2.11.9
```
