### ISSUE TITLE
Running npm run web

### ISSUE THREAD

**Issue by thisisazeez** [expo/expo-cli#4142]
### Summary

i am building a new app with expo cli and Node.js v17.3.0. after successfully creating the app i cd into the app folder to run npm run web then i got this:
hypens-root@hypens-root:~$ cd peroid/
hypens-root@hypens-root:~/peroid$ npm run web

> peroid@1.0.0 web
> expo start --web

WARNING: expo-cli has not yet been tested against Node.js v17.3.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <13.0.0 (Maintenance LTS)
* >=14.0.0 <15.0.0 (Active LTS)
* >=15.0.0 <17.0.0 (Current Release)

Starting project at /home/hypens-root/peroid
Unable to find expo in this project - have you run yarn / npm install yet?

then i did npm install it installed all the packages after that i ran npm run web then i got another exeption
hypens-root@hypens-root:~/peroid$ npm run web

> peroid@1.0.0 web
> expo start --web

WARNING: expo-cli has not yet been tested against Node.js v17.3.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <13.0.0 (Maintenance LTS)
* >=14.0.0 <15.0.0 (Active LTS)
* >=15.0.0 <17.0.0 (Current Release)

Starting project at /home/hypens-root/peroid
Developer tools running on http://localhost:19002
Starting Metro Bundler
Starting Webpack on port 19006 in development mode.
⚠ ｢wds｣: transportMode is an experimental option, meaning its usage could potentially change without warning
Web Bundling JavaScript [====                                     ] 10%Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/NormalModule.js:471:10)
    at /usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/NormalModule.js:503:5
    at /usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/NormalModule.js:358:12
    at /usr/local/lib/node_modules/expo-cli/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/usr/local/lib/node_modules/expo-cli/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/usr/local/lib/node_modules/expo-cli/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /usr/local/lib/node_modules/expo-cli/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/usr/local/lib/node_modules/expo-cli/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/usr/local/lib/node_modules/expo-cli/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/usr/local/lib/node_modules/expo-cli/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/usr/local/lib/node_modules/expo-cli/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /usr/local/lib/node_modules/expo-cli/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/home/hypens-root/peroid/node_modules/metro-hermes-compiler/src/emhermesc.js:81
          throw ex;
          ^

RuntimeError: abort(Error: error:0308010C:digital envelope routines::unsupported). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/home/hypens-root/peroid/node_modules/metro-hermes-compiler/src/emhermesc.js:796:13)
    at process.emit (node:events:390:28)
    at process.emit (/usr/local/lib/node_modules/expo-cli/node_modules/source-map-support/source-map-support.js:439:21)
    at processEmit [as emit] (/usr/local/lib/node_modules/expo-cli/node_modules/signal-exit/index.js:197:34)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:242:25)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)

Node.js v17.3.0

### Environment

WARNING: expo-cli has not yet been tested against Node.js v17.3.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <13.0.0 (Maintenance LTS)
* >=14.0.0 <15.0.0 (Active LTS)
* >=15.0.0 <17.0.0 (Current Release)

  Expo CLI 5.0.3 environment info:
    System:
      OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 17.3.0 - /usr/bin/node
      npm: 8.3.0 - /usr/local/bin/npm
    npmPackages:
      expo: ~44.0.2 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Chrome LTS version

### Error output

hypens-root@hypens-root:~/peroid$ npm run web

> peroid@1.0.0 web
> expo start --web

WARNING: expo-cli has not yet been tested against Node.js v17.3.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <13.0.0 (Maintenance LTS)
* >=14.0.0 <15.0.0 (Active LTS)
* >=15.0.0 <17.0.0 (Current Release)

Starting project at /home/hypens-root/peroid
Developer tools running on http://localhost:19002
Starting Metro Bundler
Starting Webpack on port 19006 in development mode.
⚠ ｢wds｣: transportMode is an experimental option, meaning its usage could potentially change without warning
Web Bundling JavaScript [====                                     ] 10%Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/NormalModule.js:471:10)
    at /usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/NormalModule.js:503:5
    at /usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/NormalModule.js:358:12
    at /usr/local/lib/node_modules/expo-cli/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/usr/local/lib/node_modules/expo-cli/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/usr/local/lib/node_modules/expo-cli/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /usr/local/lib/node_modules/expo-cli/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/usr/local/lib/node_modules/expo-cli/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/usr/local/lib/node_modules/expo-cli/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/usr/local/lib/node_modules/expo-cli/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/usr/local/lib/node_modules/expo-cli/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /usr/local/lib/node_modules/expo-cli/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/home/hypens-root/peroid/node_modules/metro-hermes-compiler/src/emhermesc.js:81
          throw ex;
          ^

RuntimeError: abort(Error: error:0308010C:digital envelope routines::unsupported). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/home/hypens-root/peroid/node_modules/metro-hermes-compiler/src/emhermesc.js:796:13)
    at process.emit (node:events:390:28)
    at process.emit (/usr/local/lib/node_modules/expo-cli/node_modules/source-map-support/source-map-support.js:439:21)
    at processEmit [as emit] (/usr/local/lib/node_modules/expo-cli/node_modules/signal-exit/index.js:197:34)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:242:25)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)

Node.js v17.3.0

### Reproducible demo or steps to reproduce from a blank project

Am Just Starting the Project Sorry for the inconvenience

**Comment by kbrandwijk** [comment]
Did you try with a supported Node version? The log above shows that warning about 4 times.

**Comment by EvanBacon** [comment]
Expo CLI does not currently support Node 17.
