### ISSUE TITLE
uri-scheme an unexpected error was encountered. Please report it as a bug

### ISSUE THREAD

**Issue by EduardoAraujoB** [expo/expo-cli#4181]
# Problem
I was trying to use `uri-scheme` to test deep linking, but for some reason it failes on the macbook m1 pro

command: `npx uri-scheme open safari:// --ios`
logs:
```
› iOS: Opening URI "safari://" in simulator
An error was encountered processing the command (domain=NSOSStatusErrorDomain, code=-10814):
The operation couldn’t be completed. (OSStatus error -10814.)

Aborting run
An unexpected error was encountered. Please report it as a bug:
Error: xcrun exited with non-zero code: 194
    at ChildProcess.d (/Users/eduardoaraujob/.npm/_npx/0475317ec596de5d/node_modules/uri-scheme/build/index.js:1:1073)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    ...
    at Object.spawnAsync [as default] (/Users/eduardoaraujob/.npm/_npx/0475317ec596de5d/node_modules/uri-scheme/build/index.js:1:558)
    at Object.openAsync (/Users/eduardoaraujob/.npm/_npx/0475317ec596de5d/node_modules/uri-scheme/build/index.js:1:485862)
    at Object.openAsync (/Users/eduardoaraujob/.npm/_npx/0475317ec596de5d/node_modules/uri-scheme/build/index.js:1:490506)
    at Command.<anonymous> (/Users/eduardoaraujob/.npm/_npx/0475317ec596de5d/node_modules/uri-scheme/build/index.js:1:481784)
    at Command.r (/Users/eduardoaraujob/.npm/_npx/0475317ec596de5d/node_modules/uri-scheme/build/index.js:1:465437)
    at Command.emit (node:events:390:28)
    at Command.parseArgs (/Users/eduardoaraujob/.npm/_npx/0475317ec596de5d/node_modules/uri-scheme/build/index.js:1:468609)
    at Command.parse (/Users/eduardoaraujob/.npm/_npx/0475317ec596de5d/node_modules/uri-scheme/build/index.js:1:466564)
    at Object.<anonymous> (/Users/eduardoaraujob/.npm/_npx/0475317ec596de5d/node_modules/uri-scheme/cli.js:5:9)
    at Module._compile (node:internal/modules/cjs/loader:1101:14) {
  pid: 40523,
  output: [ '', '' ],
  stdout: '',
  stderr: '',
  status: 194,
  signal: null
}
```

# Info

hardware: Macbook Pro m1
OS: macOS monterey
node: 16.13.1
npm: 8.1.2

**Comment by kbrandwijk** [comment]
What is this 'safari://' uri scheme?

**Comment by EduardoAraujoB** [comment]
its a deeplink just to test if I can open safari, but it also doesnt work for other apps

**Comment by EduardoAraujoB** [comment]
I found what is causing the problem and it seems to be an issue with macOS because the command that crash is this one
`xcrun simctl openurl booted someapp://route`
it does that with this message
```
An error was encountered processing the command (domain=NSOSStatusErrorDomain, code=-10814):
The operation couldn’t be completed. (OSStatus error -10814.)
```

**Comment by kbrandwijk** [comment]
It gives that error when you try to use a scheme that doesn't exist (safari:// doesnt' exist). Try `maps://something` or another known good one.

**Comment by EduardoAraujoB** [comment]
ok, will try it out, thanks

**Comment by ToniLloyds** [comment]
I have similar problem. Just added new uri-schema and if i run npx `uri-scheme list` it shows this schema. So it should exist ?

**Comment by damien-mcmahon** [comment]
Hopefully you've resolved the problem, I had the same issue but have just upgraded Xcode tools to 13.3 and this problem has now gone away.

**Comment by aphillipo** [comment]
I'll update Xcode I guess then... 😂

**Comment by cmejet** [comment]
@aphillipo did updating xcode resolve your issue? I'm on 13.3 and I'm still getting the error on m1.

**Comment by insacc** [comment]
I'm having this issue as well, I'm on the latest code version so I cannot update it, does anyone have any idea why it might be happening?

**Comment by jaaconsulting** [comment]
Hi - I am having the same issue when trying to set up deep-link on iOS. Below is my react-native information. Pls help.

System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 820.71 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 9.2.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.2 => 0.71.2
