### ISSUE TITLE
ApiV2Error: An unknown error occurred.

### ISSUE THREAD

**Issue by NRHunsdale** [expo/expo-cli#4207]
### Summary

When running `expo start` and launching on a device, the error seen below is shown. 

![image](https://user-images.githubusercontent.com/6906036/153524576-99e0a84b-9fcc-4f27-84b6-60509da5018d.png)

In addition, when attempting to login to https://expo.dev/login, an error shows up stating "An unknown error occured"

![image](https://user-images.githubusercontent.com/6906036/153524848-b0678220-9532-4172-8141-ec622722488f.png)

Finally, when `expo whoami`, `expo login`, or `expo logout` is entered into the terminal, the output below is presented:

![image](https://user-images.githubusercontent.com/6906036/153524989-5fb0d414-e25d-4ff5-891a-9f269dab2368.png)

### Environment

Expo CLI 5.1.2 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.9.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
      npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7935034
    npmPackages:
      babel-preset-expo: 9.0.1 => 9.0.1
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Pixel 4 emulator, Pixel 5 emulator, iPhone X simulator, Pixel 2 XL, iPhone 6

### Error output

ApiV2Error: An unknown error occurred.
    at ApiV2Client._requestAsync (C:\Users\hunsd\AppData\Roaming\nvm\v16.9.1\node_modules\expo-cli\node_modules\xdl\src\ApiV2.ts:244:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at UserManagerInstance._getProfileAsync (C:\Users\hunsd\AppData\Roaming\nvm\v16.9.1\node_modules\expo-cli\node_modules\xdl\src\User.ts:455:12)
    at UserManagerInstance.getCurrentUserAsync (C:\Users\hunsd\AppData\Roaming\nvm\v16.9.1\node_modules\expo-cli\node_modules\xdl\src\User.ts:295:16)
    at UserManagerInstance.ensureLoggedInAsync (C:\Users\hunsd\AppData\Roaming\nvm\v16.9.1\node_modules\expo-cli\node_modules\xdl\src\User.ts:200:16)
    at getSignedManifestStringAsync (C:\Users\hunsd\AppData\Roaming\nvm\v16.9.1\node_modules\expo-cli\node_modules\xdl\src\start\ManifestHandler.ts:417:16)
    at getManifestStringAsync (C:\Users\hunsd\AppData\Roaming\nvm\v16.9.1\node_modules\expo-cli\node_modules\xdl\src\start\ManifestHandler.ts:389:12)
    at getManifestResponseAsync (C:\Users\hunsd\AppData\Roaming\nvm\v16.9.1\node_modules\expo-cli\node_modules\xdl\src\start\ManifestHandler.ts:315:22)
    at C:\Users\hunsd\AppData\Roaming\nvm\v16.9.1\node_modules\expo-cli\node_modules\xdl\src\start\ManifestHandler.ts:151:49

### Reproducible demo or steps to reproduce from a blank project

There are 3 scenarios which are presenting errors:

**Scenario 1**
- `npm install -g expo-cli`
- Run `expo start` in the terminal
- Press `a` to run on emulator
- Witness the error mentioned in _Error output_

**Scenario 2**
- `npm install -g expo-cli`
- Enter `expo whoami`, `expo login`, , and/or  to the terminal `expo logout`
- Witness an error that solely states "_An unknown error occurred_"

**Scenario 3**
- Attempt to login to https://expo.dev/login
- Enter username, password, and passcode from authenticator
- Witness error "_An unknown error occurred._"

**Comment by jonsamp** [comment]
Thanks for reporting this issue. We just deployed a bug fix to address this issue. Please let me know if you continue to see it.
