### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by sarkisboufrancis** [expo/expo-cli#4232]
### Summary

hi

### Environment

hi

### Please specify your device/emulator/simulator platform, model and version

windows

### Error output

Developer tools running on http://localhost:19002
Cannot find module 'react-native/package.json'
Require stack:
- C:\Users\user\myproject\noop.js
Error: Cannot find module 'react-native/package.json'
Require stack:
- C:\Users\user\myproject\noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at resolveFileName (C:\Users\user\myproject\node_modules\resolve-from\index.js:29:39)
    at resolveFrom (C:\Users\user\myproject\node_modules\resolve-from\index.js:43:9)
    at Object.module.exports [as default] (C:\Users\user\myproject\node_modules\resolve-from\index.js:46:47)
    at getDefaultConfig (C:\Users\user\myproject\node_modules\@expo\metro-config\src\ExpoMetroConfig.ts:91:51)
    at Object.loadAsync (C:\Users\user\myproject\node_modules\@expo\metro-config\src\ExpoMetroConfig.ts:268:23)
    at runMetroDevServerAsync (C:\Users\user\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\dev-server\src\MetroDevServer.ts:86:45)
    at startDevServerAsync (C:\Users\user\AppData\Roaming\npm\node_modules\expo-cli\node_modules\xdl\src\start\startDevServerAsync.ts:77:55)
    at startAsync (C:\Users\user\AppData\Roaming\npm\node_modules\expo-cli\node_modules\xdl\src\start\startAsync.ts:69:41)

### Reproducible demo or steps to reproduce from a blank project

hi

**Comment by sarkisboufrancis** [comment]
please if someone can help me

**Comment by EvanBacon** [comment]
`react-native` is not installed in your project, try running `npm install`. Please be sure to also fill out all of the questions in the issue template next time.
