### ISSUE TITLE
Expo run:android crash without error

### ISSUE THREAD

**Issue by fabienlege** [expo/expo-cli#4240]
### Summary

Expo crash when try to run android without any explanation

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      Yarn: 1.21.1 - /usr/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.2.0
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Android Studio Bumblebee | 2021.1.1 Patch 1 Build #AI-211.7628.21.2111.8139111, built on February 1, 2022 Runtime version: 11.0.11+0-b60-7590822 amd64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. Linux 5.4.0-100-generic GC: G1 Young Generation, G1 Old Generation Memory: 1280M Cores: 8 Registry: external.system.auto.import.disabled=true  Current Desktop: ubuntu:GNOME With Nexus 10 API 30

### Error output

expo client:install:android

Error
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

### Reproducible demo or steps to reproduce from a blank project

```
npm init test
cd test
yarn android
```
the error occur just with this 3 commands, without any file modification

**Comment by EvanBacon** [comment]
I could not reproduce locally, can you please try again with the environment variable `EXPO_DEBUG=1` enabled and provide the more detailed error output.

**Comment by hgulersen** [comment]
@EvanBacon I am having the same problem for a long time now, couldn't find a solution anywhere. The output with `EXPO_DEBUG=1` is the same, not much information. This also happens when I create a new expo managed project from scratch. 

```
$ echo $EXPO_DEBUG 
1
$ expo run:android
Error
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Please let me know what else I can provide so you can reproduce

**Comment by EvanBacon** [comment]
Run `EXPO_DEBUG=1 expo run:android` then it should print the underlying command, something like:
```
/Users/evanbacon/Documents/GitHub/lab/yolo83/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand -PreactNativeDevServerPort=8081 -PreactNativeDevServerPort=8081
```

`cd` into the `android` folder and run that command, then share the results. This will help narrow down if the issue is related to the build or something else.

**Comment by hgulersen** [comment]
@EvanBacon unfortunately it's the same error message as above without any other information. I know it's not helpful but that's what I'm getting, also I should note that it errors out pretty much instantly so I have a feeling it happens even before starting the build

**Comment by amritk** [comment]
I'm having the same issue I think, how can I get any more info?
```
AwesomeProject (master) ✗ EXPO_DEBUG=1 expo run:android               

Error
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
➜ AwesomeProject (master) ✗ 
```

**Comment by EvanBacon** [comment]
- `which expo` -> outputs a path like `/Users/evanbacon/.nvm/versions/node/v16.13.0/bin/expo`
- Run `node --inspect-brk /Users/evanbacon/.nvm/versions/node/v16.13.0/bin/expo run:android`
- Open `chrome://inspect/#devices` in Chrome, then select the remote target, something like `Target (v14.17.6)`.
- Once the chrome debugger opens, activate "Pause on exceptions" (top right corner) and press play:
<img width="221" alt="Screen Shot 2022-03-21 at 11 52 54 AM" src="https://user-images.githubusercontent.com/9664363/159316987-f23a095c-f5b1-4604-8b40-0eb91d5361b8.png">

This should give you complete insight into where the process is failing.

**Comment by EvanBacon** [comment]
Possibly related https://github.com/expo/expo-cli/issues/4267

**Comment by hgulersen** [comment]
Thanks @EvanBacon for the detailed explanation, very helpful! 

For anyone experiencing this issue, I would recommend activating the debugger as @EvanBacon mentioned above in a blank project because doing it in an actual project is much harder due to exceptions in dependencies. 

The problem for me was that I had a conflicting environment variable for `ANDROID_SDK`. Once I found the source of that and removed it, I was able to run `run:android` again. 

Also weirdly enough, my VS Code integrated terminal kept on giving the same error even after restart, but running it from iTerm did the trick.

**Comment by samtgarson** [comment]
I've had this exact issue trying to run on an Android VD for the first time, and did some digging around using the debugging methods listed above.

I tracked the issue to [this method](https://github.com/expo/expo-cli/blob/main/packages/xdl/src/Android.ts#L286)
![image](https://user-images.githubusercontent.com/6242344/162259340-1f63341e-1a92-47b2-afcf-5e6a4f68bb7f.png)

Looks like there's some strangely specific (brittle) string manipulation there which looks for `"error:"` when the actual error starts with `"Error:"`, which might be the reason we don't get any error reported upwards (the `errorMessage` remains an empty string in the existing code). 

It seems like we'd be much better off just throwing the whole error string, rather than trying to cut out the `error:` prefix and risk reporting nothing and causing frustration—I'll put in a PR for this if it's desired.

So anyway, it looks like the actual error (for me at least) is `Error: spawn /usr/local/share/android-sdk/platform-tools/adb ENOENT`, which evidently means `expo` can't find my `adb` installation—which makes sense, as the reported location is not the value of my `ANDROID_SDK` environment variable.

Turns out, this is because I also have `ANDROID_HOME` defined in my shell, and despite [the docs](https://docs.expo.dev/workflow/android-studio-emulator/) saying to set `ANDROID_SDK`, `expo` seems to be [looking for `ANDROID_HOME`](https://github.com/expo/expo-cli/blob/main/packages/xdl/src/Android.ts#L55-L60). 

Running `export ANDROID_HOME="$ANDROID_SDK"` got me past this issue (and onto the next one 🙈 😅)

Interested to see if others have the same issue, and if a PR would be accepted to provide a more useful error message?

**Comment by amritk** [comment]
@samtgarson interesting, I think my issues started when I tried to setup hardware acceleration for the emulator.

**Comment by EvanBacon** [comment]
I've added some internal tasks to add additional validation against known system configurations that work. If others hit this issue and find resolutions, please post your findings so I can add them to the list of validations.

**Comment by karlhorky** [comment]
I also just had this issue with the "empty" error message while trying to write an Expo + React Native section in [this System Setup guide](https://github.com/upleveled/system-setup/blob/main/readme.md) for our students.

The [comment](https://github.com/expo/expo-cli/issues/4240#issuecomment-1079657227) by @hgulersen above was really helpful. Running the command below showed a bunch of duplication:

```bash
echo $PATH | grep platform-tools --color=always
```

<img width="585" alt="Screen Shot 2022-04-12 at 13 53 35" src="https://user-images.githubusercontent.com/1935696/162956119-8594c113-9c8a-4c3e-8062-0318d2e3434a.png">

I'm guessing probably because of running a bunch of commands multiple times, to add things to my path.

### Resolution

Starting a new terminal 😬 Which reset my `PATH` to something sane:

<img width="576" alt="Screen Shot 2022-04-12 at 13 55 34" src="https://user-images.githubusercontent.com/1935696/162957158-9b1f7773-093e-4e34-995a-37f6e97fb442.png">

**Comment by karlhorky** [comment]
As for the missing error message, it was indeed the faulty error message manipulation in the `xdl` package:

https://github.com/expo/expo-cli/blob/044075e94e8b9ff7836de1fefe0bafb451fed14a/packages/xdl/src/Android.ts#L281-L285

I edited the `/Users/k/.nvm/versions/node/v16.11.0/lib/node_modules/xdl/build/Android.js` file and commented the error massaging out:

```diff
async function adbAlreadyRunning(adb) {
  try {
    const result = await (0, _spawnAsync().default)(adb, ['start-server']);
    const lines = (0, _trim().default)(result.stderr).split(/\r?\n/);
    return lines.includes('* daemon started successfully') === false;
  } catch (e) {
-    let errorMessage = (0, _trim().default)(e.stderr || e.stdout);
+    // let errorMessage = (0, _trim().default)(e.stderr || e.stdout);

-    if (errorMessage.startsWith(BEGINNING_OF_ADB_ERROR_MESSAGE)) {
-      errorMessage = errorMessage.substring(BEGINNING_OF_ADB_ERROR_MESSAGE.length);
-    }
+    // if (errorMessage.startsWith(BEGINNING_OF_ADB_ERROR_MESSAGE)) {
+    //   errorMessage = errorMessage.substring(BEGINNING_OF_ADB_ERROR_MESSAGE.length);
+    // }

-    e.message = errorMessage;
+    // e.message = errorMessage;

    throw e;
  }
}
```

And then, the error message appeared again:

```bash
spawn /opt/homebrew/share/android-commandlinetools/platform-tools/adb ENOENT
Error: spawn /opt/homebrew/share/android-commandlinetools/platform-tools/adb ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

It's apparently looking for `adb` in this location, which is actually NOT in my `$PATH` and also doesn't exist... 🤔

```bash
$ l -al /opt/homebrew/share/android-commandlinetools/platform-tools
ls: /opt/homebrew/share/android-commandlinetools/platform-tools: No such file or directory
$ ls -al /opt/homebrew/share/android-commandlinetools               
ls: /opt/homebrew/share/android-commandlinetools: No such file or directory
```

So I'm guessing there's something weird going on with the `adb` path resolution in Expo CLI.

**Comment by karlhorky** [comment]
Duplicate paths in the `$PATH` variable can come from the built-in VS Code Terminal on macOS, apparently:

https://code.visualstudio.com/docs/editor/integrated-terminal#_why-are-there-duplicate-paths-in-the-terminals-path-environment-variable-andor-why-are-they-reversed

**Comment by brunolcarlos** [comment]
I have the same issue and no logs
npm run android crashes and the eas preview apk crashes but the expo go works

{
  "name": "xxxxxxx",
  "version": "75",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "@babel/preset-env": "^7.1.6",
    "@expo/vector-icons": "^13.0.0",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",
    "@types/react": "^18.0.15",
    "@types/react-native": "^0.69.3",
    "axios": "^0.21.4",
    "expo": "^45.0.0",
    "expo-ads-admob": "~13.0.0",
    "expo-av": "~11.2.3",
    "expo-build-properties": "~0.2.0",
    "expo-cli": "^5.4.12",
    "expo-constants": "~13.1.1",
    "expo-device": "~4.2.0",
    "expo-file-system": "~14.0.0",
    "expo-keep-awake": "~10.1.1",
    "expo-media-library": "~14.1.0",
    "expo-modules-autolinking": "~0.8.1 || ~0.9.0",
    "expo-modules-core": "~0.9.2",
    "expo-notifications": "~0.15.4",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "expo-system-ui": "~1.2.0",
    "expo-web-browser": "~10.2.1",
    "glob": "^7.2.0",
    "html-entities": "^2.3.3",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-big-list": "^1.5.4",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-navigation-bar-color": "^2.0.1",
    "react-native-reanimated": "~2.8.0",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-web": "0.17.7",
    "react-native-webview": "11.18.1",
    "uri-scheme": "^1.0.120"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}

{
  "expo": {
    "name": "xxxxxxx",
    "slug": "xxxxxxxxx",
    "version": "1.0.74",
    "orientation": "portrait",
    "icon": "./assets/iconweebp.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/new_splash.png",
      "resizeMode": "cover",
      "backgroundColor": "#151D29"
    },
    "androidStatusBar": {
      "backgroundColor": "#151D29",
      "translucent": false
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "bundleIdentifier": "com.xxxxxxx.ios",
      "supportsTablet": false
    },
    "android": {
      "versionCode": 75,
      "package": "com.xxxxxx.webview",
      "adaptiveIcon": {
        "foregroundImage": "./assets/512_.png",
        "backgroundColor": "#151D29"
      },
      "googleServicesFile": "./google-services.json"
    },
    "web": {
      "favicon": "./assets/iconweebp.png"
    },
    "androidNavigationBar": {
      "barStyle": "light-content",
      "backgroundColor": "#151D29"
    },
    "notification": {
      "icon": "./assets/iconweebp.png"
    },
    "extra":{
      "eas":{
        "projectId":"d93facb3-c613-4c15-9041-668d734fb132" 
      }
    },
    "plugins": [
      [
        "expo-build-properties",
        {
          "android": {
            "compileSdkVersion": 31,
            "targetSdkVersion": 31,
            "buildToolsVersion": "31.0.0"
          },
          "ios": {
            "deploymentTarget": "13.0"
          }
        }
      ],
      [
        "expo-notifications",
        {
          "icon": "./assets/iconweebp.png",
          "color": "#151D29"
        }
      ]
    ]
  }
}

**Comment by brunolcarlos** [comment]
> As an update, in the new versioned Expo CLI we will provide better Android global environment setup validation which should help mitigate this issue.

I have the same issue and no logs
npm run android crashes and the eas preview apk crashes but the expo go works

{
"name": "xxxxxxx",
"version": "75",
"scripts": {
"start": "expo start --dev-client",
"android": "expo run:android",
"ios": "expo run:ios",
"eject": "expo eject"
},
"dependencies": {
"@babel/preset-env": "^7.1.6",
"@expo/vector-icons": "^13.0.0",
"@react-native-async-storage/async-storage": "~1.17.3",
"@react-navigation/native": "^6.0.11",
"@react-navigation/native-stack": "^6.7.0",
"@types/react": "^18.0.15",
"@types/react-native": "^0.69.3",
"axios": "^0.21.4",
"expo": "^45.0.0",
"expo-ads-admob": "~13.0.0",
"expo-av": "~11.2.3",
"expo-build-properties": "~0.2.0",
"expo-cli": "^5.4.12",
"expo-constants": "~13.1.1",
"expo-device": "~4.2.0",
"expo-file-system": "~14.0.0",
"expo-keep-awake": "~10.1.1",
"expo-media-library": "~14.1.0",
"expo-modules-autolinking": "~0.8.1 || ~0.9.0",
"expo-modules-core": "~0.9.2",
"expo-notifications": "~0.15.4",
"expo-splash-screen": "~0.15.1",
"expo-status-bar": "~1.3.0",
"expo-system-ui": "~1.2.0",
"expo-web-browser": "~10.2.1",
"glob": "^7.2.0",
"html-entities": "^2.3.3",
"react": "17.0.2",
"react-dom": "17.0.2",
"react-native": "0.68.2",
"react-native-big-list": "^1.5.4",
"react-native-gesture-handler": "~2.2.1",
"react-native-navigation-bar-color": "^2.0.1",
"react-native-reanimated": "~2.8.0",
"react-native-safe-area-context": "4.2.4",
"react-native-screens": "~3.11.1",
"react-native-web": "0.17.7",
"react-native-webview": "11.18.1",
"uri-scheme": "^1.0.120"
},
"devDependencies": {
"@babel/core": "^7.12.9"
},
"private": true
}

{
"expo": {
"name": "xxxxxxx",
"slug": "xxxxxxxxx",
"version": "1.0.74",
"orientation": "portrait",
"icon": "./assets/iconweebp.png",
"userInterfaceStyle": "light",
"splash": {
"image": "./assets/new_splash.png",
"resizeMode": "cover",
"backgroundColor": "#151D29"
},
"androidStatusBar": {
"backgroundColor": "#151D29",
"translucent": false
},
"updates": {
"fallbackToCacheTimeout": 0
},
"assetBundlePatterns": [
"**/*"
],
"ios": {
"bundleIdentifier": "com.xxxxxxx.ios",
"supportsTablet": false
},
"android": {
"versionCode": 75,
"package": "com.xxxxxx.webview",
"adaptiveIcon": {
"foregroundImage": "./assets/512_.png",
"backgroundColor": "#151D29"
},
"googleServicesFile": "./google-services.json"
},
"web": {
"favicon": "./assets/iconweebp.png"
},
"androidNavigationBar": {
"barStyle": "light-content",
"backgroundColor": "#151D29"
},
"notification": {
"icon": "./assets/iconweebp.png"
},
"extra":{
"eas":{
"projectId":"767787666-c613-4c15-9041-6666556788787"
}
},
"plugins": [
[
"expo-build-properties",
{
"android": {
"compileSdkVersion": 31,
"targetSdkVersion": 31,
"buildToolsVersion": "31.0.0"
},
"ios": {
"deploymentTarget": "13.0"
}
}
],
[
"expo-notifications",
{
"icon": "./assets/iconweebp.png",
"color": "#151D29"
}
]
]
}
}
