### ISSUE TITLE
Creating a new module from template error.

### ISSUE THREAD

**Issue by gtokman** [expo/expo-cli#4266]
### Summary

Running `npx create-expo-module` causes a TS error while building.

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Mac m1

### Error output

⬇️  Downloading module template from npm...
🎨 Creating Expo module from the template files...
📦 Installing dependencies...
🛠  Compiling TypeScript files...
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: yarn exited with non-zero code: 2
    at ChildProcess.completionListener (/Users/gary/.npm/_npx/62900f925a4b91dc/node_modules/@expo/spawn-async/build/spawnAsync.js:43:23)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1062:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    ...
    at spawnAsync (/Users/gary/.npm/_npx/62900f925a4b91dc/node_modules/@expo/spawn-async/build/spawnAsync.js:8:21)
    at run (/Users/gary/.npm/_npx/62900f925a4b91dc/node_modules/create-expo-module/build/create-expo-module.js:137:41)
    at postActionsAsync (/Users/gary/.npm/_npx/62900f925a4b91dc/node_modules/create-expo-module/build/create-expo-module.js:145:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.main (/Users/gary/.npm/_npx/62900f925a4b91dc/node_modules/create-expo-module/build/create-expo-module.js:61:5) {
  pid: 59563,
  output: [ '', '' ],
  stdout: '',
  stderr: '',
  status: 2,
  signal: null
}

Node.js v17.3.1

### Reproducible demo or steps to reproduce from a blank project

1. Run `npx create-expo-module`

**Comment by EvanBacon** [comment]
`npx create-expo-module` is not in this repo, not sure what that module is 🤔

**Comment by JThobbyist** [comment]
I got a similar error, except the line-number was 

```
node:internal/process/promises:279
triggerUncaughtException(err, true /* fromPromise */);
^
```

Turns out I didn't have _Typescript_ installed!

I ran ```npm i -g typescript``` , and then ```npx create-expo-module``` completed successfully without any error.

**Comment by hyochan** [comment]
Same here.

<img width="953" alt="Screen Shot 2022-04-26 at 10 12 57 PM" src="https://user-images.githubusercontent.com/27461460/165307723-271031fc-52b1-4df0-af75-5a0ba79e808d.png">

**Comment by tsapeta** [comment]
Fixed in https://github.com/expo/expo/pull/17821 so I'm closing this issue. The new version will be available later today 😉

**Comment by iqqmuT** [comment]
I get the same error but it occurs when installing dependencies:
```
$ npx create-expo-module
npx: installed 109 in 4.151s
✔ What is the project name? … Test
✔ How would you describe the module? … 
✔ What is the Android package name? … expo.modules.test
✔ Who is the author? … 
✔ What is the license? … MIT
✔ What is the repository URL? … 
⬇️  Downloading module template from npm...
🎨 Creating Expo module from the template files...
📦 Installing dependencies...
(node:103576) UnhandledPromiseRejectionWarning: Error: npm exited with non-zero code: 1
    at ChildProcess.completionListener (/home/tumppi/.npm/_npx/103576/lib/node_modules/create-expo-module/node_modules/@expo/spawn-async/build/spawnAsync.js:43:23)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
    ...
    at spawnAsync (/home/tumppi/.npm/_npx/103576/lib/node_modules/create-expo-module/node_modules/@expo/spawn-async/build/spawnAsync.js:8:21)
    at run (/home/tumppi/.npm/_npx/103576/lib/node_modules/create-expo-module/build/create-expo-module.js:125:41)
    at postActionsAsync (/home/tumppi/.npm/_npx/103576/lib/node_modules/create-expo-module/build/create-expo-module.js:131:11)
    at Command.main (/home/tumppi/.npm/_npx/103576/lib/node_modules/create-expo-module/build/create-expo-module.js:64:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:103576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:103576) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm using Node.js 14.

**Comment by iqqmuT** [comment]
```shell
$ node --version
v14.18.2
$ npm --version
6.14.15
```

I tried to upgrade to Node.js v18.4.0, but the same error occurred.
