### ISSUE TITLE
SDK 44 upgrade incompatible with expo-cli@5.3.0

### ISSUE THREAD

**Issue by nmschulte-aviture** [expo/expo-cli#4274]
### Summary

A project depends upon `expo-cli` as a means of dev-ops practice, while Expo recommends installing `expo-cli` globally on the system.

Expo SDK 44 is incompatible with (the current version of, but ... ) expo-cli: `expo upgrade` upgrades `expo-cli`, and `expo-cli@5.3.0` has a dependency upon `graphql` that is incompatible with Expo SDK 44.

One solution is to remove `expo-cli` dependency, but this is a non-start.
Another solution is to depend on `graphql` in a manner to fix the issue; `npm install graphql@0.13.2` seems to work.

### Environment

ok

### Please specify your device/emulator/simulator platform, model and version

ok

### Error output

```
Body must be a string. Received: undefined.
Error: Body must be a string. Received: undefined.
    at devAssert (/home/nmschulte/decision_logic/decision-logic-digital-manager/node_modules/graphql/jsutils/devAssert.js:12:11)
    at new Source (/home/nmschulte/decision_logic/decision-logic-digital-manager/node_modules/graphql/language/source.js:37:56)
    at new Parser (/home/nmschulte/decision_logic/decision-logic-digital-manager/node_modules/graphql/language/parser.js:86:62)
    at Object.parse (/home/nmschulte/decision_logic/decision-logic-digital-manager/node_modules/graphql/language/parser.js:30:16)
    at Object.<anonymous> (/home/nmschulte/decision_logic/decision-logic-digital-manager/node_modules/graphql-tools/src/stitching/introspectSchema.ts:7:48)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
```

### Reproducible demo or steps to reproduce from a blank project

https://github.com/expo/expo-cli/pull/2286#issuecomment-927605102

?? https://github.com/expo/expo-cli/issues/2025 ??

**Comment by nmschulte-aviture** [comment]
Another solution in this instance seems to be to uninstall `expo-cli` prior to `expo upgrade` and then later re-installing `expo-cli`.

**Comment by nmschulte-aviture** [comment]
This situation still exists with Expo SDK 45 and `expo-cli` v5.5.1.
