### ISSUE TITLE
Failed to construct transformer

### ISSUE THREAD

**Issue by RitzieWilliams** [expo/expo-cli#4275]
When running on Node v17.4.0 I get:

`Failed to construct transformer:  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at stableHash (/Users/home/Desktop/Weeat/node_modules/metro-cache/src/stableHash.js:19:8)
    at JsTransformer.getCacheKey (/Users/home/Desktop/Weeat/node_modules/metro/src/JSTransformer/worker.js:478:7)
    at getTransformCacheKey (/Users/home/Desktop/Weeat/node_modules/metro/src/DeltaBundler/Transformer/getTransformCacheKey.js:39:29)
    at new Transformer (/Users/home/Desktop/Weeat/node_modules/metro/src/DeltaBundler/Transformer.js:147:28)
    at /Users/home/Desktop/Weeat/node_modules/metro/src/Bundler.js:54:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}`

and when trying to run on the iOS simulator I get:
Xcode needs to be installed (don't worry, you won't have to use it), would you like to continue to the App Store?

I have Xcode installed...

**Comment by kbrandwijk** [comment]
Node 17 is not supported yet by the underlying webpack engine, used by the bundler. See this issue for more details: https://github.com/expo/expo-cli/issues/3988
