### ISSUE TITLE
Error executing "expo start" command (Node +17 Metro compat)

### ISSUE THREAD

**Issue by jsotomedina** [expo/expo-cli#4334]
### Summary

Error executing "expo start" command

### Environment

Failed to construct transformer:  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at stableHash (D:\App\React-native\miprimeraappreactnative\node_modules\metro-cache\src\stableHash.js:19:8)
    at Object.getCacheKey (D:\App\React-native\miprimeraappreactnative\node_modules\metro-transform-worker\src\index.js:647:7)
    at getTransformCacheKey (D:\App\React-native\miprimeraappreactnative\node_modules\metro\src\DeltaBundler\getTransformCacheKey.js:32:19)
    at new Transformer (D:\App\React-native\miprimeraappreactnative\node_modules\metro\src\DeltaBundler\Transformer.js:180:28)
    at D:\App\React-native\miprimeraappreactnative\node_modules\metro\src\Bundler.js:58:29 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

### Please specify your device/emulator/simulator platform, model and version

Windows 11, Node v18.0.0, Expo 5.4.0

### Error output

expo start

Failed to construct transformer:  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at stableHash (D:\App\React-native\miprimeraappreactnative\node_modules\metro-cache\src\stableHash.js:19:8)
    at Object.getCacheKey (D:\App\React-native\miprimeraappreactnative\node_modules\metro-transform-worker\src\index.js:647:7)
    at getTransformCacheKey (D:\App\React-native\miprimeraappreactnative\node_modules\metro\src\DeltaBundler\getTransformCacheKey.js:32:19)
    at new Transformer (D:\App\React-native\miprimeraappreactnative\node_modules\metro\src\DeltaBundler\Transformer.js:180:28)
    at D:\App\React-native\miprimeraappreactnative\node_modules\metro\src\Bundler.js:58:29 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

### Reproducible demo or steps to reproduce from a blank project

In CMD I write the command "expo start" and the error described above appears

**Comment by byCedric** [comment]
Hi @jsotomedina and @realtril! The error is an incompatibility issue from Metro (React Native's bundler) with Node 17+. You can always use the latest active Node LTS, [which is currently Node 16](https://nodejs.org/en/about/releases/).

**Comment by EvanBacon** [comment]
This appears to be fixed in SDK 47.
