### ISSUE TITLE
Unable to resolve sharp-cli in M1 

### ISSUE THREAD

**Issue by wobsoriano** [expo/expo-cli#4340]
### Summary

I'm getting this error when I run `expo eject`:

```
✔ Created native projects | /android, /ios already created | gitignore already synced
✔ Updated package.json and added index.js entry point for iOS and Android
🧶 Using Yarn to install packages. Pass --npm to use npm instead.
✔ Installed JavaScript dependencies 925ms
✖ Config sync failed
[android.dangerous]: withAndroidDangerousBaseMod: Failed to find the instance of sharp used by the global sharp-cli package.
```

```bash
❯ which sharp
/Users/yesyes/.volta/bin/sharp
```

I'm using [volta](https://volta.sh/) as my tool manager.

### Environment

```bash
expo-env-info 1.0.3 environment info:
  System:
    OS: macOS 12.3
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.volta/tools/image/node/16.14.2/bin/node
    Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 8.5.0 - ~/.volta/tools/image/node/16.14.2/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  npmPackages:
    expo: ~44.0.0 => 44.0.6
    react: 17.0.1 => 17.0.1
    react-dom: 17.0.1 => 17.0.1
    react-native: 0.64.3 => 0.64.3
    react-native-web: 0.17.1 => 0.17.1
  Expo Workflow: bare
```

### Please specify your device/emulator/simulator platform, model and version

iPhone 12 (iOS 14.4)

### Error output

```
[android.dangerous]: withAndroidDangerousBaseMod: Failed to find the instance of sharp used by the global sharp-cli package.
Error: [android.dangerous]: withAndroidDangerousBaseMod: Failed to find the instance of sharp used by the global sharp-cli package.
    at Object.findSharpInstanceAsync (/Users/yesyes/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/node_modules/@expo/image-utils/src/sharp.ts:200:11)
    at getSharpAsync (/Users/yesyes/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/node_modules/@expo/image-utils/src/Image.ts:95:47)
    at resizeAsync (/Users/yesyes/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/node_modules/@expo/image-utils/src/Image.ts:24:22)
    at generateImageAsync (/Users/yesyes/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/node_modules/@expo/image-utils/src/Image.ts:166:14)
    at /Users/yesyes/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/node_modules/@expo/prebuild-config/src/plugins/icons/withAndroidIcons.ts:130:9
    at async Promise.all (index 2)
    at configureLegacyIconAsync (/Users/yesyes/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/node_modules/@expo/prebuild-config/src/plugins/icons/withAndroidIcons.ts:121:3)
    at setIconAsync (/Users/yesyes/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/node_modules/@expo/prebuild-config/src/plugins/icons/withAndroidIcons.ts:102:3)
    at /Users/yesyes/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/node_modules/@expo/prebuild-config/src/plugins/icons/withAndroidIcons.ts:49:7
    at action (/Users/yesyes/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:227:23)
    at interceptingMod (/Users/yesyes/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/yesyes/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at action (/Users/yesyes/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/createBaseMod.ts:82:21)
    at interceptingMod (/Users/yesyes/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at evalModsAsync (/Users/yesyes/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:172:25)
    at compileModsAsync (/Users/yesyes/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:82:10)
```

_No response_

### Reproducible demo or steps to reproduce from a blank project

1. `expo init myProject`
2. `expo eject`

**Comment by wobsoriano** [comment]
So looks like [Volta](https://github.com/volta-cli/volta) has a different way of handling `which` commands.

Here's an output when running `which sharp` vs `volta which sharp`:

```bash
Documents/tests/app
❯ which sharp
/Users/yesyes/.volta/bin/sharp

Documents/tests/app
❯ volta which sharp
/Users/yesyes/.volta/tools/image/packages/sharp-cli/bin/sharp

Documents/tests/app
❯ which node
/Users/yesyes/.volta/bin/node

Documents/tests/app
❯ volta which node
/Users/yesyes/.volta/tools/image/node/16.14.2/bin/node
```

I think we can fix this by checking if `.volta` exists in when running `spawnAsync('which', ['sharp'])` [here](https://github.com/expo/expo-cli/blob/main/packages/image-utils/src/sharp.ts#L169)?

So it'll look like this then

```ts
let sharpCliPath;
if (process.platform !== 'win32') {
  try {
    sharpCliPath = (await spawnAsync('which', ['sharp'])).stdout.toString().trim();
  } catch {}
} else {
  // On Windows systems, nested dependencies aren't linked to the paths within `require.resolve.paths`.
  // Yarn installs these modules in a different folder, let's add yarn to the other attempts.
  // See: https://github.com/expo/expo-cli/issues/2708
  let yarnGlobalPath = '';
  try {
    yarnGlobalPath = path.join(
      (await spawnAsync('yarn', ['global', 'dir'])).stdout.toString().trim(),
      'node_modules'
    );
  } catch {}
  try {
    sharpCliPath = require.resolve('sharp-cli/package.json', {
      paths: (require.resolve.paths('sharp-cli') || []).concat(yarnGlobalPath),
    });
  } catch {}
}

if (sharpCliPath.includes('/.volta/')) {
  sharpCliPath = (await spawnAsync('volta', ['which', 'sharp'])).stdout.toString().trim();
}
```

I have tried it locally and it was able to execute sharp.

**Comment by wobsoriano** [comment]
Fix is to run `yarn eject` instead of `expo eject`. Seems like Volta has weird stuff going on.

**Comment by byCedric** [comment]
Hi @wobsoriano! I'm glad you could make it work with Volta. If you still think this is an issue we should fix or support better, please open an issue on [github.com/expo/expo](https://github.com/expo/expo).

Closing this issue since it involves external tooling, and a solution was found.
