### ISSUE TITLE
[Mirror] Stripe outdated for plugin config

### ISSUE THREAD

**Issue by ScreamZ** [expo/expo-cli#4358]
### Summary

I create this mirror issue for tracking current bug with SDK 45 and stripe RN.
Dropped hotfix in this PR, you might check. https://github.com/stripe/stripe-react-native/pull/935

```
PREPARE_CREDENTIALS] Importing distribution certificate into the keychain
[PREPARE_CREDENTIALS] Initializing provisioning profile
[PREPARE_CREDENTIALS] Validating whether distribution certificate has been imported successfully
[PREPARE_CREDENTIALS] Verifying whether the distribution certificate and provisioning profile match
[PREBUILD] - Creating native project directories (./ios and ./android) and updating .gitignore
[PREBUILD] ✔ Created native project
[PREBUILD] - Adding Metro bundler config
[PREBUILD] ✔ Added Metro config
[PREBUILD] - Updating your package.json scripts, dependencies, and main file
[PREBUILD] ✔ Updated package.json and added index.js entry point for iOS and Android
[PREBUILD] - Config syncing
[PREBUILD] ✖ Config sync failed
[PREBUILD] [12:46:32] [ios.xcodeproj]: withIosXcodeprojBaseMod: Could not locate a valid AppDelegate at root: "/private/var/folders/tt/zmqlq5ws4kx6_dvdxp90f5v80000gn/T/eas-build-local-nodejs/fb014d24-5622-42ba-8dfe-4cc7c74a027f/build"
[PREBUILD] Please report this as an issue on https://github.com/expo/expo-cli/issues
[PREBUILD] [12:46:32] UnexpectedError: [ios.xcodeproj]: withIosXcodeprojBaseMod: Could not locate a valid AppDelegate at root: "/private/var/folders/tt/zmqlq5ws4kx6_dvdxp90f5v80000gn/T/eas-build-local-nodejs/fb014d24-5622-42ba-8dfe-4cc7c74a027f/build"
[PREBUILD] Please report this as an issue on https://github.com/expo/expo-cli/issues
[PREBUILD]     at getAppDelegateFilePath (/private/var/folders/tt/zmqlq5ws4kx6_dvdxp90f5v80000gn/T/eas-build-local-nodejs/fb014d24-5622-42ba-8dfe-4cc7c74a027f/build/node_modules/@stripe/stripe-react-native/node_modules/@expo/config-plugins/src/ios/Paths.ts:26:11)
[PREBUILD]     at getAppDelegate (/private/var/folders/tt/zmqlq5ws4kx6_dvdxp90f5v80000gn/T/eas-build-local-nodejs/fb014d24-5622-42ba-8dfe-4cc7c74a027f/build/node_modules/@stripe/stripe-react-native/node_modules/@expo/config-plugins/src/ios/Paths.ts:63:20)
[PREBUILD]     at Object.getSourceRoot (/private/var/folders/tt/zmqlq5ws4kx6_dvdxp90f5v80000gn/T/eas-build-local-nodejs/fb014d24-5622-42ba-8dfe-4cc7c74a027f/build/node_modules/@stripe/stripe-react-native/node_modules/@expo/config-plugins/src/ios/Paths.ts:68:23)
[PREBUILD]     at getProjectName (/private/var/folders/tt/zmqlq5ws4kx6_dvdxp90f5v80000gn/T/eas-build-local-nodejs/fb014d24-5622-42ba-8dfe-4cc7c74a027f/build/node_modules/@stripe/stripe-react-native/node_modules/@expo/config-plugins/src/ios/utils/Xcodeproj.ts:33:28)
[PREBUILD]     at /private/var/folders/tt/zmqlq5ws4kx6_dvdxp90f5v80000gn/T/eas-build-local-nodejs/fb014d24-5622-42ba-8dfe-4cc7c74a027f/build/node_modules/@stripe/stripe-react-native/node_modules/@expo/config-plugins/src/ios/XcodeProjectFile.ts:23:25
[PREBUILD]     at action (/private/var/folders/tt/zmqlq5ws4kx6_dvdxp90f5v80000gn/T/eas-build-local-nodejs/fb014d24-5622-42ba-8dfe-4cc7c74a027f/build/node_modules/@stripe/stripe-react-native/node_modules/@expo/config-plugins/src/plugins/withMod.ts:214:29)
[PREBUILD]     at interceptingMod (/private/var/folders/tt/zmqlq5ws4kx6_dvdxp90f5v80000gn/T/eas-build-local-nodejs/fb014d24-5622-42ba-8dfe-4cc7c74a027f/build/node_modules/@stripe/stripe-react-native/node_modules/@expo/config-plugins/src/plugins/withMod.ts:100:27)
[PREBUILD]     at action (/private/var/folders/tt/zmqlq5ws4kx6_dvdxp90f5v80000gn/T/eas-build-local-nodejs/fb014d24-5622-42ba-8dfe-4cc7c74a027f/build/node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins/src/plugins/withMod.ts:228:14)
[PREBUILD]     at interceptingMod (/private/var/folders/tt/zmqlq5ws4kx6_dvdxp90f5v80000gn/T/eas-build-local-nodejs/fb014d24-5622-42ba-8dfe-4cc7c74a027f/build/node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
[PREBUILD]     at interceptingMod (/Users/screamz/.npm/_npx/4303fabdaa4f873a/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
[PREBUILD]     at interceptingMod (/Users/screamz/.npm/_npx/4303fabdaa4f873a/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
[PREBUILD]     at interceptingMod (/Users/screamz/.npm/_npx/4303fabdaa4f873a/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
[PREBUILD]     at interceptingMod (/Users/screamz/.npm/_npx/4303fabdaa4f873a/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
[PREBUILD]     at interceptingMod (/Users/screamz/.npm/_npx/4303fabdaa4f873a/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
[PREBUILD]     at interceptingMod (/Users/screamz/.npm/_npx/4303fabdaa4f873a/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
[PREBUILD]     at interceptingMod (/Users/screamz/.npm/_npx/4303fabdaa4f873a/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
[PREBUILD] 
Error: bash exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/screamz/.npm/_npx/4303fabdaa4f873a/node_modules/@expo/spawn-async/build/spawnAsync.js:43:23)
    at Object.onceWrapper (node:events:646:26)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at spawnAsync (/Users/screamz/.npm/_npx/4303fabdaa4f873a/node_modules/@expo/spawn-async/build/spawnAsync.js:8:21)
    at spawn (/Users/screamz/.npm/_npx/4303fabdaa4f873a/node_modules/@expo/turtle-spawn/dist/index.js:17:47)
    at BuildContext.runExpoCliCommandAsync [as runExpoCliCommand] (/Users/screamz/.npm/_npx/4303fabdaa4f873a/node_modules/eas-cli-local-build-plugin/dist/expoCli.js:14:39)
    at prebuildAsync (/Users/screamz/.npm/_npx/4303fabdaa4f873a/node_modules/@expo/build-tools/dist/utils/prebuild.js:14:15)
    at /Users/screamz/.npm/_npx/4303fabdaa4f873a/node_modules/@expo/build-tools/dist/builders/ios.js:33:52
    at BuildContext.runBuildPhase (/Users/screamz/.npm/_npx/4303fabdaa4f873a/node_modules/@expo/build-tools/dist/context.js:48:34)
    at Object.iosBuilder (/Users/screamz/.npm/_npx/4303fabdaa4f873a/node_modules/@expo/build-tools/dist/builders/ios.js:29:23)
    at async buildIosAsync (/Users/screamz/.npm/_npx/4303fabdaa4f873a/node_modules/eas-cli-local-build-plugin/dist/ios.js:49:27)
    at async buildAsync (/Users/screamz/.npm/_npx/4303fabdaa4f873a/node_modules/eas-cli-local-build-plugin/dist/build.js:28:32)
    at async main (/Users/screamz/.npm/_npx/4303fabdaa4f873a/node_modules/eas-cli-local-build-plugin/dist/main.js:16:9)
[CLEAN_UP_CREDENTIALS] Destroying keychain - /var/folders/tt/zmqlq5ws4kx6_dvdxp90f5v80000gn/T/turtle-v2-a2ce6cff-2f2c-480b-8a8f-776d4014faf2.keychain
[CLEAN_UP_CREDENTIALS] Removing provisioning profile
```

### Environment

// Not needed

### Please specify your device/emulator/simulator platform, model and version

IOS

### Reproducible demo or steps to reproduce from a blank project

Not Needed

**Comment by ScreamZ** [comment]
@brentvatne @EvanBacon The fix has been released: https://github.com/stripe/stripe-react-native/pull/936/files

Can you update the `expo install` version for this package?

**Comment by EvanBacon** [comment]
Will do this now

**Comment by brentvatne** [comment]
I asked the stripe folks if they can backport this config-plugin version bump to the 0.6.x release. Until then you can use yarn resolutions or just install the latest 0.9.0 version of @stripe/stripe-react-native, provided that you don't use Expo Go

**Comment by ScreamZ** [comment]
> @ScreamZ We will do this now. We are also investigating moving to a public endpoint that the community can contribute to.

Would be awesome yep, so we can contribute 🥳

> I asked the stripe folks if they can backport this config-plugin version bump to the 0.6.x release. Until then you can use yarn resolutions or just install the latest 0.9.0 version of @stripe/stripe-react-native, provided that you don't use Expo Go

That's what I did 💪🏻 what's the release process for upgrading external libs to newer version ? How can we help you for that ?


Thanks

**Comment by EvanBacon** [comment]
Not much we can do from this repo since config plugins are decentralized.
