### ISSUE TITLE
Running expo upgrade gives error: Failed to install expo package with error: yarnpkg exited with signal: SIGABRT

### ISSUE THREAD

**Issue by haibert** [expo/expo-cli#4366]
### Summary

Running expo upgrade gives error: Failed to install expo package with error: yarnpkg exited with signal: SIGABRT

### Environment

 expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
      Watchman: 2022.02.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.1 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.3
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Mac M1 

### Error output

`
Error: yarnpkg exited with signal: SIGABRT
    at ChildProcess.completionListener (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:64:13)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    ...
    at spawnAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at YarnPackageManager._runAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/package-manager/src/NodePackageManagers.ts:327:31)
    at YarnPackageManager.addWithParametersAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/package-manager/src/NodePackageManagers.ts:272:16)
    at YarnPackageManager.addAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/package-manager/src/NodePackageManagers.ts:276:5)
    at upgradeAsync (/usr/local/lib/node_modules/expo-cli/src/commands/info/upgradeAsync.ts:496:7)
    at actionAsync (/usr/local/lib/node_modules/expo-cli/src/commands/info/upgradeAsync.ts:42:3)
`

### Reproducible demo or steps to reproduce from a blank project

Cant reproduce

**Comment by haibert** [comment]
I was able to work around this by initializing a new project and moving all my code over.

**Comment by IjzerenHein** [comment]
Having the same problem here on an **Intel based Mac**:

```
hein@HFJs-MacBook-Pro app % expo upgrade
Your git working tree is clean
To revert the changes after this command completes, you can run the following:
  git clean --force && git reset --hard
✔ You are currently using SDK 44.0.0. Would you like to update to the latest version, 45.0.0? … yes


✖ Failed to install expo package with error: yarnpkg exited with signal: SIGABRT
yarnpkg exited with signal: SIGABRT
Error: yarnpkg exited with signal: SIGABRT
    at ChildProcess.completionListener (/Users/hein/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:64:13)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    ...
    at spawnAsync (/Users/hein/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at YarnPackageManager._runAsync (/Users/hein/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/node_modules/@expo/package-manager/src/NodePackageManagers.ts:327:31)
    at YarnPackageManager.addWithParametersAsync (/Users/hein/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/node_modules/@expo/package-manager/src/NodePackageManagers.ts:272:16)
    at YarnPackageManager.addAsync (/Users/hein/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/node_modules/@expo/package-manager/src/NodePackageManagers.ts:276:5)
    at upgradeAsync (/Users/hein/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/src/commands/info/upgradeAsync.ts:496:7)
    at actionAsync (/Users/hein/.volta/tools/image/packages/expo-cli/lib/node_modules/expo-cli/src/commands/info/upgradeAsync.ts:42:3)
```

Env:

```
hein@HFJs-MacBook-Pro app % expo --version
5.4.7
hein@HFJs-MacBook-Pro app % expo doctor
🎉 Didn't find any issues with the project!
hein@HFJs-MacBook-Pro app % npx expo-env-info
Need to install the following packages:
  expo-env-info
Ok to proceed? (y) y

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.volta/tools/image/node/16.13.0/bin/node
      Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
      npm: 8.1.0 - ~/.volta/tools/image/node/16.13.0/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/hein/.rvm/gems/ruby-2.6.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 26, 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2, 31.0.0
        System Images: android-22 | Google APIs ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Android TV Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Android TV Intel x86 Atom, android-30 | Google Play Intel x86 Atom
        Android NDK: 21.3.6528147
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.6 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed
```

**Comment by IjzerenHein** [comment]
For me, deleting `yarn.lock` and `node_modules`, and re-running `yarn` did the trick.
After that `expo upgrade` worked as expected.
