### ISSUE TITLE
Fresh project fails to build with expo run:android

### ISSUE THREAD

**Issue by homosape** [expo/expo-cli#4389]
### Summary

I've initialized a fresh project with expo init using a bare workflow and expo run:android command fails with the following errors
<img width="1126" alt="Screenshot 2022-05-23 at 02 33 38" src="https://user-images.githubusercontent.com/70649220/169718863-aadf5d2b-c99c-4255-9727-fb9861ae97d0.png">
 

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.18 - ~/.yarn/bin/yarn
      npm: 8.5.0 - /usr/local/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0
        System Images: android-28 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-S | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.6
    Expo Workflow: bare

```

### Please specify your device/emulator/simulator platform, model and version

Android Emulator Pixel 4 XL, API 31, arm64

### Error output

```

> Task :app:compileDebugJavaWithJavac FAILED
/Users/ika/Desktop/mab/android/app/src/main/java/com/mab/newarchitecture/MainApplicationReactNativeHost.java:22: error: cannot find symbol
import com.mab.BuildConfig;
              ^
  symbol:   class BuildConfig
  location: package com.mab
/Users/ika/Desktop/mab/android/app/src/main/java/com/mab/newarchitecture/MainApplicationReactNativeHost.java:42: error: cannot find symbol
    return BuildConfig.DEBUG;
           ^
  symbol:   variable BuildConfig
  location: class MainApplicationReactNativeHost
/Users/ika/Desktop/mab/android/app/src/main/java/com/mab/MainApplication.java:29: error: cannot find symbol
      return BuildConfig.DEBUG;
             ^
  symbol: variable BuildConfig
/Users/ika/Desktop/mab/android/app/src/main/java/com/mab/MainApplication.java:52: error: cannot find symbol
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
        ^
  symbol:   variable BuildConfig
  location: class MainApplication
/Users/ika/Desktop/mab/android/app/src/main/java/com/mab/MainApplication.java:52: error: illegal parenthesized expression
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
       ^
/Users/ika/Desktop/mab/android/app/src/main/java/com/mab/MainApplication.java:63: error: cannot find symbol
    ReactFeatureFlags.useTurboModules = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
                                        ^
  symbol:   variable BuildConfig
  location: class MainApplication
/Users/ika/Desktop/mab/android/app/src/main/java/com/mab/MainApplication.java:85: error: cannot find symbol
    if (BuildConfig.DEBUG) {
        ^
  symbol:   variable BuildConfig
  location: class MainApplication
/Users/ika/Desktop/mab/android/app/src/main/java/com/mab/MainApplication.java:85: error: illegal parenthesized expression
    if (BuildConfig.DEBUG) {
       ^
/Users/ika/Desktop/mab/android/app/src/main/java/com/mab/MainActivity.java:18: error: package R does not exist
    setTheme(R.style.AppTheme);
              ^
Note: /Users/ika/Desktop/mab/android/app/src/debug/java/com/mab/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
9 errors
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 52s
516 actionable tasks: 267 executed, 249 up-to-date
/Users/ika/Desktop/mab/android/gradlew exited with non-zero code: 1
Error: /Users/ika/Desktop/mab/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:483:26)
    at ChildProcess.emit (events.js:376:20)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
    ...
    at spawnAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnGradleAsync (/usr/local/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:83:18)
    at assembleAsync (/usr/local/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:57:16)
    at actionAsync (/usr/local/lib/node_modules/expo-cli/src/commands/run/android/runAndroid.ts:143:9)
```

### Reproducible demo or steps to reproduce from a blank project

Initialize new bare react native project with expo init and run expo run:android

**Comment by homosape** [comment]
My bad, I had a mismatch of package names.

**Comment by stoickeyboard** [comment]
@homosape what do you mean buy mismatch in package names? I'm runnung into the same issue

**Comment by homosape** [comment]
@stoickeyboard for example go to MainActivity.java and on the first line you should see the following
```
package com.example
```

1. Make sure that you are using same package name wherever it's mentioned in android folder
2. Make sure your folder names match your package. For example
```
android > app > src > main > java > com > example
```
Here **com > example** folders match my package name in MainActivity.java

**Comment by stoickeyboard** [comment]
@homosape Gotcha. Thanks for the reply. I ended up using this solution to handle the naming automatically

https://github.com/expo/expo/issues/21477#issuecomment-1454260119
