### ISSUE TITLE
Expo start not working web

### ISSUE THREAD

**Issue by Samyak-Coder** [expo/expo-cli#4400]
### Summary

I was trying to run my react app with expo start in npm v18.2.0 , after I installed expo-cli i also audited it. 
Then i ran the expo start command and pressed "w" for web and got this error -

RuntimeError: abort(Error: error:0308010C:digital envelope routines::unsupported). Build with -s ASSERTIONS=1 for more info.
    at process.abort (C:\Users\DELL\Desktop\joyous-cookies\node_modules\metro-hermes-compiler\src\emhermesc.js:796:13)
    at process.emit (node:events:527:28)
    at process.emit (C:\Users\DELL\AppData\Roaming\npm\node_modules\expo-cli\node_modules\source-map-support\source-map-support.js:439:21)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:32)
Node.js v18.2.0

even the javaScript didn't started buliding after pressing 'w'

### Environment

i have npm and this command is not working, sorry

### Please specify your device/emulator/simulator platform, model and version

windows 11,  i3-4030U CPU

### Error output

RuntimeError: abort(Error: error:0308010C:digital envelope routines::unsupported). Build with -s ASSERTIONS=1 for more info.
    at process.abort (C:\Users\DELL\Desktop\joyous-cookies\node_modules\metro-hermes-compiler\src\emhermesc.js:796:13)
    at process.emit (node:events:527:28)
    at process.emit (C:\Users\DELL\AppData\Roaming\npm\node_modules\expo-cli\node_modules\source-map-support\source-map-support.js:439:21)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:32)
Node.js v18.2.0

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.dev/@samyak-coder/chat-app-beta

**Comment by EvanBacon** [comment]
This should be fixed with the new Expo CLI in SDK 46
