### ISSUE TITLE
`npx install-expo-modules` throw an unknown syntax error `yarn add expo@>=45.0.0 --non-interactive` on yarn 3.2.1

### ISSUE THREAD

**Issue by DevYuns** [expo/expo-cli#4406]
### Summary

When I try to `npx install-expo-modules` on my bare project, then throw an error like below. 
```
❯ npx install-expo-modules
✔ Expo modules minimum iOS requirement is 12.0. This tool will change your iOS deployment target to 12.0. Do you want to continue? … yes
› Updating your project...
› Installing expo packages...
> yarn add expo@^45.0.0 --non-interactive
Unknown Syntax Error: Command not found; did you mean one of:

  0. yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
  1. yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
```

I think this error was occurred due to the yarn version. because there is no error if I tried to that command(`npx install-expo-modules`) in yarn@1.22.1. When I tried with `yarn@3.2.1`, then throw the error.

### Environment

```  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 3.2.1 - ~/.nvm/versions/node/v16.13.1/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
      Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.16.23 => 0.16.24
      expo: ^45.0.2 => 45.0.4
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 18.1.0
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.3
    Expo Workflow: bare
```

### Please specify your device/emulator/simulator platform, model and version

N/A

### Error output

```
android.mainApplication: withDefaultBaseMods ➜ withAndroidBaseMods ➜ withGeneratedBaseMods ➜ withAndroidMainApplicationBaseMod
android.mainApplication: withAndroidModules ➜ withPlugins ➜ withStaticPlugin ➜ withAndroidModulesMainApplication ➜ withMainApplication
android.mainActivity: withDefaultBaseMods ➜ withAndroidBaseMods ➜ withGeneratedBaseMods ➜ withAndroidMainActivityBaseMod
android.mainActivity: withAndroidModules ➜ withPlugins ➜ withStaticPlugin ➜ withAndroidModulesMainActivity ➜ withMainActivity
android.settingsGradle: withDefaultBaseMods ➜ withAndroidBaseMods ➜ withGeneratedBaseMods ➜ withAndroidSettingsGradleBaseMod
android.settingsGradle: withAndroidModules ➜ withPlugins ➜ withStaticPlugin ➜ withAndroidModulesSettingGradle ➜ withSettingsGradle
ios.dangerous: withDefaultBaseMods ➜ withIosBaseMods ➜ withGeneratedBaseMods ➜ withIosDangerousBaseMod
ios.dangerous: withIosDeploymentTarget ➜ withIosDeploymentTargetPodfile ➜ withDangerousMod
ios.dangerous: withIosModules ➜ withPlugins ➜ withStaticPlugin ➜ withIosModulesPodfile ➜ withDangerousMod
ios.dangerous: withIosModules ➜ withPlugins ➜ withStaticPlugin ➜ withIosModulesSwiftBridgingHeader ➜ withDangerousMod
ios.dangerous: withIosModules ➜ withPlugins ➜ withStaticPlugin ➜ withIosModulesAppDelegateObjcHeader ➜ withDangerousMod
ios.xcodeproj: withDefaultBaseMods ➜ withIosBaseMods ➜ withGeneratedBaseMods ➜ withIosXcodeprojBaseMod
ios.xcodeproj: withIosDeploymentTarget ➜ withIosDeploymentTargetXcodeProject ➜ withXcodeProject
ios.appDelegate: withDefaultBaseMods ➜ withIosBaseMods ➜ withGeneratedBaseMods ➜ withIosAppDelegateBaseMod
ios.appDelegate: withIosModules ➜ withPlugins ➜ withStaticPlugin ➜ withIosModulesAppDelegate ➜ withAppDelegate
› Installing expo packages...
> yarn add expo@^45.0.0 --non-interactive
Unknown Syntax Error: Command not found; did you mean one of:

  0. yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
  1. yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...

While running add expo@^45.0.0 --non-interactive
> yarn add expo@>=45.0.0-0 <46.0.0 --non-interactive
Unknown Syntax Error: Command not found; did you mean one of:

  0. yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
  1. yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...

While running add "expo@>=45.0.0-0 <46.0.0" --non-interactive
Uncaught Error Error: yarnpkg exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/dean/Documents/workspace/dooboolab/dooboo-native-ts/node_modules/install-expo-modules/build/index.js:2:19423)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    ...
    at spawnAsync (/Users/dean/Documents/workspace/dooboolab/dooboo-native-ts/node_modules/install-expo-modules/build/index.js:2:18874)
    at YarnPackageManager._runAsync (/Users/dean/Documents/workspace/dooboolab/dooboo-native-ts/node_modules/install-expo-modules/build/index.js:33:914024)
    at YarnPackageManager.addWithParametersAsync (/Users/dean/Documents/workspace/dooboolab/dooboo-native-ts/node_modules/install-expo-modules/build/index.js:33:912961)
    at async installExpoPackageAsync (/Users/dean/Documents/workspace/dooboolab/dooboo-native-ts/node_modules/install-expo-modules/build/index.js:33:976785)
    at async runAsync (/Users/dean/Documents/workspace/dooboolab/dooboo-native-ts/node_modules/install-expo-modules/build/index.js:33:959789)
    at async /Users/dean/Documents/workspace/dooboolab/dooboo-native-ts/node_modules/install-expo-modules/build/index.js:33:959994 {
  pid: 72506,
  output: [ '', '' ],
  stdout: '',
  stderr: '',
  status: 1,
  signal: null
}
```

### Reproducible demo or steps to reproduce from a blank project

1. Init a project with `react-native init`
2. Specifying the yarn version : set `packageManager: yarn@3.2.1` in your package.json
3. try to `npx install-expo-modules`
4. then you can get the same error above.

**Comment by AskaHD** [comment]
Same issue here with `"packageManager": "yarn@3.2.0"`. I need to migrate from `unimodules` and `npx install-expo-modules` would help me quite a lot in the process.

**Comment by kbrandwijk** [comment]
Apparently, this command `yarn add expo@^45.0.0 --non-interactive` doesn't work because the `--non-interactive` flag is no longer available in yarn v3. At this moment, all I can say is: don't use yarn v3...

**Comment by DevYuns** [comment]
@kbrandwijk Ok. I will downgrade the yarn version 😢

**Comment by traviswimer** [comment]
I was able to make this work with Yarn v3 by cloning the repo and removing the yarn check that adds `--non-interactive`.

Basically, change [this line](https://github.com/expo/expo-cli/blob/48d14b4dddf8e6612d71c6ac8a7ca1c3bd1dc659/packages/install-expo-modules/src/utils/packageInstaller.ts#L12) to:
```javacsript
const isYarn = false;
```

Also, why was this closed? It seems like this bug could be fixed relatively easily by adding another check for the version of Yarn.
