### ISSUE TITLE
Request failed with status code 500 - expo build:android -t apk

### ISSUE THREAD

**Issue by ayez0001** [expo/expo-cli#4419]
### Summary

expo version 5.4.9
expo sdk 44

i use  expo  build:android -t apk to build apk file
but always receive below error.
May i know why ? it started happen yesterday. Pervious day is ok to build apk file.

Error: Request failed with status code 500
    at createError (/app/turtle/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/turtle/node_modules/axios/lib/core/settle.js:17:12)
    at RedirectableRequest.handleResponse (/app/turtle/node_modules/axios/lib/adapters/http.js:231:9)
    at RedirectableRequest.emit (events.js:387:35)
    at RedirectableRequest.emit (domain.js:470:12)
    at RedirectableRequest._processResponse (/app/turtle/node_modules/follow-redirects/index.js:426:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/app/turtle/node_modules/follow-redirects/index.js:57:10)
    at Object.onceWrapper (events.js:482:26)
    at ClientRequest.emit (events.js:375:28)
    at ClientRequest.emit (domain.js:470:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at HTTPParser.execute (<anonymous>)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:375:28)
    at TLSSocket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    npmPackages:
      babel-preset-expo: 9.0.1 => 9.0.1
      expo: ^44.0.6 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-navigation: ^4.3.1 => 4.4.4
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

cannot build. if can build i use Samsung S6 device to install apk file

### Reproducible demo or steps to reproduce from a blank project

1. open terminal
2. type "expo build:android -t apk" at project folder path
3. during "build in progress" --> terminal show  " Build failed.  Standalone build failed! "
4. i check log data from expo.dev --> show below error under "reading manifest" 

Error: Request failed with status code 500
    at createError (/app/turtle/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/turtle/node_modules/axios/lib/core/settle.js:17:12)
    at RedirectableRequest.handleResponse (/app/turtle/node_modules/axios/lib/adapters/http.js:231:9)
    at RedirectableRequest.emit (events.js:387:35)
    at RedirectableRequest.emit (domain.js:470:12)
    at RedirectableRequest._processResponse (/app/turtle/node_modules/follow-redirects/index.js:426:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (/app/turtle/node_modules/follow-redirects/index.js:57:10)
    at Object.onceWrapper (events.js:482:26)
    at ClientRequest.emit (events.js:375:28)
    at ClientRequest.emit (domain.js:470:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at HTTPParser.execute (<anonymous>)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:375:28)
    at TLSSocket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)

**Comment by ayez0001** [comment]
i am able to build apk file now. I think Expo side fix the issue. Thank you very much.
