### ISSUE TITLE
Could not locate a valid AppDelegate at root

### ISSUE THREAD

**Issue by mustafakameldev** [expo/expo-cli#4430]
### Summary

When I command ```expo eject```
I got this error with the below log

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.3.0 - /opt/homebrew/bin/node
      Yarn: 1.22.10 - /opt/homebrew/bin/yarn
      npm: 8.11.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 23, 26, 28, 29, 30, 31
        Build Tools: 23.0.1, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs ARM 64 v8a, android-31 | Google Play ARM 64 v8a, android-S | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7678000
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.5 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 4.7.3
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

MacBook pro M1

### Error output

```[ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "estColor"
Please report this as an issue on https://github.com/expo/expo-cli/issues
UnexpectedError: [ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "/../testColor"
Please report this as an issue on https://github.com/expo/expo-cli/issues
    at getAppDelegateFilePath (/opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:26:11)
    at getAppDelegate (/opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:63:20)
    at Object.getSourceRoot (/opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:68:23)
    at getProjectName (/opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/utils/Xcodeproj.ts:32:28)
    at getIosNamedProjectPath (/opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:172:23)
    at setIconsAsync (/opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:107:31)
    at /opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:15:13
    at action (/opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:214:29)
    at interceptingMod (/opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:100:27)
    at action (/opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/createBaseMod.ts:73:27)
    at interceptingMod (/opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:100:21)
    at evalModsAsync (/opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:182:25)
    at compileModsAsync (/opt/homebrew/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:92:10)
    at configureManagedProjectAsync (/opt/homebrew/lib/node_modules/expo-cli/src/commands/eject/configureProjectAsync.ts:64:12)
    at prebuildAsync (/opt/homebrew/lib/node_modules/expo-cli/src/commands/eject/prebuildAsync.ts:92:25)
    at ejectAsync (/opt/homebrew/lib/node_modules/expo-cli/src/commands/eject/ejectAsync.ts:23:19)```

### Reproducible demo or steps to reproduce from a blank project

create expo app
then run ```expo eject```

**Comment by kbrandwijk** [comment]
It seems like you are using a dependency that uses an older version of `@expo/config-plugins`, which causes this error. You can run `yarn why @expo/config-plugins` (or `npm why ...`) and see which package uses an older version.

Also make sure you have the latest `expo-cli` installed.

**Comment by theohdv** [comment]
Removing `expo-udpates` from my dependencies fix the issue in our project.

Don't know how to use both ..

**Comment by codal-mpawar** [comment]
@kbrandwijk https://github.com/expo/expo-cli/issues/4391#issuecomment-1246635841 Can you please help? we are stuck here.
