### ISSUE TITLE
ApiV2Error: Cannot sign manifest with scopeKey, projectId, originalFullName, or currentFullName fields.

### ISSUE THREAD

**Issue by MisterMunchkin** [expo/expo-cli#4440]
### Expected Behavior

Run expo start --tunnel, and then be able to scan the qr code on my physical ios device.

### Actual Behavior

After scanning the qr code I get the error mentioned 
<img width="692" alt="Screen Shot 2022-06-23 at 10 48 13 PM" src="https://user-images.githubusercontent.com/9417970/175327994-d671c342-d7fb-4b6f-a657-2aa317a3bf8e.png">
![thumbnail_12139](https://user-images.githubusercontent.com/9417970/175329205-21744589-0cfe-4ca3-af71-cbc23f50cc51.jpg)

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 29, 30, 31, 32
        Build Tools: 29.0.2, 30.0.0, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
        System Images: android-29 | Android TV Intel x86 Atom, android-29 | ARM 64 v8a, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play ARM 64 v8a, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.16.16 => 0.16.23 
      babel-preset-expo: 8.5.1 => 8.5.1 
      expo: >=43.0.0-0 <44.0.0 => 43.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.4.11
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

iPhone 8 plus, A1897, 15.5

### Error output

ApiV2Error: Cannot sign manifest with scopeKey, projectId, originalFullName, or currentFullName fields.
    at ApiV2Client._requestAsync (/Users/robint/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/xdl/src/ApiV2.ts:244:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at getSignedManifestStringAsync (/Users/robint/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/xdl/src/start/ManifestHandler.ts:418:24)
    at getManifestStringAsync (/Users/robint/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/xdl/src/start/ManifestHandler.ts:389:12)
    at getManifestResponseAsync (/Users/robint/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/xdl/src/start/ManifestHandler.ts:315:22)
    at /Users/robint/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/xdl/src/start/ManifestHandler.ts:151:49
ApiV2Error: Cannot sign manifest with scopeKey, projectId, originalFullName, or currentFullName fields.
    at ApiV2Client._requestAsync (/Users/robint/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/xdl/src/ApiV2.ts:244:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at getSignedManifestStringAsync (/Users/robint/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/xdl/src/start/ManifestHandler.ts:418:24)
    at getManifestStringAsync (/Users/robint/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/xdl/src/start/ManifestHandler.ts:389:12)
    at getManifestResponseAsync (/Users/robint/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/xdl/src/start/ManifestHandler.ts:315:22)
    at /Users/robint/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/xdl/src/start/ManifestHandler.ts:151:49
ApiV2Error: Cannot sign manifest with scopeKey, projectId, originalFullName, or currentFullName fields.
    at ApiV2Client._requestAsync (/Users/robint/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/xdl/src/ApiV2.ts:244:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at getSignedManifestStringAsync (/Users/robint/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/xdl/src/start/ManifestHandler.ts:418:24)
    at getManifestStringAsync (/Users/robint/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/xdl/src/start/ManifestHandler.ts:389:12)
    at getManifestResponseAsync (/Users/robint/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/xdl/src/start/ManifestHandler.ts:315:22)
    at /Users/robint/.nvm/versions/node/v16.14.2/lib/node_modules/expo-cli/node_modules/xdl/src/start/ManifestHandler.ts:151:49

### Reproducible demo or steps to reproduce from a blank project

I don't know how I can reproduce this without my environment.

**Comment by kbrandwijk** [comment]
Do you have any of these fields (especially `originalFullName` or `currentFullName`) in your app.json? If so, remove those.

**Comment by MisterMunchkin** [comment]
Removing the two fields mentioned above worked! Thanks a lot!

Out of curiosity what were those fields for?

**Comment by kbrandwijk** [comment]
Those are internal fields that shouldn't be used directly.

**Comment by pagreczner** [comment]
@kbrandwijk why is this listed in the app.json documentation if it shouldn't be used? https://docs.expo.dev/versions/latest/config/app/#originalfullname

Trying to understand what from the docs we can/should specify and what is considered internal. Thanks!

**Comment by kbrandwijk** [comment]
> @kbrandwijk why is this listed in the app.json documentation if it shouldn't be used? https://docs.expo.dev/versions/latest/config/app/#originalfullname
> 
> Trying to understand what from the docs we can/should specify and what is considered internal. Thanks!

We'll make sure to document this better.

**Comment by pagreczner** [comment]
> > @kbrandwijk why is this listed in the app.json documentation if it shouldn't be used? https://docs.expo.dev/versions/latest/config/app/#originalfullname
> > Trying to understand what from the docs we can/should specify and what is considered internal. Thanks!
> 
> We'll make sure to document this better.

Ok, thanks for the update

**Comment by RomeHein** [comment]
`originalFullName` is also required when using `AuthSession` with `proxy: true`...
What would be the solution then ?

**Comment by Mashpy** [comment]
> `originalFullName` is also required when using `AuthSession` with `proxy: true`... What would be the solution then ?

```expo logout``` works for me
