### ISSUE TITLE
Error: Body must be a string. Received: undefined.

### ISSUE THREAD

**Issue by deleonn** [expo/expo-cli#4450]
### Summary

Im using `eas` and `expo` to build and start my application. Upon running `eas build --platform android --profile=development` I do a `expo start --dev-client` for android, but the expo start fails with an error. My project is running inside a lerna monorepo.

**Dependencies**
```
"react": "17.0.2",
"react-native": "0.68.2",
"expo": "^45.0.0",
"eas-cli": "^0.53.0",
"expo-cli": "^5.4.11",
"expo-dev-client": "^0.9.6",
```

**Node**
```
❯ node -v                                                                                                                                
v16.15.1
❯ npm -v                                                                                                                                
v8.11.0
```

### Environment

  expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 30, 31
        Build Tools: 29.0.2, 31.0.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.16.10 => 0.16.24 
    npmGlobalPackages:
      eas-cli: 0.49.0
      expo-cli: 5.4.12
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

N/A

### Error output

```
Error: Body must be a string. Received: undefined.
    at devAssert (../node_modules/graphql/jsutils/devAssert.js:12:11)
    at new Source (../node_modules/graphql/language/source.js:32:32)
    at new Parser (../node_modules/graphql/language/parser.js:98:9)
    at Object.parse (../node_modules/graphql/language/parser.js:31:18)
    at Object.<anonymous> (../node_modules/graphql-tools/src/stitching/introspectSchema.ts:7:48)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

### Reproducible demo or steps to reproduce from a blank project

expo start --dev-client --android

**Comment by fridaystreet** [comment]
not much help at this stage I know, but I'm having the exact same error but I'm using graphql yoga server in lambda. . Did you manage to solve this?
