### ISSUE TITLE
npx expo-optimize command not working...

### ISSUE THREAD

**Issue by hypercoder457** [expo/expo-cli#4459]
### Summary

As you can see by the title, npx expo-optimize is failing to work. The error told me to report that as a bug, so here's the full error:
![image](https://user-images.githubusercontent.com/63746650/177821878-ddb64199-49e7-4048-a0c2-09a6e34b134c.png)

### Environment

expo-env-info 1.0.4 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD   
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Windows 10 dell laptop

### Error output

This will overwrite the original assets.

› Optimizing assets...

Aborting run
An unexpected error was encountered. Please report it as a bug:
Error: ENOENT: no such file or directory, stat 'C:\Users\rpshende\AppData\Local\Temp\4ff737f1759b7061b7a65172bf06c76a\favicon.png'
    at Object.statSync (node:fs:1538:3)
    at C:\Users\rpshende\AppData\Local\npm-cache\_npx\98ec667596dd93f6\node_modules\expo-optimize\build\index.js:28:66414
    at C:\Users\rpshende\AppData\Local\npm-cache\_npx\98ec667596dd93f6\node_modules\expo-optimize\build\index.js:41:934467        
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'C:\\Users\\rpshende\\AppData\\Local\\Temp\\4ff737f1759b7061b7a65172bf06c76a\\favicon.png'
}

### Reproducible demo or steps to reproduce from a blank project

1. Run "`expo init test`", then choose a blank project under the managed workflow
2. After the command finishes, go into the directory of the project & run the command '`npx expo-optimize`'.
3. You should see a message like this:
![image](https://user-images.githubusercontent.com/63746650/177824635-b915873a-2830-49b6-aa1b-3c366a44a772.png)

NOTE: in my case, the directory that is not found always changes.

**Comment by ahbridged** [comment]
seeing this same issue as well

**Comment by bzozoo** [comment]
I have same issue

**Comment by elwheshi** [comment]
Same issue here

**Comment by tedymeer** [comment]
I'm facing the same issue

**Comment by jordann93** [comment]
Same here...

**Comment by Ashizl** [comment]
Also having this issue.

**Comment by rahuldasgupta** [comment]
Still facing the same issue here as well.

**Comment by zechs1460** [comment]
Same

**Comment by AhmedAlihashi** [comment]
dealing with the same problem

**Comment by WaDadidou** [comment]
Same issue

**Comment by copelandhouse2** [comment]
Same issue

**Comment by enagorny** [comment]
Works for me on macOS. Could it be Windows only issue?

**Comment by copelandhouse2** [comment]
> Works for me on macOS. Could it be Windows only issue?

Yes, I believe it is a Windows issue.  I have a colleague on the project that uses a mac and he can run it fine.  I cannot.

**Comment by copelandhouse2** [comment]
Not a Windows issue... but an issue with the expo-optimize command on Windows.

**Comment by Layrovell** [comment]
Still facing the same issue as well.
