### ISSUE TITLE
JavaScript engine configuration is inconsistent between app.config.ts and Android native project

### ISSUE THREAD

**Issue by lumairink** [expo/expo-cli#4460]
### Summary

I'm using expo SDK 44 and I'm trying to publish my project with hermes enabled but I've got the following error:

```
Error: JavaScript engine configuration is inconsistent between app.config.ts and Android native project.
```
But I have hermes enabled in both app.json and the Android native project

![Screenshot 2022-07-07 165844](https://user-images.githubusercontent.com/8965805/177867029-938038f4-c124-4afd-bf76-48db80ea5b13.png)

A strange thing that happened was when I disabled hermes in the app.json the expo-cli started to identify the hermes in the native project, but of course it gave me an inconsistency error:

![Screenshot 2022-07-07 165654](https://user-images.githubusercontent.com/8965805/177867934-a803fa05-7b0a-4eec-951d-acfc8f24b84c.png)

### Environment

expo-env-info 1.0.4 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.13.2 - C:\node\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.1 - C:\node\npm.CMD
    SDKs:
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8092744
    npmPackages:
      expo: ~44.0.6 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Emulator Pixel 3 API 29

### Error output

```
Error: JavaScript engine configuration is inconsistent between app.config.ts and Android native project.
Please check the following files for inconsistencies:
  - C:\workspace\app-aprova-brasil\app.config.ts
  - C:\workspace\app-aprova-brasil\android\gradle.properties
  - C:\workspace\app-aprova-brasil\android\app\build.gradle
Learn more: https://expo.fyi/hermes-android-config
    at maybeThrowFromInconsistentEngineAsync (C:\nvm\v16.13.2\node_modules\expo-cli\node_modules\@expo\dev-server\src\HermesBundler.ts:112:11)
    at maybeAddHermesBundleAsync (C:\nvm\v16.13.2\node_modules\expo-cli\node_modules\@expo\dev-server\sdev-server\src\Hermrc\MetroDevServer.ts:214:5)
    at bundleAsync (C:\nvm\v16.13.2\node_modules\expo-cli\node_modules\@expo\dev-server\src\MetroDevSerrc\MetroDevServer.tver.ts:247:26)
    at createBundlesAsync (C:\nvm\v16.13.2\node_modules\expo-cli\node_modules\xdl\src\project\createBunver.ts:247:26)     dlesAsync.ts:100:19)                                                                                   dlesAsync.ts:100:19
    at Object.publishAsync (C:\nvm\v16.13.2\node_modules\expo-cli\node_modules\xdl\src\project\publishAsync.ts:86:19)                                                                                         sync.ts:86:19)     
    at actionAsync (C:\nvm\v16.13.2\node_modules\expo-cli\src\commands\publish\publishAsync.ts:103:18)
```

### Reproducible demo or steps to reproduce from a blank project

- Create an expo project in bare workflow
- Enable hermes in both app.json and native project
- Publish the app (via `expo publish`)

I don't know if it makes any difference but I have some native UI components using OpenCV in the project.

**Comment by lumairink** [comment]
@brentvatne Yes. We initialized the project with SDK 44, so this configuration is automatic

**Comment by brentvatne** [comment]
share a link to a minimal github project where this can be reproduced please :)

**Comment by lucasfsduarte** [comment]
I'm facing the same error on SDK 49. @lumairink did you provide some reproducible example?
