### ISSUE TITLE
Expo-cli crashes while running project on web-browser

### ISSUE THREAD

**Issue by Synonymous64** [expo/expo-cli#4463]
### Summary

I am trying to run my project/app through web-browser not from any sort of emulator, but every time I select to run it from web-browser it crashes down even after being root user in Linux Ubuntu. I guess it probably not tested for latest Node.js v18.1.0. It is supposed to run smoothy as I saw in my youtube tutorials.
![Screenshot from 2022-07-09 19-27-55](https://user-images.githubusercontent.com/85348583/178109317-dd754d42-8025-4694-9273-90aa244e101f.png)
![Screenshot from 2022-0
![Screenshot from 2022-07-09 19-28-42](https://user-images.githubusercontent.com/85348583/178109331-e4405c34-d324-472a-93e8-58030d2be8c0.png)
7-09 19-28-37](https://user-images.githubusercontent.com/85348583/178109326-db61d3b3-8938-408e-ba0d-06cb5e079362.png)

### Environment

`yarn run start`

› Press a │ open Android
› Press w │ open web

› Press r │ reload app
› Press m │ toggle menu
› Press d │ show developer tools
› shift+d │ toggle auto opening developer tools on startup (disabled)
› Press ? │ show all commands

### Please specify your device/emulator/simulator platform, model and version

Using yarn with Node.js v18.1.0. in Ubuntu 20.04.4 LTS x86_64

### Error output

`EXPD_DEBUG=TRUE<w>`

*OUTPUT->*

Starting Webpack on port 19006 in development mode.
⚠ ｢wds｣: transportMode is an experimental option, meaning its usage could potentially change without warning
› Open in the web browser...
› Press ? │ show all commands
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/NormalModule.js:471:10)
    at /usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/NormalModule.js:503:5
    at /usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/NormalModule.js:358:12
    at /usr/local/lib/node_modules/expo-cli/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/usr/local/lib/node_modules/expo-cli/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/usr/local/lib/node_modules/expo-cli/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /usr/local/lib/node_modules/expo-cli/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/usr/local/lib/node_modules/expo-cli/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/usr/local/lib/node_modules/expo-cli/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/usr/local/lib/node_modules/expo-cli/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/usr/local/lib/node_modules/expo-cli/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /usr/local/lib/node_modules/expo-cli/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/home/synonymous/Desktop/React-Native/AwesomeProject/node_modules/metro-hermes-compiler/src/emhermesc.js:77
          throw ex;
          ^

RuntimeError: abort(Error: error:0308010C:digital envelope routines::unsupported). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/home/synonymous/Desktop/React-Native/AwesomeProject/node_modules/metro-hermes-compiler/src/emhermesc.js:402:15)
    at process.emit (node:events:539:35)
    at process.emit (/usr/local/lib/node_modules/expo-cli/node_modules/source-map-support/source-map-support.js:439:21)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:32)

Node.js v18.1.0
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### AFTER CREATING PROJECT -->

`yarn run start`

_Metro waiting on exp://address_

_press w to run in web-browser_

_› Open in the web browser...
› Press ? │ show all commands
Error: error:0308010C:digital envelope routines::unsupported_

**Comment by kbrandwijk** [comment]
> Error: error:0308010C:digital envelope routines::unsupported

This error looks similar to what we've seen on Node 17. Please stick to an LTS version of Node, as mentioned in our docs. This will be addressed in the new [versioned CLI](https://blog.expo.dev/new-versioned-expo-cli-cf6e10632656) before Node 18 becomes LTS.
