### ISSUE TITLE
Can"t build on web with latest expo-cli version

### ISSUE THREAD

**Issue by gyl89** [expo/expo-cli#4507]
### Summary

When I try to deploy my react native app on web using the command `npx expo export:web`, I get an error. Installing webpack locally or webpack-dev-server.

This happens for expo-cli 6.0.2.

I had a different issue with 6.0.1 where my web app  would build but it was blank and the console displays some cryptic webpack error.

Everything is fine with expo-cli 5.*

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.3 - /opt/local/bin/node
      Yarn: 1.22.10 - /opt/local/bin/yarn
      npm: 7.21.1 - /opt/local/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.2 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 0.54.1
      expo-cli: 6.0.2
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

MacBook pro M1 2020

### Error output

```
(node:3973) UnhandledPromiseRejectionWarning: Error: Cannot find module 'webpack-dev-middleware/lib/util'
Require stack:
- /localpath/node_modules/@expo/dev-server/build/webpack/getFileAsync.js
- /localpath/node_modules/@expo/dev-server/build/webpack/symbolicateMiddleware.js
- /localpath/node_modules/@expo/cli/build/src/start/server/webpack/WebpackBundlerDevServer.js
- /localpath/node_modules/@expo/cli/build/src/export/web/exportWebAsync.js
- /localpath/node_modules/@expo/cli/build/src/export/web/index.js
- /localpath/node_modules/@expo/cli/build/bin/cli
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/localpath/node_modules/@expo/dev-server/build/webpack/getFileAsync.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/localpath/node_modules/@expo/dev-server/build/webpack/symbolicateMiddleware.js:10:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3973) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3973) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Reproducible demo or steps to reproduce from a blank project

Not relevant

**Comment by EvanBacon** [comment]
Fixed in https://github.com/expo/expo/pull/18439 but you can workaround by using expo-cli, or by installing `webpack-dev-middleware` in your project.
