### ISSUE TITLE
[next-js] Error: Unable to resolve module ./index from <PROJECT_ROOT>

### ISSUE THREAD

**Issue by oVerde** [expo/expo-cli#4509]
### Summary

The project can't even start, as the build phase starts it crash asking for a missing module that its name is unknown.

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.19 Pop!_OS 22.04 LTS
      Shell: 5.9 - /home/linuxbrew/.linuxbrew/bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.volta/tools/image/node/16.16.0/bin/node
      Yarn: 3.2.2 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
      npm: 8.12.1 - ~/.volta/tools/image/npm/8.12.1/bin/npm
      Watchman: 2022.07.04.00 - /home/linuxbrew/.linuxbrew/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 26, 30, 31, 32, 33
        Build Tools: 26.0.0, 29.0.2, 30.0.2, 30.0.3, 33.0.0, 33.0.0
        System Images: android-30 | Google Play Intel x86 Atom_64
    npmPackages:
      expo: ~46.0.3 => 46.0.3 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
    npmGlobalPackages:
      expo-cli: 5.5.1
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

ExpoGO

### Error output

```
Logs for your project will appear below. Press Ctrl+C to exit.
Started Metro Bundler
Error: Unable to resolve module ./index from /home/daniloverde/conduit/Conduit/.: 

None of these files exist:
  * index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * index/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
    at ModuleResolver.resolveDependency (/home/daniloverde/conduit/Conduit/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:136:15)
    at DependencyGraph.resolveDependency (/home/daniloverde/conduit/Conduit/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at /home/daniloverde/conduit/Conduit/node_modules/metro/src/lib/transformHelpers.js:129:24
    at Server._resolveRelativePath (/home/daniloverde/conduit/Conduit/node_modules/metro/src/Server.js:1137:12)
    at Server.requestProcessor [as _processBundleRequest] (/home/daniloverde/conduit/Conduit/node_modules/metro/src/Server.js:464:37)
    at Server._processRequest (/home/daniloverde/conduit/Conduit/node_modules/metro/src/Server.js:420:9)
Error: Unable to resolve module ./index from /home/daniloverde/conduit/Conduit/.: 

None of these files exist:
  * index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * index/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
    at ModuleResolver.resolveDependency (/home/daniloverde/conduit/Conduit/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:136:15)
    at DependencyGraph.resolveDependency (/home/daniloverde/conduit/Conduit/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at /home/daniloverde/conduit/Conduit/node_modules/metro/src/lib/transformHelpers.js:129:24
    at Server._resolveRelativePath (/home/daniloverde/conduit/Conduit/node_modules/metro/src/Server.js:1137:12)
    at Server.requestProcessor [as _processBundleRequest] (/home/daniloverde/conduit/Conduit/node_modules/metro/src/Server.js:464:37)
    at Server._processRequest (/home/daniloverde/conduit/Conduit/node_modules/metro/src/Server.js:420:9)
› Stopped server
```

### Reproducible demo or steps to reproduce from a blank project

- Bootstrap your project with Expo
  - Install the CLI: `npm i -g expo-cli`
  - Create a project: `expo init --template blank`
  - `cd` into the project
- Install the adapter:
  - **yarn:** `yarn add @expo/next-adapter`
  - npm: `npm i --save @expo/next-adapter`
- Add Next.js support: `yarn next-expo`
  - Always commit your changes first!
  - You can optionally choose which customizations you want to do with `--customize or -c`
  - Force reload changes with `--force or -f`
- Start the project with `yarn next dev`
  - Go to `http://localhost:3000/` to see your project!

### The Next wont' start neither `expo start`

**Comment by nrowley** [comment]
having the same issue too

**Comment by nrowley** [comment]
this is the package.json for the expo app, I don't have `@expo/next-adapter`

```


{
  "name": "@acme/expo",
  "version": "0.1.0",
  "main": "src/_app.tsx",
  "scripts": {
    "start": "expo start",
    "dev": "expo start --ios",
    "clean": "rm -rf .expo .turbo node_modules",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@acme/api": "*",
    "@shopify/flash-list": "^1.2.1",
    "@tanstack/react-query": "^4.7.2",
    "@trpc/client": "10.0.0-proxy-beta.13",
    "@trpc/react": "10.0.0-proxy-beta.13",
    "@trpc/server": "10.0.0-proxy-beta.13",
    "expo": "~46.0.10",
    "expo-status-bar": "~1.4.0",
    "nativewind": "^2.0.5",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-native": "0.70.1",
    "react-native-safe-area-context": "4.3.1",
    "react-native-web": "~0.18.9"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3",
    "@babel/preset-env": "^7.19.3",
    "@babel/runtime": "^7.19.0",
    "@types/react": "^18.0.21",
    "@types/react-native": "~0.70.4",
    "postcss": "^8.4.14",
    "tailwindcss": "^3.1.8",
    "typescript": "^4.8.3"
  },
  "private": true
}
```

**Comment by nrowley** [comment]
@oVerde did you manage to fix this or is this issue still a problem for you?

**Comment by EvanBacon** [comment]
@nrowley your project is using `"main": "src/_app.tsx"` which is not supported. React Native is hard coded to require the initial file to be `./index.js` (all extensions are supported). This is partially fixed in SDK 47 when using `expo-dev-client` in development. `expo-dev-client` replaces the hardcoded search in development, and Expo SDK 47 has a script to automatically detect the main file in production.

A more permanent solution will involve us shipping `expo-dev-client` in all projects.

**Comment by kevinhylant** [comment]
@EvanBacon should this warning be resolved by now using Expo SDK 49 & Expo Router?

I'm still getting the same warning since the main file is now app/_layout

**Comment by mikib0** [comment]
I get it after upgrade from sdk 48 to 49.

> @EvanBacon should this warning be resolved by now using Expo SDK 49 & Expo Router?
> 
> I'm still getting the same warning since the main file is now app/_layout
