### ISSUE TITLE
[ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate

### ISSUE THREAD

**Issue by sky150** [expo/expo-cli#4556]
### Summary

I want to start my react native with 'npm run ios'. 
This is the first time i've tried to run this project on mac (iphone simulator).
But since i cloned this project to my mac nothing has been working.

### Environment

Run `npm run ios``
Output:

> myplantsapp@1.0.0 ios
> expo run:ios

┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (6.0.5).                 │
│   You are currently using expo-cli 4.13.0                               │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
✔ The ios project is malformed, would you like to clear the project files and reinitialize them? … yes
✔ Cleared ios code
✔ Created native project | gitignore already synced
⚠️  Skipped Metro config updates:
› Existing Metro config found; not overwriting.
› You will need to extend the default @expo/metro-config in your Metro config.
  Learn more: https://docs.expo.dev/guides/customizing-metro

✔ Updated package.json and added index.js entry point for iOS and Android
🧶 Using Yarn to install packages. Pass --npm to use npm instead.
✔ Installed JavaScript dependencies 622ms
✖ Config sync failed
[ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "/Users/nataliesumbofilipe/app-projects/MyPlantsApp"
Please report this as an issue on https://github.com/expo/expo-cli/issues
UnexpectedError: [ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "/Users/nataliesumbofilipe/app-projects/MyPlantsApp"
Please report this as an issue on https://github.com/expo/expo-cli/issues
    at getAppDelegateFilePath (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:52:11)
    at getAppDelegate (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:114:20)
    at Object.getSourceRoot (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:119:23)
    at getProjectName (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/utils/Xcodeproj.ts:33:28)
    at getIosNamedProjectPath (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:172:23)
    at setIconsAsync (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:107:31)
    at /Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:15:13
    at action (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:227:29)
    at interceptingMod (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:27)
    at action (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/createBaseMod.ts:82:27)
    at interceptingMod (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at evalModsAsync (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:172:25)
    at compileModsAsync (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:82:10)
    at configureManagedProjectAsync (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/src/commands/eject/configureProjectAsync.ts:64:12)
    at prebuildAsync (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/src/commands/eject/prebuildAsync.ts:90:21)
    at actionAsync (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/src/commands/run/ios/runIos.ts:45:5)

### Please specify your device/emulator/simulator platform, model and version

Iphone 14 Emulator

### Error output

> myplantsapp@1.0.0 ios
> expo run:ios

┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (6.0.5).                 │
│   You are currently using expo-cli 4.13.0                               │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
✔ The ios project is malformed, would you like to clear the project files and reinitialize them? … yes
- Clearing ios
✔ Cleared ios code
- Creating native project directories (./ios and ./android) and updating .gitignore
✔ Created native project | gitignore already synced
- Adding Metro bundler config
⚠️  Skipped Metro config updates:
› Existing Metro config found; not overwriting.
› You will need to extend the default @expo/metro-config in your Metro config.
  Learn more: https://docs.expo.dev/guides/customizing-metro

- Updating your package.json scripts, dependencies, and main file
✔ Updated package.json and added index.js entry point for iOS and Android
🧶 Using Yarn to install packages. Pass --npm to use npm instead.
- Installing JavaScript dependencies
> yarn install
- Installing JavaScript dependencies
yarn install v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.23s.
✔ Installed JavaScript dependencies 467ms
- Config syncing
ios.dangerous: withDefaultBaseMods ➜ withIosBaseMods ➜ withGeneratedBaseMods ➜ withIosDangerousBaseMod
- Config syncing
ios.dangerous: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withIosIcons ➜ withDangerousMod
- Config syncing
✖ Config sync failed
[ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "/Users/nataliesumbofilipe/app-projects/MyPlantsApp"
Please report this as an issue on https://github.com/expo/expo-cli/issues
UnexpectedError: [ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "/Users/nataliesumbofilipe/app-projects/MyPlantsApp"
Please report this as an issue on https://github.com/expo/expo-cli/issues
    at getAppDelegateFilePath (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:52:11)
    at getAppDelegate (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:114:20)
    at Object.getSourceRoot (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:119:23)
    at getProjectName (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/utils/Xcodeproj.ts:33:28)
    at getIosNamedProjectPath (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:172:23)
    at setIconsAsync (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:107:31)
    at /Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:15:13
    at action (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:227:29)
    at interceptingMod (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:27)
    at action (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/createBaseMod.ts:82:27)
    at interceptingMod (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at evalModsAsync (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:172:25)
    at compileModsAsync (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:82:10)
    at configureManagedProjectAsync (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/src/commands/eject/configureProjectAsync.ts:64:12)
    at prebuildAsync (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/src/commands/eject/prebuildAsync.ts:90:21)
    at actionAsync (/Users/nataliesumbofilipe/app-projects/MyPlantsApp/node_modules/expo-cli/src/commands/run/ios/runIos.ts:45:5)

### Reproducible demo or steps to reproduce from a blank project

[curious-juice-box (1).zip](https://github.com/expo/expo-cli/files/9632316/curious-juice-box.1.zip)

**Comment by itamarbareket** [comment]
Same here

**Comment by thelamedia** [comment]
I also have this issue after an upgrade from SDK 44 > 45.

**Comment by itamarbareket** [comment]
I managed to solve it by:
- Upgrading expo-cli
- running expo-cli as a non-global command (via npx)
- intentionally install these packages and set them to the latest version:
```
yarn add @expo/config-plugins
yarn add @expo/prebuild-config
```

**Comment by andrewminton** [comment]
Same issue. iOs clean build in simulator results in the AppDelegate error. 

This happens with an empty project on a mac. 

'expo init'

the 'expo prebuild'

Output is searching for AppDelegate:

`The ios project is malformed, would you like to clear the project files and reinitialize them? … yes
✔ Cleared ios code
✔ Created native projects | /android already created | gitignore already synced
⚠️  Skipped Metro config updates:
› Existing Metro config found; not overwriting.
› You will need to extend the default @expo/metro-config in your Metro config.
  Learn more: https://docs.expo.dev/guides/customizing-metro

✔ Updated package.json and added index.js entry point for iOS and Android
🧶 Using Yarn to install packages. Pass --npm to use npm instead.
✔ Installed JavaScript dependencies 948ms
✖ Config sync failed
[ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "/Users/andrewminton/Apps/APP/repo"
Please report this as an issue on https://github.com/expo/expo-cli/issues
UnexpectedError: [ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "/Users/andrewminton/Apps/POP2HOP/Pop2HopExpoOct2022/pop2hop"
Please report this as an issue on https://github.com/expo/expo-cli/issues
    at getAppDelegateFilePath (/Users/andrewminton/.config/yarn/global/node_modules/@expo/config-plugins/src/ios/Paths.ts:52:11)
    at getAppDelegate (/Users/andrewminton/.config/yarn/global/node_modules/@expo/config-plugins/src/ios/Paths.ts:114:20)
    at Object.getSourceRoot (/Users/andrewminton/.config/yarn/global/node_modules/@expo/config-plugins/src/ios/Paths.ts:119:23)
    at getProjectName (/Users/andrewminton/.config/yarn/global/node_modules/@expo/config-plugins/src/ios/utils/Xcodeproj.ts:33:28)
    at getIosNamedProjectPath (/Users/andrewminton/.config/yarn/global/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:172:23)
    at setIconsAsync (/Users/andrewminton/.config/yarn/global/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:107:31)
    at /Users/andrewminton/.config/yarn/global/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:15:13
    at action (/Users/andrewminton/.config/yarn/global/node_modules/@expo/config-plugins/src/plugins/withMod.ts:227:29)
    at interceptingMod (/Users/andrewminton/.config/yarn/global/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:27)
    at action (/Users/andrewminton/.config/yarn/global/node_modules/@expo/config-plugins/src/plugins/createBaseMod.ts:82:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at interceptingMod (/Users/andrewminton/.config/yarn/global/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at evalModsAsync (/Users/andrewminton/.config/yarn/global/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:172:25)
    at compileModsAsync (/Users/andrewminton/.config/yarn/global/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:82:10)
    at configureManagedProjectAsync (/Users/andrewminton/.config/yarn/global/node_modules/expo-cli/src/commands/eject/configureProjectAsync.ts:64:12)
    at prebuildAsync (/Users/andrewminton/.config/yarn/global/node_modules/expo-cli/src/commands/eject/prebuildAppAsync.ts:90:21)`

**Comment by byCedric** [comment]
For anyone running into this issue, it's likely caused by `expo-cli` being replaced with `npx expo` (a CLI within the `expo` package). If you run into this, try running `npx expo prebuild` instead, or uninstall the `expo-cli` globally.

Hope this helps!

**Comment by pdandradeb** [comment]
In my case I wasn't building locally but using eas. Updating `expoCli` version from `5.2.0` to `6.1.0` on `eas.json` solved the issue.

**Comment by akinlekan28** [comment]
> I managed to solve it by:
> 
> * Upgrading expo-cli
> * running expo-cli as a non-global command (via npx)
> * intentionally install these packages and set them to the latest version:
> 
> ```
> yarn add @expo/config-plugins
> yarn add @expo/prebuild-config
> ```

this solved my issue
