### ISSUE TITLE
Error using Node 19 with `expo-cli start --web` 

### ISSUE THREAD

**Issue by ninjasort** [expo/expo-cli#4575]
### Summary

`expo start --web` throws an unknown error

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 19.0.0 - ~/.nvm/versions/node/v19.0.0/bin/node
      npm: 8.19.2 - ~/.nvm/versions/node/v19.0.0/bin/npm
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.2 
      expo: ~46.0.16 => 46.0.16 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      expo-cli: 6.0.6
    Expo Workflow: managed

```

### Please specify your device/emulator/simulator platform, model and version

macOS 12.2

### Error output

```
> imageshare@1.0.0 web
> expo start --web

Starting project at /Users/cameronroe/Documents/ImageShare
Starting Metro Bundler
Starting Webpack on port 19006 in development mode.
⚠ ｢wds｣: transportMode is an experimental option, meaning its usage could potentially change without warning
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/Users/cameronroe/Documents/ImageShare/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/cameronroe/Documents/ImageShare/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/cameronroe/Documents/ImageShare/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/cameronroe/Documents/ImageShare/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/cameronroe/Documents/ImageShare/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/cameronroe/Documents/ImageShare/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/cameronroe/Documents/ImageShare/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/cameronroe/Documents/ImageShare/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/cameronroe/Documents/ImageShare/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/cameronroe/Documents/ImageShare/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/cameronroe/Documents/ImageShare/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v19.0.0
```

### Reproducible demo or steps to reproduce from a blank project

`npx create-expo-app my-app`
`npm run start`

**Comment by DPDmancul** [comment]
A temporary workaround is `NODE_OPTIONS=--openssl-legacy-provider expo start --web`

**Comment by cameronroe** [comment]
I'm currently using a `.nvmrc` with `v16.18.0`.

Getting the same issue in `v18.12.0`

```
Logs for your project will appear below. Press Ctrl+C to exit.
Starting Webpack on port 19006 in development mode.
⚠ ｢wds｣: transportMode is an experimental option, meaning its usage could potentially change without warning
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/cameronroe/Documents/ImageShare/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/cameronroe/Documents/ImageShare/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/cameronroe/Documents/ImageShare/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/cameronroe/Documents/ImageShare/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/cameronroe/Documents/ImageShare/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/cameronroe/Documents/ImageShare/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/cameronroe/Documents/ImageShare/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/cameronroe/Documents/ImageShare/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/cameronroe/Documents/ImageShare/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/cameronroe/Documents/ImageShare/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/cameronroe/Documents/ImageShare/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by timscodebase** [comment]
Thanks for this solution.  I was really getting discouraged. ❤️

**Comment by 1OneGroup** [comment]
Same Error





Starting Webpack on port 19006 in development mode.
‼ ｢wds｣: transportMode is an experimental option, meaning its usage could potentially change without warning
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\Code\React Native\ifm-app\ifm-app\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\Code\React Native\ifm-app\ifm-app\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\Code\React Native\ifm-app\ifm-app\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\Code\React Native\ifm-app\ifm-app\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\Code\React Native\ifm-app\ifm-app\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\Code\React Native\ifm-app\ifm-app\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\Code\React Native\ifm-app\ifm-app\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (D:\Code\React Native\ifm-app\ifm-app\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\Code\React Native\ifm-app\ifm-app\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)      
    at D:\Code\React Native\ifm-app\ifm-app\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at D:\Code\React Native\ifm-app\ifm-app\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1

**Comment by ngualpha** [comment]
Same issues. Can't even start my projects. The projects are stuck at start. I upgraded to node 18.12.0.

**Comment by goatandsheep** [comment]
This should be fixed when webpack-config is updated with webpack v5 #3763
