### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by mmarada** [expo/expo-cli#4615]
### Summary

Logs for your project will appear below. Press Ctrl+C to exit.
Starting Webpack on port 19006 in development mode.
‼ ｢wds｣: transportMode is an experimental option, meaning its usage could potentially change without warning
Web Bundling JavaScript [======                                                          ] 10%Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-loader\lib\index.js:59:103

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~47.0.9 => 47.0.9
      react: 18.1.0 => 18.1.0
      react-dom: ^18.2.0 => 18.2.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.7 => 0.18.10
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Web browser

### Error output

Logs for your project will appear below. Press Ctrl+C to exit.
Starting Webpack on port 19006 in development mode.
‼ ｢wds｣: transportMode is an experimental option, meaning its usage could potentially change without warning
Web Bundling JavaScript [======                                                          ] 10%Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\mmarada\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-loader\lib\index.js:59:103

### Reproducible demo or steps to reproduce from a blank project

expo start with w option for web browser

**Comment by drilind1** [comment]
Same issue suspecting that the version of **expo/webpack-config** does not match the version other packages!

**Comment by EvanBacon** [comment]
Closing in favor of #4575
