### ISSUE TITLE
Failed to construct transformer:  Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by pksingh17** [expo/expo-cli#4616]
### Summary

WARNING: expo-cli has not yet been tested against Node.js v18.12.1. If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues. expo-cli supports following Node.js versions:
* >=12.13.0 <15.0.0 (Maintenance LTS)
* >=16.0.0 <17.0.0 (Active LTS)
at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at stableHash (E:\Apps\React-Native Development\snack\MealsToGo\node_modules\metro-cache\src\stableHash.js:19:8)
    at Object.getCacheKey (E:\Apps\React-Native Development\snack\MealsToGo\node_modules\metro-transform-worker\src\index.js:647:7)
    at getTransformCacheKey (E:\Apps\React-Native Development\snack\MealsToGo\node_modules\metro\src\DeltaBundler\getTransformCacheKey.js:32:19)        
    at new Transformer (E:\Apps\React-Native Development\snack\MealsToGo\node_modules\metro\src\DeltaBundler\Transformer.js:180:28)
    at E:\Apps\React-Native Development\snack\MealsToGo\node_modules\metro\src\Bundler.js:58:29
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processTimers (node:internal/timers:504:9) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'

### Environment

expo-CLI problems in node 18.

### Please specify your device/emulator/simulator platform, model and version

Windows 11 and Node 18

### Error output

Failed to construct transformer:  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at stableHash (E:\Apps\React-Native Development\snack\MealsToGo\node_modules\metro-cache\src\stableHash.js:19:8)
    at Object.getCacheKey (E:\Apps\React-Native Development\snack\MealsToGo\node_modules\metro-transform-worker\src\index.js:647:7)
    at getTransformCacheKey (E:\Apps\React-Native Development\snack\MealsToGo\node_modules\metro\src\DeltaBundler\getTransformCacheKey.js:32:19)        
    at new Transformer (E:\Apps\React-Native Development\snack\MealsToGo\node_modules\metro\src\DeltaBundler\Transformer.js:180:28)
    at E:\Apps\React-Native Development\snack\MealsToGo\node_modules\metro\src\Bundler.js:58:29
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processTimers (node:internal/timers:504:9) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

### Reproducible demo or steps to reproduce from a blank project

 expo start        
WARNING: expo-cli has not yet been tested against Node.js v18.12.1.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <15.0.0 (Maintenance LTS)
* >=16.0.0 <17.0.0 (Active LTS)

Starting project at E:\Apps\React-Native Development\snack\MealsToGo
Developer tools running on http://localhost:19002
Starting Metro Bundler

**Comment by EvanBacon** [comment]
I've opened an internal issue ENG-7144. If you want to use newer versions of Node.js with Expo, then you'll need to use the latest `npx expo` CLI and not the global `expo-cli` package. Closely related to #4575

**Comment by sandy57011** [comment]
Please refer to this article to resolve this issue. [digital envelope routines unsupported](https://theknowledgeadda.com/how-to-fix-edigital-envelope-routines-unsupported)

**Comment by EvanBacon** [comment]
Now using Webpack 5 and supporting any node version loosely https://github.com/expo/expo-cli/pull/3763

**Comment by ganpatigarv** [comment]
For React Native
Windows/Linux/Mac: **npx cross-env NODE_OPTIONS=--openssl-legacy-provider yarn start**
Linux/Mac: **NODE_OPTIONS=--openssl-legacy-provider yarn start**

**Comment by Armanidrisi** [comment]
> 
Its works

**Comment by sverano** [comment]
> For React Native
> Windows/Linux/Mac: **npx cross-env NODE_OPTIONS=--openssl-legacy-provider yarn start**
> Linux/Mac: **NODE_OPTIONS=--openssl-legacy-provider yarn start**

thanks

**Comment by shiraliali** [comment]
> npx cross-env NODE_OPTIONS=--openssl-legacy-provider

not worked in react native using npm

**Comment by itsfaraaz** [comment]
> > npx cross-env NODE_OPTIONS=--openssl-legacy-provider
> 
> not worked in react native using npm

any solution?

**Comment by usmanabid94** [comment]
any update on this? facing the same issue now using the node version 20.8.1 in react native app

**Comment by ivandortulov** [comment]
Using Node 20.9.0 here and facing the same issue.

**Comment by VikasTiwari7** [comment]
I also facing same issue
