### ISSUE TITLE
Can not open react native project on web

### ISSUE THREAD

**Issue by devrudraa** [expo/expo-cli#4634]
### Summary

I am trying to run my react native project on the web but it crashes after giving an error although it runs smoothly on the android emulator so I don't think there is any problem with my code, I am just not able to open it on the web... and also I did not made any change in the project it is normal starting code which expo gives after creating the blank project with JavaScript.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 18.13.0 - /usr/local/bin/node
      npm: 8.19.3 - /usr/local/bin/npm
    npmPackages:
      @expo/webpack-config: ^0.17.4 => 0.17.4 
      expo: ~47.0.12 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-dom: ^18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ^0.18.10 => 0.18.10 
    npmGlobalPackages:
      expo-cli: 6.1.0
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)

### Error output

Logs for your project will appear below. Press Ctrl+C to exit.
Starting Webpack on port 19006 in development mode.
⚠ ｢wds｣: transportMode is an experimental option, meaning its usage could potentially change without warning
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/satyam/Coding/1Code/JAVA SCRIPT/React/ReactNative/ChatAPP/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/satyam/Coding/1Code/JAVA SCRIPT/React/ReactNative/ChatAPP/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/satyam/Coding/1Code/JAVA SCRIPT/React/ReactNative/ChatAPP/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/satyam/Coding/1Code/JAVA SCRIPT/React/ReactNative/ChatAPP/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/satyam/Coding/1Code/JAVA SCRIPT/React/ReactNative/ChatAPP/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/satyam/Coding/1Code/JAVA SCRIPT/React/ReactNative/ChatAPP/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/satyam/Coding/1Code/JAVA SCRIPT/React/ReactNative/ChatAPP/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/satyam/Coding/1Code/JAVA SCRIPT/React/ReactNative/ChatAPP/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/satyam/Coding/1Code/JAVA SCRIPT/React/ReactNative/ChatAPP/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/satyam/Coding/1Code/JAVA SCRIPT/React/ReactNative/ChatAPP/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/satyam/Coding/1Code/JAVA SCRIPT/React/ReactNative/ChatAPP/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.13.0

### Reproducible demo or steps to reproduce from a blank project

This is a blank project with JavaScript.

Here is the Snack of the blank project:
https://snack.expo.dev/@devrudra/error-project

**Comment by EvanBacon** [comment]
Closing in favor of #4575
