### ISSUE TITLE
Installing Android client in emulator results in failure to uninstall error

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#476]
```
> expo install:android
Uninstalling Expo from Android device.
Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: host.exp.exponent
	at com.android.server.pm.Settings.isOrphaned(Settings.java:4289)
	at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:21095)
	at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:17916)
	at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:736)
	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:1486)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:193)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21328)
	at android.os.Binder.shellCommand(Binder.java:634)
	at android.os.Binder.onTransact(Binder.java:532)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2821)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3856)
	at android.os.Binder.execTransact(Binder.java:731)
```

I don't actually have a copy of the client in the emulator, so it's unclear why it's trying to uninstall. We should probably ignore this error if it comes up and go ahead and install the client anyways - I downloaded the client from the tools page and ran `adb install` and it worked.

**Comment by EvanBacon** [comment]
This appears to be fixed now in #2550
