### ISSUE TITLE
exp fetch:android:hashes crashes

### ISSUE THREAD

**Issue by dstrtop1** [expo/expo-cli#478]
## Description

I need to create a standalone app with google/facebook auth in it. In expo itself it works fine, however when i run `exp fetch:android:hashes` it crashes

## Expected Behavior

It should generate SHA-1 certificate fingerprint that I need to paste in my developer console

## Observed Behavior

I tried to set debug to true, didn't work
`export EXPO_DEBUG=true`

and the error itself
```
[10:25:35] Unrecognized command: -exportcert

[10:25:35] Process exited with non-zero code: 1
[10:25:35] Error: Process exited with non-zero code: 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/exp/node_modules/@expo/spawn-async/src/spawnAsync.ts:52:21)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:978:16)
    at Socket.stream.socket.on (internal/child_process.js:395:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:616:12)
```

## Environment

 Expo CLI 2.14.0 environment info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 11.2.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      expo: ^28.0.0 => 28.0.1 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4 
      react-navigation: ~2.3.1 => 2.3.1 
    npmGlobalPackages:
      expo-cli: 2.14.0

**Comment by brentvatne** [comment]
this should have been resolved a while ago. sorry that there was no response
