### ISSUE TITLE
create-expo-module fails with installing module dependencies

### ISSUE THREAD

**Issue by orange4glace** [expo/expo-cli#4796]
### Summary

```
✔ Downloaded module template from npm
✔ Created the module from template files
✖ Installing module dependencies
Error: npm install exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/user/.npm/_npx/62900f925a4b91dc/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:629:26)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at spawnAsync (/Users/user/.npm/_npx/62900f925a4b91dc/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at installDependencies (/Users/user/.npm/_npx/62900f925a4b91dc/node_modules/create-expo-module/build/packageManager.js:9:37)
    at /Users/user/.npm/_npx/62900f925a4b91dc/node_modules/create-expo-module/build/create-expo-module.js:86:60
    at newStep (/Users/user/.npm/_npx/62900f925a4b91dc/node_modules/create-expo-module/build/utils.js:21:22)
    at Command.main (/Users/user/.npm/_npx/62900f925a4b91dc/node_modules/create-expo-module/build/create-expo-module.js:85:35) {
  pid: 18149,
  output: [ '', '' ],
  stdout: '',
  stderr: '',
  status: 1,
  signal: null
}

```

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - /usr/local/bin/node
      Yarn: 3.6.2 - /usr/local/bin/yarn
      npm: 9.6.7 - /usr/local/bin/npm
      Watchman: 2023.11.20.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/user/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11005911
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild

```

### Please specify your device/emulator/simulator platform, model and version

-

### Reproducible demo or steps to reproduce from a blank project

`npx create-expo-module expo-settings3 --no-example`

**Comment by orange4glace** [comment]
Yarn v3 seems to be problem.
