### ISSUE TITLE
Expo CLI commands have typescript syntax in a .js file

### ISSUE THREAD

**Issue by Polygons1** [expo/expo-cli#4797]
### Summary

I want to create a new expo app but I am getting an error, the error was that there is a typescript syntax is a javascript file

### Environment

error with that too

### Please specify your device/emulator/simulator platform, model and version

Docker ubuntu:latest Aarch64 on Apple M1

### Error output

/root/.bun/install/global/node_modules/@npmcli/config/lib/definitions/definitions.js:2244
    const ciName = ciInfo.name?.toLowerCase().split(' ').join('-') || null
                               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/.bun/install/global/node_modules/@npmcli/config/lib/definitions/index.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10

--- --- --- --- --- --- --- --- --- --- --- --- --- --- ---

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

### Reproducible demo or steps to reproduce from a blank project

npx / bunx create-expo app

**Comment by Polygons1** [comment]
the error is in the CLI itself (npx)
