### ISSUE TITLE
expo build:ios -c returns 500

### ISSUE THREAD

**Issue by jordanstreiff** [expo/expo-cli#481]
## Description

Was having some problems building ios (build gets stuck in queue, timesout), so I attempted to first delete distribution profile, certs etc and then run expo build:ios -c. Doing so results in a 500 error. 

## Expected Behavior

running expo build:ios -c should clear out the certificates and distribution profile for the apple dev account so that expo will recreate them when I run expo build:ios

## Observed Behavior

After I run expo build:ios -c I receive the following error:

```
Checking if there is a build in progress...

Request failed with status code 500
Error: Request failed with status code 500
    at createError (../.nvm/versions/node/v8.10.0/lib/node_modules/expo-cli/node_modules/xdl/node_modules/axios/lib/core/createError.js:16:15)
    at settle (../.nvm/versions/node/v8.10.0/lib/node_modules/expo-cli/node_modules/xdl/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (../.nvm/versions/node/v8.10.0/lib/node_modules/expo-cli/node_modules/xdl/node_modules/axios/lib/adapters/http.js:236:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

## Environment

  Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 2.3 AI-162.4069837
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.6.0 
    npmGlobalPackages:
      expo-cli: 2.14.0

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by jordanstreiff** [comment]
Attempted to use expo logout and signing out didn't help. Created a new expo account with alternate email address and was able to build without issue.
