### ISSUE TITLE
expo build:android [Standalone build failed!]

### ISSUE THREAD

**Issue by benson7667** [expo/expo-cli#549]
## Description
```expo build:ios``` is working fine to build an ipa file!
However, i try to build android apk file by using the command ```expo build:android```, after running for few mins, system returned me the error log as below. I was successfully build for android apk file before with no issues. Does expo mess up with my keystore file? This is the command i run!
```
expo fetch:android:keystore   // I change the app.json file to the correct bundle id first so expo fetch the correct keystore based on the bundle id in app.json
expo build:android --release-channel prod -c    // I change the app.json file to the correct bundle id first so expo build accordingly to the bundle id
Pass in the path of the keystore i downloaded and provide the credential
```

I have the keystore and credential for both of my production build and staging build. And I can confirmed the keystore i used is totally correct as I double verify with external tools by placing my keystore and password, the tools output the correct bundle id name and information.

This is my app.json file when i trying to build production apk:
```
{
  "expo": {
    "version": "2.0.12",
    "name": "GetJobsforMe",
    "description": "A mobile application for user to seek for part-time jobs",
    "sdkVersion": "31.0.0",
    "privacy": "unlisted",
    "orientation":"portrait",
    "icon": "./src/assets/icon.png",
    "splash": {
      "image": "./src/assets/splash.png",
      "resizeMode": "cover"
    },
    "notification": {
      "icon": "./src/assets/notificationicon.png"
    },
    "ios": {
      "bundleIdentifier": "com.jilcreation.getjobs",
      "buildNumber": "18"
    },
    "android": {
      "versionCode": 18,
      "package": "com.jilcreation.getjobs",
      "googleServicesFile": "./src/assets/fcm/google-services.json",
      "permissions": [
        "CAMERA",
        "CAMERA_ROLL",
        "NOTIFICATIONS",
        "VIBRATE",
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE"
      ]
    }
  }
}
```

This is my app.json file when i wanna build a staging apk:
```
{
  "expo": {
    "version": "2.0.12",
    "name": "Demo GetJobsforMe",
    "description": "A mobile application for user to seek for part-time jobs",
    "sdkVersion": "31.0.0",
    "privacy": "unlisted",
    "orientation":"portrait",
    "icon": "./src/assets/icon.png",
    "splash": {
      "image": "./src/assets/splash.png",
      "resizeMode": "cover"
    },
    "notification": {
      "icon": "./src/assets/notificationicon.png"
    },
    "ios": {
      "bundleIdentifier": "com.jilcreation.getjobsDemoApp",
      "buildNumber": "18"
    },
    "android": {
      "versionCode": 18,
      "package": "com.jilcreation.getjobsDemoApp",
      "googleServicesFile": "./src/assets/fcm/google-services.json",
      "permissions": [
        "CAMERA",
        "CAMERA_ROLL",
        "NOTIFICATIONS",
        "VIBRATE",
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE"
      ]
    }
  }
}
```

## Expected Behavior
Successfully build the android standalone apk by providing a url link for downloading the apk file

## Observed Behavior
https://expo.io/builds/ffbd40e9-fae6-4de1-866c-f3061916a2c7
```
Error: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: AAPT2 error: check logs for details
:app:mergeProdMinSdkProdKernelReleaseResources 
FAILED
[stderr] warning: Attempt to recreate a file for type com.raizlabs.android.dbflow.config.ExponentKernel$Database
[stderr] warning: Attempt to recreate a file for type com.raizlabs.android.dbflow.config.ExponentKernel$Database
[stderr] warning: File for type 'com.raizlabs.android.dbflow.config.GeneratedDatabaseHolder' created in the last round will not be subject to annotation processing.
[stderr] Note: Some input files use or override a deprecated API.
[stderr] Note: Recompile with -Xlint:deprecation for details.
[stderr] Note: Some input files use unchecked or unsafe operations.
[stderr] Note: Recompile with -Xlint:unchecked for details.
[stderr] 3 warnings
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:mergeProdMinSdkProdKernelReleaseResources'.
[stderr] > 
[stderr] Error: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: AAPT2 error: check logs for details
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 6m 37s
690 actionable tasks: 690 executed
Error: ./gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/app/node_modules/@expo/spawn-async/build/spawnAsync.js:51:23)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
    ...
    at spawnAsync (/app/node_modules/@expo/spawn-async/build/spawnAsync.js:16:21)
    at /app/node_modules/xdl/build/detach/ExponentTools.js:78:71
    at Generator.next (<anonymous>)
    at step (/app/node_modules/xdl/build/detach/ExponentTools.js:249:191)
    at /app/node_modules/xdl/build/detach/ExponentTools.js:249:437
    at new Promise (<anonymous>)
    at /app/node_modules/xdl/build/detach/ExponentTools.js:249:99
    at spawnAsyncThrowError (/app/node_modules/xdl/build/detach/ExponentTools.js:89:18)
    at /app/node_modules/xdl/build/detach/AndroidShellApp.js:417:13
    at Generator.next (<anonymous>)
    at step (/app/node_modules/xdl/build/detach/AndroidShellApp.js:610:191)
    at /app/node_modules/xdl/build/detach/AndroidShellApp.js:610:361
    at <anonymous>
```

## Environment

Expo CLI 2.15.4 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^31.0.0 => 31.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.1 => 0.57.1 
      react-navigation: ^2.0.1 => 2.14.2 
    npmGlobalPackages:
      expo-cli: 2.15.4

**Comment by dsokal** [comment]
Hello,
it has nothing to do with your Android keystore. The build failed because your notification icon is missing on Expo servers - you can find this information in logs. I'm not sure why it's not uploaded, that file is most probably corrupted.

**Comment by benson7667** [comment]
Thank you @dsokal ... Yes, I had found the issues. I removed this line from my app.json and the build is suceed now.
```
"notification": {
      "icon": "./src/assets/notificationicon.png"
},
```
I will open another issues regarding to the notification icon. The icon notification icon I created follow the guideline from Expo - 96x96 .png grayscale transparent
