### ISSUE TITLE
expo build:ios credential errors

### ISSUE THREAD

**Issue by robertobrogi** [expo/expo-cli#64]
windows 10 * Expo-cli 2.2.0
when i try make a build with expo build:ios i have this error:

`? What’s your Apple ID? xxx@xxx.com
? Password? [hidden]
[14:56:24] Validating Credentials…
[14:56:24] Running: bash.exe -c PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /mnt/c/Users/roberto.brogi/AppData/Roaming/npm/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-linux/traveling-fastlane-1.5.0-linux-x86_64/validate_apple_credentials "xxx@xxx.com xxx"
[14:56:32] Error while gathering & validating credentials
[14:56:32] Error: Reason:Invalid credentials, raw:“Invalid username and password combination. Used ‘xxx@xxx.com’ as the username.”
[14:56:32] Reason:Invalid credentials, raw:“Invalid username and password combination. Used ‘xxx@xxx.com’ as the username.”
[14:56:32] Error: Reason:Invalid credentials, raw:“Invalid username and password combination. Used ‘xxx@xxx.com’ as the username.”
at Object._callee4$ (C:\expo-cli@2.2.0\src\commands\build\auth.js:134:11)
at tryCatch (C:\Users\roberto.brogi\AppData\Roaming\npm\node_modules\expo-cli\node_modules\regenerator-runtime\runtime.js:62:40)
at Generator.invoke [as _invoke] (C:\Users\roberto.brogi\AppData\Roaming\npm\node_modules\expo-cli\node_modules\regenerator-runtime\runtime.js:296:22)
at Generator.prototype.(anonymous function) [as next] (C:\Users\roberto.brogi\AppData\Roaming\npm\node_modules\expo-cli\node_modules\regenerator-runtime\runtime.js:114:21)
at step (C:\Users\roberto.brogi\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
at C:\Users\roberto.brogi\AppData\Roaming\npm\node_modules\expo-cli\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
at 
at process._tickCallback (internal/process/next_tick.js:188:7)`

the credential are correct because if i try in itunesconnect work fine... not have a space in the psw...

**Comment by robertobrogi** [comment]
I released the first app version 6 moth ago and this process worked fine, but in this time have another account... last month i removed completely the old account from expo web site and have make new account in expo web site... maybe there is some wrong account in expo server?
there is a solution about this....

**Comment by jakubste** [comment]
@robertobrogi did you managed to overcome this?
