### ISSUE TITLE
codemod: when using babel, babel.config.js is being ignored

### ISSUE THREAD

**Issue by 3p3r** [expo/expo-cli#676]
## Description

I am upgrading from SDK 32 to 33 and would like to use the `codemod` tool to fix my Expo imports. I am also using `mobx` in my project and it seems like when running `codemod` with babel, the parser ignores what I have set in my project's root `babel.config.js`. This causes all files with `mobx` decorators to throw an error while being parsed.

## Expected Behavior

I was expecting the `codemod` tool's babel integration to read my project's root `babel.config.js`.

## Observed Behavior

It seems like `babel.config.js` is being entirely ignored, as even making it an invalid javascript file still does not affect `codemod`. In other words, `babel.config.js` is not being read.

The following error messages are emitted while going through files with `mobx`:

```
SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (101:2)
    at Object.raise (~/.npm/_npx/15024/lib/node_modules/expo-codemod/node_modules/@babel/parser/lib/index.js:6344:17)
    at Object.expectOnePlugin (~/.npm/_npx/15024/lib/node_modules/expo-codemod/node_modules/@babel/parser/lib/index.js:7674:18)
    at Object.parseDecorator (~/.npm/_npx/15024/lib/node_modules/expo-codemod/node_modules/@babel/parser/lib/index.js:9970:10)
    at ~/.npm/_npx/15024/lib/node_modules/expo-codemod/node_modules/@babel/parser/lib/index.js:10574:32
    at Object.withTopicForbiddingContext (~/.npm/_npx/15024/lib/node_modules/expo-codemod/node_modules/@babel/parser/lib/index.js:9683:14)
    at Object.parseClassBody (~/.npm/_npx/15024/lib/node_modules/expo-codemod/node_modules/@babel/parser/lib/index.js:10563:10)
    at Object.parseClass (~/.npm/_npx/15024/lib/node_modules/expo-codemod/node_modules/@babel/parser/lib/index.js:10537:22)
    at Object.parseStatementContent (~/.npm/_npx/15024/lib/node_modules/expo-codemod/node_modules/@babel/parser/lib/index.js:9830:21)
    at Object.parseStatement (~/.npm/_npx/15024/lib/node_modules/expo-codemod/node_modules/@babel/parser/lib/index.js:9788:17)
    at Object.parseBlockOrModuleBlockBody (~/.npm/_npx/15024/lib/node_modules/expo-codemod/node_modules/@babel/parser/lib/index.js:10364:25)
```

## Environment

```
  Expo CLI 2.19.1 environment info:
    System:
      OS: Linux 4.18 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 12.3.1 - ~/.nvm/versions/node/v12.3.1/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v12.3.1/bin/npm
    npmPackages:
      expo: ^33.0.0 => 33.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.19.1
```

My `babel.config.js`:

```
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    env: {
      production: {
        plugins: ['transform-remove-console'],
      },
    },
    plugins: [['@babel/plugin-proposal-decorators', { legacy: true }]],
  };
};

```

**Comment by p-sebastian** [comment]
Same thing happening to me, but with module-resolver, since I want to have absolute imports, it took me a while to realize that the entire babel.config.js was being ignored

Also on SDK 33

**Comment by SchlagerKhan** [comment]
For me it didn't work with clearing the cache.

However, inspired by https://github.com/facebook/jscodeshift/issues/256 I got it to work with the flag  `--parser=flow` such as:

`npx expo-codemod sdk33-imports src --parser=flow`

Might help somebody 👍

**Comment by brentvatne** [comment]
@SchlagerKhan - i updated the readme to mention this tip, thanks for sharing!
