### ISSUE TITLE
init command fails on download project files ( proxy / ssl )

### ISSUE THREAD

**Issue by poserr** [expo/expo-cli#70]
## Description

I have problems with `expo-cli init`, I think it is somehow related to proxy setting (I am behind corporate proxy, environment variable **HTTPS_PROXY** is set to _http://some.local.domain.com:3128_ 

## Expected Behavior

Project initialization 

## Observed Behavior

right after choice of template , on "Downloading project files", I get the following error:

```
$ expo-cli init
? Choose a project name: jl-react
? Choose a template: blank
[14:03:51] Downloading project files...
[14:03:51] write EPROTO 140736142529408:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

[14:03:51] Error: write EPROTO 140736142529408:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite (net.js:864:14)
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

```
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.4
  Yarn: 1.9.4
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 10.0 Build version 10L232m
  Android Studio: Not Found

```

**Comment by programmer-yang** [comment]
I had the same problem

**Comment by ssskip** [comment]
it's axios bug https://github.com/axios/axios/issues/925

**Comment by poserr** [comment]
> it's axios bug [axios/axios#925](https://github.com/axios/axios/issues/925)

Is there any workaround?

**Comment by Peluko** [comment]
Same here. Planning a demo on the office about how easy would be to work with React Native, and I can't even start it.

**Comment by poserr** [comment]
With expo CLI 2.2.1, I still have the same problem:

```
expo -V
2.2.1
sergeysworkimac:jl-expo sergey.popov$ expo init
? Choose a project name: jl-rn
? Choose a template: blank
[11:49:49] Downloading project files...
[11:49:49] write EPROTO 140736142529408:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

[11:49:49] Error: write EPROTO 140736142529408:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite (net.js:864:14)
```

**Comment by ssskip** [comment]
@fson   https://github.com/expo/expo-cli/blob/e4a1c33e014d5b3afdc071736d36c002707befa4/packages/expo-cli/package.json#L92


should be `51.4.1`
