### ISSUE TITLE
Cannot find module '.../expo-cli/node_modules/@expo/image-utils/build/index.js'.

### ISSUE THREAD

**Issue by Bram-Zijp** [expo/expo-cli#759]
After updating the expo cli to version 2.20.3, I get the following error.

```
~/projects/projectName$ EXPO_DEBUG=true yarn start
yarn run v1.16.0
$ expo start
Starting project at /home/bramzijp/projects/projectName
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Cannot find module '/home/linuxbrew/.linuxbrew/lib/node_modules/expo-cli/node_modules/@expo/image-utils/build/index.js'. Please verify that the package.json has a valid "main" entry
Error: Cannot find module '/home/linuxbrew/.linuxbrew/lib/node_modules/expo-cli/node_modules/@expo/image-utils/build/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:228:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:365:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:27)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/@expo/xdl@55.0.3/src/AssetUtils.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
error Command failed with exit code 1.
```

Looking at the image-utils package installed under `/home/linuxbrew/.linuxbrew/lib/node_modules/expo-cli/node_modules/@expo/image-utils`, I notice that there is no build folder as expected by the package.json 'main' key.

I'm tried both yarn and npm as package managers. I'm running on Ubuntu 18.04 LTS

**Comment by Bram-Zijp** [comment]
Closed due to duplicate of #758
