### ISSUE TITLE
Cannot build project after ejecting

### ISSUE THREAD

**Issue by elewin** [expo/expo-cli#76]
## Description

Cannot build projects after ejecting

## Expected Behavior

I did the following:

* `create-react-native-app test` and chose a blank template

* `cd test`

* `expo eject` and chose React Native

* `yarn start`

* Attempt to build the project in Android Studio (`Build -> Make Project`)

## Observed Behavior

Project failed to build

```
10-08 11:08:05.569 12974-13407/? E/Watchdog: !@Sync 422728 [10-08 11:08:05.585]
10-08 11:08:06.679 7890-6599/? E/ctxmgr: [BaseServerTask]Server task (FetchAclSet) got error statusCode=-1.
    com.android.volley.VolleyError: Unable to obtain auth token - is the device online?
        at edi.a(:com.google.android.gms@14366006@14.3.66 (020300-213742215):31)
        at dyo.run(:com.google.android.gms@14366006@14.3.66 (020300-213742215):2)
        at dym.handleMessage(:com.google.android.gms@14366006@14.3.66 (020300-213742215):3)
        at qey.run(:com.google.android.gms@14366006@14.3.66 (020300-213742215):4)
        at qfk.run(:com.google.android.gms@14366006@14.3.66 (020300-213742215):35)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at qll.run(:com.google.android.gms@14366006@14.3.66 (020300-213742215))
        at java.lang.Thread.run(Thread.java:818)
10-08 11:08:06.679 7890-6599/? E/ctxmgr: [AccountAclCallback]Failed Acl fetch: network status=-1
10-08 11:08:35.569 12974-13407/? E/Watchdog: !@Sync 422729 [10-08 11:08:35.586]
```

## Environment

```
Environment:
  OS: Windows 10
  Node: 8.11.3
  Yarn: 1.9.4
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4907809

Packages: (wanted => installed)
  expo: Not Found
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/rainmaker-98818ea8-bde9-43c9-8118-d9b7c23a05ab.tar.gz
  ```

  (I'm not sure why it says `expo: Not Found`, but `expo -V` shows `2.2.0`)

**Comment by esamelson** [comment]
Hi @elewin - sorry for the slow followup here. I've not seen this error before. Was your computer offline when you were trying to build this, by any chance?

**Comment by ccheever** [comment]
Closing for now since no response for almost a year and output from error makes it seem like the computer needed something from the Internet and was offline. 

If you (anyone who has found this issue page or the OP) are having this problem, please reopen this issue and give details, including offline/online status of your machine. Thanks!
