### ISSUE TITLE
[web] It was not possible to generate splash screen on web build

### ISSUE THREAD

**Issue by chrisdrackett** [expo/expo-cli#760]
## Description

Running `expo build:web` in a fresh `expo init` project fails its an error.

## Expected Behavior

Project builds successfully

## Observed Behavior

Error:

```
Building Webpack bundle [=================== ] 95% (8.5 seconds) emitting(node:39753) UnhandledPromiseRejectionWarning: Error: It was not possible to generate splash screen '/Users/cwd/src/web-test/assets/splash.png'. NaN/Users/cwd/.config/yarn/global/node_modules/sharp-cli/bin/cli.js exited with non-zero code: 1
Output: internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module 'sharp'
Require stack:
- /Users/cwd/.config/yarn/global/node_modules/sharp-cli/lib/constants.js
- /Users/cwd/.config/yarn/global/node_modules/sharp-cli/lib/cli.js
- /Users/cwd/.config/yarn/global/node_modules/sharp-cli/lib/index.js
- /Users/cwd/.config/yarn/global/node_modules/sharp-cli/bin/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/cwd/.config/yarn/global/node_modules/sharp-cli/lib/constants.js:28:15)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)

    at new IconError (/@expo/webpack-pwa-manifest-plugin@1.1.3/src/errors/IconError.js:2:20)
    at _callee3$ (/@expo/webpack-pwa-manifest-plugin@1.1.3/src/icons.js:135:11)
    at tryCatch (/Users/cwd/.config/yarn/global/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/cwd/.config/yarn/global/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as throw] (/Users/cwd/.config/yarn/global/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/cwd/.config/yarn/global/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/cwd/.config/yarn/global/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
(node:39753) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:39753) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Environment

```
 Expo CLI 2.20.5 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.1.0 - /usr/local/bin/node
      Yarn: 1.16.0 - ~/.config/yarn/global/node_modules/.bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.19 => 16.8.22 
      @types/react-native: ^0.57.60 => 0.57.63 
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
```

## Reproducible Demo

Using unmodified output of `expo init` choosing the `blank (typescript)` option.

**Comment by EvanBacon** [comment]
This is due to common issue with the sharp library. You can try `npm uninstall -g expo-cli && npm i -g expo-cli` or run `expo build:web --no-pwa` to prevent the generation of PWA images. We are working on a new library `@expo/image-utils` which will help prevent issues like this.

**Comment by brookemitchell** [comment]
I had a similar issue trying to run `expo build:web` , `icons.js`was passing _buffer as `undefined`. Happy just running ```no-pwa``` for now 👍 , just wish I'd seen this earlier
> expo build:web

```
UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined
    at Hash.update (internal/crypto/hash.js:58:11)
    at exports.default (/@expo/webpack-pwa-manifest-plugin@1.1.3/src/helpers/fingerprint.js:6:6)
    at processIcon (/@expo/webpack-pwa-manifest-plugin@1.1.3/src/icons.js:41:29)
    at _callee2$ (/@expo/webpack-pwa-manifest-plugin@1.1.3/src/icons.js:111:10)
```

**Comment by kay-is** [comment]
I get this error when running `expo start` which doesn't have a `--no-pwa` option.

**Comment by chase-metzger** [comment]
> I get this error when running `expo start` which doesn't have a `--no-pwa` option.

I did too. It was because I had enabled production mode by passing `--no-dev` at some point to `expo start`. If you do `expo start --dev --web` or `--web-only`, it will enable development mode. And hopefully that works.

**Comment by EvanBacon** [comment]
It took me a few PRs to fix this but now if you cannot install sharp, webpack config will use Jimp and also cache the images based on the image hash and app.json `splash` settings. If sharp is installed as a global dependency then it'll be used (faster) but regardless, the caching will drastically lower rebuild times. The optimal route is logged in the console when appropriate and everything is automatically configured. Sorry for any inconvenience this may have caused.

- One related PR: #1347
