### ISSUE TITLE
buildPhaseLogger error

### ISSUE THREAD

**Issue by c316** [expo/expo-cli#779]
## Description

When I attempt to publish using the CLI I'm getting this error message. 

```
Building JavaScript bundle [] 100%[01:49:26] Finished building JavaScript bundle in 296ms.
[01:49:26] Uploading JavaScript bundles
[01:49:28] buildPhaseLogger.info is not a function
[01:49:28] TypeError: buildPhaseLogger.info is not a function
    at Object.getManifestAsync (/@expo/xdl@55.0.10/src/detach/ExponentTools.ts:91:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Exited with code 1
```

## Expected Behavior

I'd expect the publish to complete successfully. It got to 100%, then got an error

## Environment

The environment is CircleCI's circleci/node:10.15 docker container

I was able to find that others are having the same issue. 
https://forums.expo.io/t/expo-cli-2-20-10-publish-error/24416

**Comment by mjgallag** [comment]
@cruzach here are the steps that reproduce it for me. All I did was eject a blank template to ExpoKit. Hope this helps.
```
Mikes-MacBook:expo-kit-diff Mike$ expo init
? Choose a template: expo-template-blank
✔ Please enter a few initial configuration values.
  Read more: https://docs.expo.io/versions/latest/workflow/configuration/ · 100% completed
Extracting project files...
Customizing project...
Installing dependencies...
npm WARN deprecated deep-assign@3.0.0: Check out `lodash.merge` or `merge-options` instead.
npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.

> fsevents@1.2.9 install /Users/Mike/Documents/expo-kit-diff/expo-kit-diff/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[fsevents] Success: "/Users/Mike/Documents/expo-kit-diff/expo-kit-diff/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> core-js@3.1.4 postinstall /Users/Mike/Documents/expo-kit-diff/expo-kit-diff/node_modules/@babel/register/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.9 postinstall /Users/Mike/Documents/expo-kit-diff/expo-kit-diff/node_modules/babel-runtime/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js-pure@3.1.4 postinstall /Users/Mike/Documents/expo-kit-diff/expo-kit-diff/node_modules/core-js-pure
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.9 postinstall /Users/Mike/Documents/expo-kit-diff/expo-kit-diff/node_modules/fbjs-scripts/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.9 postinstall /Users/Mike/Documents/expo-kit-diff/expo-kit-diff/node_modules/metro-babel-register/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.9 postinstall /Users/Mike/Documents/expo-kit-diff/expo-kit-diff/node_modules/metro/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.9 postinstall /Users/Mike/Documents/expo-kit-diff/expo-kit-diff/node_modules/react-native-web/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.9 postinstall /Users/Mike/Documents/expo-kit-diff/expo-kit-diff/node_modules/react-native/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN react-google-maps@9.4.5 requires a peer of @types/googlemaps@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-google-maps@9.4.5 requires a peer of @types/markerclustererplus@^2.1.29 but none is installed. You must install peer dependencies yourself.
npm WARN react-google-maps@9.4.5 requires a peer of @types/react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-reanimated@1.0.1 requires a peer of react@16.0.0-alpha.6 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-reanimated@1.0.1 requires a peer of react-native@^0.44.1 but none is installed. You must install peer dependencies yourself.

added 910 packages from 457 contributors and audited 36965 packages in 30.574s
found 11 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

Your project is ready at /Users/Mike/Documents/expo-kit-diff/expo-kit-diff

To get started, you can type:

  cd expo-kit-diff
  npm start

Mikes-MacBook:expo-kit-diff Mike$ cd expo-kit-diff/
Mikes-MacBook:expo-kit-diff Mike$ expo eject
Warning: This project contains unoptimized assets. Please run `expo optimize` in your project directory.
We didn't find any uses of the Expo SDK in your project, so you should be fine to eject to "Plain" React Native.
(This check isn't very sophisticated, though.)

Warning! Your git working tree is dirty.
It's recommended to commit all your changes before proceeding,
so you can revert the changes made by this command if necessary.

? How would you like to eject your app?
  Read more: https://docs.expo.io/versions/latest/expokit/eject/ ExpoKit
? What would you like your iOS bundle identifier to be? expo.kit.diff

> react-native-unimodules@0.4.1 postinstall /Users/Mike/Documents/expo-kit-diff/expo-kit-diff/node_modules/react-native-unimodules
> node ./scripts/postinstall.js


Successfully installed react-native-unimodules. This package contains core unimodules that are commonly depended on by other unimodules. You will need to configure your project before using other unimodules like expo-camera, expo-media-library and others.
See configuration guide:
  https://www.npmjs.com/package/react-native-unimodules/v/0.4.1

+ react-native-unimodules@0.4.1
added 2 packages from 1 contributor and audited 37007 packages in 4.149s
found 11 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
TypeError: buildPhaseLogger.info is not a function
    at Object.configureAsync (/@expo/xdl@55.0.10/src/detach/IosNSBundle.js:459:22)
buildPhaseLogger.info is not a function
Set EXPO_DEBUG=true in your env to view the stack trace.
Mikes-MacBook:expo-kit-diff Mike$ expo diagnostics

  Expo CLI 2.20.10 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 2.20.10

Mikes-MacBook:expo-kit-diff Mike$ 
```

**Comment by hotaryuzaki** [comment]
i have same problem
