### ISSUE TITLE
Can not find module '$HOME/.config/yarn/global/node_modules/@expo/image-utils/build/index.js''

### ISSUE THREAD

**Issue by erdemkeren** [expo/expo-cli#785]
There is no build folder under `$HOME/.config/yarn/global/node_modules/@expo/image-utils/` 

Can you please help me?

```
expo init Project
cd Project
EXPO_DEBUG=true yarn start
```

Output:

```
yarn run v1.16.0
$ expo start
Starting project at $HOME/path-to-project/Project
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Cannot find module '$HOME/.config/yarn/global/node_modules/@expo/image-utils/build/index.js'. Please verify that the package.json has a valid "main" entry
Error: Cannot find module '$HOME/.config/yarn/global/node_modules/@expo/image-utils/build/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:228:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:365:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:27)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/@expo/xdl@55.0.12/src/AssetUtils.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
error Command failed with exit code 1.
```

Expo CLI 2.21.0 environment info:

```
  Expo CLI 2.21.0 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
```

package.json:

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^33.0.0",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-web": "^0.11.4"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.1.1"
  },
  "private": true
}
```

**Comment by fson** [comment]
Please install `expo-cli` version `2.21.1`, it should fix this issue. (There was a problem with publishing the previous release and some files were left out from that package. It was fixed 20 minutes later, but looks like you got the faulty version in the meantime. I'm sorry about that!)

**Comment by erdemkeren** [comment]
Thanks @fson. I am grateful for the reply. I can sleep in peace now 🙏
