### ISSUE TITLE
Error Cannot find module './common/isInstalled' while running npm start

### ISSUE THREAD

**Issue by isuhendro** [expo/expo-cli#786]
Expo experts,

I am getting an error `Cannot find module './common/isInstalled'` while running `npm start`
Below is the complete error log. Let me know if you have any suggestion. Many thanks in advance

``` 
Starting project at /Users/user123/git/my-app
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
module.js:550
throw err;
^

Error: Cannot find module './common/isInstalled'
at Function.Module.\_resolveFilename (module.js:548:15)
at Function.Module.\_load (module.js:475:25)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/Users/user123/git/my-app/node_modules/@react-native-community/cli/build/commands/link/ios/index.js:9:43)
at Module.\_compile (module.js:653:30)
at Object.Module.\_extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module.\_load (module.js:498:3)

Metro Bundler process exited with code 1
Set EXPO_DEBUG=true in your env to view the stack trace.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/user123/.npm/\_logs/2019-06-28T02_36_40_306Z-debug.log
```

**Comment by isuhendro** [comment]
Below is the version of packages I am using
```
expo: 2.21.1
react-native-cli: 2.0.1
react-native: 0.59.8
```

**Comment by isuhendro** [comment]
Resolved it after reinstalling `@react-native-community/cli`
