### ISSUE TITLE
react-native-web crashes expo-CLI... maybe related to clean-webpackplugin web-build has been removed??

### ISSUE THREAD

**Issue by cdcv** [expo/expo-cli#793]
## Description

Sometimes, for reasons that we cannot determine, trying to open the app in a browser using react-native-web by pressing 'w' in the terminal window causes expo-cli to crash, producing the stacktrace shown below.  Other times, with the exact same code, this problem is not observed and the code runs in a web browser as expected.

## Expected Behavior

Ran:
expo start --localhost --offline -c 
(Have tried other variants of expo start and gotten similar behavior)
Press 'w' in terminal.  App starts in browser.

## Observed Behavior
Ran:
expo start --localhost --offline -c 
expo-cli crashes, with stacktrace shown below.
Something deep in the netherworlds of expo-land seems to be getting cached.  

It would be *extremely helpful* to have commands that will *clear absolutely everything* that's stored anywhere by any aspect of expo, piece by piece, so that in a circumstance like this we don't have to try 400 different methods of trying to clear whatever thing might be causing the problem... since we have no idea where it's coming from.  As a relatively new Expo developer, I spend the greatest amount of my wasted time overall with trying to figure out how to clear Expo-related states: eg expo start -c, rm -rf node_modules, delete the app, restart the simulator, wipe the simulator, delete the Expo app on my device, (new on just this week, even after delete the expo App, it restores its data on Android, so then you also have to teach your beta user how to clear the app's storage using settings)... etc.

We then start a long and painful process of trying to get our code to run again.  This involves many long, slow steps.  Trying individual steps doesn't work (eg removing the node-modules directory, or reinstalling expo-cli, or using a different version of expo-cli).  We've never been able to figure out which steps actually solve the problem.  Here's what seems to work:
remove app directory entirely
uninstall expo-cli
reinstall expo-cli
git clone app from repo
npm i
expo start --localhost --offline -c 
'w' to start in web browser

I *think* that whenever we see this when we press 'w':
clean-webpack-plugin: /Users/cdecharms/code/Brainful/BrainfulAppReactNative/web-build has been removed.
the process will end in expo-cli crashing.

If this workaround of a complete reinstall of everything sounds pretty painful... it is.  Especially since whatever is causing this happens multiple times per day.
Note: this means that the exact same codebase works after complete reinstall... so it isn't an error in the code.  For that reason, we haven't tried to reproduce this with a sample project.

It takes so long to get things working again, that we've been reluctant to do too much testing on what causes this problem... it seems to arise out of nowhere.
The one thing that seemed to *produce* the error, we think, was to run:
expo build:web
This (we think) was what caused the problem the first time that we observed it.  After that command, we could no longer get the app to build for web, and the only solution we could find was the total-reinstall we describe above.

```
clean-webpack-plugin: /Users/cdecharms/code/Brainful/BrainfulAppReactNative/web-build has been removed.
Building Webpack bundle [==============      ] 70% (18.8 seconds) building modulesTypeError: Cannot read property 'children' of undefined
    at unionChildren (/usr/local/lib/node_modules/expo-cli/node_modules/deep-scope-analyser/src/analyser/moduleAnalyser.ts:298:30)
    at usedModuleScopeIds.forEach.id (/usr/local/lib/node_modules/expo-cli/node_modules/deep-scope-analyser/src/analyser/moduleAnalyser.ts:315:9)
    at Array.forEach (<anonymous>)
    at ModuleAnalyser.generateExportInfo (/usr/local/lib/node_modules/expo-cli/node_modules/deep-scope-analyser/src/analyser/moduleAnalyser.ts:304:24)
    at compilation.hooks.dependencyReference.tap (/usr/local/lib/node_modules/expo-cli/node_modules/webpack-deep-scope-plugin/index.js:34:56)
    at SyncWaterfallHook.eval (eval at create (/usr/local/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:16)
    at Compilation.getDependencyReference (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/Compilation.js:1492:41)
    at processDependency (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:80:37)
    at processDependenciesBlock (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:67:8)
    at compilation.hooks.optimizeDependencies.tap.modules (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/FlagDependencyUsagePlugin.js:109:7)
    at SyncBailHook.eval (eval at create (/usr/local/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:20:16)
    at SyncBailHook.lazyCompileHook (/usr/local/lib/node_modules/expo-cli/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/Compilation.js:1180:36)
    at hooks.make.callAsync.err (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:546:17)
    at _done (eval at create (/usr/local/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at _err1 (eval at create (/usr/local/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:22)
    at tap.fn.args (/usr/local/lib/node_modules/expo-cli/node_modules/react-dev-utils/ModuleNotFoundPlugin.js:114:15)
    at _addModuleChain (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/Compilation.js:1082:12)
    at processModuleDependencies.err (/usr/local/lib/node_modules/expo-cli/node_modules/webpack/lib/Compilation.js:998:9)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)

```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

  Expo CLI 2.21.1 environment info:
    System:
      OS: macOS 10.14.1
      Shell: Unknown - /usr/local/bin/fish
    Binaries:
      Node: 11.4.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^5.1.3 => 5.1.3 
      expo: ^33.0.0 => 33.0.5 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.0.9 => 3.9.1 
    npmGlobalPackages:
      expo-cli: 2.21.1

Also specify:

This is on a Mac using up to date Chrome browser (but it doesn't get to that point as the browser never opens).

## Reproducible Demo

Don't know how to create one since this doesn't seem to be based on the code itself.
One potential clue?  During our long total-rebuild process, we accidentally rebuilt the master branch, then switched to our current development branch, then npm i, then rebuilt that, then were able to get the web to work.  Not sure if this had anything to do with the outcome or not.  We've tried doing those steps in isolation (without the total reinstall) and not succeeded.

Thanks for your help.

**Comment by EvanBacon** [comment]
This was related to some missing error messages. Fixed in `expo@3.0.3` Run `npm i -g expo-cli` to get the latest. Now it'll inform you correctly if your code is broken.
