### ISSUE TITLE
Invalid comparator: latest

### ISSUE THREAD

**Issue by chabanov** [expo/expo-cli#802]
```
Expo DevTools is running at http://localhost:19002
Invalid comparator: latest
TypeError: Invalid comparator: latest
    at Comparator.parse (/usr/local/lib/node_modules/expo-cli/node_modules/semver/semver.js:690:11)
    at new Comparator (/usr/local/lib/node_modules/expo-cli/node_modules/semver/semver.js:674:8)
    at /usr/local/lib/node_modules/expo-cli/node_modules/semver/semver.js:840:12
    at Array.map (<anonymous>)
    at Range.parseRange (/usr/local/lib/node_modules/expo-cli/node_modules/semver/semver.js:839:13)
    at Range.<anonymous> (/usr/local/lib/node_modules/expo-cli/node_modules/semver/semver.js:781:17)
    at Array.map (<anonymous>)
    at new Range (/usr/local/lib/node_modules/expo-cli/node_modules/semver/semver.js:780:40)
    at Function.intersects (/usr/local/lib/node_modules/expo-cli/node_modules/semver/semver.js:1306:8)
    at _callee3$ (/expo-cli@2.21.2/src/commands/start.js:130:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by NiciusB** [comment]
When running expo start,  it will check package.json and crash if any package doesn't have traditional semver syntax.

That includes `latest` (which I guess could be changed to `*`? Idk), but it also includes any github repo.
It would be useful to be able to put repos in the dependencies, since they might not be published on npm, or you might want to use your own fork

**Comment by irhamputra** [comment]
@chabanov you should check your package.json and make sure everything is fine. I did have same issue after I checked my package.json. They changed completely and I solve it manually. Hope it helpful

**Comment by hlprmnky** [comment]
> When running expo start, it will check package.json and crash if any package doesn't have traditional semver syntax.

Is this a bug? Desired but undocumented functionality? Our project has forks of dependencies _specifically to work around other issues in SDK33_ (e.g., Branch, generally), so being unable to build with those forks in place is a very frustrating situation.

**Comment by brentvatne** [comment]
sorry about this! it has since been resolved. thanks for reporting the issue!
