### ISSUE TITLE
`expo start` fails w/ expo-web

### ISSUE THREAD

**Issue by n-sviridenko** [expo/expo-cli#848]
### Environment

```
  Expo CLI 2.20.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
```

### Steps to Reproduce

1. Add `web` to `app.json`
2. Install `react-dom` and `react-native-web` (w/o specifying version so that it will take the latest compatible)
3. Run `expo start`

### Expected Behavior

It runs w/o errors.

### Actual Behavior

After adding `web` to `app.json` on SDK 33, I'm having the following error after calling `expo start`:

```
(node:73688) UnhandledPromiseRejectionWarning: Error: Cannot find module './transformation/file/file'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (<edited by me>/node_modules/metro/node_modules/@babel/core/lib/index.js:147:36)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

(node:73688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:73688) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Reproducible Demo

Nope

**Comment by federicobarera** [comment]
Similar issues on Win10

```
"dependencies": {
    "expo": "^33.0.0",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-web": "^0.11.4"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.1.1"
  },
```

```
Opening DevTools in the browser... (press shift-d to disable)
Warning: This project contains unoptimized assets. Please run `expo optimize` in your project directory.
Starting Metro Bundler on port 19001.
Tunnel ready.
Cannot find module 'eslint'
Set EXPO_DEBUG=true in your env to view the stack trace.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ web: `expo start --web`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ web script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ira\AppData\Roaming\npm-cache\_logs\2019-07-21T19_48_42_691Z-debug.log
```

**Comment by nicolasrouanne** [comment]
I have exactly the same issue with a brand new `expo` project bootstrapped with _expo-cli_ (`v3.0.2`) using SDK 33.

```bash
$  expo init test-expo
$ cd test-expo/
$ yarn install
$ yarn start
> w
Trying to open the project in a web browser...
(node:69961) UnhandledPromiseRejectionWarning: Error: Cannot find module 'eslint'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at module.exports (/Users/nicolasrouanne/.nvm/versions/node/v10.16.0/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/webpack/webpack.common.js:448:37)
(node:69961) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:69961) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by k2xl** [comment]
Also happening on mac
```
Expo CLI 3.0.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.19 => 16.8.23 
      @types/react-native: ^0.57.60 => 0.57.65 
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.0.2
```

**Comment by n-sviridenko** [comment]
@cruzach Looks like there is really something wrong ..

**Comment by cruzach** [comment]
Duplicate. Closing to keep track of in #859 instead
