### ISSUE TITLE
Expo start yields blank screen in browser

### ISSUE THREAD

**Issue by cdcv** [expo/expo-cli#866]
## Description
Command:
expo start 
Result: brings up browser at http://localhost:19002/ with black screen only

## Expected Behavior
expo start 
-> expo UI screen appears on localhost in browser (the screen that you get when you press 'd' for devtools, and that normally comes up automatically, and shows the bundler, QR code, settings, etc).

## Observed Behavior

Black screen appeared.  No error msg.  No console log in browser.
Clearly expo is still working, because if I hit 'w' in the terminal, I still get the app to appear correctly in a browser, and I can still open the app using the mobile expo client on a device (using the local server url, eg exp://192.168.0.109:19000).
Many hours get spent uninstalling and reinstalling things.

Examples of things that don't solve the problem:
Running in different 'clean' browser.
expo start -c, expo start --web.
uninstall reinstall expo-cli, node, npm, change node version.
Things had previously been working fine, and there were no obvious intentional changes made to anything... it just stopped working all of a sudden.  Same app.  Same install.  Same machine.  Etc.  As I mentioned, expo is clearly still running, and serving the app, it just isn't showing up in the web browser.  Some kind of cache somewhere?

```
Error message: inky blackness that makes you feel deep inside that your project is dying at the hands of Expo tools

```
Here is the web page that's rendered where the 'normal' page, which doesn't really have a title, but says Metro Bundler in the top left, is supposed to be rendered:

<html><head><meta charset="utf-8" class="next-head"><link rel="preload" href="/_next/5c2811eb-2ef7-41f9-bd08-9df590a42489/page/index.js" as="script"><link rel="preload" href="/_next/5c2811eb-2ef7-41f9-bd08-9df590a42489/page/_error.js" as="script"><link rel="preload" href="/_next/5c2811eb-2ef7-41f9-bd08-9df590a42489/main.js" as="script"><title>Expo Developer Tools</title><link rel="apple-touch-icon" sizes="180x180" href="/static/apple-touch-icon.png"><link rel="icon" type="image/png" sizes="32x32" href="/static/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="/static/favicon-16x16.png"><link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5"><meta name="msapplication-TileColor" content="#da532c"><link rel="manifest" href="/static/site.webmanifest"><meta name="theme-color" content="#ffffff"><style>@font-face{font-family:bold;src:url('/static/fonts/MaisonNeue-Bold.woff2');src:url('/static/fonts/MaisonNeue-Bold.woff') format('woff');}@font-face{font-family:regular;src:url('/static/fonts/MaisonNeue-Book.woff2');src:url('/static/fonts/MaisonNeue-Book.woff') format('woff');}@font-face{font-family:demi;src:url('/static/fonts/MaisonNeue-Demi.woff2');src:url('/static/fonts/MaisonNeue-Demi.woff') format('woff');}@font-face{font-family:light;src:url('/static/fonts/MaisonNeue-Light.woff2');src:url('/static/fonts/MaisonNeue-Light.woff') format('woff');}@font-face{font-family:mono;src:url('/static/fonts/MaisonNeueMono-Regular.woff2');src:url('/static/fonts/MaisonNeueMono-Regular.woff') format('woff');}html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,center,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,embed,figure,figcaption,footer,header,hgroup,menu,nav,output,ruby,section,summary,time,mark,audio,video{box-sizing:border-box;margin:0;padding:0;border:0;vertical-align:baseline;}article,aside,details,figcaption,figure,footer,header,hgroup,menu,nav,section{display:block;}@-webkit-keyframes rotate{from{-webkit-transform:rotate(0deg);-ms-transform:rotate(0deg);transform:rotate(0deg);}to{-webkit-transform:rotate(360deg);-ms-transform:rotate(360deg);transform:rotate(360deg);}}@keyframes rotate{from{-webkit-transform:rotate(0deg);-ms-transform:rotate(0deg);transform:rotate(0deg);}to{-webkit-transform:rotate(360deg);-ms-transform:rotate(360deg);transform:rotate(360deg);}}@-webkit-keyframes fadeInRight{from{opacity:0;-webkit-transform:translate3d(100%,0,0);-ms-transform:translate3d(100%,0,0);transform:translate3d(100%,0,0);}to{opacity:1;-webkit-transform:translate3d(0,0,0);-ms-transform:translate3d(0,0,0);transform:translate3d(0,0,0);}}@keyframes fadeInRight{from{opacity:0;-webkit-transform:translate3d(100%,0,0);-ms-transform:translate3d(100%,0,0);transform:translate3d(100%,0,0);}to{opacity:1;-webkit-transform:translate3d(0,0,0);-ms-transform:translate3d(0,0,0);transform:translate3d(0,0,0);}}html,body{height:100%;font-size:12px;background:#111111;}html::-webkit-scrollbar,body::-webkit-scrollbar{width:0px;background:transparent;}html::-webkit-scrollbar-thumb,body::-webkit-scrollbar-thumb{background:#111111;}#__next{height:100%;}[data-reactroot]{height:100%;}</style><style type="text/css" data-emotion=""></style></head><body><div id="__next"></div><div id="__next-error"></div><script>
          __NEXT_DATA__ = {"props":{},"page":"/","pathname":"/","query":{},"buildId":"5c2811eb-2ef7-41f9-bd08-9df590a42489","assetPrefix":"","nextExport":true,"err":null,"ids":["0","14w768r"],"chunks":[]}
          module={}
          __NEXT_LOADED_PAGES__ = []
          __NEXT_LOADED_CHUNKS__ = []

          __NEXT_REGISTER_PAGE = function (route, fn) {
            __NEXT_LOADED_PAGES__.push({ route: route, fn: fn })
          }

          __NEXT_REGISTER_CHUNK = function (chunkName, fn) {
            __NEXT_LOADED_CHUNKS__.push({ chunkName: chunkName, fn: fn })
          }

          false
        </script><script async="" id="__NEXT_PAGE__/" src="/_next/5c2811eb-2ef7-41f9-bd08-9df590a42489/page/index.js"></script><script async="" id="__NEXT_PAGE__/_error" src="/_next/5c2811eb-2ef7-41f9-bd08-9df590a42489/page/_error.js"></script><script src="/_next/5c2811eb-2ef7-41f9-bd08-9df590a42489/main.js" async=""></script><style>.tb_button {padding:1px;cursor:pointer;border-right: 1px solid #8b8b8b;border-left: 1px solid #FFF;border-bottom: 1px solid #fff;}.tb_button.hover {borer:2px outset #def; background-color: #f8f8f8 !important;}.ws_toolbar {z-index:100000} .ws_toolbar .ws_tb_btn {cursor:pointer;border:1px solid #555;padding:3px}   .tb_highlight{background-color:yellow} .tb_hide {visibility:hidden} .ws_toolbar img {padding:2px;margin:0px}</style></body></html>

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:
  Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.1
      Shell: Unknown - /usr/local/bin/fish
    Binaries:
      Node: 11.4.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^5.1.3 => 5.1.3 
      @types/react: ^16.8.23 => 16.8.23 
      @types/react-native: ^0.60.0 => 0.60.0 
      expo: ^33.0.0 => 33.0.5 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.0.9 => 3.9.1 
    npmGlobalPackages:
      expo-cli: 2.21.2

Also specify:
None relevant, but code running correctly on Pixel 3XL during this problem.

## Reproducible Demo
Close your eyes and imagine that you will never see light ever again.

**Comment by hodgef** [comment]
I initially thought there was something wrong with Chrome, but now I see that other people are having the same issue.

![image](https://user-images.githubusercontent.com/25509135/61673883-55d0f780-acbf-11e9-9bad-0badf345cccd.png)

```
Expo CLI 2.21.2 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by AdamJNavarro** [comment]
Hey all,

Can you try updating to the latest version of `expo cli` (At the time of this post that would be `3.0.4`). I've been unable to reproduce this on either `3.0.3` or `3.0.4`.

Cheers,
Adam

**Comment by Saganic** [comment]
> Hey all,
> 
> Can you try updating to the latest version of `expo cli` (At the time of this post that would be `3.0.4`). I've been unable to reproduce this on either `3.0.3` or `3.0.4`.
> 
> Cheers,
> Adam

Reporting the same issue. I can't upgrade until the team at vue-native upgrade to expo 3.03 or 3.04 - is there are work around for older versions of expo (2.21.2)

**Comment by hodgef** [comment]
I can confirm that this is fixed in expo cli `3.0.4`. Thanks expo team for the quick fix !

**Comment by mikasjoman** [comment]
Same here, just get a black screen :(

**Comment by mikasjoman** [comment]
upgrading to 3.0.4 fixed it :)

**Comment by flieks** [comment]
i have CLI 3.0.10 and also have the problem (chrome). Restarted pc which didn't help. running via CLI (to send to phone) still works but screen is black

**Comment by ParAnton** [comment]
I have cli 3.0.10 and get the same behaviour as @flieks

**Comment by ericwestbrook** [comment]
upgrading fixed for me as well. thanks!

**Comment by ParAnton** [comment]
strange when I start expo as an npm script
`$ npm run start`
which triggers
` "start": "expo start",`
I get a blackscreen in my browser but running
 `$ npm expo start`
everything works fine

**Comment by elektronik2k5** [comment]
@ParAnton perhaps you have `expo-cli` as a dependency. npm scripts run locally installed dependencies first, if they are installed, and otherwise fallback to global packages.

**Comment by JackDavidson** [comment]
I'm getting this issue on and off with expo-cli 3.1.1

The expo developer tools page shows up correctly about 1/10th of the times I run 'npm start' but 9/10 times, I get the black screen. I'm on a clean install of ubuntu 19.04, with a clean download of node from https://nodejs.org/dist/v10.16.3/node-v10.16.3-linux-x64.tar.xz, and I just ran expo init to create a new app, so its a fresh react native project too. I can still run the project on my phone by just pressing 'a' or on web with 'w' (after following the workaround at https://github.com/expo/expo/issues/5727).

**Comment by arrygoo** [comment]
The issue is back in `3.1.2`

**Comment by danielcolgan** [comment]
@arrygoo I run `expo login` and after login again, started expo process with `expo start` and everything worked!

**Comment by EvanBacon** [comment]
Closing as duplicate of this https://github.com/expo/expo-cli/issues/739

**Comment by Innovativeappz** [comment]
i uninstall node 12.12.0 & install 10.13.0 version. now no black screen appear & app run on my physical android device.

**Comment by adir1661** [comment]
@AdamJNavarro 
my expo version is:
    >expo --version
    3.15.5
and i still have a black screen in my browser (chrome, firefox)

**Comment by sanaiftikhar** [comment]
Same issue how to resolve ???



Expo CLI 3.11.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.21.0 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD

**Comment by destinybonavita** [comment]
I'm running into the same issue. I think this should be reopened

**Comment by Blinchick** [comment]
ran into the same issue.. here is my output

Expo CLI 3.21.5 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - /usr/local/bin/node
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.12
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.21.5

**Comment by mikescott** [comment]
Also getting this in Expo 3.21.9

**Comment by star-scraper** [comment]
I just updated to version 37 of the SDK and I'm getting the same screen "Error loading DevTools" is all that appears in the browser.

**Comment by brentvatne** [comment]
@star-scraper can you open up chrome dev tools and show us the logs that you see?

**Comment by star-scraper** [comment]
Nvm @brentvatne I just re-installed the expo-cli again and that fixed it, sorry for the confusion, but I appreciate the help ;)

**Comment by diegolaciar** [comment]
+1  

just upgrade from expo 37 to expo 38.

I get the same black screen with message "Error loading DevTools"
No error on the terminal.
I removed node_modules, re-installed all  and the same issue.

expo-cli@3.22.0

**Comment by brentvatne** [comment]
@diegolaciar - can you open up chrome dev tools and show us the logs that you see?

**Comment by alexborton** [comment]
@brentvatne I also have this problem as described by @diegolaciar. 

Only occurs when running in Expo 38 - the app itself seems to run correctly. No logs in the console for `Expo Developer Tools`- just the display of onscreen message `Error loading DevTools`

The debug from the application could shed some light;

```
DevTools failed to load SourceMap: Could not load content for http://localhost:19001/debugger-ui/debuggerWorker.cff11639.js.map: HTTP error: status code 500, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

This displays immediately as a warning.

**Comment by diegolaciar** [comment]
@brentvatne 

 Yes, as @alexborton say, there is no logs on the devtool console

**Comment by brentvatne** [comment]
- if you `npm uninstall -g expo-cli` and then `npm i -g expo-cli` does that fix it?
- if you clear your cache in chrome, does that fix it?

**Comment by dominik992** [comment]
Same problem. If I run with `expo start -c` I get "Error loading DevTools" error. However if I remove `-c` flag, it works

**Comment by JorgeOsorio97** [comment]
Same issue with expo-cli 3.23.3
Node 12.18.3

**Comment by raniyer** [comment]
I had the same issue with expo-cli 3.23.3  node-14.7.0 browser firefox. But reinstalling node fixed it for me.

**Comment by TheGreatFellow** [comment]
I have the same problem even though i was using the updated version from the start.
Using ```expo start``` instead of ```npm start``` solves the issue.

**Comment by defrex** [comment]
I'm also experiencing this issue. I've noticed something interesting. Here is my graphql websocket log.

```
{"type":"connection_init","payload":{"clientAuthenticationToken":"[secret, probably]"}}
{"id":"1","type":"start","payload":{"variables":{},"extensions":{},"operationName":"IndexPageQuery","query":"query IndexPageQuery {\n  currentProject {\n    id\n    manifestUrl\n    settings {\n      hostType\n      dev\n      minify\n      __typename\n    }\n    config {\n      name\n      description\n      slug\n      githubUrl\n      __typename\n    }\n    sources {\n      id\n      name\n      messages {\n        count\n        unreadCount\n        nodes {\n          ...MessageFragment\n          __typename\n        }\n        pageInfo {\n          lastReadCursor\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    messages {\n      pageInfo {\n        lastCursor\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  userSettings {\n    id\n    sendTo\n    __typename\n  }\n  projectManagerLayout {\n    id\n    selected {\n      id\n      __typename\n    }\n    sources {\n      id\n      __typename\n    }\n    __typename\n  }\n  processInfo {\n    isAndroidSimulatorSupported\n    isIosSimulatorSupported\n    webAppUrl\n    __typename\n  }\n  user {\n    username\n    __typename\n  }\n}\n\nfragment MessageFragment on Message {\n  id\n  msg\n  time\n  level\n  ... on DeviceMessage {\n    includesStack\n    __typename\n  }\n  __typename\n}\n"}}
{"type":"connection_ack"}
{"type":"error","id":"1","payload":{"message":"Cannot use GraphQLSchema \"[object GraphQLSchema]\" from another module or realm.\n\nEnsure that there is only one instance of \"graphql\" in the node_modules\ndirectory. If different versions of \"graphql\" are the dependencies of other\nrelied on modules, use \"resolutions\" to ensure only one version is installed.\n\nhttps://yarnpkg.com/en/docs/selective-version-resolutions\n\nDuplicate \"graphql\" modules cannot be used at the same time since different\nversions may have different capabilities and behavior. The data from one\nversion used in the function from another could produce confusing and\nspurious results."}}
{"id":"1","type":"stop"}
```

Notice the error,

```
Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
```

I'm using Apollo Client in my app, and thus have the `graphql` package installed. Is it possible that there is a version incompatibility between my dep and a downstream version used by Expo Dev Tools?

**Comment by kgorol** [comment]
After the upgrade from Expo 37 to 38 when I run command "npm start" ("start": "expo start") I receive black page with `Error loading DevTools` message, along with these console logs:

```
TypeError: can't access property "sources", e is undefined
    NextJS 20
commons.bcfc4fb2e85568d289cc.js:1:163814
TypeError: can't access property "sources", e is undefined
    NextJS 20
commons.bcfc4fb2e85568d289cc.js:1:163814
TypeError: can't access property "sources", e is undefined
    NextJS 20
```

However, when I run directly `expo start' it works just fine.

**Comment by actuallymentor** [comment]
To everyone with this issue, I'm not sure which of this fixes anything but try:

1. Update `expo` and `expo-cli`
2. Run this:
	```shell
	# Tool specific caches
	npm cache clean --force || echo "No npm binary found, skipped"
	watchman watch-del-all || echo "No watchman binary found, skipped"
	jest --clearCache || echo "No jest binary found, skipped"

	# Cache directories
	rm -rf .expo && echo "Expo cache cleared"
	rm -fr $TMPDIR/metro* && echo "Metro cache cleared"
	  
	# Dependency reset
	rm package-lock.json
	rm -rf node_modules
	npm i
	```
3. If your `expo preview` app is on android: go to the app info ( long press > app info ) force close it and clear cache
4. Try again

**Comment by alexborton** [comment]
As an FYI, i found that `yarn install` would start Expo as expected, whereas (my usual) `npm install` would fail to run the dev screen in chrome. 

I tried all the usual cache clearing, to no avail. I suppose i will be switching to `yarn` to use Expo `38.0.0` 🤷‍♂️ 

I do unfortunately still have an issue with the DevTools actually running, but that is more [as described here](https://stackoverflow.com/questions/59658998/expo-unable-to-resolve-module-debugger).

**Comment by qwrwed** [comment]
I have the same issue in Firefox 81.0.1. In the console I get the error `Firefox can't establish a connection to the server at ws://localhost:19002/1etrArriHP_UwbjDTnHhqbCSmh0GDygAZ_-erKkEDFw/graphql.`, along with GET requests to the same address with status `400 Bad Request`. For some reason, it works in a Private Window, but not in a normal one, even in Safe Mode.

**Comment by brentvatne** [comment]
hello! this could be related to browser caching. try clearing your browser cache

**Comment by qwrwed** [comment]
It still happens with cache cleared.

**Comment by mendzak** [comment]
For me, `logout` and then `login` worked.

**Comment by mendzak** [comment]
> For me, `logout` and then `login` worked.

Well, today this approach does not work.

**Comment by brentvatne** [comment]
to people experiencing this: do you have `expo-cli` installed as a dependency of your local project?

**Comment by defrex** [comment]
@brentvatne yes. I generally avoid global dependencies of any kind.

**Comment by defrex** [comment]
I can confirm that switching to a globally installed `expo-cli` (and deleting the local install) fixed the issue for me. 🎉

**Comment by defrex** [comment]
That said, a global install isn't optimal.

We like to make sure key commands, like starting expo, are in `scripts` in `package.json` for discoverability, and also that things in `scripts` don't require global installs for easy setup.

But perhaps now that the source of the problem is known it'll be easier to fix.

**Comment by EvanBacon** [comment]
We're working on making expo-cli have more versioned aspects to it, but unfortunately it's a very big project is it's taking a while.

**Comment by EwenQuim** [comment]
Same problem with expo (3.28.6 and 4.0.1 tested) installed globally or locally with yarn or npm (tried everything uh).

It's very frustrating because there is no error message, just a black screen instead of the usual DevTools, and it worked yesterday until I tried to upgrade my expo version.
Expo is still running because the web version works, but the android/ios app can't be used as well as the dev tools.

**Comment by hajeklu** [comment]
Same problem.. 
Firefox 84.0. 
Ubuntu 20.04 LTS 
expo": "~40.0.0",
    "expo-status-bar": "~1.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native-web": "~0.13.12"

**Comment by wfparrish** [comment]
The solution for me was to NOT ctrl-click the link in the terminal. Just copy the address:
http://localhost:19002
Then paste it into the browser. Worked like magic!

**Comment by amoat7** [comment]
still having this blank page issue. Done fresh installs still doesn't work.

**Comment by igormcsouza** [comment]
> The solution for me was to NOT ctrl-click the link in the terminal. Just copy the address:
> http://localhost:19002
> Then paste it into the browser. Worked like magic!

Holly!! That worked Pretty Well! Thanks!! :D

**Comment by SirMishaa** [comment]
> 
> 
> The solution for me was to NOT ctrl-click the link in the terminal. Just copy the address:
> http://localhost:19002
> Then paste it into the browser. Worked like magic!

This is working too for me.  Thanks !

**Comment by AlexWang18** [comment]
> 
> 
> The solution for me was to NOT ctrl-click the link in the terminal. Just copy the address:
> http://localhost:19002
> Then paste it into the browser. Worked like magic!

That worked for me in Chrome but still ran into same black screen on Firefox

**Comment by senica** [comment]
Hi All! This is the closest thing I've seen to my issue. I compiled and deployed on the app store...no issues. However, on android I get the following message all the time:
```
[Unhandled promise rejection: Error: Could not open URL 'about:blank': No Activity found to handle Intent { act=android.intent.action.VIEW dat=about:blank flg=0x10000000 }]
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:103:50 in promiseMethodWrapper
at node_modules/qs/lib/utils.js:145:4 in encode
at node_modules/qs/lib/parse.js:254:5 in module.exports
at http://192.168.0.103:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false:230588:35 in onLoadingStart
at [native code]:null in callFunctionReturnFlushedQueue
```

This doesn't really seem to affect anything when testing in Genymotion, but on the play store clicking a button opens a blank, black chrome window. 

I do not have expo-cli as a dependency. I do have expo as a dependency.

I'm using expo-cli 4.3.4

`expo diagnostics`
```
 Expo CLI 4.3.4 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.11.0 - ~/projects/simplylegalusa/react-mobile-new/env/bin/node
      Yarn: 1.22.10 - ~/projects/simplylegalusa/react-mobile-new/env/bin/yarn
      npm: 7.6.0 - ~/projects/simplylegalusa/react-mobile-new/env/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.7199119
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      expo-cli: 4.3.4
    Expo Workflow: managed
```

Any ideas on this?

**Comment by s-satsangi** [comment]
Just putting this here in case it helps, but I was having this same issue in Windows 10(using WSL -- Windows Subsystem for Linux) while using Visual Studio Code as my IDE.  Instead of using the terminal inside VSC, I opened up a Ubuntu window and invoked expo using yarn in my project's directory:

`yarn expo start`

That seems to have consistently removed the problem.

**Comment by covidhelpers** [comment]
Expo CLI 4.4.3 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\HP\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 21, 23, 26, 27, 28, 29, 30
        Build Tools: 21.1.2, 23.0.2, 27.0.3, 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.3, 31.0.0
        System Images: android-25 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ~41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

**Comment by thamudi** [comment]
> This happens quite often. Use `expo upgrade`. This worked for me every single time or try reinstalling expo.

This fixed my issue

SDK version:

```bash
expo-cli --version
4.13.0
```
Project dependences:

```json
{
    "expo": "~43.0.2",
    "expo-status-bar": "~1.1.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-web": "0.17.1"
}
```

**Comment by rohan9024** [comment]
It's because of your browser ....switch to chrome instead.

**Comment by d-roduit** [comment]
I had the same problem (black screen and the graphql websocket error in the console) in Firefox (Developer Edition, v. 97.0beta).

I used `expo-cli` installed globally and had no other `expo-cli` installed locally. 
I tried to reinstall `expo-cli` with `npm install -g expo-cli` but it did not fix the problem.

It seems that the fact of either copy-pasting directly the URL in the browser instead of opening the URL from the terminal or opening the URL in a private tab fixed it.

**Comment by samal-rasmussen** [comment]
A hard reload worked for me.

**Comment by remydev47** [comment]
Am still having this problem up to now..

**Comment by rohan9024** [comment]
> 
Use a different browser. It will work
