### ISSUE TITLE
Expo build:android errors

### ISSUE THREAD

**Issue by jciccio** [expo/expo-cli#867]
## Description

Each time I try to execute expo build:android, build:ios or even expo optimize I get errors.
For expo build:android I get `Request failed with status code 500`

The exact errors is:

```
Error: Request failed with status code 500
    at createError (/Users/jose/.config/yarn/global/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/jose/.config/yarn/global/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/jose/.config/yarn/global/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Tried to update to the latest expo-cli

Reinstall expo cli using yarn or npm and have the same results.

Running expo diagnostics throw:
```
  Expo CLI 3.0.2 environment info:
    System:
      OS: macOS Sierra 10.12.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 8.3.3/8E3004b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ~2.3.1 => 2.3.1 
```

Also, if I try to publish the project from the browser, gets stuck and never ends. So can't do it from console or the browser, probably it is all related.

**Comment by AdamJNavarro** [comment]
Hey @jciccio,

Are you still encountering this error? It may have been a transient issue. I successfully ran the commands you mentioned just now.

Cheers,
Adam

**Comment by Alhydra** [comment]
I was having the same problem all day long, for both build:ios and build:android

Any solutions?

**Comment by jciccio** [comment]
@AdamJNavarro yes, still have the issue

**Comment by jciccio** [comment]
@AdamJNavarro in fact just tried again and seems to be fixed.

**Comment by pierol** [comment]
Hi all, same error now with `expo build:ios -c`:
`expo build:ios -c
Checking if there is a build in progress...

Request failed with status code 500
Error: Request failed with status code 500
    at createError (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:205:15)
    at IncomingMessage.EventEmitter.emit (domain.js:471:20)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)`

**Comment by pierol** [comment]
After some more investigations i've found that if i run the command `expo build:ios` with out the `-c` option the build start but i obtain the error:
```
Failed to generate Apple Provisioning Profile
Reason: No cert available to make provision profile against, raw: "Make sure you were able to make a certificate prior to this step"
```
the reason is that i need to change the distribution certificate on EXPO server but if i try to do a `expo build:ios --clear-dist-cert` i obtain the same error of `-c` option:
```
expo build:ios --clear-dist-cert
Checking if there is a build in progress...

Request failed with status code 500
Error: Request failed with status code 500
    at createError (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:205:15)
    at IncomingMessage.EventEmitter.emit (domain.js:471:20)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

**Comment by ivansenic** [comment]
I am getting the same error even with the `publish` command. I did a clean reinstall of the expo-cli and updated to the latest version. Did not help.

```
$ expo diagnostics && EXPO_DEBUG=true expo publish --release-channel prod-v0 

  Expo CLI 3.0.6 environment info:
    System:
      OS: Linux 4.18 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/bin/node
      npm: 6.9.0 - /usr/bin/npm
    npmPackages:
      @types/react: ^16.8.23 => 16.8.23 
      @types/react-native: ^0.57.65 => 0.57.65 
      @types/react-navigation: ^3.0.7 => 3.0.7 
      expo: ^34.0.1 => 34.0.2 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.6

Publishing to channel 'prod-v0'...
Request failed with status code 500
Error: Request failed with status code 500
    at createError (/home/ise/npm/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/ise/npm/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/ise/npm/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by jciccio** [comment]
I think this one can be closed, it is not happening to me anymore

**Comment by josehernandezv** [comment]
I'm still having this issue for iOS

`expo build:ios -c
Checking if there is a build in progress...

Request failed with status code 500
Error: Request failed with status code 500
    at createError (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`
