### ISSUE TITLE
Fresh project `npm start` fails with error message

### ISSUE THREAD

**Issue by baradusov** [expo/expo-cli#877]
## Description

After fresh `expo init`, `npm start` fails with error message `Cannot find module '../../tools/PackageManager'`

## Expected Behavior

Expected `npm start` to start the local development server of Expo CLI.

## Observed Behavior

```
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module '../../tools/PackageManager'
Require stack:
- /home/baradusov/dev/apps/test/test/node_modules/@react-native-community/cli/build/commands/install/install.js
- /home/baradusov/dev/apps/test/test/node_modules/@react-native-community/cli/build/commands/index.js
- /home/baradusov/dev/apps/test/test/node_modules/@react-native-community/cli/build/cliEntry.js
- /home/baradusov/dev/apps/test/test/node_modules/@react-native-community/cli/build/index.js
- /home/baradusov/dev/apps/test/test/node_modules/react-native/local-cli/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/baradusov/dev/apps/test/test/node_modules/@react-native-community/cli/build/commands/install/install.js:10:46)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/baradusov/dev/apps/test/test/node_modules/@react-native-community/cli/build/commands/install/install.js',
    '/home/baradusov/dev/apps/test/test/node_modules/@react-native-community/cli/build/commands/index.js',
    '/home/baradusov/dev/apps/test/test/node_modules/@react-native-community/cli/build/cliEntry.js',
    '/home/baradusov/dev/apps/test/test/node_modules/@react-native-community/cli/build/index.js',
    '/home/baradusov/dev/apps/test/test/node_modules/react-native/local-cli/cli.js'
  ]
}

Metro Bundler process exited with code 1

```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:
```
  Expo CLI 3.0.4 environment info:
    System:
      OS: Linux 4.15 elementary OS 5.0 Juno
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 12.7.0 - /usr/bin/node
      npm: 6.10.2 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
    npmPackages:
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.0.4

```
Also specify:

- Phone/emulator/simulator platform, model and version:

```
Android emulator, Nexus 5, API21
```

## Reproducible Demo

1. `expo init`
2. `cd fresh_project`
3. `npm start`

Relative issue https://github.com/react-native-community/cli/issues/586

**Comment by ekwoodrich** [comment]
I have the same problem with expo init, spent hours tweaking the package versions but even manually setting the React Native version to .60 (which builds) breaks at runtime. Happens with both yarn and npm.

**Comment by sebous** [comment]
I'm experiencing the same problem

**Comment by baradusov** [comment]
Seems like the issue is resolved https://github.com/react-native-community/cli/issues/586#issuecomment-514962365. Closing.
