### ISSUE TITLE
Expo CLI always tries to reinstall the client on the iOS 13 simulator

### ISSUE THREAD

**Issue by ide** [expo/expo-cli#880]
I compiled the Expo client from source and ran it on the iOS 13 simulator, and then tried to open a project. Expo CLI got stuck at:
```
Downloading the latest version of Expo client app
Installing Expo client on iOS simulator
-
^C
Stopping packager...
Error running `xcrun simctl list devices --json`: 
Error installing or running app. Error: xcrun exited with signal: SIGINT

setRawMode EIO
```

**Comment by kitingChris** [comment]
Same problem.

Tried also the hint from here: https://docs.expo.io/versions/latest/introduction/installation/ with Exponent-X.XX.X.app but did not help. Still stuck on "Installing Expo client on iOS simulator"

```
myMac:app dev$ yarn ios
yarn run v1.17.3
$ expo start --ios
Starting project at /Users/dev/Workspace/app
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Starting Metro Bundler on port 19001.
Tunnel ready.
Downloading the latest version of Expo client app
Installing Expo client on iOS simulator
^C
Stopping packager...

myMac:app dev$ › Closing Expo server
Error running `xcrun simctl list devices --json`:
Error installing or running app. Error: xcrun exited with signal: SIGINT
setRawMode EIO
Error: setRawMode EIO
    at ReadStream.setRawMode (tty.js:73:31)
    at startWaitingForCommand (/expo-cli@3.1.0/src/commands/start/TerminalUI.js:107:11)
    at Object.startAsync (/expo-cli@3.1.0/src/commands/start/TerminalUI.js:119:3)
    at action (/expo-cli@3.1.0/src/commands/start.js:77:22)
    at /expo-cli@3.1.0/src/commands/start.js:231:16
    at Command.<anonymous> (/expo-cli@3.1.0/src/exp.ts:82:7)
```

**Comment by VanLaerAshley** [comment]
Will this be resolved?

**Comment by kitingChris** [comment]
Looks like this problem is reported more than once https://github.com/expo/expo-cli/issues/933
And an PR is already pending. https://github.com/expo/expo-cli/pull/957

Hope it will be merged soon.

**Comment by fson** [comment]
This was fixed in https://github.com/expo/expo-cli/commit/5f209e26ba47d978ca7006d7b528db93930ae9e3.
