### ISSUE TITLE
expo build:ios -c on Windows, Authentication with Apple Developer Portal failed! (Unexpected end of JSON input)

### ISSUE THREAD

**Issue by Miscavel** [expo/expo-cli#886]
Hi, I tried to build ios .ipa on Windows 10 but kept getting the same error even after using Apple ID with developer status.

For some reason even if I typed in an incorrect password the same error still occurs, but if I typed in an incorrect username it would say "Incorrect Credentials" instead of the errors below.

With EXPO_DEBUG=true, the following errors were printed :
{"result":"success","teams":[{"status":"active" ...
.... {json_objects}
.... accessed_at: *1\n"}
Authentication with Apple Developer Portal failed!
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at runAction (C:\expo-cli@3.0.4\src\commands\build\ios\appleApi\fastlane.js:19:36)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at Object.authenticate (C:\expo-cli@3.0.4\src\commands\build\ios\appleApi\authenticate.js:15:40)
    at IOSBuilder.getAppleCtx (C:\expo-cli@3.0.4\src\commands\build\ios\IOSBuilder.js:47:24)
    at IOSBuilder.produceMissingCredentials (C:\expo-cli@3.0.4\src\commands\build\ios\IOSBuilder.js:122:22)
    at IOSBuilder.prepareCredentials (C:\expo-cli@3.0.4\src\commands\build\ios\IOSBuilder.js:65:7)
    at IOSBuilder.run (C:\expo-cli@3.0.4\src\commands\build\ios\IOSBuilder.js:19:7)
    at IOSBuilder.command (C:\expo-cli@3.0.4\src\commands\build\BaseBuilder.js:54:7)

I'm using expo-cli version 3.0.4
Thank you for your attention.

**Comment by cruzach** [comment]
Could you run `expo diagnostics` and paste the output here?  Also, make sure you've followed our Windows-specific instructions for building standalone apps:

> Windows users must have WSL enabled. You can follow the installation guide here. We recommend picking Ubuntu from the Windows Store. Be sure to launch Ubuntu at least once. After that, use an Admin powershell to run: Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux

**Comment by Miscavel** [comment]
Hi, apologize for the slow response. I finally managed to solve the problem, it turned out that I installed 'Bash on Ubuntu' instead of 'Ubuntu' itself, which made expo think that I had WSL enabled. After picking 'Ubuntu' from the store everything works great.

**Comment by cruzach** [comment]
Thanks for sharing the fix here!
