### ISSUE TITLE
expo client:install:android fails if Expo is not yet installed on an emulator

### ISSUE THREAD

**Issue by SounD120** [expo/expo-cli#950]
## Description

`expo client:install:android` command fails if Expo app is not installed on target emulator. If application was installed earlier then command works without errors. 

## Expected Behavior

Expo installs on Android emulator without errors.

## Observed Behavior

The following error happens if Expo is not yet installed on Android emulator when ran `client:install:android`
```
Uninstalling Expo from Android device.
Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: host.exp.exponent
        at com.android.server.pm.Settings.isOrphaned(Settings.java:4289)
        at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:21095)
        at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:17916)
        at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:736)
        at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:1486)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:193)
        at android.os.ShellCommand.exec(ShellCommand.java:103)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21328)
        at android.os.Binder.shellCommand(Binder.java:634)
        at android.os.Binder.onTransact(Binder.java:532)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2821)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3856)
        at android.os.Binder.execTransact(Binder.java:731)
```
This error is not present if run `expo android` command from Expo 34 project. In such case Expo app deploys on emulator successfully.
## Environment

```
  Expo CLI 3.0.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.17.3 - C:\Users\yuri.skorokhodov\AppData\Roaming\npm\yarn.CMD
      npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
```
Android Studio emulator x86 API 28 Android 9.0

**Comment by EvanBacon** [comment]
I cannot repro this with Expo SDK 39
