### ISSUE TITLE
undefined method `start_with?' for nil:NilClass

### ISSUE THREAD

**Issue by iDuuck** [expo/expo-cli#958]
## Description

When I try to upload my iOS version, the expo cli is raising an error, and I am not sure how to fix this behavior.

## Expected Behavior

Running `expo upload:ios` to be uploading the app to the App Store Connect.

## Observed Behavior

It isn't uploading properly.

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
[20:41:44]: [DevCenter] App 'APP_IDENTIFIER' already exists, nothing to do on the Dev Center
[20:41:48]: App 'APP_IDENTIFIER' already exists (ID_OF_THE_APP), nothing to do on App Store Connect
Uploading the app to Testflight, hold tight...
[20:41:49]: Login to App Store Connect (MY_EMAIL)
[20:41:51]: Login successful
[20:41:52]: Ready to upload new build to TestFlight (App: ID_OF_THE_APP)...
Failed to upload the standalone app to the app store.
undefined method `start_with?' for nil:NilClass
Error: undefined method `start_with?' for nil:NilClass
    at runFastlaneAsync (/expo-cli@3.0.10/src/commands/upload/utils.js:54:11)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at IOSUploader._uploadToTheStore (/expo-cli@3.0.10/src/commands/upload/IOSUploader.js:188:5)
    at IOSUploader.upload (/expo-cli@3.0.10/src/commands/upload/BaseUploader.js:24:5)
    at /expo-cli@3.0.10/src/commands/upload.js:98:7
    at Command.<anonymous> (/expo-cli@3.0.10/src/exp.ts:82:7)

```

## Environment

```
➜ expo diagnostics

  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.7.1 - /usr/local/bin/zsh
    Binaries:
      Node: 12.8.0 - ~/.asdf/shims/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.2 - ~/.asdf/shims/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.7
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.0 => 3.11.1
    npmGlobalPackages:
      expo-cli: 3.0.10
```

**Comment by iDuuck** [comment]
For other people stumbling across this issue, I just found a solution for this problem:

https://github.com/fastlane/fastlane/issues/11605#issuecomment-359163627
