### ISSUE TITLE
Changing app.json path doesn't work for web

### ISSUE THREAD

**Issue by andrzejpolis** [expo/expo-cli#964]
## Description

Cannot start expo web with different app.json path using --config parameter.

## Expected Behavior

`expo start --web --config <different-app.json>` should start properly.

## Observed Behavior

When you move/rename app.json and pass --config parameter with path to moved/renamed app.json expo fails to start with an error:

```
$ expo start --config ./config/app-staging.json --web -c
Starting project at <PROJECT_ROOT>
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Starting Metro Bundler on port 19001.
Your JavaScript transform cache is empty, rebuilding (this may take a minute).
Tunnel ready.
Can't read JSON file: <PROJECT_ROOT>/app.json
└─ Cause: Error: ENOENT: no such file or directory, open '<PROJECT_ROOT>/app.json'
JsonFileError: Can't read JSON file: <PROJECT_ROOT>/app.json
└─ Cause: Error: ENOENT: no such file or directory, open '<PROJECT_ROOT>/app.json'
    at Function.<anonymous> (<PROJECT_ROOT>/node_modules/@expo/webpack-config/node_modules/@expo/json-file/src/JsonFile.ts:125:13)
    at Generator.throw (<anonymous>)
    at rejected (<PROJECT_ROOT>/node_modules/@expo/webpack-config/node_modules/@expo/json-file/build/JsonFile.js:5:65)
```

It is a problem with webpack-config I suppose as giving an incorrect file or file path results in an error on earlier stages. Overriden app.json path is correctly read multiple times until web pack tries to load it.

**Comment by andrzejpolis** [comment]
Old problem. Works after upgrading '@expo/webpack-config'
