### ISSUE TITLE
problem while trying to upload expo app to app store

### ISSUE THREAD

**Issue by leebenalal** [expo/expo-cli#968]
I am trying to upload my expo app to the app store (ios).
While running the command $expo upload:ios I get this error:

[15:27:31]: Ready to upload new build to TestFlight (App: 1478118518)…

[15:27:32]: undefined method `split’ for nil:NilClass

Failed to upload the standalone app to the app store.

Unexpected token x in JSON at position 0

SyntaxError: Unexpected token x in JSON at position 0

at JSON.parse (<anonymous>)

at runFastlaneAsync (/expo-cli@3.0.10/src/commands/upload/utils.js:46:20)

at process._tickCallback (internal/process/next_tick.js:68:7)
Do you have any idea how to solve it?

Thanks!

**Comment by brentvatne** [comment]
hopefully this has been resolved but closing this as we are tracking in https://github.com/expo/expo-cli/issues/1078

apologies that there was no reply
