### ISSUE TITLE
expo customize:web fails

### ISSUE THREAD

**Issue by chayancbnits** [expo/expo-cli#977]
Trying to run “expo customize:web” produces the following error:

Cannot read property 'readConfigJsonAsync' of undefined
TypeError: Cannot read property 'readConfigJsonAsync' of undefined
    at action (/expo-cli@3.0.10/src/commands/customize.ts:78:25)
    at Command.action (/expo-cli@3.0.10/src/exp.ts:82:13)
Any ideas?

**Comment by lochstar** [comment]
Looks like it has been fixed here: https://github.com/expo/expo-cli/pull/960

**Comment by chayancbnits** [comment]
After install expo 3.0.11-alpha.1 ,then run expo build:web , then it is always showing

[=================== ] 95% (56.1 seconds)(node:20438) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined
at Hash.update (internal/crypto/hash.js:58:11)
at exports.default (/@expo/webpack-pwa-manifest-plugin@1.2.4/src/helpers/fingerprint.js:6:6)
at processIcon (/@expo/webpack-pwa-manifest-plugin@1.2.4/src/icons.js:44:29)
at _callee3$ (/@expo/webpack-pwa-manifest-plugin@1.2.4/src/icons.js:137:10)
