### ISSUE TITLE
Failure of uploading on CircleCI

### ISSUE THREAD

**Issue by iDuuck** [expo/expo-cli#980]
## Description

I am experiencing an issue with the `app_produce`. And I am not able to find the bug or occurance of the error.

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
bash-3.2$ EXPO_DEBUG=true expo upload:ios
- Making sure project is set up correctly...
Downloading build from https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/ios/%40nick_kg/quesk-app-IDIDIDIDID-archive.ipa
Downloading [================================================================] 100% 0.0s
Ensuring the app exists on App Store Connect, this may take a while...
Now using node v12.9.1 (npm v6.10.2)
default -> v12.9.1
Now using node v12.9.1 (npm v6.10.2)
default -> v12.9.1
Failed to upload the standalone app to the app store.
/usr/local/share/.config/yarn/global/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.9.11-osx/app_produce exited with non-zero code: 2
Error: /usr/local/share/.config/yarn/global/node_modules/@expo/traveling-fastlane-darwin/traveling-fastlane-1.9.11-osx/app_produce exited with non-zero code: 2
    at ChildProcess.completionListener (/usr/local/share/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:297:20)
    at ChildProcess.emit (events.js:209:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
    ...
    at spawnAsync (/usr/local/share/.config/yarn/global/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnAsyncThrowError (/@expo/xdl@56.2.1/src/detach/ExponentTools.ts:131:19)
    at runFastlaneAsync (/expo-cli@3.0.10/src/commands/upload/utils.js:31:28)
    at IOSUploader._uploadToTheStore (/expo-cli@3.0.10/src/commands/upload/IOSUploader.js:181:11)
    at IOSUploader.upload (/expo-cli@3.0.10/src/commands/upload/BaseUploader.js:24:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at /expo-cli@3.0.10/src/commands/upload.js:98:7
```

## Environment

```

  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.9.1 - ~/.nvm/versions/node/v12.9.1/bin/node
      Yarn: Now using node v12.9.1 (npm v6.10.2)
default -> v12.9.1
1.10.1 - /usr/local/bin/yarn
      npm: 6.10.2 - ~/.nvm/versions/node/v12.9.1/bin/npm
    IDEs:
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild

```

**Comment by iDuuck** [comment]
Seems like the error is because of some permission issues. Running the `expo upload:ios` command as `sudo` is letting me go further.

However, I am now stuck, because the `app_produce` isn't accepting my Application specific password.

**Comment by iDuuck** [comment]
Any update?
