### ISSUE TITLE
Unable to run Jest tests with default minimal TypeScript project

### ISSUE THREAD

**Issue by craigotis** [expo/expo-cli#987]
## Description

When creating a new project with `expo-cli init TestProject`, that project does not support running Jest tests if the `minimal (TypeScript)` configuration is selected.

## Expected Behavior

You should be able to run standard commands like `npm run ios` and `npm test` out-of-the-box, without issue.

## Observed Behavior

While the iOS application starts properly (I didn't test Android), the `npm test` command fails without any modifications:

```
> @ test /Users/craig/projects/ReactJest
> jest

 FAIL  __tests__/App.js
  ✕ renders correctly (9ms)

  ● renders correctly

    Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

      at invariant (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:55:15)
      at createFiberFromTypeAndProps (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2056:11)
      at createFiberFromElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2077:15)
      at reconcileSingleElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4629:23)
      at reconcileChildFibers (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4686:35)
      at reconcileChildren (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6508:28)
      at updateHostRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6920:5)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7745:14)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11413:12)
      at workLoop (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11445:24)

  console.error node_modules/react/cjs/react.development.js:188
    Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.855s, estimated 1s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:
```
expo diagnostics                                                  SIGINT(2) ↵

  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.9.1 - /usr/local/bin/node
      npm: 6.10.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.23 => 16.9.2
      @types/react-native: ^0.57.65 => 0.57.65
      expo: ^34.0.1 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: 0.59.10 => 0.59.10
    npmGlobalPackages:
      expo-cli: 3.0.10
```

## Reproducible Demo

You can run these commands, in this order, without any modifications to reproduce the issue:
```
expo-cli init TestProject
(select the "minimal (TypeScript)" option, I couldn't figure out how to send this to -t)
cd TestProject
npm test
```

**Comment by ide** [comment]
It looks like the bug is that `app.json` is getting loaded instead of `App.tsx`. By default Jest looks for `["js", "json", "jsx", "ts", "tsx", "node"]`. You can work around this for now by adding `.tsx` to your import.

**Comment by craigotis** [comment]
Closing, as this seems to be an `expo/expo` issue, not `expo/expo-cli`. I've opened a PR here: https://github.com/expo/expo/pull/5710
